### ISSUE TITLE
head方法返回的user meta为 null

### ISSUE THREAD

**Issue by 294007813** [ali-sdk/ali-oss#1009]
* **Browser Version or Node Version**:  Google Chrome 版本 94.0.4606.61（正式版本） （64 位）
* **ali-oss Version**: 6.16.0
* **Mini Showcase Repository**: 
* **Network Resoponse Header x-oss-request-id**: 6195FFD17125543537335A52

1 put方法上传带入{meta: { duration: 7.849 }}成功
2 head方法获取数据meta属性为null
<img width="548" alt="meta-null" src="https://user-images.githubusercontent.com/5668941/142373058-fe10a1fb-639d-4964-a104-a679ceb22e6a.png">

**Comment by PeterRao** [comment]
需要将 x-oss-meta-xxx 加入跨域头
