### ISSUE TITLE
并没有到兼容IE10

### ISSUE THREAD

**Issue by heruns** [ali-sdk/ali-oss#1019]
* **Browser Version or Node Version**:IE10
* **ali-oss Version**:6.16.0
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

README 中写着兼容性为：

> IE >= 10 & Edge

实际使用中发现只要引入 `ali-oss` 在 IE10 中就会报错
![image](https://user-images.githubusercontent.com/20581745/143372593-a75ff521-eed0-4d4c-a54c-f5b09c354e16.png)

原因是引入的 `buffer` 这个包是由 `browserify` 来管理的，项目中依赖的 `browserify` 版本是 `^16.5.2`，其 `package.json` 中引用的 `buffer` 版本为 `~5.2.1`，`buffer@5.2.x` 版本不兼容 IE10。建议修复该兼容问题，或修改 README 中的兼容性描述，以免误导用户。

**Comment by taotao7** [comment]
已修改
