### ISSUE TITLE
Put/Multipart请求中如果带有callback，没有正确处理返回的json

### ISSUE THREAD

**Issue by rockuw** [ali-sdk/ali-oss#102]
如果PUT/MultipartUpload时带有`x-oss-callback`头，则OSS会在PUT/CompleteMultipartUpload中返回JSON格式的数据，而不是XML，SDK没有处理这种情况，会导致parseXML出错。

```js
yield client.multipartUpload(key, file, {
  progress: progress,
  headers: {
    'x-oss-callback': callback
  }
});
```

https://help.aliyun.com/document_detail/oss/api-reference/object/Callback.html

> 需要注意的是，如果类似CompleteMultipartUpload这样的请求，在返回请求本身body中存在内容（如XMl格式的信息），使用上传回调功能后会覆盖原有的body的内容如{"a":"b"}，希望对此处做好判断处理。

**Comment by liangShengSen** [comment]
![image](https://user-images.githubusercontent.com/21200409/61988821-46540480-b059-11e9-9ca0-e99d6a0b4a76.png)
我加了callback后都上传不了，也没报错，不加headers是可以上传的
