### ISSUE TITLE
repo description error

### ISSUE THREAD

**Issue by wanming** [ali-sdk/ali-oss#1022]
![image](https://user-images.githubusercontent.com/1776500/144556480-20af4e76-744d-4176-8345-b36e264ed5e1.png)

**Comment by taotao7** [comment]
你好，具体在哪个文件呢？

**Comment by taotao7** [comment]
> ![image](https://user-images.githubusercontent.com/1776500/144556480-20af4e76-744d-4176-8345-b36e264ed5e1.png)

你好，具体在哪个文件呢？

**Comment by taotao7** [comment]
![图片](https://user-images.githubusercontent.com/24582204/147445702-2c5c2e0c-dcd5-4361-8c22-cca660ef03ee.png)

**Comment by wanming** [comment]
![image](https://user-images.githubusercontent.com/1776500/147446089-d9f1fd57-544a-4e03-be75-45085874c97b.png)
项目描述里

**Comment by taotao7** [comment]
好的
