### ISSUE TITLE
ConnectionTimeoutError: Connect timeout for 60000ms 与设置的 timeout 时间不同

### ISSUE THREAD

**Issue by TaraLoveCats** [ali-sdk/ali-oss#1024]
* **Browser Version or Node Version**: Chrome 86
* **ali-oss Version**: 6.8.0
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

`Failed to upload some parts with error: ConnectionTimeoutError: Connect timeout for 60000ms, PUT https://zhihu-pics-upload.zhimg.com/v2-65aa03e9f2be365931ace4aed3a44602?partNumber=4&uploadId=27CF8FE702D7476EA1E75796738930C6 -2 (connected: false, keepalive socket: false)
headers: {} part_num: 4`

上传过程中出现 ConnectionTimeoutError 后台错误信息显示超时 60s，但使用 multipartUpload API 设置的 timeout 是 20s，为什么还是用了 60s 默认值？目前分片大小是 1M，使用版本是 6.8.0；

另外还有一个很重要的问题，根据官方 [multipartUpload](https://github.com/ali-sdk/ali-oss#multipartuploadname-file-options) 文档，遇到 ConnectionTimeoutError 问题时，可以减小分片大小、增加超时时间
![image](https://user-images.githubusercontent.com/24261011/146139882-cf4647f2-69cd-43fa-8679-dff8544e648f.png)
请问对于分片大小、超时时间有更具体的建议吗？比如说超时时间和分片大小的关系？

**Comment by taotao7** [comment]
![图片](https://user-images.githubusercontent.com/24582204/147449893-c1e1c9a0-2c70-4132-adfd-64f7af079125.png)

经过测试6.8.0版本确实有这个bug，只会使用默认60s，建议该换新版6.16.0

文件分片之后如果还是很大，且在当前带宽环境下上传很慢，在超时时间前还没上传完成就会报错。

建议如果当前带宽环境不是很理想容易失败建议分片更小或者超时设置更长
