### ISSUE TITLE
使用vite打包后访问会报process is not defined

### ISSUE THREAD

**Issue by hejun311** [ali-sdk/ali-oss#1042]
1、使用环境vite2+vue,导入方式为npm包，打包到线上部署会出现process is not defined
2、后使用cdn方式引入，报错消失，建议还是解决下

**Comment by PeterRao** [comment]
直接require dist 目录下面打包好的库

**Comment by cnguu** [comment]
@hejun311 刚好遇到用vite搭建的后台打包遇到相关问题，我是这样使用的：

```
import AliOSS from 'ali-oss/lib/client';
```
