### ISSUE TITLE
请问如何在js上传oss后能得到一个浏览器能打开的图片链接而不是直接下载链接？

### ISSUE THREAD

**Issue by ramseyfeng** [ali-sdk/ali-oss#1067]
ali oss version: "6.17.1"

想实现上传照片然后回显，用了js sdk找半天没找到如何能传ObjectMetadata的例子。只找到个java的例子。

调用put方法总是返回一个下载链接，想要返回一个可以在浏览器里直接打开的链接，多谢！

**Comment by without-yy** [comment]
上传回显可以直接使用 URL.createObjectURL(file)

**Comment by PeterRao** [comment]
需要绑定cname才不会自动下载 https://help.aliyun.com/document_detail/39545.html
