### ISSUE TITLE
使用put方法时爆socket hang up

### ISSUE THREAD

**Issue by terryvi** [ali-sdk/ali-oss#107]
大概代码是这样的：
for (var i = arr.length - 1; i >= 0; i--) {
   var tmp = arr[i];
    co(function\* () {
        var obj = yield client.put('/operation/'+ tmp,fs.createReadStream(UPLOAD_IMG_PATH+'/'+tmp));
        if( obj.res.statusCode == 200 ){
            // do  sth
        }else{
           //log sth
        }
    }).catch(function (err) {
        // log err
    });
}
通过一个循环把服务器上的文件（主要就是图片）上传，经常（10个会有4,5个）会有图片上传失败，看log的话，基本上都是：ResponseError: socket hang up (req "error"), PUT http://cycang-act.oss-cn-hangzhou.aliyuncs.com/operation/img/1462419785/1462419709777.png -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":21,"closeSocketCount":3,"errorSocketCount":0,"timeoutSocketCount":9,"requestCount":11,"freeSockets":{"cycang-act.oss-cn-hangzhou.aliyuncs.com:80::":9},"sockets":{"cycang-act.oss-cn-hangzhou.aliyuncs.com:80::":3},"requests":{}})
headers: {} 
跟put还是putstream 并没有关系，似乎是一个样子的。

os: CentOS 6.5 64位
node:官网LTS
web框架：express 4.13.1

**Comment by rockuw** [comment]
可能是你的网络状况较差，你可以ping cycang-act.oss-cn-hangzhou.aliyuncs.com看看延时。

**Comment by terryvi** [comment]
@rockuw  很正常的，也没有丢包 @_@

**Comment by rockuw** [comment]
你的文件很大吗？

你把for循环放到`co(function*() {})`里面试试。你现在的写法是并行上传的。

**Comment by terryvi** [comment]
我先试试。 图片不算很大平均200K不到

**Comment by terryvi** [comment]
@rockuw ok了，测试了几次，没什么大问题。 并行上传为什么会可能出现这样的问题咧?就报错的这几句还是不大能理解并行上传怎么影响到正常运行的=0=。 是SDK对并行上传有特殊的处理么？

**Comment by dead-horse** [comment]
并行上传可能导致同一时间建立了非常多的链接同时上传

**Comment by justquanyin** [comment]
需求如果就是并行上传的话，有什么解决方案么？

**Comment by luozhang002** [comment]
@可以通过Promise.all的方法，自己控制逻辑，比如每次上传5个

**Comment by PeterRao** [comment]
https://github.com/ali-sdk/ali-oss/issues/429 ，设置maxSockets

**Comment by Anndy-Han** [comment]
修改了maxSockets，也设置keepAlive为false，循环上传大量文件还是报错。
![image](https://user-images.githubusercontent.com/29654838/88512735-9a514a80-d019-11ea-8a10-d0e0c2aabe25.png)
