### ISSUE TITLE
ali-oss depend的platform js在client端报错？

### ISSUE THREAD

**Issue by baibing** [ali-sdk/ali-oss#110]
我在一个Meteor的app里打算使用ali-oss从浏览器直接上传文件，程序会在我call `import OSS from 'ali-oss';`时报错说platform.js 734行的exec result为null。请问ali-oss支持浏览器端直接上传文件吗？这个会不会是platform.js在浏览器端执行的问题？谢了！

`line 734: version = /[\d.]+/.exec(data.version)[0];`

`Uncaught TypeError: Cannot read property '0' of null platform.js:734`
`parse @ platform.js:734`
`(anonymous function) @ platform.js:1127`
`meteorInstall.node_modules.ali-oss.node_modules.platform.platform.js @ platform.js:1135`
`fileEvaluate @ install.js:141`
`require @ install.js:75`
`meteorInstall.node_modules.ali-oss.lib.client.js @ client.js:28`
`fileEvaluate @ install.js:141`
`require @ install.js:75`
`meteorInstall.client.components.task_detail.index.jsx @ index.jsx:4`
`fileEvaluate @ install.js:141`
`require @ install.js:75`

**Comment by rockuw** [comment]
你可以参考一下：https://github.com/rockuw/oss-in-browser

**Comment by baibing** [comment]
我刚刚改了下platform js的source code，log了他在734行的data object，version是一个empty string，所以regex return null。

看你分享的例子貌似也是用的这个sdk，但是是从cdn上直接download一个min js。这样子是为了避免call import/require platform package么？我试一下

**Comment by baibing** [comment]
恩，直接load min js worked。不过还需要调一下cors方面的东西。多谢了
