### ISSUE TITLE
一群牧羊犬，老子花了钱，你们这群狗开发者，就他妈搞英文的文档，会点鸟语就是人上人，恶心。

### ISSUE THREAD

**Issue by Sponggebob** [ali-sdk/ali-oss#1110]
没花钱看英文文档我认，我花了前，看文档。还只能看英文。恶心,会点鸟语。真成人上人了？？

**Comment by coolme200** [comment]
请注意文明用语，有需要帮助尽管说，我们会提供必要的帮助。此 issue 跟技术无关，关闭。

**Comment by mickeyinfoshan** [comment]
前排合影

**Comment by LeePillar** [comment]
赞

**Comment by PeterRao** [comment]
官网有 中文文档 https://help.aliyun.com/document_detail/64041.html 以及工单支持，这里主要面向sdk本身开发者

**Comment by zhang97goodboy** [comment]
合影合影
