### ISSUE TITLE
在生产环境下能不能不console.warn stsToken的打印

### ISSUE THREAD

**Issue by 724493602** [ali-sdk/ali-oss#1120]
* **Browser Version or Node Version**: chrome
* **ali-oss Version**:6.17.1
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:
请求在生产环境移除这个打印， 实际业务存在只会上传一次的使用，不需要定时去获取token，但是老是有这个打印
It's recommended to set 'refreshSTSToken' and 'refreshSTSTokenInterval' to refresh stsToken、accessKeyId、accessKeySecret automatically when sts token has expired

**Comment by PeterRao** [comment]
这个设置下，也不是很复杂，如果不过期不会去请求的。
