### ISSUE TITLE
微信小程序如何删除OSS文件？

### ISSUE THREAD

**Issue by wiexin** [ali-sdk/ali-oss#1123]
官方文档中写了微信小程序如何去上传文件到OSS https://help.aliyun.com/document_detail/92883.htm。 
目前已实现上传功能。但是翻遍文档除了用SDK方法管理文件，没找到其他在小程序上可行方法。请问小程序是否能管理OSS文件？

**Comment by PeterRao** [comment]
这个目前只能自己封装下请求，调用delete接口就行。和put方法差不多的方式

**Comment by zhengmenghuang** [comment]
有封装示例么 我这里封装的一致报403
