### ISSUE TITLE
有办法下载一个目录下的所有文件吗？

### ISSUE THREAD

**Issue by xyy7260** [ali-sdk/ali-oss#1124]
上传的时候在oss 做了图片目录区分。目前需要下载全部图片有办法做吗？

**Comment by PeterRao** [comment]
需要指定前缀，然后调用list接口，如果需要list全部文件，需要根据token持续的往下调用list接口。

**Comment by xyy7260** [comment]
@PeterRao  图片达到上几万张呢 😆。  函数计算FC 这个行吗

**Comment by PeterRao** [comment]
这个无论是用fc还是 ecs上，还是用什么工具，原理都一样的，都要持续list获取目录上所有的文件。
如果对实时性要求不高，可以尝试使用Bucket清单功能，导出文件列表。

**Comment by xyy7260** [comment]
@PeterRao 我就用了工具手动下载， 这
