### ISSUE TITLE
client.copy throw 403 AccessDenied

### ISSUE THREAD

**Issue by hellohejinyu** [ali-sdk/ali-oss#1138]
* **Browser Version or Node Version**: Node 16.16.0
* **ali-oss Version**: 6.17.1
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**: 62CCDE8D7CF84234320D192D

<img width="983" alt="image" src="https://user-images.githubusercontent.com/8766034/178396811-3ccdfb2a-0b0b-4511-9328-2bfaa457e4e2.png">

![image](https://user-images.githubusercontent.com/8766034/178396938-e8a4527f-64bb-4df7-a68d-d3783949578b.png)

**Comment by PeterRao** [comment]
403权限错误，检查ak用户的权限

**Comment by hellohejinyu** [comment]
> 403权限错误，检查ak用户的权限

复制的权限和上传不一样吗？我是可以正常上传的，只是用这个 copy 方法复制文件的时候会报错。
