### ISSUE TITLE
OSS 服务端签名前端直传是否支持分片上传？

### ISSUE THREAD

**Issue by 2eha0** [ali-sdk/ali-oss#1145]
S3 可以对每一个分片生成预签名的 url，oss 的预签名貌似只能支持单体文件的上传？

**Comment by lslzl3000** [comment]
同问，貌似目前只能单个文件上传，我也想要比如 append 等其他上传方式的签名

**Comment by taotao7** [comment]
当个分片然后签名这个功能不支持，但是分片上传是支持的，multipartUpload
