### ISSUE TITLE
在vue3+vite上传，提示TypeError: Cannot read properties of undefined (reading 'protocol')

### ISSUE THREAD

**Issue by lizzieSunshine** [ali-sdk/ali-oss#1149]
* **node**: 16.13.1
* **ali-oss**: 6.17.1

在vue3+vite+ts的环境下使用put方式上传单张图片：
```js
const client = new OSS({ /**/ })
client.put('test.png', file, {
    headers: {}
  }).then(res => {
    console.log(res);
  })
```

发现请求并没有发送，并且浏览器报错：
![KVA$ZI5~YIQF4W%65%1NLIR](https://user-images.githubusercontent.com/39180355/186866735-7f1e648e-9204-45a1-b613-02f387483e89.png)

同样的代码在vue3+webpack的环境下就能上传成功

**Comment by xjiangiao** [comment]
我最近迁移一个vue 2 项目到vite也发现这个问题，后来看了下源码，猜测是[https://github.com/ali-sdk/ali-oss/blob/a759699be8c7e4acbdc72a5f8d121f2224a7f846/shims/stream-http/index.js](url) 跟这个文件对protocol的调用有关。
通过阅读代码可以知道报错的代码应该是第19行，代码对global.location.protocol的search方法进行了调用， 而global作为node端特性，在浏览器中是不能运行的，因此vite默认是没有挂载global，这个时候我们可以通过window挂在到global上解决这个问题
`export default defineConfig({
  plugins: ...
  esbuild: ...

  define: {
    // By default, Vite doesn't include shims for NodeJS/
    // necessary for segment analytics lib to work
    global: "window",
  },
})`

**Comment by cuiguojie** [comment]
> 我最近迁移一个vue 2 项目到vite也发现这个问题，后来看了下源码，猜测是https://github.com/ali-sdk/ali-oss/blob/a759699be8c7e4acbdc72a5f8d121f2224a7f846/shims/stream-http/index.js 跟这个文件对protocol的调用有关。 通过阅读代码可以知道报错的代码应该是第19行，代码对global.location.protocol的search方法进行了调用， 而global作为node端特性，在浏览器中是不能运行的，因此vite默认是没有挂载global，这个时候我们可以通过window挂载到global上解决这个问题
> 
> ```
> export default defineConfig({
>   plugins: ...
>   esbuild: ...
> 
>   define: {
>     // By default, Vite doesn't include shims for NodeJS/
>     // necessary for segment analytics lib to work
>     global:  "window",
>   },
> })
> ```

在我的项目（vite4 + vue3）中，发现这样配  dev 环境 OK 了，但是 build 的时候会报错，需要写环境模式判断才能绕过去

```
export default defineConfig(({ mode }) => {
  const isDev = (mode === 'development');

  return {
    define: {
      'global': isDev ? 'window' : 'global',
    },
```
