### ISSUE TITLE
{"name":"RequestError","status":-1,"code":"RequestError"}

### ISSUE THREAD

**Issue by zheng456xiang** [ali-sdk/ali-oss#1158]
multipartUpload 分片上传报 {"name":"RequestError","status":-1,"code":"RequestError"}
SDK 6.16

**Comment by liangbus** [comment]
+1 同样遇到了，楼主有解决方案吗？

**Comment by liangxiwei** [comment]
把token的过期时间设置得大一点，每次上传都用最新的token，这样就不会出现上传过程中刷新token的现象，基本上能避免这种问题

**Comment by mianxiaoqian** [comment]
简单上传模式下 报{"code":"RequestError","name":"RequestError","status":-1} 这个错误
每次报错后已经重新获取token再次上传还是会报这个错，会连续出现
该怎么解决呢

**Comment by mianxiaoqian** [comment]
找公司运维查日志发现是跨域导致
