### ISSUE TITLE
你好, 使用client.getStream 报错找不到这个方法, putStream 能够成功上传

### ISSUE THREAD

**Issue by weiyi01** [ali-sdk/ali-oss#1168]
ali-oss@^6.8.0

![image](https://user-images.githubusercontent.com/51228290/195488163-2ec0a664-e6a5-4399-aa7c-44d7e61b8eae.png)

**Comment by yyhdev** [comment]
+1

**Comment by taotao7** [comment]
browser端没有stream

**Comment by ricky11** [comment]
no stream on browser side?  File.stream()   Please confirm why we cant use stream on brower sdie?
