### ISSUE TITLE
nodejs删除多个文件时报超时错误

### ISSUE THREAD

**Issue by denglouhen** [ali-sdk/ali-oss#1171]
用的就是官网上Nodejs删除多个文件的代码：
```
async handleDel(name: string): Promise<void> {
    try {
      await this.client.delete(name)
    } catch (error: any) {
      error.failObjectName = name
      return error
    }
  }
  async deletePrefix(prefix: string): Promise<void> {
    const list = await this.client.list({
      prefix: prefix,
      'max-keys': 1000,
    })
    list.objects = list.objects || []
    await Promise.all(list.objects.map((v: any) => this.handleDel(v.name)))
  }
```

然后list.objects 一共149个文件，但是删除的过程中，会报错一部分文件socket超时，导致不能全部删除干净：
RequestError: connect ETIMEDOUT xxxxxx:80, DELETE xxxxxx.js -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":149,"createSocketErrorCount":0,"closeSocketCount":50,"errorSocketCount":0,"timeoutSocketCount":50,"requestCount":95,"freeSockets":{"xxxxxxxxx:":43},"sockets":{"xxxxxxxxx:":56},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0) headers: {}

是因为同时删掉的文件数太多了吗？我应该怎么做呢？

**Comment by taotao7** [comment]
用队列来控制下，在限制下并发,这是node扛不住了
