### ISSUE TITLE
有uploadid后缀的图片地址无法访问和下载

### ISSUE THREAD

**Issue by LiZheGuang** [ali-sdk/ali-oss#1172]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

demo地址：http://byapp-test.oss-cn-beijing.aliyuncs.com/operation/IMG_9968.JPG?uploadId=3CCA9FDE473C4B85A339F1AC6584FA54
有id的无法访问，但当id删除掉 就可以进行访问与下载

x-oss-request-id：635A583603524B34324B7078
http://byapp-test.oss-cn-beijing.aliyuncs.com/operation/IMG_9968.JPG

**Comment by LiZheGuang** [comment]
end

**Comment by wpc669418** [comment]
怎么解决的？需要手动删除？

**Comment by LiZheGuang** [comment]
> 怎么解决的？需要手动删除？

印象好像最后改成直传了，如果体积过小还是切片上传的会有这个问题；
