### ISSUE TITLE
v6.17.1 browserjs 调用signatureUrl方法会触发refreshSTSToken

### ISSUE THREAD

**Issue by ivestszheng** [ali-sdk/ali-oss#1178]
> 我的refreshSTSToken每次调用signatureUrl都会刷新是什么原因？

我也是，
按照 [这里](https://github.com/ali-sdk/ali-oss#node-usage) 的方式配置了STS 刷新， 每次 signatureUrl 都会刷新一次

_Originally posted by @BonderTam in https://github.com/ali-sdk/ali-oss/issues/960#issuecomment-1301734139_

**Comment by ivestszheng** [comment]
回退至版本6.16.0后表现正常

**Comment by taotao7** [comment]
#1182
