### ISSUE TITLE
accessKeyId、accessKeySecret、stsToken的重复书写问题

### ISSUE THREAD

**Issue by Jasmine011** [ali-sdk/ali-oss#1188]
<img width="842" alt="ta" src="https://user-images.githubusercontent.com/96428529/216931461-0e8464db-b7f0-495b-98f2-aefe75343ffd.png">
这边为什么同样的东西要写两遍，不可以直接在初始化的时候执行一次refreshSTSToken吗

**Comment by taotao7** [comment]
你第一次初始化的时候填写的ak sk 早就过期了才会调用refrehSTSToken这个方法，从你的sts服务器获取新的ak sk，如果不太懂这个概念可以看看sts文档
