### ISSUE TITLE
如何在multipartupload中自定义content disposition来重命名下载文件？

### ISSUE THREAD

**Issue by baibing** [ali-sdk/ali-oss#119]
在client端我们将文件名以hash的形式存储在oss中以达到同一文件多版本的功能，可是希望在点击url下载时能以原文件名下载。

我尝试以html5的download attribute实现该功能，可是没有work，应该是因为有默认的content disposition以上传文件名设置在了header中。从文档中我看到put和putStream API都可以自定义Content-Disposition，但是multipartupload中并没有。

https://github.com/ali-sdk/ali-oss#multipartuploadname-file-options

```
    var client = new OSS.Wrapper({
      region: 'oss-cn-beijing',
      accessKeyId: *,
      accessKeySecret: *,
      bucket: '*'
    });

    let updatedFiles = files.map(file => {
      file.progress = 0;
      const id = Random.id();
      client.multipartUpload(id, file, {
        progress: function* (p) {
          file.progress = p;
        }
      }).then(function(res) {
        addFile(file.name, file.type, file.size, client.signatureUrl(id), task._id);
      });
      return file;
    });

```

**Comment by baibing** [comment]
我需要记录上传进度，只有通过multipart upload才能得到进度反馈，如果有其他方法能从put读取上传进度也可以解决此问题

**Comment by rockuw** [comment]
与put一样，在options中指定headers参数即可。

**Comment by baibing** [comment]
谢谢回复，我尝试过直接添加headers（代码如下），但是在client端会开始得到TypeError

```
      client.multipartUpload(id, file, {
        progress: function* (p) {
          file.progress = p;
        },
        headers: {
          'Content-Disposition': file.name
        }
      }).then(function(res) {
```

aliyun-oss-sdk.min.js:9 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Invalid value (req "error"), PUT http://mvp-launch-data.oss-cn-beijing.aliyuncs.com/WuEidLC2FKa4K5n2K -1 (connected: false, keepalive socket: false, agent status: {"createSocketCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{},"requests":{}})(…)

**Comment by rockuw** [comment]
这个不是headers导致的错误。你把process去掉试试。

**Comment by baibing** [comment]
你是指progress吗？去掉以后仍然是同样的error，这个error只在添加了headers这个field之后才会出现

```
      client.multipartUpload(id, file, {
        headers: {
          'Content-Disposition': file.name
        }
      }).then(function(res) {
```

**Comment by rockuw** [comment]
file.name的值是什么呢？

**Comment by baibing** [comment]
恩。。有意思，file.name是一个string `name : "C案例.xlsx"`。

我发现可能是字符串编码问题，我先后手动hardcode为 `'Content-Disposition': 'abc.xlsx'`上传文件并成功，hardcode为 `'Content-Disposition': '案例.xlsx'`就会收到之前的error。

不过另外就算我以英文设置Content-Disposition后，当我下载该文件时仍然以hash id为文件名，我自定义的abc.xlsx并没有被用到

**Comment by rockuw** [comment]
请搜索一下content-disposition的用法。

**Comment by baibing** [comment]
嗯啊，多谢，搞定了。建议一下，希望能update一下API document顺便加上content disposition的example code会帮助很多。

**Comment by rockuw** [comment]
文档已更新，谢谢反馈。
