### ISSUE TITLE
what about multipart upload

### ISSUE THREAD

**Issue by denjones** [ali-sdk/ali-oss#12]
may it be supported?

**Comment by liuwenchao** [comment]
对啊，支持网页直接上传么？s3可以的哦

**Comment by fengmk2** [comment]
嗯，应该是支持的，尽快实现。

同时就解决流式上传了。

**Comment by fengmk2** [comment]
https://docs.aliyun.com/#/pub/oss/api-reference/multipart-upload&abstract

Multipart Upload: 

- 需要支持断点上传。
- 上传超过100MB大小的文件。
- 网络条件较差，和OSS的服务器之间的链接经常断开。
- 上传文件之前，无法确定上传文件的大小。

**Comment by fengmk2** [comment]
https://github.com/cojs/readable

**Comment by liuwenchao** [comment]
:+1:

**Comment by fengmk2** [comment]
今天得知支持 chunked 编码上传的，我试试看。
