### ISSUE TITLE
建议不用content-type的值来生成url signature

### ISSUE THREAD

**Issue by surelax** [ali-sdk/ali-oss#1200]
* **Browser Version or Node Version**:18.16.0
* **ali-oss Version**:6.17.1
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

不是SDK的问题，但是我在使用signed url在浏览器上上传图片的时候总是出错，经过排查之后，发现原因是因为服务器端使用了content-type的值来验证signature。

但是用`XMLHttpRequest`来上传文件的时候，Content-Type是浏览器自动生成的，它的值目前我没有找到办法提前设定，因为这个问题导致目前没办法使用signed url来上传文件。

如果手动设置了content-type，虽然可以过signature验证，但是上传的文件会损坏。没法用。

这里可以建议把content-type从signature验证里面去掉吗？

大致的客户端代码如下：

```
      let request = new XMLHttpRequest();
      request.open('PUT', `${signedUrl}`);

      // upload progress event
      request.upload.addEventListener('progress', function (e) {
        // upload progress as percentage
        let percent_completed = (e.loaded / e.total) * 100;
        onProgressUpdate(percent_completed);
      });

      // send POST request to server
      request.send(data);
```

**Comment by PeterRao** [comment]
OSS 本身设计是这样，因为Content-Type 会作为 meta 写入到对象数据中，content-type 需要加入签名，防止篡改。所以需要content-type 加入签名，并且发送请求时，header 带上同样的content-type。设置content-type 可以根据后缀，使用 https://www.npmjs.com/package/mime-lite 来进行判断。

**Comment by emclab** [comment]
Hi， @PeterRao, 我在上传JPG image碰到类似的问题。后端node在生成上传签名URL时用image/jpeg，前端React native用React nativeBlobUtil.fs.readFile读进jpg image后 fetch PUT应该用什么content-type？
