### ISSUE TITLE
When will you release the new version?

### ISSUE THREAD

**Issue by qinmaye** [ali-sdk/ali-oss#1209]
It's been over a year since your last new release, and a lot of new features are on the master branch, but you haven't released a new version to get those features out.

Can I ask when it will be released?

**Comment by ricky11** [comment]
do you mean version 7?  yes i agree the current master branch v.6 has many old dependencies and is very huge and outdated. our company is now moving back to another provider.

**Comment by qinmaye** [comment]
@ricky11 They seem to be working on version 7 right now, but haven't released version 7 on npm in two years. I'm furious about this because we pay for their services.
So your company isn't going to use aliyun anymore?

**Comment by ricky11** [comment]
v.7 is started about 2 years ago, you are right, but i think they have many legacy old customers that will not be able to support v.7. the main reason v.7 is started is that the bundle size is huge for v.6.  I think you can use v.7 yourself now.

i think there are only 2 or 3 developers who work very hard for ali-oss node package without much official support from the big company...

yes while ali-oss worked well for us last 2 years, it is dated, and we will move to cloudflare r2 or some other service within 6 months.

**Comment by qinmaye** [comment]
@ricky11  It's dangerous to use an untested version in a production environment, so I didn't use v7.

I am using aliyun-oss for some of my personal projects, nothing to do with the company. Aliyun is faster in China and able to invoice lol.

**Comment by ricky11** [comment]
They should just allow to use s3 sdk/compatible SDK then they don't need to do anything, we just change the endpoint..  anyway i think v7 can be used for personal projects.

**Comment by ricky11** [comment]
any comment from @fengmk2 or ali-oss team? we really need to update dependency, as many are already deprecated, and also reduce bundle size.. we have been asking for 3 years for this.

**Comment by fengmk2** [comment]
I'm no longer involved in ali-oss development, so any ali-oss issues can be addressed to the Aliyun maintenance staff by opening a new issue. My original intention in writing ali-oss was to allow Node.js programs to access OSS services, but after Aliyun's maintainers stepped in, it needed to be compatible with both browsers and Node.js environments, which broadened the scope of its functionality and made it very difficult to maintain.

In 2022 I forked ali-oss to [oss-client](https://github.com/node-modules/oss-client), removing all the capabilities for browser support and keeping only the code that works for Node.js environments.
