### ISSUE TITLE
在multipartUpload时出现Error:_getFileSize requires Buffer/File/String.

### ISSUE THREAD

**Issue by Catlite91** [ali-sdk/ali-oss#121]
在multipartUpload时出现Error:_getFileSize requires Buffer/File/String.

file文件为multer解析出的对象
```
{ fieldname: 'video',
  originalname: 'IMG_2211.MOV',
  encoding: '7bit',
  mimetype: 'video/quicktime',
  buffer: <Buffer 00 00 00 14 66 74 79 70 71 74 20 20 00 00 00 00 71 74 20 20 00 00 00 08 77 69 64 65 03 31 e8 87 6d 64 61 74 00 cc 40 07 00 fa 9b cc 3e bc 94 15 96 e5 ... >,
  size: 53616182 }
```

node版本v5.11.0

**Comment by rockuw** [comment]
这个错误已经很明确了，file参数只能是Buffer/String/File，而不是任意对象。

**Comment by Catlite91** [comment]
请问这个是符合要求的file对象么
```
{ fieldname: 'video',
  originalname: 'IMG_2211.MOV',
  encoding: '7bit',
  mimetype: 'video/quicktime',
  buffer: <Buffer 00 00 00 14 66 74 79 70 71 74 20 20 00 00 00 00 71 74 20 20 00 00 00 08 77 69 64 65 03 31 e8 87 6d 64 61 74 00 cc 40 07 00 fa 9b cc 3e bc 94 15 96 e5 ... >,
  size: 53616182 }
```

我改成传file.buffer
出现
`Error: _createStream requires File/String.`

**Comment by Catlite91** [comment]
我发现在`lib/multipart.js`中判断是否为file的方法里的typeof File始终是undefined
```
is.file = function (file) {
  return typeof(File) !== 'undefined' && file instanceof File;
};
```

**Comment by Catlite91** [comment]
WebFileReadStream.prototype._read = function () {
  if (!this.reader) {
    var that = this;
    that.reader = new FileReader();
    that.reader.onload = function (e) {
      that.push(new Buffer(new Uint8Array(e.target.result)));
      that.push(null);
    };
    that.reader.readAsArrayBuffer(that.file);
  }
};

FileReader是浏览器端的吧？

**Comment by rockuw** [comment]
String表示本地文件路径，将这个文件上传到OSS，
File表示浏览器选中的文件，将其上传到OSS。

不知道你是要怎样？

**Comment by Catlite91** [comment]
node中没有FileReader 以及 File对象

**Comment by rockuw** [comment]
浏览器中有，可以参考：https://github.com/rockuw/oss-in-browser

**Comment by Catlite91** [comment]
那node端无法使用multipartUpload？

**Comment by rockuw** [comment]
https://github.com/ali-sdk/ali-oss/blob/master/test/multipart.test.js

**Comment by cesiya23** [comment]
我在上传blob对象的时候也会出现这种报错，请问这种情况该怎么处理呢？

**Comment by Catlite91** [comment]
@cesiya23 貌似只能在浏览器跑multipart
https://github.com/aliyun-UED/aliyun-sdk-js 试试这个

**Comment by cesiya23** [comment]
@Catlite91 我的就是浏览器上传呢。

ali-sdk 
ali-oss 
aliyun-sdk.js

感觉阿里的应用包及文档太多了……

浏览器上传是参考你上面给我发的链接是吗？

**Comment by Catlite91** [comment]
@cesiya23 浏览器的话我现在是用的aliyun-sdk-js 配合os-js-upload https://github.com/aliyun-UED/oss-js-upload能进行分片上传的

**Comment by micate** [comment]
如果是从 checkpoint 中恢复的，比如 localStorage，那需要手动把文件放到 checkpoint 中，比如：

```
var checkpoint = window.localStorage.getItem('xxx') || {};
checkpoint.file = file;

client.multipartUpload('name', file, {
    checkpoint: checkpoint,
    ...
});
```

我遇到的问题是这样解决的。

**Comment by Catlite91** [comment]
吐槽：明明是个node端的库，为什么会有浏览器环境。
