### ISSUE TITLE
生成临时链接存在越权漏洞

### ISSUE THREAD

**Issue by xuliuzhu1834** [ali-sdk/ali-oss#1213]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

```
const url = oss.signatureUrl('.');

const url = oss.signatureUrl('/');
```
类似这种参数，访问生成的url却是keys list，此时便能拿到该桶下所有文件列表

**Comment by PeterRao** [comment]
对象的命名是有规则的，不能以 / 开头，不过这个有些特殊场景可能会出现以/开头的对象，所以sdk并未对入参进行校验。
这里'.' 是合法的命名，不过在url语义中认为是根目录，出发嘞listobject的响应，而不是getobject，语义上有冲突。这里不好做区分。
权限问题本质是ak来控制的，这里需要使用的ak，不要用listobject权限，并不是生成的url产生越权问题。
