### ISSUE TITLE
put方式文件上传文件类型的判定bug

### ISSUE THREAD

**Issue by jockiech** [ali-sdk/ali-oss#1216]
我在使用富文本组件粘贴图片自动通过ali-oss/nodejs-sdk中的put api进行上传时遇到这个错误【Must provide Buffer/Blob/File for put.】。在源码中发现抛出错误的原因是因为isFile函数和isBlob函数的返回值均为false，它是通过instanceof来进行类型判定，但这个类型判定的结果受执行上下文环境影响。目前情况就是我这里正常走上传流程没有问题，但是图片粘贴生成的文件流做上传就会遇到这个问题。不知这里为什么没有考虑使用Object.prototype.toString.call()进行类型判定？

**Comment by Hedgehogking** [comment]
请问这个问题在后续的版本有修复吗

**Comment by Hedgehogking** [comment]
> 请问这个问题在后续的版本有修复吗

通过把file文件的blob再重新new File(file, file.name) 一下就能成功put了
