### ISSUE TITLE
有否 访问私有文件的前端解决方案

### ISSUE THREAD

**Issue by cesiya23** [ali-sdk/ali-oss#123]
有一个私有bucket，有文件的存储路径，请问如何实现访问私有文件。

**Comment by rockuw** [comment]
https://github.com/rockuw/oss-in-browser

**Comment by cesiya23** [comment]
@rockuw 是无法直接访问私有文件。

比如我的仓库是私有的：`http://cc23.oss-cn-shanghai.aliyuncs.com`

我想要访问其中的 `/test/10.jpg`

```html
<img src="http://cc23.oss-cn-shanghai.aliyuncs.com/test/10.jpg">
```
这样是无法直接访问的，求教该如何解决呢？

**Comment by rockuw** [comment]
1. 把bucket设置成public-read：https://help.aliyun.com/document_detail/31869.html
2. 把这个object的ACL设置成public-read：https://github.com/ali-sdk/ali-oss#putaclname-acl-options
3. 使用签名URL：https://github.com/ali-sdk/ali-oss#signatureurlname-options

上面3个方法都不能阻止别人访问你的文件，但是你可以设置防盗链防止别人在网站上直接引用你的文件：https://help.aliyun.com/document_detail/31869.html
