### ISSUE TITLE
依赖包中vm2存在严重的沙箱逃逸漏洞，是否考虑升级版本修复？

### ISSUE THREAD

**Issue by asermoon** [ali-sdk/ali-oss#1232]
- **ali-oss Version**: 6.17.1

**Comment by joel611** [comment]
Please fix it because one of our project is using this package for production.

**Comment by bakabird** [comment]
fixed it please

**Comment by fengmk2** [comment]
fixed in urllib v2 https://github.com/node-modules/urllib/pull/457
