### ISSUE TITLE
jest测试ali-oss报错：SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by lyanerzhang** [ali-sdk/ali-oss#1235]
ali-oss使用jest跑测试用例报错
node_modules/ali-oss/lib/common/utils/lowercaseKeyHeader.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { isObject } from './isObject';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module
    
Version
"ali-oss": "^6.17.1",
"ts-jest": "^26.0.3",
"vue-jest": "^5.0.0-0",

请问是什么原因呢

**Comment by riguang** [comment]
我也遇到了，你是怎么解决的

**Comment by lyanerzhang** [comment]
![image](https://github.com/ali-sdk/ali-oss/assets/38914404/a15a4a07-d4eb-40b8-ae87-1e642b83b9b3)
配置了这个

**Comment by riguang** [comment]
> 

我是 node 端环境，试了下不好使~ 可能还和其他配置，谢谢
