### ISSUE TITLE
list方法为什么只能返回1000限制？几万个文件怎么办？

### ISSUE THREAD

**Issue by openwings** [ali-sdk/ali-oss#1240]
- **Browser Version or Node Version**:
- **ali-oss Version**:
- **Mini Showcase Repository**:
- **Network Resoponse Header x-oss-request-id**:

**Comment by openwings** [comment]
离谱的是，你不包含market，只包含market后面的，就无法判断了。
如果你找不到，也不会返回空值，居然返回了第一个文件名。。。
这个是用脑子写出来的？

**Comment by openwings** [comment]
匹配名称你的实现是不是模糊匹配？居然返回了一个完全不再顺序位置上的marker，还标记isTruncated true！！！！！

**Comment by PeterRao** [comment]
对象存储本身是这样设计，不是数据库系统，分页是marker方式，一直往下list
