### ISSUE TITLE
Node 最新版本 enableProxy 导致找不到 x-oss-request-id

### ISSUE THREAD

**Issue by cipchk** [ali-sdk/ali-oss#1245]
## 原因

主要是 `urllib` 依赖包里面的 `proxy-agent` 为可选项，所以如果要想让代理生效，需要自行加入：

```
"proxy-agent": "^5.0.0"
```

建议 `ali-oss` 要么直接依赖它，或者在 README 当中进一步说明。

**Comment by zlswzy** [comment]
请问proxy-agent这个依赖要添加到当前项目的package.json里么，还是别的地方呢，我也遇到了这个问题，但是添加之后依然无法生效

**Comment by JaremyCheng** [comment]
一样遇到这个问题, 项目增加proxy-agent依赖也不行

**Comment by cipchk** [comment]
> 请问proxy-agent这个依赖要添加到当前项目的package.json里么，还是别的地方呢，我也遇到了这个问题，但是添加之后依然无法生效

是的，就是在你的 `package.json` 中加入。

**Comment by DevinXian** [comment]
Works for me，many thanks
