### ISSUE TITLE
6.18.0 更新日志在哪里？是 npm 账号被盗用了么？

### ISSUE THREAD

**Issue by xiaweiss** [ali-sdk/ali-oss#1247]
<img width="444" alt="image" src="https://github.com/ali-sdk/ali-oss/assets/17960084/a8c98415-d200-460e-b7d8-89d7b2f0139c">

**Comment by YunZZY** [comment]
更新日志可查看CHANGELOG

**Comment by xiaweiss** [comment]
@YunZZY github 右侧的 release 没有呢

**Comment by YunZZY** [comment]
[CHANGELOG.md](https://github.com/ali-sdk/ali-oss/blob/master/CHANGELOG.md)
