### ISSUE TITLE
webpack 打包报错

### ISSUE THREAD

**Issue by suhaotian** [ali-sdk/ali-oss#126]
![_c8bg68ls7j94p3wc3xjuh6](https://cloud.githubusercontent.com/assets/6512574/16937011/fa688c7e-4d9d-11e6-8d3b-4de512e462c8.png)

**Comment by rockuw** [comment]
我们使用browserify，参考：https://github.com/ali-sdk/ali-oss#browser-usage

**Comment by suhaotian** [comment]
我们使用 webpack @rockuw .

找到原因了，`lib/client.js` 30 行：
```js
var pkg = require('../package.json')
```

去掉就好了

**Comment by suhaotian** [comment]
@rockuw 我这是 react 单页应用，上传文件只有一个场景页面有，本来打算直接 import 写成  react 组件。现在看起来不行，因为好像只能 script 标签引入

**Comment by rockuw** [comment]
webpack我没有用过，可能是会有一些问题需要解决。

script标签引入有什么问题吗？

**Comment by suhaotian** [comment]
@rockuw 我只有一个页面需要上传啊，这个页面是按需加载的... script 标签怎么引入

**Comment by suhaotian** [comment]
@rockuw 如果要 script 标签引入，那么只有在 index.html 里面写死了，但是其他页面就无缘无故多加载了 100 多kb 多 js 代码

**Comment by rockuw** [comment]
那只能去研究一下webpack了

**Comment by suhaotian** [comment]
你们或许需要另开一个 repo ，js 代码基于浏览器的，而不是基于 Node
可以参考下七牛的 jssdk ...

**Comment by rockuw** [comment]
不分开是不想重复，参考aws的js sdk。你的问题是和webpack一起使用的问题，而不是分不分开的问题。

**Comment by suhaotian** [comment]
哎，就拿一个小例子来说，node 可以直接支持 require('xxx.json')，但是对于 webpack，就会无法识别 `.json` 扩展名，你们的代码大部分都是可以共用的，只是写法上要区分 node 和浏览器的区别，node 支持  fs ，但是在浏览器端就会报错，，

**Comment by suhaotian** [comment]
如果你们连基本的 webpack 打包都不支持，很难想象高级开发者中有多少人用你们的东西

**Comment by rockuw** [comment]
浏览器端不会使用fs，你报错只是你的用法不对。

如果webpack是很多用户的诉求，我们当然会提供支持。

**Comment by suhaotian** [comment]
问题是，你们啥时候支持？

**Comment by rockuw** [comment]
你可以参考一下issue的平均解决时间:)

**Comment by suhaotian** [comment]
好的，那我目前暂时先 script 引入，因为还是在开发阶段

**Comment by suhaotian** [comment]
支持 webpack 打包的另一个好处是，打包体积会变小一些，因为 babel 代码可以共用

**Comment by suhaotian** [comment]
还有一个问题，你们自己内部用，直接 ie10+ 么

**Comment by rockuw** [comment]
什么叫“直接ie10+”？

**Comment by suhaotian** [comment]
换七牛了， :smile:

**Comment by simplefeel** [comment]
我们项目中也是使用webpack进行打包的，遇到的问题和上面的同学遇到的差不多，ossjavascript包能否在webapck下运行，如果可以的话是否可以出个脚手架工程？

**Comment by simplefeel** [comment]
补充一下，我们使用react+webpack

**Comment by tolerious** [comment]
同问啊。

**Comment by suhaotian** [comment]
@tolerious 上传可以参考文档那个直传的例子，没必要非要用 SDK

**Comment by tolerious** [comment]
@suhaotian  是的啊， 但是我发起请求的部分在我的Vue组件内，我的Vue组件是通过Webpack打包的，直接用`<script>`标签引入，我在Vue的组件内无法使用的呢。

**Comment by suhaotian** [comment]
可以通过 script 全局引入，虽然有点丑

**Comment by tolerious** [comment]
@suhaotian  通过`script`标签引入的，再Vue单文件组件中可以使用？

**Comment by suhaotian** [comment]
const plupload = plupload

**Comment by tolerious** [comment]
啥？

**Comment by suhaotian** [comment]
我加你 qq 吧

**Comment by tolerious** [comment]
@suhaotian 390549824

**Comment by suhaotian** [comment]
@tolerious 报 undefined 的错？

**Comment by suhaotian** [comment]
@tolerious 如果是报 undefined 你声明下，const xx = xx
