### ISSUE TITLE
ali-oss 不支持在 cloudflare workers 中使用 

### ISSUE THREAD

**Issue by notedit** [ali-sdk/ali-oss#1264]
安装的版本： 

  "name": "ali-oss",
  "version": "6.18.1",

service core:user:dotai-service: Uncaught ReferenceError: window is not defined
  at index.js:42592:8 in node_modules/ali-oss/dist/aliyun-oss-sdk.js
  at index.js:19:52 in __require2
  at index.js:69155:30

**Comment by notedit** [comment]
自己封装了一下 API   解决

**Comment by rowthan** [comment]
> 自己封装了一下 API 解决

有发包吗～

**Comment by ricky11** [comment]
How did you get ali-oss to work in cloudflare workers?

**Comment by ricky11** [comment]
In a cloudflare worker ,if 

import OSS from 'ali-oss'

I get a window not defined already, even before I create the cleint.

How are you importing ES6 style?

const OSS = await import('ali-oss/dist/aliyun-oss-sdk');
const { default: OSS } = await import('ali-oss')
import {OSS} from 'ali-oss';

Which way?
