### ISSUE TITLE
如何实现大文件断点续传下载

### ISSUE THREAD

**Issue by swift-fs** [ali-sdk/ali-oss#1274]
如题，我看到Go，Java都有断点续传下载，唯独nodejs没有，想问一下是实现难度大吗？

**Comment by YunZZY** [comment]
可以参考这篇文档：https://help.aliyun.com/zh/oss/developer-reference/resumable-upload-5

**Comment by swift-fs** [comment]
> 如题，我看到Go，Java都有断点续传下载，唯独nodejs没有，想问一下是实现难度大吗？

已实现。
