### ISSUE TITLE
listBuckets 的类型声明

### ISSUE THREAD

**Issue by floruitShow2** [ali-sdk/ali-oss#1295]
`listBuckets(query: OSS.ListBucketsQueryType | null, options?: OSS.RequestOptions): Promise<OSS.Bucket[]>;`

按声明文件的描述，listBuckets 的返回值应该是 buckets 数组，但是调用后的返回值却是这样的？

![7465bf63206e7e41597a3f9337a66c1](https://github.com/ali-sdk/ali-oss/assets/82753320/70afa4e9-8be5-4824-9f0a-d0807ff0f500)

有点奇怪

依赖版本：
"ali-oss": "^6.20.0",
"@types/ali-oss": "^6.16.11",

**Comment by YunZZY** [comment]
@types/ali-oss这个库不是官方维护的，目前需要您自己定义一下类型或者用别的方式绕过呢
