### ISSUE TITLE
OSS上传回调中如何设置自定义header的

### ISSUE THREAD

**Issue by Johnny-young** [ali-sdk/ali-oss#1297]
![image](https://github.com/ali-sdk/ali-oss/assets/22856244/b2037086-085f-4c4d-b4f8-0eb53078f48b)
例如，oss发送回调请求到我的服务器，如何自定义header在这个回调请求中？因为请求到我的服务器时，需要请求头携带token验证，官方文档没有案例

**Comment by YunZZY** [comment]
根据官网的[Callback](https://help.aliyun.com/zh/oss/developer-reference/callback)文档，是不支持自定义header的呢，如果您有什么特殊场景，可以提工单找售后支持一下
