### ISSUE TITLE
(node:32184) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.

### ISSUE THREAD

**Issue by ShenHongFei** [ali-sdk/ali-oss#1303]
- **Browser Version or Node Version**:
v22.2.0
- **ali-oss Version**:
"ali-oss": "^6.20.0",
- **Mini Showcase Repository**:
- **Network Resoponse Header x-oss-request-id**:

**Comment by YunZZY** [comment]
代码里目前没有找到直接调用util._extend的地方，可以提供下是调用什么方法时出现的这条警告吗，我们看下是不是依赖的库需要升级
