### ISSUE TITLE
signatureUrl方法修改 process、response 参数后访问链接提示 SignatureDoesNotMatch

### ISSUE THREAD

**Issue by JeanCHhhh** [ali-sdk/ali-oss#1310]
oss-js-sdk：6.20.0 

场景：使用 signatureUrl 方法，携带 stsToken，入参修改 x-oss-process、response-content-type、response-content-disposition 时，签名链接无法访问，提示 “SignatureDoesNotMatch”

```js
const OSS = require('ali-oss');

const client = new OSS({
  accessKeyId: 'my accessKeyId',
  accessKeySecret: 'my accessKeySecret',
  stsToken:  'my stsToken',
  region: 'oss-cn-hangzhou',
  bucket: 'my bucket',
  secure: true,
});

const url = client.signatureUrl('object name', {
  process: 'doc/preview',
  response: {
    'content-type': 'text/html',
    'content-disposition': 'inline',
  },
});
```

其他验证case：
1. signatureUrl 入参仅修改 x-oss-process，不会提示 "SignatureDoesNotMatch"（但报错需要增加 response-content 参数）
2. signatureUrl 入参仅修改 response-content-type、response-content-disposition，提示 "SignatureDoesNotMatch"
3. signatureUrl 入参不修改 x-oss-process、response-content-type、response-content-disposition，可正常访问

**Comment by YunZZY** [comment]
6.21.0版本已发布
