### ISSUE TITLE
node使用，上传的时候没有指定cname，但是起了一个自定义域名解析到aliyuncs的域名，这样可以生效吗？

### ISSUE THREAD

**Issue by p2227** [ali-sdk/ali-oss#1323]
```
const client = new OSS({
      accessKeyId: credentials.accessKeyId!,
      accessKeySecret: credentials.accessKeySecret!,
      stsToken: credentials.securityToken,
      bucket,
      region,
      endpoint,
      refreshSTSToken: async () => {
        const info = await this.getSts();
        const credentials = info.data.data;

        return {
          accessKeyId: credentials.accessKeyId!,
          accessKeySecret: credentials.accessKeySecret!,
          stsToken: credentials.stsToken,
        };
      },
      refreshSTSTokenInterval: 300000,
    });
```

- **Browser Version or Node Version**: Node v18.20.4
- **ali-oss Version**: "ali-oss": "^6.20.0",
- **Mini Showcase Repository**:
- **Network Resoponse Header x-oss-request-id**: 66BD9C1335EA8A3730061A0F

上传的时候，初始化oss没有用 cname，只是在阿里云的后台配置了 s.xxx.com cname到 somebucket.oss-cn-shanghai.aliyuncs.com

那是不是 somebucket.oss-cn-shanghai.aliyuncs.com/object.key与  s.xxx.com/object.key 都能访问到我上传的文件（排除apk等特殊情况）

**Comment by YunZZY** [comment]
1. 对于“在阿里云的后台配置了 s.xxx.com cname到 somebucket.oss-cn-shanghai.aliyuncs.com”，如果指的是[绑定自定义域名至Bucket默认域名](https://help.aliyun.com/zh/oss/user-guide/map-custom-domain-names-5)的话，那么通过bucket域名和您的自定义域名都可以访问到您的文件（前提是您没有什么其他的特殊配置）
2. 在JS SDK中使用自定义域名时，需要在初始化的时候将cname置为true

**Comment by p2227** [comment]
是生效的，谢谢大家。
