### ISSUE TITLE
list() API 返回数据中，子目录和父目录同名时，返回的prefixes值有问题

### ISSUE THREAD

**Issue by xiazhaohui** [ali-sdk/ali-oss#1333]
- **Browser Version or Node Version**: userAgent:
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Code/1.92.2 Chrome/124.0.6367.243 Electron/30.1.2 Safari/537.36"
- **ali-oss Version**: "^6.21.0"
- **Mini Showcase Repository**:
- **Network Resoponse Header x-oss-request-id**:

在开发vscode插件中，有使用到阿里云OSS的SDK ali-oss，通过调用 list() API 查询数据。在使用过程发现，当一个bucket下某个目录和子目录名字一样，API 返回数据中 prefixes 值不对。

比如，我要查询virtual_human目录下名为27的子目录的数据，该27目录有一个子目录，也叫27
<img width="650" alt="image" src="https://github.com/user-attachments/assets/b04e93f4-1ed0-4207-95d9-1a829bbf6f41">

请求参数为
```
client.list({prefix: 'virtual_human/27/', delimiter: "/", "max-keys": 1000}, {}) 
```

返回数据中 prefixes 值为
```
{
    "res": {
        "status": 200,
        "statusCode": 200,
        "statusMessage": "OK",
        "headers": {
            "content-length": "842",
            "connection": "keep-alive",
            "content-type": "application/xml",
            "date": "Fri, 06 Sep 2024 03:13:09 GMT",
            "keep-alive": "timeout=4",
            "proxy-connection": "keep-alive",
            "server": "AliyunOSS",
            "vary": "Origin",
            "x-oss-request-id": "66DA7345CEA8B835368C713A",
            "x-oss-server-time": "85"
        },
        "size": 842,
        "aborted": false,
        "rt": 140,
        "keepAliveSocket": true,
        "data": {
            "type": "Buffer",
            "data": []
        },
        "requestUrls": [ ],
        "timing": null,
        "remoteAddress": "127.0.0.1",
        "remotePort": 4780,
        "socketHandledRequests": 1,
        "socketHandledResponses": 1
    },
    "objects": [],
    "prefixes": [
        "virtual_human/27//",
        "virtual_human/27/Audio/",
        "virtual_human/27/Image/",
        "virtual_human/27/Video/",
        "virtual_human/27/audio/",
        "virtual_human/27/image/",
        "virtual_human/27/video/"
    ],
    "nextMarker": null,
    "isTruncated": false
}
```

可以看到，prefixes数据中本该返回 "virtual_human/27/27/", 但是却返回了一个 "virtual_human/27//"。
是不是因为子目录和父目录同名的原因，造成的一些处理逻辑问题？

**Comment by YunZZY** [comment]
我这边没有复现出这个问题，您那边如果还能复现的话，可以提单找客服看下呢

**Comment by xiazhaohui** [comment]
> 我这边没有复现出这个问题，您那边如果还能复现的话，可以提单找客服看下呢

嗯嗯呢 找时间提个工单吧 谢谢🙏

**Comment by YunZZY** [comment]
好的，辛苦，因为排查的话可能需要麻烦您提供一些信息，所以还是提单比较合适
