### ISSUE TITLE
Refresh sts token manually

### ISSUE THREAD

**Issue by divinerapier** [ali-sdk/ali-oss#1335]
- **Browser Version or Node Version**:
- **ali-oss Version**:
- **Mini Showcase Repository**:
- **Network Resoponse Header x-oss-request-id**:

在 Spark + Iceberg + OSS 的场景中，如何处理 STS Token 自动刷新。

我们开发了一套基于上述技术栈的大数据开发平台，为了保证在开发场景中，避免出现 accesskey / secretkey 泄漏的场景，打算使用 STS Token 让 Spark 能够访问保存在 OSS 上的 Iceberg 数据表。但是，通过文档 https://help.aliyun.com/zh/oss/developer-reference/authorize-access-1#section-nyk-bzc-kfb 了解到，Token 最长有效时间仅为 1h，这个应该是无法满足需求的。

请问，在这个场景能够通过 refreshToken 来刷新吗？

**Comment by YunZZY** [comment]
JS SDK支持更新STS Token的，您可以参考下这篇文档
https://help.aliyun.com/zh/oss/developer-reference/node-js-configure-access-credentials

**Comment by divinerapier** [comment]
> JS SDK支持更新STS Token的，您可以参考下这篇文档
> https://help.aliyun.com/zh/oss/developer-reference/node-js-configure-access-credentials

感谢回答，我去学习一下。

**Comment by divinerapier** [comment]
> JS SDK支持更新STS Token的，您可以参考下这篇文档 https://help.aliyun.com/zh/oss/developer-reference/node-js-configure-access-credentials

@YunZZY 您好，我看到文档中使用 sts token 的方法是基于 oss 本身提供了配置，直接设置参数就可以。可能和我的预期需求有一些不同。

我的目标是在 spark 应用中，访问 oss 的文件。请问，这种情况要如何配置 sts token 呢？oss 是公司内部私有化部署的服务。

**Comment by YunZZY** [comment]
这个问题需要进一步了解和分析一下您的场景，麻烦提工单咨询下售后吧。

**Comment by divinerapier** [comment]
好的。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by divinerapier** [comment]
> 这个问题需要进一步了解和分析一下您的场景，麻烦提工单咨询下售后吧。

好的。

**Comment by divinerapier** [comment]
@YunZZY 再请教一个问题。我印象中，oss 对同一个 AccessKey 的请求有频率的限制，如果使用 STS 的话，同一个 AccessKey 申请的不同 STS 是否就不受这个限制了?

**Comment by YunZZY** [comment]
这个限制是按照bucket所属主账号来限制，不按照子账号来限制的，更详细的您可以咨询下售后
