### ISSUE TITLE
Append Object support?

### ISSUE THREAD

**Issue by liuyanghejerry** [ali-sdk/ali-oss#134]
I see there's an API for appending objects, but I can't find it supported in this library.

Do we have any support on this? If no, any plans on it?

Ref: https://help.aliyun.com/document_detail/31981.html
API: http://docs-aliyun.cn-hangzhou.oss.aliyun-inc.com/pdf/oss-sdk-cn-zh-2016-08-17.pdf

**Comment by rockuw** [comment]
> Do we have any support on this?
No.

>If no, any plans on it?
Maybe. Later.

**Comment by binghaiwang** [comment]
node is support , but is not support for browser, we will support it later
