### ISSUE TITLE
用 nodes js api 调用服务虽然出现错误了，但是还是上传了

### ISSUE THREAD

**Issue by xiekw2010** [ali-sdk/ali-oss#136]
![screenshot](https://img.alicdn.com/tps/TB1FMESMVXXXXctXFXXXXXXXXXX-2686-1572.jpg)

这个是我上传了，虽然 try catch 到了错误，但线上还是成功的URL 地址 http://wechatlook.oss-cn-shanghai.aliyuncs.com/2016/8/29/bbb11500-81c8-4335-935f-8959b78fa9bc.gif

**Comment by rockuw** [comment]
与 #107 遇到的问题一样。

**Comment by rockuw** [comment]
@fengmk2 按理来说我们使用了keep-alive的agent，是会维护一个连接池的吧？为什么同时请求数多的时候会出现socket hang up的错误？

**Comment by fengmk2** [comment]
同时请求数是多少呢？10，100，还是1000？

**Comment by rockuw** [comment]
@xiekw2010 你能提供一个复现的代码吗？

我这样试了几次都未能重现：

```js
for (var i = 0; i < 200; i++) {
  co(function* () {
    var r = yield client.put('put-object', '/tmp/file.100k');
    console.log(r);
  }).catch(function (err) {
    console.log(err);
  });
}
```

**Comment by nothingmi** [comment]
这个就会出现hang up的情况，几乎是必现，并发连接数应该在30左右 @rockuw 

```javascript
#!/usr/bin/env node

// MUST LF

'use strict';

var co = require('co');
var OSS = require('ali-oss');
var fs = require('fs');
var path = require('path');
var program = require('commander');

program
    .version(process.version)
    .option('-l, --local-path [cwd]', 'Local Path', process.cwd())
    .option('-b, --bucket [name]', 'Bucket Name', '')
    .option('-k, --key [empty]', 'Key Prefix', '')
    .option('-r, --region [oss-cn-shenzhen]', 'Region of Bucket', 'oss-cn-shenzhen')
    .option('-i, --access-key-id [empty]', 'Access Key ID', '')
    .option('-s, --access-key-secret [empty]', 'Access Key Secret', '')
    .parse(process.argv);

program.localPath = path.normalize(program.localPath);

var tasks = [];

var client = new OSS({
    region: program.region,
    accessKeyId: program.accessKeyId,
    accessKeySecret: program.accessKeySecret,
    bucket: program.bucket
});

function upload(dir) {
    let list = fs.readdirSync(dir);
    list.forEach((it) => {
        let stat = fs.statSync(`${dir}/${it}`);
        if (stat.isFile()) {
            tasks.push({
                key: program.key + `${dir}/${it}`.substr(program.localPath.length + 1),
                path: `${dir}/${it}`
            });
        } else {
            upload(`${dir}/${it}`);
        }
    });
}

upload(program.localPath);

console.log(tasks);

tasks.forEach((it) => {
    co(function *() {
        let key = it.key;
        let stream = fs.createReadStream(it.path);
        let result = yield client.put(key, stream);
        console.log(result);
    }).catch(function (err) {
        console.error(err);
        process.exit(1);
    });
});
```

**Comment by fengmk2** [comment]
oss client 不是不会去控制并发数的，这个并发控制应用由使用者来控制的。
默认的 agent `maxSockets= Infinity` 是不会限制并发数的 https://github.com/ali-sdk/ali-oss/blob/master/lib/client.js#L21

@nothingmi 你可以传入你自己初始化的 agent，设置 maxSockets = 30 https://github.com/ali-sdk/ali-oss/blob/master/lib/client.js#L45 ，就可以控制最多对一个 host 创建 30个 sockets 的限制了。

**Comment by on99** [comment]
```

**Comment by on99** [comment]
确认了一下, 在阿里云内网中无此问题.

**Comment by taojoe** [comment]
阿里云内网遇到此问题

**Comment by kidlj** [comment]
阿里云内网，使用internal，并发上传 4 个 10~20M 的视频文件，每次都出现这个问题。

**Comment by wuyuedefeng** [comment]
阿里内网 设置`"internal": true`, 会报·socket hang up (req "error")，  不设置，用外网运行正常，求教！！！

**Comment by harlanc** [comment]
@fengmk2  能具体举个例子如何才能控制并发socket数么？

http.Agent = function () {}
http.Agent.defaultMaxSockets = 4

找到了上面两行代码，默认是并发4个？？

**Comment by lovelife10000** [comment]
遇到一样的问题，有时候数组里第2个就上传不上去，有时候都能上传上去，大多数还是卡在第二个上传不上去ResponseError: socket hang up, PUT
 for (let i = 0; i < d.length; i++) {
        if (d[i].status === 'downloaded') {
            let filename = d[i].filename;
            let OSSName = filename.slice(filename.lastIndexOf('/') + 1);
            const wenjianjia = moment().format('YYYY-MM-DD').toString();
            let r1 = await client.put(OSSName, path.join(__dirname, '../public/upload/images/' + wenjianjia + '/' + OSSName));
            console.log(1);
            sleep(10000);
            console.log(2);
        }

    }

**Comment by luozhang002** [comment]
socket hang up 这种问题，之前我写过类似的demo,通过promise.all去控制并发数上传是OK的。

**Comment by PeterRao** [comment]
用for of循环迭代await。这种写法相当于同时上传所有文件了
