### ISSUE TITLE
修改文件的content-disposition

### ISSUE THREAD

**Issue by ovack** [ali-sdk/ali-oss#137]
网页版可以手动修改，但是文件太多，sdk我查阅文档没有修改content-disposition的接口

**Comment by rockuw** [comment]
可以通过copy文件自身来修改文件的header：

```js
yield client.copy('a', 'a', {
  headers: {
    'content-disposition': 'value'
  }
});
```

但是目前SDK存在一个bug，导致不能正确地修改header。稍后会修复。

**Comment by chuge** [comment]
copy存在不能正确地修改header这个问题是否解决了？
