### ISSUE TITLE
multipartUpload 希望支持 base64 Blob ArrayBuffer 等

### ISSUE THREAD

**Issue by wangfengming** [ali-sdk/ali-oss#141]
我使用[lrz](https://github.com/think2011/localResizeIMG)压缩图片后无法上传oss

**Comment by rockuw** [comment]
如果文件不大，可以直接使用put/putStream接口上传。

**Comment by wangfengming** [comment]
是在浏览器中使用。

**Comment by rockuw** [comment]
浏览器中也可以使用put接口：https://github.com/rockuw/oss-in-browser/blob/master/app.js#L66

**Comment by wangfengming** [comment]
https://github.com/ali-sdk/ali-oss/blob/master/lib/object.js#L55
所以我需要先把 Blob/base64/ArrayBuffer 转换成Buffer是吗？
https://github.com/feross/buffer

**Comment by rockuw** [comment]
我上面贴的链接已经有完整的例子了啊：
![image](https://cloud.githubusercontent.com/assets/1209779/19295666/b2ccfe1e-9068-11e6-875a-956a2d3dd368.png)

**Comment by wangfengming** [comment]
我知道，我只是提个意见，并不是是所有人都是在broswerify环境下开发的，原生不支持Buffer。
multipartUpload 本来是可以直接支持blob的，只是你们加了个type验证让blob不通过。

**Comment by rockuw** [comment]
Buffer是通过`OSS.Buffer` export出来的。

```js
var Buffer = OSS.Buffer;
```

与browserify无关。

**Comment by Sweet-KK** [comment]
> https://github.com/ali-sdk/ali-oss/blob/master/lib/object.js#L55
> 所以我需要先把 Blob/base64/ArrayBuffer 转换成Buffer是吗？
> https://github.com/feross/buffer

请问你解决了吗 我也是lrz压缩了 上传不了 base64 blob arraybuffer file都不行  multipartUpload和put方法都试过了 各有各的报错
