### ISSUE TITLE
百度编辑器图片自动上传到OSS上

### ISSUE THREAD

**Issue by guoliangli123** [ali-sdk/ali-oss#145]
当我改写百度编辑器使图片直接上传到OSS上时，ali-oss报错无法获得文件，是什么原因呢？因为百度编辑器里的input是写在iframe里面，所以无法获取文件吗

**Comment by mars-coder** [comment]
使用的哪个接口？是浏览器环境吗？还是nodejs环境？
如果是浏览器环境使用put接口的时候不能直接传入一个文件地址，浏览器环境put接口没办法直接读取本地文件，只能传入一个buffer或是一个stream

**Comment by binghaiwang** [comment]
浏览器端请将数据内容转换成file或buffer 使用multipartUpload
