### ISSUE TITLE
Promise.all多文件上传的问题

### ISSUE THREAD

**Issue by renshan1990** [ali-sdk/ali-oss#148]
我们项目的使用环境是IOS10，使用Promise.all并发上传时可能会出现文件校验失败，概率非常高。而且IOS9、PC均无这个问题；我猜测上传过程中出现了分片乱续而导致。

**Comment by mars-coder** [comment]
能说明一下你使用的接口和具体使用的方法吗？

**Comment by renshan1990** [comment]
坑爹的产品需要在手机浏览器端上传多张(10-20)无压缩图片，每一个上传我使用的Promise来包裹，通过Promise.all触发上传。我使用本地存储来保存上传进度，很可能是key错乱了，后来使用递归来顺序上传便好。这应该不是一个bug。

**Comment by renshan1990** [comment]
这个问题是应因为我在上传进度的key中使用了文件(File API)的元数据，IOS9和IOS10浏览器API不一致导致的。

**Comment by mars-coder** [comment]
额，看着有点懵，能先说一下你具体使用的哪个接口吗？(put? putStream? multipartUpload?)
代码运行所在的浏览器是Safari？还是Chrome？
最好能把有问题的代码也发一下，文字描述理解起来比较费劲，注意不要把敏感信息发出来……

**Comment by renshan1990** [comment]
接口是multipartUpload，浏览器是safari。代码仓促之下写的，太丑就不贴出来了，我所描述的问题不是一个bug^_^，是我粗心大意弄错的。。。。
