### ISSUE TITLE
OSS 的 Authorization 怎么生成

### ISSUE THREAD

**Issue by harrisz** [ali-sdk/ali-oss#151]
请问如何在服务端生成Authorization，然后在前端使用Authorization，前端上传文件？

**Comment by rockuw** [comment]
1. OSS的签名细节有官方文档：https://help.aliyun.com/document_detail/31951.html
2. 你也可以参考ali-oss的实现：https://github.com/ali-sdk/ali-oss/blob/master/lib/client.js#L163
