### ISSUE TITLE
webpack 报错SyntaxError: Unexpected token: keyword (const) [./~/ali-oss/lib/client.js:67

### ISSUE THREAD

**Issue by wuzhuzhu** [ali-sdk/ali-oss#152]
node版本 6.8.1
现在有解决方案了吗

**Comment by zqmath1994** [comment]
待解决 这个问题

**Comment by mars-coder** [comment]
抱歉，我们暂时没有通过webpack打包过，稍后我们搭建一个webpack测试确认一下问题，然后进行修正

**Comment by jk1420** [comment]
同样使用webpack管理代码，刚处理了import aliyun-oss失败的问题，又遇上了这个issue，不知道现在是否有具体的解决方案

**Comment by boostbob** [comment]
在meteor中使用，使用 meteor build 打包，报同样的错误，无法处理 const, generator 函数等，请问有没有适用于 node 4.6.1 的源代码版本啊?

**Comment by li2go** [comment]
0.0 。一开始的时候使用webpack打包出了问题，然后在webpack里面加上了 fs，child_process的例外。现在准备打包发布的时候又碰到了问题，，就是这。
```
ERROR in e68dbf99/bundle.main.js from UglifyJs
SyntaxError: Unexpected token: keyword (const) [./~/ali-oss/lib/client.js:68,0]
```

**Comment by wuxjim** [comment]
遇到同样的问题，这是阿里官方维护的库么？

**Comment by fengmk2** [comment]
@wuxjim 请问如何重现？

**Comment by wuxjim** [comment]
@fengmk2 我这边是基于 ant-design 进行的开发，使用官方的 atool-build（封装的 webpack）进行打包。如上面其他人提到的，主要问题是打包时压缩插件引起的，因此在调试模式下（dora）能够正常运行。但是我查看了一下，用的其他很多库也都是 es6, 打包都没问题。。就是你们这个库报错。。我想是不是需要你们把打包好的发布出来？

**Comment by wuxjim** [comment]
@fengmk2  不好意思，是我自己 webpack 不太熟悉，手动设置把你们库加入到例外就可以了

**Comment by PeterRao** [comment]
使用 4.11.0 版本
