### ISSUE TITLE
使用multipart上传出现cors问题

### ISSUE THREAD

**Issue by zhaoyao91** [ali-sdk/ali-oss#153]
![image](https://cloud.githubusercontent.com/assets/3808838/20338986/201af184-ac15-11e6-9a84-14bb5dea9a6b.png)

关键是cors也进行了设置的

![image](https://cloud.githubusercontent.com/assets/3808838/20339018/41400638-ac15-11e6-8d5f-23c488862833.png)

**Comment by zhaoyao91** [comment]
我发现哈，cors设置为具体的域名就没有问题，另外，域名要用*的话，使用cdn引入的sdk也没有问题，这是什么毛病？

**Comment by mars-coder** [comment]
用这个文档的demo代码试一下？

**Comment by mars-coder** [comment]
长时间无更新，默认问题已经解决，issue关闭。
如果还有问题，请开新issue
