### ISSUE TITLE
前端是通过webpack打包的，如何使用JavaScript SDK呢？

### ISSUE THREAD

**Issue by tolerious** [ali-sdk/ali-oss#154]
我的前端是基于Vue.js的，然后用Webpack进行打包， 文档里面说引用JavaScript SDK的浏览器方式要直接引入标签， 那么针对我这种好用Webpack打包的项目如何使用呢？

**Comment by mars-coder** [comment]
能具体描述一下你是在代码里怎么引用js sdk的吗？

**Comment by 1120340041** [comment]
就是直接在html中引入了js的SDK，但是用webpack打包启动之后，OSS对象是undefined

**Comment by PeterRao** [comment]
使用 4.11.0 版本
