### ISSUE TITLE
Multipart-Upload failed when file size exceeds 500MB

### ISSUE THREAD

**Issue by Ryannnnnnn** [ali-sdk/ali-oss#160]
I use Chrome to upload a file that has a size of more than 500MB, it ended up with an error `net::ERR_FILE_NOT_FOUND` when nearly 500MB content uploaded. 

But it works fine on Safari.

Seems like it's a bug of Chrome, which is discussed on:
* https://github.com/feross/webtorrent/issues/319
* https://code.google.com/p/chromium/issues/detail?id=375297

I'm not quite sure if this is the problem I'm facing to. Or the problem in [multipart.js L113]( https://github.com/ali-sdk/ali-oss/blob/master/lib/multipart.js#L113) you create all jobs all in once that you have to read the entire file into memory.

Have you guys meet the same issue before? and I'm wondering if there is some workaround already?

**Comment by rockuw** [comment]
This has been fixed in #155 . Will release a new version soon. 

Thanks.

**Comment by zzuieliyaoli** [comment]
@rockuw 

When will the new version release?

Thanks.

**Comment by rockuw** [comment]
@Ryannnnnnn @zzuieliyaoli 

4.6.3

Sorry for the delay. Thanks.
