### ISSUE TITLE
zlib.gunzip is not a function 错误

### ISSUE THREAD

**Issue by jieme** [ali-sdk/ali-oss#165]
采用browser方式访问执行https://github.com/rockuw/oss-in-browser中的代码aliyun-oss-sdk.js文件报错。
“Uncaught TypeError: zlib.gunzip is not a function”
![image](https://cloud.githubusercontent.com/assets/5328234/21385631/3bdb799c-c7aa-11e6-9da6-0c28772f22f6.png)

![image](https://cloud.githubusercontent.com/assets/5328234/21385617/2610d4fe-c7aa-11e6-999b-745f6cffb050.png)

**Comment by mars-coder** [comment]
请具体描述一下你的使用方式？以及运行代码的浏览器类型和版本。

**Comment by mars-coder** [comment]
长时间无更新，默认问题已经解决，issue关闭。
如果还有问题，请开新issue
