### ISSUE TITLE
不兼容IE吗？

### ISSUE THREAD

**Issue by euphratica** [ali-sdk/ali-oss#171]
webpack之后，在IE 11以及10下报错

**Comment by mars-coder** [comment]
暂时还没有做webpack的兼容，目前在IE中直接引用是可以work的，能否把相关的报错截图贴一下，后续我们做webpack兼容的时候来一并解决

**Comment by euphratica** [comment]
![qq 20170410163133](https://cloud.githubusercontent.com/assets/5935516/24853189/d0bd0c8e-1e0c-11e7-95d4-9c64c903426a.png)
![zw phx d59l qm6l ink0b](https://cloud.githubusercontent.com/assets/5935516/24853195/d7e9f76a-1e0c-11e7-8bf4-ea4cf82c1492.png)
