### ISSUE TITLE
360极速浏览器使用multipartUpload上传文件出错

### ISSUE THREAD

**Issue by zxfishhack** [ali-sdk/ali-oss#172]
在360浏览器中，使用multipartUpload上传超过500MB文件时，在超过500MB的时候，会出现content-length为0的请求，并且不会报错。但会在最后的确认文件完成时出错。
并且无法使用progress回调的checkpoint恢复断点续传。

sdk版本：4.6.3

**Comment by mars-coder** [comment]
收到，我们会尽快调查这个问题

**Comment by ypwlal** [comment]
sdk版本： 4.8.0也有这个问题

**Comment by jinjinyun** [comment]
Safari浏览器也有问题，100m以上的也可能有问题。不稳定复现。可能和Safari的非焦点状态网络连接挂起有关系。直接导致的结果是有些分片在服务端的size＝0。前端并没有把这个错暴露出来。

除了这种情况，可能还有其他的分片上传失败情况。sdk啥时候会考虑实现分片重传机制？

**Comment by wuzhihui1123** [comment]
我这边也遇到这个问题，当前很多用户在上传比较大点的文件时会失败（safari和360浏览器）。麻烦阿里云大神们紧急解决下[拜托]

**Comment by zxdmrg** [comment]
这个问题现在解决了吗？360浏览器不定时出现这个问题。用的是oss-sdk-4.4.4

**Comment by semisleep** [comment]
这个可是很严重的问题，导致随机上传失败，客户经常投诉。
怎么从一月份到现在还没解决这个问题啊？有没有人在维护这个库的？

**Comment by daqi** [comment]
建议大家暂时先走一下服务器，用这个库做一个中转 [aliyun-oss-upload-stream](https://github.com/berwin/aliyun-oss-upload-stream)

**Comment by fengmk2** [comment]
ping @mars-coder

**Comment by wuzhihui1123** [comment]
因为这个问题， 现在都是强制客户去使用chrome浏览器进行文件上传。问题提出到现在已经快一年了，都没有修复和消息。
  之前我是在对多个云存储平台调研后选择阿里云的OSS，但现在因为这个问题，我需要承受大家对我的质疑和压力 @mars-coder @fengmk2 @rockuw

**Comment by fengmk2** [comment]
@wuzhihui1123 非常抱歉，主要原因是这个模块只在 nodejs 环境测试和使用的，浏览器支持是额外做的。

@mars-coder @rockuw 是否详细跟进一下？或者还有谁可以来跟进？

**Comment by mars-coder** [comment]
很多浏览器在blob类型对象的内存有限制，另外在js的对象内存释放各个浏览器的策略也不同，之前通过其他方法让chrome浏览器大概率的不出问题，但是目前还没有完美的解决方案，相关的一些参考文章：
https://bugs.chromium.org/p/chromium/issues/detail?id=375297
http://ccloli.com/201509/bullshit-about-blob-and-object-url/

360这个看起来也是类似问题，但是它的内存管理非常诡异，360的资料比较少，暂时还没找到很优雅的方案来解决，我们正在筹备浏览器专用版本的sdk，目前可以先使用plupload这个组件来协助在360中上传：
https://help.aliyun.com/document_detail/31927.html?spm=5176.doc31926.6.632.VJnFQ2
http://oss-demo.aliyuncs.com/oss-h5-upload-js-php-callback/index.html?spm=5176.doc31927.2.3.a8Uc0f

**Comment by wuzhihui1123** [comment]
谢谢回复 @fengmk2 @mars-coder ， 期待浏览器专用版的SDK。我这边也再了解下其他的上传方式。
另外： 同样的问题也会出现在firefox,safari等浏览器中

**Comment by PeterRao** [comment]
底层 https://github.com/jhiesey/stream-http/issues/57 修复，默认使用arraybuffer 进行数据传输。发版4.11.5解决。

**Comment by wuzhihui1123** [comment]
@PeterRao  这是个影响了我这边很长时间的一个痛点，  大赞
