### ISSUE TITLE
引入oss上传文件，报跨域等一系列问题？麻烦看下

### ISSUE THREAD

**Issue by ninjai001** [ali-sdk/ali-oss#175]
![image](https://cloud.githubusercontent.com/assets/12545571/21748091/6a41edec-d5b6-11e6-80fa-8bf35e199829.png)

以下是报的错误
![image](https://cloud.githubusercontent.com/assets/12545571/21748097/80c77f78-d5b6-11e6-81f8-9016805e2637.png)

**Comment by mars-coder** [comment]
这段代码是在浏览器中(chrome)执行吗？如果是可以参考这个demo代码：
https://github.com/rockuw/oss-in-browser/blob/master/app.js
如果demo代码不能参考，最好说明一下执行环境和代码的上下文。

**Comment by ninjai001** [comment]
我在手机h5的方式，npm  install  ali-oss；
然后在react 工程中这么引用
var OSS = require('ali-oss').Wrapper;
![image](https://cloud.githubusercontent.com/assets/12545571/21841444/298bca84-d81d-11e6-9249-4dfc34eed4fd.png)
下面是错误信息
![image](https://cloud.githubusercontent.com/assets/12545571/21841524/6e55b7c4-d81d-11e6-89c3-0b70fba58a61.png)

**Comment by ninjai001** [comment]
服务端，我们已经设置了跨域的问题

**Comment by mars-coder** [comment]
目前还还不支持React框架

**Comment by ninjai001** [comment]
这么大阿里！！！！

**Comment by ninjai001** [comment]
包问题，其实是没问题的，就是不知道网络请求这块为什么报跨域问题

**Comment by ninjai001** [comment]
那ali-oss 包在什么环境下用？不知道网络请求这块为什么报跨域问题

**Comment by mars-coder** [comment]
跨域请求的设定参考文档：【Bucket设置】部分
https://help.aliyun.com/document_detail/32069.html?spm=5176.doc44687.6.733.czK2bF

**Comment by ninjai001** [comment]
![2](https://cloud.githubusercontent.com/assets/12545571/21880550/8ad848c2-d8da-11e6-9088-52e9ffeb8e72.png)
 你看返回的response 都是有设置跨域问题

**Comment by mars-coder** [comment]
如果想在浏览器中访问oss，需要在oss bucket中配置跨域属性，配置的方法参考文档：https://help.aliyun.com/document_detail/32069.html?spm=5176.doc44687.6.733.czK2bF
