### ISSUE TITLE
我想问一下javascript  sdk直接让普通用户使用会不会不安全，

### ISSUE THREAD

**Issue by cnzhangxl** [ali-sdk/ali-oss#177]
如果我使用STS设置，让普通用户js sdk，比如使用断点续传，会不会有安全问题，这个javascript sdk的使用场景是哪里，非常感谢

**Comment by mars-coder** [comment]
如果要把sdk给到用户执行，安全起见需要使用sts：
https://help.aliyun.com/document_detail/32075.html?spm=5176.doc32069.2.1.FpkNef
