### ISSUE TITLE
After calling abortMultipartUpload function, browser still uploads file

### ISSUE THREAD

**Issue by zzuieliyaoli** [ali-sdk/ali-oss#182]
Source code of ali-oss shown below.

I find that `abortMultipartUpload` function only posts a delete request, and does nothing about stopping `multipartUpload` function.

Do we have any methods to stop `multipartUpload` function?  

I don't want to see these console errors.

![logos](https://cloud.githubusercontent.com/assets/6713367/22051295/d35ec75a-dd7c-11e6-913a-3d78fb16e0fa.png)

404 response:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchUpload</Code>
  <Message>The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.</Message>
  <RequestId>**********</RequestId>
  <HostId>waffle.oss-cn-shanghai.aliyuncs.com</HostId>
  <UploadId>**********</UploadId>
</Error>

```

https://github.com/ali-sdk/ali-oss/blob/master/lib/multipart.js#L172

```js
proto.abortMultipartUpload = function* abortMultipartUpload(name, uploadId, options) {
  options = options || {};
  options.subres = {uploadId: uploadId};
  var params = this._objectRequestParams('DELETE', name, options);
  params.successStatuses = [204];

  var result = yield this.request(params);

  return {
    res: result.res
  };
};
```

**Comment by mars-coder** [comment]
Sorry,  `abortMultipartUpload` is the only way to stop multipart upload for now.
We will think abort adding a more grace function to stop multipart upload later.

**Comment by zzuieliyaoli** [comment]
Ok, thanks.

**Comment by zzuieliyaoli** [comment]
@mars-coder 

By the way, if you guys patch this, please let me know.

**Comment by fengmk2** [comment]
@zzuieliyaoli you can try to implement `abortMultipartUpload` for us.

**Comment by chaxiaoyou** [comment]
问题没解决 你关闭个毛线

**Comment by zzuieliyaoli** [comment]
@fengmk2 @mars-coder 

讲道理的话，我确实去试了一下。

我的实现思路是：
- 在每次 `uploadPart` 时去校验该 part 是否可以上传
- 在上面的基础上，调用 `abortMultipartUpload` 后就将未上传的 part 设置为 `不可传`

这样的实现，需要对上传过程有更强的控制性：
- 单个 part 是否可以上传
- 上传队列的控制

但是我看了现有的代码：

```js
var jobs = [];
for (var i = 0; i < todo.length; i++) {
   jobs.push(uploadPartJob(this, todo[i]));
}
const defaultParallel = 5;
var parallel = options.parallel || defaultParallel;
var results = yield gather(jobs, parallel);
```

在这里，完全对上传队列以及 part 失去了控制。
我也去看了 `gather` 的实现，并没有发现有相关的方法。

所以，你们有什么好的想法吗？如果有好的想法，我很乐意去实现。

**Comment by encorehe** [comment]
你好 我这也碰到这个问题了 终止了报一个404，然后其他的分片也同时停止了 有解决办法吗 @mars-coder
