### ISSUE TITLE
更灵活的internal选项设置

### ISSUE THREAD

**Issue by fanchangyong** [ali-sdk/ali-oss#188]
我们的需求是,upload使用内网地址，但提供给用户的下载地址使用外网地址。
现在的internal选项是在全局的构造函数中传入的，所以实现不了这个需求。

**Comment by rockuw** [comment]
https://github.com/ali-sdk/ali-oss#getobjecturlname-baseurl

`getObjectUrl`这个接口可以传入一个base url来生成url

**Comment by mars-coder** [comment]
如果没有问题，我就关闭issue，如果还有其他问题，请创建新的issue
