### ISSUE TITLE
上传网页使用 https 承载时上传失败，而使用http 可以。

### ISSUE THREAD

**Issue by orwenxiang** [ali-sdk/ali-oss#194]
请求地址：
https://bk_name.oss-cn-hangzhou.aliyuncs.com:80/3d/35b/3d35b72df9a1203b6d7441a4c6f7efde.mp3?uploads=

表面原因：
使用的协议和端口号不匹配

**Comment by mars-coder** [comment]
能否描述一下具体使用sdk 接口的接口的方式？
是怎么搞出问题中的地址的？

另外目前使用https访问需要在endpoint上指定如下：
```
var client = new OSS({
  accessKeyId: 'your_id',
  accessKeySecret: 'your_key',
  bucket: 'your_bucket,
  endpoint: 'https://oss-cn-hangzhou.aliyuncs.com'
});
```

**Comment by orwenxiang** [comment]
类似的就是使用var client = new OSS({
  accessKeyId: 'your_id',
  accessKeySecret: 'your_key',
  bucket: 'your_bucket,
  endpoint: 'https://oss-cn-hangzhou.aliyuncs.com'
});

**Comment by ypwlal** [comment]
源码中有个涉及到https的参数secure
试试：
```javascript
var client = new OSS({
region: 'oss-cn-hangzhou',
bucket: 'your_bucket',
endpoint: 'https://oss-cn-hangzhou.aliyuncs.com',
secure: true
});
```

**Comment by bighua** [comment]
@ypwlal 碰到类似的问题，确实是设置sercue这个参数，多谢！

**Comment by PeterRao** [comment]
@luozhang002 该问题还存在，下个版本修复下

**Comment by luozhang002** [comment]
@PeterRao 好的
