### ISSUE TITLE
TypeError: S.gunzip is not a function

### ISSUE THREAD

**Issue by printfcoder** [ali-sdk/ali-oss#199]
当请求的参数dir过长时，会报该错误
第一步，从我们后台请求creds:
{
  "data": {
    "accessKeyId": "正常id",
    "accessKeySecret": "正常secret",
    "securityToken": "正常token",
    "path": "E1C879F8-C493-D26A-699D-604DE42A2BE6-COMPANY/task/file/3C9ABAF5-ED88-746E-0E0A-15FAB2DDCBFB-T/201703021331430800/5z7cV506q8/"
  },
  "success": true
}
第二步
urllib.request(url, {
        method: 'GET', 
    }).then{}
此时报该错误，request时后台正确处理请求，并返回第一步中的token等验证信息，then没有执行。
但是当我把path调成E1C879F8-C493-D26A-699D-604DE42A2BE6-COMPANY/task/file/3C9ABAF5/201703021331430800/5z7cV506q8/ 时就正常了

**Comment by printfcoder** [comment]
![image](https://cloud.githubusercontent.com/assets/20906540/23494533/6fcfd514-ff4e-11e6-9e8a-d13281a2a92e.png)

**Comment by mars-coder** [comment]
从你的描述来看，在还没有调用oss js sdk之前就报错了，这个错误应该和oss js sdk无关吧？

**Comment by printfcoder** [comment]
不，如果无关，那为什么把URL缩短就可以了，是不是你们提供的urllib工具有问题。
上传目录的文件名或路径深度与长度调到尽可能大就会报这个错误。
