### ISSUE TITLE
使用koa2将会很常态，ali-oss能不能支持下async/await？

### ISSUE THREAD

**Issue by sessionboy** [ali-sdk/ali-oss#201]
目前使用koa2开发，抛弃generator，使用async/await，可是ali-oss根本不支持，能不能支持下？

**Comment by fengmk2** [comment]
现阶段可以使用 co 将接口变成 Promise 。

**Comment by linkeo** [comment]
现在 Node.js v8 都发布LTS版本了，是时候将接口都改成async function了。

**Comment by loliconer** [comment]
+1，期待async/await

**Comment by feng-fu** [comment]
+1 现在已经2018啦

**Comment by yhc-yhc** [comment]
+1，期待async/await
