### ISSUE TITLE
urllib 工具不能处理深度与长度过长的creds.path   S.gunzip is not a function

### ISSUE THREAD

**Issue by printfcoder** [ali-sdk/ali-oss#203]
之前上传一个问题 [参考](https://github.com/ali-sdk/ali-oss/issues/199)，可能没有描述清楚
简单说就是上传的dir如果过名称过长，就会报错误 S.gunzip is not a function

**Comment by Ryannnnnnn** [comment]
我也碰到这个问题了。

问题在于你在请求 STS 的时候，服务端的返回 Header 为 content-encoding: gzip

然后 ali-oss 用的 urllib 这个库里，decode 时用的 zlib 包没有办法被打包进 SDK，所以出现了这个问题。
换掉 urllib 用别的 HTTP 库即可。

**Comment by printfcoder** [comment]
是的，我用的其它库解决的

**Comment by PeterRao** [comment]
根本原因是浏览器环境的 SDK，是从 node 兼容出来的，对于服务器返回的 gzip 内容，调用了 node 的zlib.gunzip 方法。这边正在抽离出node 核心模块，后续会提出一个浏览器的兼容版本。
