### ISSUE TITLE
上传pdf文件不能上传返回错误

### ISSUE THREAD

**Issue by chaxiaoyou** [ali-sdk/ali-oss#205]
[Error: Unexpected close tag
Line: 0
Column: 94
Char: >
raw xml: <!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>403 Forbidden</title></head><body><h1>403 Forbidden</h1><p>You do not have permission to view this resource.</p></body></html>]
  status: 403,
  requestId: undefined,
  params: 
   { object: '11640/aaa8c26692c1a78820233976eac227d7',
     bucket: 'sz-files',
     method: 'POST',
     subres: 'uploads',
     timeout: undefined,
     headers: {},
     mime: 'application/pdf',
     xmlResponse: true,
     successStatuses: [ 200 ] } }
Error: Unexpected close tag
Line: 0
Column: 94
Char: >

**Comment by chaxiaoyou** [comment]
请问这个问题是什么原因？

**Comment by chaxiaoyou** [comment]
不是pdf类型的文件都可以上传。应该不是文件权限的问题。

**Comment by mars-coder** [comment]
请问是在node环境还是浏览器环境运行报错？
