### ISSUE TITLE
安装之后使用就报错

### ISSUE THREAD

**Issue by AnyGong** [ali-sdk/ali-oss#212]
` ERROR  Failed to compile with 6 errors                                                                                                                                                             7:47:19 AM

These dependencies were not found:

* fs in ./~/ali-oss/lib/object.js, ./~/ali-oss/lib/multipart.js and 3 others
* child_process in ./~/address/lib/address.js
`
我是使用 vue的cli模板 webpack 环境，一启动 npm run dev 就报这个错误

**Comment by luke-Yang** [comment]
请问这个问题解决了嘛？在var oss  = require('ali-oss')的时候报6个错误

**Comment by chezhe** [comment]
遇到相同问题，阿里对问题反应这么慢啊。再不改用七牛去了。

**Comment by fengmk2** [comment]
@mars-coder 跟进看看？

@AnyGong @luke-Yang 你们的重现方式或者报错终端截图能否发一下呢？

**Comment by chezhe** [comment]
我用的 react + webpack , 配置为
```
{
  externals: {
    'ali-oss': 'ali-oss'
  }
}
```
然后通过`<script>`引入库，在使用到的地方没有通过`require`引入，然后可以正常工作了。

**Comment by fantasykai** [comment]
您好，在vue-cli的工程里使用，

这样引入的
npm install ali-oss
npm install co

-- 引入依赖
  "dependencies": {
    "ali-oss": "^4.8.0",
    "axios": "^0.16.1",
    "child_process": "^1.0.2",
    "fs": "0.0.1-security", 
      "co": "^4.6.0",

---npm run dev 启动报错
       ERROR  Failed to compile with 6 errors                                                                                                                                                                                                                                                                      16:51:36

These dependencies were not found:

* fs in ./~/ali-oss/lib/object.js, ./~/ali-oss/lib/multipart.js and 3 others
* child_process in ./~/address/lib/address.js

To install them, you can run: npm install --save fs child_process

安装了 fs child_process ，启动依然报此错误

**Comment by chezhe** [comment]
@fantasykai 浏览器是不支持fs这个包的，如果你用的是webpack的话按照我上面的配置试试，不要使用import，直接在代码里使用，然后用<script>标签引入ali-oss的脚本

**Comment by fantasykai** [comment]
@chezhe 谢谢，我直接只用cdn的方式引入了。。。

**Comment by wuyan1234** [comment]
@chezhe @fantasykai  我也遇到一样的问题，请问一下<script>标签的引入方式是什么样的，cdn的引入方式又是什么样的，麻烦贴出来我看一下，请赐教，谢谢！

**Comment by chezhe** [comment]
@wuyan1234 
这样引入
![default](https://cloud.githubusercontent.com/assets/2902414/26775051/c6ec60d6-4a05-11e7-8e25-16d317140d06.jpeg)

使用时不用像其他模块那样
```
import _ from 'lodash'
```
直接使用OSS的相关函数，我用的VS Code，会提示
![default](https://cloud.githubusercontent.com/assets/2902414/26775155/27c9d0a0-4a06-11e7-8ef8-826c2e9bb78e.jpeg)
运行、编译是没问题的

**Comment by LgxWalker** [comment]
@chezhe 你好，我用vue写项目，但是我按照你的方法用cdn引入也是不行，还是报找不到ali-oss依赖的错误，然后我在webpack配置上写上这个{
  externals: {
    'ali-oss': 'ali-oss'
  }
}，终端没报错，但是在浏览器的控制台就报ali-oss undefined错误，请问一下，还需要配置什么吗？谢谢

**Comment by chezhe** [comment]
@LgxWalker 把控制台信息截图我看一下

**Comment by LgxWalker** [comment]
@chezhe 
![image](https://user-images.githubusercontent.com/20140096/27811459-1ca804b8-6099-11e7-941f-93bf2fb2a10b.png)
这是报的错误，我在webpack上是直接
![image](https://user-images.githubusercontent.com/20140096/27811470-33af8fdc-6099-11e7-9bbf-36bd619111e9.png)这样写

**Comment by chezhe** [comment]
为什么是`ali is not defined`？你的代码部分呢？

**Comment by LgxWalker** [comment]
@chezhe 上面那个webpack配置就是报错的位置，我去掉配置那个的话，就不会报这个错，但是会在终端报错没有ali-oss依赖
![image](https://user-images.githubusercontent.com/20140096/27820662-1232d66e-60d2-11e7-8062-02c8aa9843cf.png)
这个我只是引入而已

**Comment by chezhe** [comment]
把`var OSS = require('ali-oss')`注释掉

类似这样
```
const result = await OSS.urllib.request(`${sip}/oss`, {
      method: 'GET'
    });

    const creds = JSON.parse(result.data);
    const client = new OSS.Wrapper({
      region: region,
      ...
    });
```

**Comment by LgxWalker** [comment]
const result = await OSS.urllib.request(`${sip}/oss`, {
      method: 'GET'
    });
这句话的作用是获取oss上的那些token信息吗，还有`${sip}/oss`这个是什么意思

**Comment by chezhe** [comment]
@LgxWalker 是的，sip是我的服务器地址

**Comment by domingoxx** [comment]
我这边也是同样的问题，  磨了我半天的时间， 提交的工单也是回复的极其慢， 哎，急死我了。 

还是社区的大佬靠谱。

**Comment by zuoge85** [comment]
什么时候能更完美的支持webpack

**Comment by zgdhj95** [comment]
@AnyGong 
我前几天也遇到这个问题了，后来解决了，解决方法和源码已经放到github：

https://github.com/zgdhj95/vue-oss

**Comment by PeterRao** [comment]
使用 4.11.0 版本

**Comment by peterzhanghui** [comment]
@zgdhj95  正解，多谢你的方案，成功解决了同样的问题

**Comment by Katherine-bq** [comment]
在centos7上安装oss2之后，也安装了相关依赖包，成功之后，输入命令导入import oss2后报错如下：ModuleNotFoundError,no module named aliyunsdkcore.http
