### ISSUE TITLE
请求UploadId成功,但报错误 : Uncaught (in promise) Error: Text data outside of root node.

### ISSUE THREAD

**Issue by printfcoder** [ali-sdk/ali-oss#219]
请求UploadId成功：
```
<InitiateMultipartUploadResult>
  <Bucket>wepm-dev</Bucket>
  <Key>E1C879F8-C493-D26A-699D-604DE42A2BE6-COMPANY/task/file/201704051653430800/l09mKu8o1Y/dev.rar</Key>
  <UploadId>FD1DA5621D2B4A4FB9B9A7046F1B316E</UploadId>
</InitiateMultipartUploadResult>
```
但是是sdk报错
错误栈信息:
```
Uncaught (in promise) Error: Text data outside of root node.
Line: 1
Column: 0
Char: 
    at E (aliyun-oss-sdk.min.js:12)
    at k (aliyun-oss-sdk.min.js:12)
    at n.N [as write] (aliyun-oss-sdk.min.js:12)
    at n.r.Parser.n.parseString (aliyun-oss-sdk.min.js:15)
    at n.parseString (aliyun-oss-sdk.min.js:15)
    at Object.r.parseString (aliyun-oss-sdk.min.js:15)
    at o.<anonymous> (aliyun-oss-sdk.min.js:4)
    at aliyun-oss-sdk.min.js:6
    at o (aliyun-oss-sdk.min.js:6)
    at o.i (aliyun-oss-sdk.min.js:6)  
```

我跟踪了一下sdk的代码，文件是aliyun-oss-sdk.js，发现在22367行的not方法存在一个不太严谨的bug
not方法调用了is方法（第21646行），但是明显在该上下文时，not中的参数charclass是一个数组，而is方法仅仅作了一个是否正则表达式的判断，然后如果不是则判断charclass的索引c是否存在，而c是一个字符，不是数字。
如下：
第21646行：
```
 function is(charclass, c) {
    return isRegExp(charclass) ? !!c.match(charclass) : charclass[c];
  }

```
找到这个后，增加判断，如果charclass是数组，则判断c字符是否存在：
```
  function is(charclass, c) {
    if (Array.isArray(charclass)){
      return charclass.indexOf(c) > -1
    }
    return isRegExp(charclass) ? !!c.match(charclass) : charclass[c];
  }
```
问题解决，但是为什么在某些情况下就不会发生这个问题我没有去深究。但是从代码严谨的角度来看，这里是否有些欠缺？

**Comment by mars-coder** [comment]
是使用multipart upload功能吗？调用oss js sdk的代码发一下吧，注意不要贴出来accessID和accessKey

**Comment by printfcoder** [comment]
是的
`
  // 这是下载方法，作为回调函数传送给aliApplyTokenDo
 var downloadFile = function (client) {
            var path = dir + fileName
            // 该步报错上面说的那些错
            var result = client.signatureUrl(path, {
                response: {
                    'content-disposition': 'attachment; filename="' + fileName + '"'
                }
            });

            window.open(result)
            return result;
 };

// 前端用该方法向后台请求OSS 临时token
// func 是下载或上传的回调函数，和demo中差不多
function aliApplyTokenDo(func, type, id) {

            var goClient = (window.top.GoClient || window.opener.top.GoClient).getInstance()

            if (!goClient.isLegal()) {
                alert("<bean:message key="auth.fail" />")
                return
            }

            var url
            switch (type) {
                // 隐藏部分逻辑
            }
             
            return urllib.request(url, {
                method: 'GET',
                headers: goClient.getHeaders()
            }).then(function (result) {   // then 并没有执行
                var creds = JSON.parse(result.data).data;

                var client = new OSS({
                    region: region,
                    accessKeyId: creds.accessKeyId,
                    accessKeySecret: creds.accessKeySecret,
                    stsToken: creds.securityToken,
                    bucket: bucket,
                });

                dir = creds.path

                // 如果是get，则path里包含了文件名
                fileName = creds.fileName
 
                return func(client);
            });
        };`

**Comment by mars-coder** [comment]
只有片段代码，看着比较晕，你的业务是前端使用multipart upload上传，上传前通过调用服务端的接口来获取token对吧？获取token生成签名url的时候报错了吗？请问签名url是为了做啥用？你是自己直接构造url去调用multipart接口吗？还是通过oss js sdk的multipartUpload封装好的方法来调用的？

**Comment by printfcoder** [comment]
对，后台向阿里云申请临时token成功返回，sdk也成功收到，并向阿里云成功申请到UploadId
但是解析失败。
通过oss js sdk的multipartUpload，就是把demo里的代码原封不动，增加个向我们后台申请token的而已。
反正错误的直接原因就是在aliyun-oss-sdk.js的第21646行的is方法，报错时，charclass不是正则，而是数组，而c不是数字索引，而是字符串"\n"。至于为什么直接运行demo时不报错，我也不清楚。

**Comment by printfcoder** [comment]
就是在处理阿里云 OSS返回的
```
<InitiateMultipartUploadResult>
  <Bucket>wepm-dev</Bucket>
  <Key>E1C879F8-C493-D26A-699D-604DE42A2BE6-COMPANY/task/file/201704051653430800/l09mKu8o1Y/dev.rar</Key>
  <UploadId>FD1DA5621D2B4A4FB9B9A7046F1B316E</UploadId>
</InitiateMultipartUploadResult>
```
时错误

**Comment by mars-coder** [comment]
有些信息还希望能提供一下，比如服务端生成token的方式？为啥调用signatureUrl？你在工单上联系一下技术支持的同学加一下我钉钉，详细说一下把

**Comment by printfcoder** [comment]
和服务端生成token无关。
调用signatureUrl是下载用，你们提供的demo中就是这么下载的。
问题的核心就是sdk在处理**已经请求成功的UploadId**时（注意，是已经向阿里云请求成功了uploadID,为什么要请求uploadId我想是你们内部的设计，而sdk在自己处理这个Response XML报的错，哪一行错我已经说得很清楚了）失败，这一整套都是sdk内部的错误，和调用者无关。

**Comment by printfcoder** [comment]
我再理一下过程：
1、向我方后台请求临时token用于临时授权->2、调用sdk，向demo一样使用urllib.request()->3、sdk验证token正确->sdk请求UploadId->Ali OSS返回Rsp XML->sdk解析该xml->失败。

不管怎么请求，都会在urllib.request这一步出错，查看浏览器的network response，请求是成功了的。

**Comment by printfcoder** [comment]
已把我钉钉放在工单上了
