### ISSUE TITLE
React Native 下可以用这个sdk么？或者什么时间能出来RN版本的？

### ISSUE THREAD

**Issue by stlemon** [ali-sdk/ali-oss#222]
RT，谢谢！

**Comment by xclidongbo** [comment]
目前好像不行.找了一圈,没有发现RN版本的出来.

**Comment by luozhang002** [comment]
@xclidongbo @stlemon 目前React Native版本的OSS SDK 项目已经申请开源,可以试用下,有问题可以直接提issue  仓库地址: https://github.com/aliyun/aliyun-oss-react-native  develop分支,目前刚发布版本aliyun-oss-react-native 0.0.1-alpha.1，端午期间我这边会把文档demo，梳理下，然后再发个版本，有问题可以直接提issue

**Comment by luozhang002** [comment]
端午后会发1.0.0，可关注 https://github.com/aliyun/aliyun-oss-react-native 目前常用接口基本支持，上传，下载，bucket管理，object管理等
