### ISSUE TITLE
我的下载遭到劫持，导致重定向，下载失败

### ISSUE THREAD

**Issue by 2linziyi2** [ali-sdk/ali-oss#224]
<exception>: UnknowError: Unknow error, status: 302
err: UnknowError: Unknow error, status: 302
params: Object
reqParams: Object
result: Object
data: null
headers: Object
cache-control: "no-cache"
connection: "close"
content-length: "0"
location: "http://119.90.25.32/bbcloud-story.oss-cn-shenzhen.aliyuncs.com/bbcloud-story-xiaojiqiuqiubiandianxin.201701201055594.gz.tar"
server: "Apache"
__proto__: Object
res: Object
status: 302
__proto__: Object
this: Object
Closure
Object
Global
Breakpoints
client.js:309
throw err;
ConsoleSearchEmulationRendering

Preserve log

以上是抓到重定向链接，发现是一个广告

**Comment by PeterRao** [comment]
可以试一下https
