### ISSUE TITLE
webpack之后，IE下报错，什么时候做webpack兼容？

### ISSUE THREAD

**Issue by euphratica** [ali-sdk/ali-oss#225]
![qq 20170410163133](https://cloud.githubusercontent.com/assets/5935516/24853189/d0bd0c8e-1e0c-11e7-95d4-9c64c903426a.png)
![zw phx d59l qm6l ink0b](https://cloud.githubusercontent.com/assets/5935516/24853195/d7e9f76a-1e0c-11e7-8bf4-ea4cf82c1492.png)

**Comment by PeterRao** [comment]
使用 4.11.0 版本
