### ISSUE TITLE
浏览器环境下，总是提示client.multipartUpload(...).then is not a function

### ISSUE THREAD

**Issue by zhangkaixuan** [ali-sdk/ali-oss#226]
在浏览器环境下通过STS临时授权，直接上传文件，总是提示这个错误。。

**Comment by rockuw** [comment]
是什么浏览器？如果是IE的话需要添加Promise的polyfill：https://github.com/rockuw/oss-in-browser#ie-compatibility

**Comment by zhangkaixuan** [comment]
已经修复了，是定义变量错误，顺便反馈另一个问题，感觉浏览器直接上传没有变快，反而更慢了，不知道这个是普遍情况吗。

**Comment by PeterRao** [comment]
浏览器上传是官网的直传例子吗吗？直传的话是单文件上传，是木有分片多请求上传快的。这边正在开发直传使用分片上传的例子后续完成后可以试一下。

**Comment by linliyang** [comment]
请问一下，这个问题是怎么解决的吗？因为我的也一直在报is not a function这个错误

**Comment by grayFinger** [comment]
> 已经修复了，是定义变量错误，顺便反馈另一个问题，感觉浏览器直接上传没有变快，反而更慢了，不知道这个是普遍情况吗。
请问一下是什么定义变量错误能详细说一下吗，我也遇到了这个问题，

**Comment by siburuxue** [comment]
现在还是提示这个错误

**Comment by no1harm** [comment]
> 已经修复了，是定义变量错误，顺便反馈另一个问题，感觉浏览器直接上传没有变快，反而更慢了，不知道这个是普遍情况吗。

你好，我也遇到了相同的问题，请教一下定义变量错误可以详细说一下吗？
