### ISSUE TITLE
dist目录没有发布到npm

### ISSUE THREAD

**Issue by zhaoyao91** [ali-sdk/ali-oss#232]
前端项目本来是打算从npm中引用oss-sdk的（便于版本维护），但是安装之后发现ali-oss中并没有dist目录

**Comment by zhaoyao91** [comment]
官网提供的cdn也不好使，最新版只有4.7.3，而且无版本的cdn有风险，担心以后大版本升级导致不兼容。

**Comment by PeterRao** [comment]
使用 4.11.0 版本
