### ISSUE TITLE
refactor: 更好的支持前端使用 oss

### ISSUE THREAD

**Issue by dead-horse** [ali-sdk/ali-oss#239]
由于 ali-oss 本身是一个给 node 端使用的框架，所以里面也用到了许多其实本来只是在后端可以用的模块，不过通过 browserify 打包的方式支持打包支持了前端访问，但是这个改造是不彻底的。在保持 ali-oss 原生的逻辑的前提下，需要考虑将 http 请求等部分抽出来，共享前端逻辑，可以让使用者选择通过 standalone 或者 import 引入的方式自由使用。

/cc @rockuw

**Comment by fengmk2** [comment]
感觉得重复发一个大版本才能更好地支持纯前端使用。

**Comment by dead-horse** [comment]
恩，主要是我们没有前端使用的场景，不太好做，初步看起来估计要抽出一个 runtime 或者 env 的 helper 出来，前端和 node 各自继承实现。

**Comment by rockuw** [comment]
现在用户碰到的问题是不能直接import，主要是因为lib/目录下的代码使用了es6的语法。我觉得是不是可以使用像 https://github.com/aliyun/fc-nodejs-sdk 一样，自动生成一个es5/目录。

需要在webpack/react native等框架中验证一下。

**Comment by gengjiawen** [comment]
It has been long since this issue updated. Do you still plan to do this ? If I want to use aliyun oss for now, I have to write native code, which is a huge invest of time.
