### ISSUE TITLE
OSS 前端直接利用multipartUpload直接上传如何设置回调

### ISSUE THREAD

**Issue by sosout** [ali-sdk/ali-oss#241]
目前前端利用multipartUpload直接上传成功响应，但问题是不清楚如何设置callback，即根据callback请求，带上用户上传的文件信息请求应用服务器  => 应用服务器返回响应=>OSS将应用服务器的响应返回给用户。主要代码如下
`
var client = this.props.ossClient;
var file = document.getElementById('file').files[0];

var key = Config.localItem('ENTERP_CODE') + '/' + Config.ossKey.prodNet + '/' + Config.localItem('LOGIN_USER') + '/' + Config.getOssUUID() + (new Date()).getTime();
console.log(file.name + ' => ' + key);
return client.multipartUpload(key, file, {
progress: progress
}).then(function (res) {
console.log('upload success: %j', res);
// return listFiles(client);
});
期待您的回复!
        `

**Comment by fengmk2** [comment]
https://github.com/ali-sdk/ali-oss/issues/239 没有完整之前，都不会单独考虑对浏览器的支持改进。
