### ISSUE TITLE
multipartUpload失败或中止的任务会自动删除吗？

### ISSUE THREAD

**Issue by zengming00** [ali-sdk/ali-oss#245]
多次multipartUpload会产生一个列表，可以通过listUploads获取，我可以通过abortMultipartUpload中止掉，但我不想每次都这么做。
是不是能够在一段时间后自动删除呢？

**Comment by mars-coder** [comment]
可以通过bucket中的生命周期管理，添加一个规则，定期删除碎片
![image](https://user-images.githubusercontent.com/17476119/27472882-b71faf40-582f-11e7-957e-77869f0909f6.png)

![image](https://user-images.githubusercontent.com/17476119/27472877-b18b8b9e-582f-11e7-8cee-37f64577c6f9.png)
