### ISSUE TITLE
为什么multipartUpload和put方式上传的文件返回的head不一样！！！

### ISSUE THREAD

**Issue by zengming00** [ali-sdk/ali-oss#246]
```js
    const info = await this.alioss.head(name);
    const crc64ecma = info.res.headers['x-oss-hash-crc64ecma'];
    const base64MD5 = info.res.headers['content-md5'];

````
之前一直使用put方式上传，然后用md5来验证，但是现在文件大、网速又不好就改用了multipartUpload上传，结果代码就出问题了！multipartUpload上传的文件只有crc64ecma

**Comment by mars-coder** [comment]
multipart upload功能的md5校验和普通put object的原理相同，服务端都是针对本次http请求的内容进行md5校验，但是multipart是把一个文件分成几份分别请求，所以每次校验的都是本次请求的那部分文件，不是整份的文件。
另外最终上传完之后，文件也是以多个part集合方式存储在服务端，所以没法直接获取整个文件的MD5

**Comment by binghaiwang** [comment]
后续计划对multipartUpload 做下md5开关(文件md5计算会耗时),如果用户打开, 会对每一片的md5做计算给服务端 ,  然后会在最后返回的result的header中返回content-md5

**Comment by leohxj** [comment]
alioss 得到的 md5 是如何计算的，不是文件直接 md5 吧， 和我 cli 下 md5 计算出来的不同。
