### ISSUE TITLE
苹果审核ipv6访问不了对象存储oss的内容

### ISSUE THREAD

**Issue by CRAZYFAKE** [ali-sdk/ali-oss#261]
苹果过审时，在ipv6环境下，无法访问oss对象的内容，导致审核未通过。ios直接播放的oss地址

以下附苹果官方原文：
```error
Guideline 2.1 - Performance - App Completeness
 
We discovered one or more bugs in your app when reviewed on iPad running iOS 10.3.2 on Wi-Fi connected to an IPv6 network.
Specifically, the videos were unable to play properly.
```

**Comment by mars-coder** [comment]
请问是通过什么方式访问oss的？js sdk？还是ios sdk？

**Comment by CRAZYFAKE** [comment]
后端使用`ali-oss`模块生成的url，直接在IOS客户端播放，在IPV6环境下 无法访问。已经解决了，使用IOS的阿里云SDK 解决了。

**Comment by mars-coder** [comment]
是不是可以这样理解，你需要一个在后端或前端把生成的ipv4的url转换成ipv6格式的url？能否给我一个例子，我确认一下自己的理解，然后看看能否快速实现这个需求。

**Comment by CRAZYFAKE** [comment]
实在抱歉，回复晚了。整个问题过程是这样的，后端使用`ali-oss`里的`signatureUrl`方法生成一个url，然后返回给ios，直接去播放。在App Store提审时没有通过，原因就是我题目里面写的：平板链接的ipv6的wifi，导致无法播放。所以我猜测是，bucket不支持ipv6。不知道我描述清楚没有。。。 @mars-coder
