### ISSUE TITLE
使用 multipartUpload 报错

### ISSUE THREAD

**Issue by xialvjun** [ali-sdk/ali-oss#262]
搜索了 issues ，没有找到相同的错误，于是新提了个 issue。。。

代码：参照 https://github.com/rockuw/oss-in-browser/blob/master/app.js 的 uploadFile 示例函数写的

版本：http://gosspublic.alicdn.com/aliyun-oss-sdk-4.4.0.min.js
           http://gosspublic.alicdn.com/aliyun-oss-sdk-4.5.0.min.js
           https://rawgit.com/ali-sdk/ali-oss/master/dist/aliyun-oss-sdk.min.js （使用 github 链接作为 cdn，也就是最新版）
三个版本都尝试过

错误内容：Error: One or more of the specified parts could not be found or the specified entity tag might not have matched the part's entity tag.

http://gosspublic.alicdn.com/aliyun-oss-sdk-4.6.0.min.js 直接无法初始化

**Comment by rockuw** [comment]
https://github.com/rockuw/oss-in-browser#bucket-setup

> expose 'ETag' in expose headers

**Comment by xialvjun** [comment]
小文件上传没有问题，大文件就不行了。。。试过 55kb，129kb，192kb，1.4M   只有 55kb 的可行，而且得到的链接可以正常访问

**Comment by xialvjun** [comment]
哦哦哦。。。是的，一开始没找到你说的 ETag 在哪里设置，另外，又因为超小的文件是可以上传的，所以以为是别的地方错了。。。后来找到了 ETag 在哪里设置。。。就在眼皮底下，汗。。。然后设置了，果然就可以正常上传了。。。非常非常感谢。。。

**Comment by deloz** [comment]
找了几天,原来是这个原因.
要设置「跨域规则」
![-expose-header](https://user-images.githubusercontent.com/685167/29659367-97d9d704-88f0-11e7-8ee1-09ac0e4556ba.png)

**Comment by 16slowly** [comment]
@xialvjun   我也遇到了这个问题，请问 Etag 在哪里设置啊？感谢
