### ISSUE TITLE
getObjectUrl 设计有误导致几乎没有可用价值

### ISSUE THREAD

**Issue by cncolder** [ali-sdk/ali-oss#267]
[https://github.com/ali-sdk/ali-oss/blob/6611d70dcbe5586525c8c1f2210db31e8d28d9aa/lib/object.js#L455](https://github.com/ali-sdk/ali-oss/blob/6611d70dcbe5586525c8c1f2210db31e8d28d9aa/lib/object.js#L455)

```js
proto.getObjectUrl = function (name, baseUrl) {
  if (!baseUrl) {
    baseUrl = this.options.endpoint.format();
  } else if (baseUrl[baseUrl.length - 1] !== '/') {
    baseUrl += '/';
  }
  return baseUrl + this._escape(this._objectName(name));
};
```

endpoint 不包含 bucket，而且还会带入 internal，也就是说如果不提供 baseUrl 参数的话返回结果总是无法访问的。而如果 baseUrl 参数是必须提供的，那这个函数整体上就是 `baseUrl + name`，没有存在的价值。

**Comment by luozhang002** [comment]
对的，下个版本我们会修复这个问题，的确用户接口名字容易导致误解，我们会新加一个接口来满足你的需求返回一个可用的可访问的URL。
