### ISSUE TITLE
vpc100地址不支持https

### ISSUE THREAD

**Issue by cncolder** [ali-sdk/ali-oss#268]
首先，感谢源码中的注释让我明白 vpc 网络是连不上 internal 地址的，不过我发现 vpc 地址不支持 https

[https://github.com/ali-sdk/ali-oss/blob/42becbbb2dfb42be3024e72f708e849eb62b2658/lib/client.js#L508](https://github.com/ali-sdk/ali-oss/blob/42becbbb2dfb42be3024e72f708e849eb62b2658/lib/client.js#L508)

这里应该再加一行把 `protocol` 重置为 `http://`

**Comment by oraoto** [comment]
同遇到这个问题。可以把`secure`设为`false`。

~~~
oss({secure: false, accessKeyId, accessKeySecret, bucket..
~~~
