### ISSUE TITLE
multipartUpload  上传小图报错   但是图片已经上传成功  大图没有报错

### ISSUE THREAD

**Issue by zhuss** [ali-sdk/ali-oss#272]
`
aliyun-oss-sdk-4.7.3.min.js:5 Uncaught TypeError: Cannot read property 'length' of null
    at i.readFileAndPush (aliyun-oss-sdk-4.7.3.min.js:5)
    at FileReader.reader.onload (aliyun-oss-sdk-4.7.3.min.js:5)
`
本地直传代码
`
res = res.data;
          var fileName = new Date().getTime() + "." + file.name.split('.').pop();
          var region = res.data.endpoint.split("/")[2].split(".")[0];
          var client = new OSS.Wrapper({
            region: region,
            accessKeyId: res.data.accesskeyId,
            accessKeySecret: res.data.accesskeySecret,
            stsToken: res.data.securityToken,
            bucket: res.data.bucketName,
            //secure: true
          });
          var userId = localStorage.getItem('userId');
          client.multipartUpload(userId + '/image/' + fileName, file)
            .then(function(obj) {
              var result = res.data.cdnUrl + '/' + obj.name;
              self.imgurl = result;
              console.log(result);
            }).catch(function(err) {
              self.$message.error("上传失败");
            })
`

**Comment by PeterRao** [comment]
系统版本和浏览器版本是多少

**Comment by binghaiwang** [comment]
请使用最新的版本试一试呢
