### ISSUE TITLE
如何强制修改content-type

### ISSUE THREAD

**Issue by zengming00** [ali-sdk/ali-oss#277]
在web端通过signatureUrl签名的url用ajax上传后文件的mime变成了application/octet-stream，用什么方法可以改回来

**Comment by zengming00** [comment]
垃圾阿里云，坑死本汪了
https://www.npmjs.com/package/ali-oss#signatureurlname-options
![_20170801104916](https://user-images.githubusercontent.com/5255081/28807363-aee75f80-76a7-11e7-94f8-da1d17e93736.png)
# **研究过源代码后才知道真实用法是这样的，和method字段平级**
![_20170801104618](https://user-images.githubusercontent.com/5255081/28807367-b11436ac-76a7-11e7-8ffb-227e6d6e9842.png)

**Comment by fengmk2** [comment]
我们的问题。。。不是阿里云的锅。

**Comment by WeijieZhu0204** [comment]
垃圾阿里云。写的什么垃圾文档。

**Comment by 1479005017** [comment]
@zengming00 ajax怎么使用signatureUrl？我在这步卡住了
