### ISSUE TITLE
bower包的aliyun-oss-sdk.min.js和aliyun-oss-sdk.js是空的哦 

### ISSUE THREAD

**Issue by ohmountain** [ali-sdk/ali-oss#281]
1. 使用bower直接安装后发现标题所提的两个文件是空的。
2. 克隆下来执行`npm build-dist`后发现生成的目标文件也是空的。

**Comment by fengmk2** [comment]
https://github.com/ali-sdk/ali-oss/blob/master/dist/ 这里有

**Comment by ohmountain** [comment]
Tks
