### ISSUE TITLE
浏览器采用服务端签名后直传

### ISSUE THREAD

**Issue by mugbya** [ali-sdk/ali-oss#284]
昨天早上我使用 plupload 上传了一个500M 的大小的视频文件

然后下午发现oss的界面改版了，结果发现500M的文件上传上去变成了blob文件(显示变成3.205M)，下载该文件也才3.4M.

请问你们做了其他什么修改么

**Comment by binghaiwang** [comment]
有详细的信息么 可以尝试重新上传， 抓包看下请求
