### ISSUE TITLE
vue2.0  cdn和webpack方式引入均报错

### ISSUE THREAD

**Issue by yingjiayu** [ali-sdk/ali-oss#285]
```
node v6.1.0
vue v2.2.2
webpack v2.2.1
```

> **cdn方式引入：**

使用<script src="http://gosspublic.alicdn.com/aliyun-oss-sdk-4.4.4.min.js"></script>导入后，浏览器命令行访问OSS正常，webpack增加配置：
`externals: {
    'ali-oss': 'ali-oss'
  }`
在vue文件中require('ali-oss'),得到空对象，去掉require会报错：'OSS' is not defined   ,

> **webpack方式引入：**

或者使用npm install ali-oss ，启动报fs和child_process未引入错误：
`These dependencies were not found:
* fs in ./~/mime/mime.js, ./~/ali-oss/lib/object.js and 3 others
* child_process in ./~/address/lib/address.js
To install them, you can run: npm install --save fs child_process`

手动添加webpack忽略fs和child_process：
`  node: {
    fs: 'empty',
    child_process: 'empty'
  },`
访问页面，浏览器控制台报错：
`SyntaxError: Unexpected token !
    at Object.<anonymous> (0.js:2430)
    at __webpack_require__ (`

**请问是不是目前不支持前端使用此sdk？具体原因为何**

**Comment by maicong** [comment]
import 同遇到报错问题，找不到 child_process 和 fs

**Comment by zuoge85** [comment]
react webpack 同样遇到这个问题

**Comment by fengmk2** [comment]
@mars-coder 浏览器端支持现在是谁负责？请帮忙加上自动化测试吧。

**Comment by fengmk2** [comment]
@yingjiayu 或者你能否给出重现方式？

**Comment by zgdhj95** [comment]
前几天也遇到这个问题了，后来解决了，解决方法和源码已经放到github：

https://github.com/zgdhj95/vue-oss

**Comment by gjk911** [comment]
我也是遇到同样的问题。真无语。。。太不严谨了。。。

**Comment by jason90929** [comment]
........

**Comment by tianbl911** [comment]
这个问题什么时候能解决呢？项目起了 打算用 oss 但这 sdk真的是你们的吗 太无语了

**Comment by zuoge85** [comment]
+1

**Comment by PeterRao** [comment]
使用 4.11.0 版本

**Comment by peterzhanghui** [comment]
用了"ali-oss": "^4.11.0",的最新版本，项目构建的时候依然会报错。
from UglifyJs
Unexpected token: name (Mime) [./~/_ali-oss@4.11.0@ali-oss/shims/mime.js:8,0]

**Comment by PeterRao** [comment]
看下 exmaple，暂时加一下babel-loader。后面提供下es5版本的。

**Comment by Tracy-Chang** [comment]
所以，你的问题解决了么，我这边build的时候，还是会报错
from UglifyJs
Unexpected token: name (Mime) [./~/ali-oss/shims/mime.js:8,0]

**Comment by gjk911** [comment]
解决了

发自我的 iPhone

**Comment by yzzting** [comment]
@PeterRao 请问什么时候提供es5的版本呢 在我的项目里 根据exmaple里面的写法 会有其他问题..

**Comment by monkingame** [comment]
@gjk911 请问是怎么解决的？谢谢

**Comment by antiantian** [comment]
按照文档里加了还是报错
