### ISSUE TITLE
Safari 上传出错：EntityTooSmallError

### ISSUE THREAD

**Issue by semisleep** [ali-sdk/ali-oss#286]
在Safari下使用，multipartUpload上传经常出这个错：EntityTooSmallError

<img width="1013" alt="screen shot 2017-08-23 at 11 52 30 am" src="https://user-images.githubusercontent.com/9045392/29598146-9f3b61d6-87f9-11e7-98da-0205823dce6b.png">

怎么解决？谢谢

**Comment by semisleep** [comment]
另，测试文件大小在50M至2G，还有Chrome没问题，只有Safari会出错

**Comment by luki2678511** [comment]
我也遇到了同样的问题，iphone7的微信客户端打开的网页

**Comment by PeterRao** [comment]
使用 4.11.5版本
