### ISSUE TITLE
put 上传stream，成功，但没返回文件大小

### ISSUE THREAD

**Issue by shuaishenk** [ali-sdk/ali-oss#294]
res中，size为0，data.length也为0
![qq 20170908152418_](https://user-images.githubusercontent.com/3381855/30200608-41d738fe-94aa-11e7-920b-e9cad2cfbede.png)

**Comment by shuaishenk** [comment]
应该有方法返回文件的大小，openstack swift中上传后的 success事件会返回文件大小，aws s3可以在upload方法后监听httpUploadProgress事件来获得最终的e.total来获得上传文件的大小

**Comment by AsceticBoy** [comment]
`putStream` 的方式上传，发现 `size`，`content-length`，‘data’ 都是空的，但是其实已经正常上传了，`url` 能直接下载上传的资源，为啥它们是空？
![image](https://user-images.githubusercontent.com/17674762/58007137-2fa2a600-7b1c-11e9-969c-f3f43c5664c3.png)

**Comment by mytharcher** [comment]
同问，没有文件 size 返回非常不方便。需要的是与 `name`、`url` 平级的 `size` 属性，res 里的东西反而用处不大，比如：

~~~json
{
  "name": "xx.txt",
  "url": "https://aa.region.aliyuncs.com/xx.txt",
  "size": 21
}
~~~
