### ISSUE TITLE
get文件的时候，第二个参数直接用http请求的res对象被无视（res也算是一个writeableStream吧）

### ISSUE THREAD

**Issue by zhuofeijian** [ali-sdk/ali-oss#298]

**Comment by PeterRao** [comment]
http请求的res对象 实际是实现了 writeableStream 的接口，但是不是继承自 writeableStream，可以自行再转换下stream

**Comment by binghaiwang** [comment]
`proto.get = function* get(name, file, options) {
  var writeStream = null;
  var needDestroy = false;

  if (is.writableStream(file)) {
    writeStream = file;
  } else if (is.string(file)) {
    writeStream = fs.createWriteStream(file);
    needDestroy = true;
  } else {
    // get(name, options)
    options = file;
  }`
get内部有对参数做校验，不知道你这个什么意思哦

**Comment by PeterRao** [comment]
res 只是实现了writeableStream方法，并不是继承该对象。
