### ISSUE TITLE
是否表示原来的aliyun-sdk-js已经被废弃？

### ISSUE THREAD

**Issue by calidion** [ali-sdk/ali-oss#30]
我们原来使用的是
https://github.com/aliyun-UED/aliyun-sdk-js

**Comment by fengmk2** [comment]
这是基于es6的版本，基于generator，没有callback

**Comment by calidion** [comment]
这个版本的代码质量感觉要好不少。
基于generator是否意味着node版本要升级到4.X才能使用? 
目前的build状态是失败的。是不是表示还不是正式可用？
但是看到你们的npm版本已经升级到3.x。有点不明觉厉。
如果暂不可用，预计什么时候可用？

**Comment by fengmk2** [comment]
@calidion node 4.2.1 是 LTS，建议使用这个 node 版本。

travis ci 不过，是因为 travis 在美国机房，所以超时导致测试不稳定。
我们本地都确保能通过单元测试的。

我们已经文档运行一年多了，https://npm.taobao.org/ 就是基于此模块实现的。

**Comment by calidion** [comment]
好的。

PS：
1. 如果是时长导致的测试不稳定问题，可以试下设置更长的timeout。参考：
https://github.com/node-weixin/node-weixin-api/blob/master/test/mocha.opts
2. 如果只支持4.X，估计.travis.yml里的 '2', '1'需要删除掉。

```yaml
node_js:
- '4'
- '2'
- '1'
```

**Comment by calidion** [comment]
从错误提示来看， 似乎是Bucket不存在。
是否有可能是测试用例中被删除掉了？

  1) test/bucket.test.js putBucket() "after all" hook for "should throw BucketAlreadyExistsError when change exists bucket region":
     NoSuchBucketError: The specified bucket does not exist.

**Comment by rockuw** [comment]
travis CI现在已经稳定PASS了
