### ISSUE TITLE
Module not found: Can't resolve 'child_process'

### ISSUE THREAD

**Issue by shengnian** [ali-sdk/ali-oss#301]
Enviroment:
```
OS: linux
Arch: x64
Node Version: v8.5.0
Npm version: 5.4.2
Webpack: ^3.6.0
```
Useage:
`import client from 'ali-oss'`
or
`const client = require('ali-oss').Wrapper`
both are report error: `Module not found: Can't resolve 'child_process'` Failed to compile.

**Comment by PeterRao** [comment]
please use 4.11.0
