### ISSUE TITLE
 zlib.gunzip is not a function

### ISSUE THREAD

**Issue by shipSun** [ali-sdk/ali-oss#302]
使用方法：
var urllib = OSS.urllib;
    var OSS = OSS.Wrapper;
    var STS = OSS.STS;
    var fileName = 'object';
    var creds = '';
    var applyTokenDo = function (func) {
        var url = '{{ url('oss_aliyun_token')}}';
        return urllib.request(url,
            {
                method: 'GET'
            },function (result, response) {
            console.log(result);            
            creds = JSON.parse(response);
            fileName = creds.fileInfo.source.name;
            var client = new OSS({
                region: 'oss-cn-beijing',
                accessKeyId: creds.Credentials.AccessKeyId,
                accessKeySecret: creds.Credentials.AccessKeySecret,
                stsToken: creds.Credentials.SecurityToken,
                endpoint: 'oss-cn-beijing.aliyuncs.com',
                bucket: 'test1-icreative'
            });
            return func(client);
            });
    };
出现错误：
aliyun-oss-sdk.js:25310 Uncaught TypeError: zlib.gunzip is not a function
    at decodeContent (aliyun-oss-sdk.js:25310)
    at 219.exports.IncomingMessage.<anonymous> (aliyun-oss-sdk.js:25438)
    at 219.exports.IncomingMessage.162.EventEmitter.emit (aliyun-oss-sdk.js:12143)
    at endReadableNT (aliyun-oss-sdk.js:17361)
    at afterTickTwo (aliyun-oss-sdk.js:14667)
    at Item.182.Item.run (aliyun-oss-sdk.js:14839)
    at drainQueue (aliyun-oss-sdk.js:14809)
修改方法：
25310行 zlib.gunzip(body, cb);修改为 return cb(null, body, encoding);

**Comment by shipSun** [comment]
服务器启动gzip压缩

**Comment by PeterRao** [comment]
urllib是node的模块，在浏览器环境使用会有些问题，暂时不要用 urllib.request 发送请求，改用其他ajax试下。
