### ISSUE TITLE
ali-oss put文件后，没法获取文件大小

### ISSUE THREAD

**Issue by shuaishenk** [ali-sdk/ali-oss#308]
应该有方法返回文件的大小，openstack swift中上传后的 success事件会返回文件大小，aws s3可以在upload方法后监听httpUploadProgress事件来获得最终的e.total来获得上传文件的大小

**Comment by shuaishenk** [comment]
这样我上传后，还得get一下才能获得大小啊，文件越大就越慢了

**Comment by PeterRao** [comment]
put之前不就可以自行拿到文件的大小吗？get这种方式肯定不行的，会下载oss的object的，可以看下head请求。

**Comment by shuaishenk** [comment]
好的，我前端试试，多谢~
