### ISSUE TITLE
https上传失败

### ISSUE THREAD

**Issue by LazyNeo** [ali-sdk/ali-oss#309]
使用script方式引入ali-oss
版本是4.10.0

报错如下
OPTIONS https://m6fresh.oss-cn-shanghai.aliyuncs.com:80/o2o/good/fc7d5cebc5bff9add4f22468409b8d56.jpeg?uploads= net::ERR_SSL_PROTOCOL_ERROR

打印错误信息:
TypeError: Failed to fetch (req "error"), POST http://m6fresh.oss-cn-shanghai.aliyuncs.com/o2o/good/fc7d5cebc5bff9add4f22468409b8d56.jpeg?uploads= -1 (connected: false, keepalive socket: false)
headers: {}

是不是不支持https的方式上传图片啊?

**Comment by PeterRao** [comment]
是设置了endpoint吗，如果设置endpoint的话，设置成 https://m6fresh.oss-cn-shanghai.aliyuncs.com。也可以使用 `region: 'oss-cn-shanghai', secure:true`,不要设置endpoint
