### ISSUE TITLE
什么时候能有一个上传多个文件的接口呢？

### ISSUE THREAD

**Issue by sxbupt** [ali-sdk/ali-oss#311]
ali-oss非常好用，感谢~~
但是有个问题，如果同时上传多个文件的时候只能多次调用put方法，不知道是否有提供putMany(filenames[],files[][, options]))这种一次传多个文件的方法的计划呢？

真的非常需要，之前plupload做上传插件的时候还可以进行多文件上传呢~

**Comment by PeterRao** [comment]
目前在基于plupload封装插件，后面可以用这个插件。sdk 不提供多文件上传的api，可自己简单封装实现。
