### ISSUE TITLE
.put*(name, file[, options])方法每次都需要预检

### ISSUE THREAD

**Issue by sxbupt** [ali-sdk/ali-oss#312]
issue #310 并没用解决。。
bucket的跨域设置中，缓存时间（秒）设置为300.
然后用STS返回的临时token去链接，1分钟内连续上传2次，2次执行put方法都会获取options(fetch)再上传图片(text/plain)

附上2次上传(2分钟内)时，request method为OPTIONS的response：
第一次
HTTP/1.1 200 OK Server: AliyunOSS Date: Fri, 03 Nov 2017 09:41:07 GMT Content-Length: 0 Connection: keep-alive x-oss-request-id: 59FC39B360097C23595D170B Access-Control-Allow-Origin: * Access-Control-Allow-Methods: GET, POST, PUT, DELETE, HEAD Access-Control-Allow-Headers: authorization, content-md5, content-type, x-oss-date, x-oss-security-token, x-oss-user-agent Access-Control-Expose-Headers: ETag Access-Control-Max-Age: 300 x-oss-server-time: 19

第二次
HTTP/1.1 200 OK Server: AliyunOSS Date: Fri, 03 Nov 2017 09:41:39 GMT Content-Length: 0 Connection: keep-alive x-oss-request-id: 59FC39D360097C23595E5341 Access-Control-Allow-Origin: * Access-Control-Allow-Methods: GET, POST, PUT, DELETE, HEAD Access-Control-Allow-Headers: authorization, content-md5, content-type, x-oss-date, x-oss-security-token, x-oss-user-agent Access-Control-Expose-Headers: ETag Access-Control-Max-Age: 300 x-oss-server-time: 0

第2次上传之前并没用重新获取临时token,确保用的同一个临时token去上传。

**Comment by PeterRao** [comment]
在chrome下面，我看请求是少了的，之前是发了options和put两个请求，现在只有一个options了。标准里面Access-Control-Max-Age就是用来判断是否发送预检请求
