### ISSUE TITLE
针对Archive类型的Object读取 Restore Object

### ISSUE THREAD

**Issue by Freundschaft** [ali-sdk/ali-oss#317]
ali-oss好像现在没法用archive类型的object读取

https://help.aliyun.com/document_detail/52930.html

**Comment by PeterRao** [comment]
正在计划增加相关功能

**Comment by luozhang002** [comment]
@Freundschaft  这个目前已经支持 ali-sdk 版本 5.2.0，具体使用参考ReadMe.md文档
