### ISSUE TITLE
使用4.11.2multipartUpload传小文件时会报json错误

### ISSUE THREAD

**Issue by jinleli** [ali-sdk/ali-oss#319]
` case 22:
                                return d = {
                                    res: l.res,
                                    bucket: this.options.bucket,
                                    name: e,
                                    etag: l.res.headers.etag
                                },
                                n.headers && n.headers["x-oss-callback"] && (d.data = JSON.parse(l.data.toString())),
                                t.abrupt("return", d);`
在使用multipartUpload上传小于100kb的图片时，上面的JSON.parse(l.data.toString())会报JSON错误，换到4.10.1就没问题了
另外为什么有些版本不能通过http://gosspublic.alicdn.com/aliyun-oss-sdk-4.11.2.min.js获取到，怎么知道哪些版本可以通过这样的url取到呢？谢谢

**Comment by jinleli** [comment]
上面的l.data为{FileId:123}这样的格式

**Comment by PeterRao** [comment]
第一个问题我下个版本修复掉。如果想看某个版本是否有的话，可以看 History https://github.com/ali-sdk/ali-oss/blob/master/History.md

**Comment by jinleli** [comment]
@PeterRao 我的意思是通过`<script src="http://gosspublic.alicdn.com/aliyun-oss-sdk-4.10.1.min.js"></script>`来引用， https://github.com/ali-sdk/ali-oss/blob/master/History.md里面的有些版本没有，比如http://gosspublic.alicdn.com/aliyun-oss-sdk-4.10.2.min.js

**Comment by PeterRao** [comment]
这个版本当时给 node 发的版本，js少发了。后面发版本号会检查以下，保持同步。
