### ISSUE TITLE
关于代码的一点小疑问

### ISSUE THREAD

**Issue by MuYunyun** [ali-sdk/ali-oss#323]
请问这行中 ep.hostname 的 `hostname` 是哪儿传过来的呢？全局搜索并没有找到  hostname 这个字段，请求指点一二，十分感谢。
https://github.com/ali-sdk/ali-oss/blob/cd03a5c1b4acad32c57a71e63660808facb6c91f/lib/client.js#L341

**Comment by zhongjie-chen** [comment]
copy(this.options.endpoint).to(ep)

**Comment by MuYunyun** [comment]
@zhongjie-chen endpoint 只是一个url的对象，并没有看到 hostname 啊，https://github.com/ali-sdk/ali-oss/blob/cd03a5c1b4acad32c57a71e63660808facb6c91f/lib/client.js#L81

**Comment by binghaiwang** [comment]
urlutil.parse 这个方法会将设置的endpoint进行解析将hostname设置上去 @MuYunyun

**Comment by MuYunyun** [comment]
当时懵了，谢谢点拨，对 node 的库 api 比较生疏 😄
