### ISSUE TITLE
OSS.multipartUpload 方法 如何获取 Uploadid 

### ISSUE THREAD

**Issue by zhanchengkun** [ali-sdk/ali-oss#324]
目的 上传过程中 终止上传 abortMultipartUpload 需要提供uploadid  该如何获取

如何 终止上传。 @fengmk2

**Comment by zhanchengkun** [comment]
@fengmk2

**Comment by zhanchengkun** [comment]
或者可以 自定义 uploadid 传入？

**Comment by jinleli** [comment]
同样有这个问题，在使用multipartUpload时怎么获取uploadId,离开页面的时候需要终止上传

**Comment by xiaosongxiaosong** [comment]
@jinleli `multipartUpload` 的 options 中回调函数 progress 的第二个参数 checkpoint 携带了 uploadId

**Comment by zhanchengkun** [comment]
@xiaosongxiaosong @PeterRao 对是有，第一次关闭问题的时候 就是用的progress回调对象里面的uploadId，但是使用不方便，原以为会有更好的获取方式提供……才再次开启的问题。
