### ISSUE TITLE
浏览器上传Blob格式文件不支持。

### ISSUE THREAD

**Issue by mcdyzg** [ali-sdk/ali-oss#325]
我用Canvas.toBlob导出的Blob格式文件上传会报

`Error: _getFileSize requires Buffer/File/String.`

发现是multipart.js browser/multipart.js里305行
```
is.file = function (file) {
  return typeof(File) !== 'undefined' && file instanceof File;
};
```
这个方法挡住了，能否增加下对Blob格式的支持，

`return typeof(File) !== 'undefined' && (file instanceof File || file instanceof Blob);`

谢谢

**Comment by PeterRao** [comment]
把blob转换成file对象

**Comment by zcoding** [comment]
居然没有直接支持 Blob 的方法，那个 Buffer 反而不常用，强烈建议支持 Blob

**Comment by duan007a** [comment]
#400

**Comment by mcdyzg** [comment]
谢谢
