### ISSUE TITLE
ali-oss 模块不支持react吗？

### ISSUE THREAD

**Issue by zb188** [ali-sdk/ali-oss#327]
node6.1 方案react+ant+redux ，list 无法调用，跨域CORS 已经设置
错误如下
Failed to load http://xxx.oss-cn-hangzhou.aliyuncs.com/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
Uncaught (in promise) TypeError: Failed to fetch (req "error"), GET http://xxx.oss-cn-hangzhou.aliyuncs.com/ -1 (connected: false, keepalive socket: false)
headers: {}
@fengmk2  ali-oss 模块不支持react吗？

**Comment by LuoTuxiu** [comment]
我也出现上述报错，麻烦请教楼上是如何解决的 @zb188

**Comment by qm8956** [comment]
这算什么，天马行空得乱弹琴

**Comment by shuai4983958** [comment]
这怎么解决的啊，提个问题抛出啦，直接关闭了？
