### ISSUE TITLE
multipartUpload上传问题

### ISSUE THREAD

**Issue by wangxinyu** [ali-sdk/ali-oss#333]
发现大文件上传不了，某个分片上传失败后，如何重新上传这个分片，一个分片失败，导致整个文件就上传失败了。
发现分片上传很慢，改小partSize也没用，分片完成后才会调用progress，单分片上传也需要onprogress，这样上传进度不卡扽，是连续的。

**Comment by PeterRao** [comment]
需要你自行在progress回调中，保存checkpoint，重传时传入checkpoint参数
