### ISSUE TITLE
分片上传失败

### ISSUE THREAD

**Issue by shipSun** [ali-sdk/ali-oss#337]
oss-sdk.js:84 error: Error: Your proposed upload smaller than the minimum allowed size.

client.multipartUpload(data.file.name[i], this.file[i],{progress: progress}).then(function (res)

**Comment by PeterRao** [comment]
能截图看下浏览器里面的错误请求吗

**Comment by shipSun** [comment]
重新 刷新下就又能上传了

**Comment by shipSun** [comment]
重新刷新就能上传了

**Comment by PeterRao** [comment]
是不是同时进行两次的分片上传了。建议每进行一次上传重新创建一次实例。

**Comment by shipSun** [comment]
一次分片上传

**Comment by shipSun** [comment]
_completeMultipartUpload这个接口出现的错误，什么情况下会触发

**Comment by shipSun** [comment]
只有safari出现问题

**Comment by PeterRao** [comment]
能看下全部的请求截图吗

**Comment by shipSun** [comment]
全部请求是什么？

**Comment by PeterRao** [comment]
就是network那栏，看下出错请求那个地方
![image](https://user-images.githubusercontent.com/1611647/34708694-df73e8e6-f54e-11e7-8c68-eb1fcac22f3d.png)
并且把出错请求及上一个请求右键点击拷贝为cRUL，信息贴一下

**Comment by shipSun** [comment]
<img width="531" alt="_20180112144411" src="https://user-images.githubusercontent.com/13898660/34862795-2dacbdd0-f7a7-11e7-80ab-71d8b7910fd7.png">
<img width="1276" alt="_20180112144420" src="https://user-images.githubusercontent.com/13898660/34862796-2de8ead0-f7a7-11e7-8927-94db4044cd79.png">
