### ISSUE TITLE
浏览器使用 PUT 直传，返回的 url 无法显示图片

### ISSUE THREAD

**Issue by yiiouo** [ali-sdk/ali-oss#338]
```
const client = new OSS.Wrapper({ //... })
client.put(IMGKEY, new OSS.Buffer(Base64)).then((result) => {
            console.log('success:', result)
     })
```
我传入一个 base64 的图片进去，上传成功返回的 url，赋值在 img 的 src 中，是无法显示的。用浏览器打开这个 url，会自动下载一段 base64？ 

这个要如何解决？
浏览器能不能用 base64/blod/buffer 进行上传图片的？
  
  -----------------------------------------
补充下链接：

[上传后返回的 url ](http://mmjtggdev.oss-cn-shenzhen.aliyuncs.com/D7E6DB55-3014-436E-8B72-CA514BD1C2CE1515379583213jGyFtX0VSdswck0n?Expires=1515383654&OSSAccessKeyId=LTAI00ZcBuhhIyZW&Signature=9QULxUEOp9L0yufJG68mcXtOWqY%3D)

![](http://oxnbdd4i9.bkt.clouddn.com/1515381042389.jpg)

**Comment by PeterRao** [comment]
你指定下 mime 下试下

**Comment by yiiouo** [comment]
@PeterRao 这个要在管理控制台设置吗？

**Comment by PeterRao** [comment]
https://github.com/ali-sdk/ali-oss#putname-file-options 你看下options.mime 属性。这个其实就是content-type，设置完后会明确告诉服务器上传到oss的文件类型。

**Comment by yiiouo** [comment]
@PeterRao 

```
put(IMGKEY, new OSS.Buffer(file), {
  mime: 'text/plain'
})
```
设置了后，如果把 url 赋值到 img 的 src 上，是无法显示图片的，response 也是空的。但是用 ajax 去获取就可以了。这里有什么方法可以直接在 img 上显示？

**Comment by PeterRao** [comment]
```
function dataURLtoFile(dataurl, filename) {
    var arr = dataurl.split(','), mime = arr[0].match(/:(.*?);/)[1],
      bstr = atob(arr[1]), n = bstr.length, u8arr = new Uint8Array(n);
    while(n--){
      u8arr[n] = bstr.charCodeAt(n);
    }
    return new File([u8arr], filename, {type:mime});
  }

  var file = dataURLtoFile(content, 'hello.png');

  return client.multipartUpload(<oss文件名>, file).then(function (res) {
    return listFiles(client);
  });
```
转成file对象使用分片上传接口

**Comment by yiiouo** [comment]
解决了，谢谢

**Comment by HouPoc** [comment]
使用multipartUpload时，当图片Size  大于100K 时，上传会失败。下面时错误代码，
`InvalidPartError: One or more of the specified parts could not be found or the specified entity tag might not have matched the part's entity tag.`

请问有没有解决方法。 目前是浏览器上传，使用REACT 框架 @PeterRao 
谢谢
