### ISSUE TITLE
现在支持react native不

### ISSUE THREAD

**Issue by woting2017** [ali-sdk/ali-oss#343]
现在oss支持react native不

**Comment by luozhang002** [comment]
@woting2017 @internet5 目前React Native版本的OSS SDK 项目已经申请开源,可以试用下,有问题可以直接提issue 仓库地址: https://github.com/aliyun/aliyun-oss-react-native develop分支,目前刚发布版本aliyun-oss-react-native 0.0.1-alpha.1，支持常见的API接口，端午期间我这边会把文档demo，梳理下，然后再发个版本，有问题可以直接提issue。谢谢
