### ISSUE TITLE
个别文件上传报错

### ISSUE THREAD

**Issue by solomoapp** [ali-sdk/ali-oss#351]
下面是一张正常的图片，别的地方上传都没问题，而用这个sdk上传报错:

![image](https://user-images.githubusercontent.com/10527369/35097902-252e8874-fc8d-11e7-852d-141215b353dd.png)

------------------------------------------------------------------

报错信息：

![image](https://user-images.githubusercontent.com/10527369/35097923-40558cb0-fc8d-11e7-9337-05b30a255c63.png)

**Comment by PeterRao** [comment]
什么浏览器

**Comment by solomoapp** [comment]
chrome, ie, firefox都测试了，这个图片上传都会报错，你可以把这个图片另存为然后上传验证下

**Comment by solomoapp** [comment]
我用的sdk也是最新的：http://gosspublic.alicdn.com/aliyun-oss-sdk.min.js，上传其它图片没问题

**Comment by PeterRao** [comment]
我这边上传成功了，调用的代码贴一下

**Comment by solomoapp** [comment]
好的，我发到oss上了：http://malata.oss-cn-shenzhen.aliyuncs.com/upload.htm

**Comment by solomoapp** [comment]
知道问题了，这个文件上传进度cpt的值为undefined，单文件上传没问题，多文件并发上传就不好做进度条等逻辑了

function progress(percentage, cpt) {
	return function (done) {
		console.log('cpt');
		console.log(cpt);
		done();
	}
}

**Comment by PeterRao** [comment]
文件太小的话，直接就上传了。进度一次就100%了
