### ISSUE TITLE
react v16 build时，出现Failed to minify mime.js错误

### ISSUE THREAD

**Issue by monkingame** [ali-sdk/ali-oss#362]
react工程，build时出现了错误。错误信息：
Failed to compile.
Failed to minify the code from this file:
        ./node_modules/ali-oss/shims/mime.js:8

我建了一个非常简单的例子：
https://github.com/monkingame/test-ali-oss.git
就是create-react-app生成最简单的项目，然后导入ali-oss，在app.js中只写一句话：
var oss = require('ali-oss');
然后build项目，就会出现上面的错误。
困扰一天了，项目马上就要发布，却被这里卡住了。
请问怎么解决？或者有无其他解决办法可以跳过去？
我们全部用的阿里云的服务，没法更换服务器和架构啊。
非常感谢帮助！

![react-ali-oss](https://user-images.githubusercontent.com/4568610/35509206-4329d924-052e-11e8-99a0-02ff6b72d956.png)

**Comment by PeterRao** [comment]
require('ali-oss/dist/aliyun-oss-sdk.js')
