### ISSUE TITLE
设置 multipartUpload partSize 无效 

### ISSUE THREAD

**Issue by 16slowly** [ali-sdk/ali-oss#366]
使用 multipartUpload 进行大文件（2G左右）上传时，每次的分片很小，400B 左右，这导致分出来的片数非常多，partId 也远远大于官方说的 10000 ，但是设置的 partSize 没生效，分出来的片依旧是 400B 左右 ， 另，multipartUpload 接口的 partSize 默认大小好像并不是官网说的

> Multipart Upload要求除最后一个Part以外，其他的Part大小都要大于100KB。

一开始没有对 partSize 做设置：

![image](https://user-images.githubusercontent.com/15927205/35602919-c539b536-0675-11e8-9a65-4fe5e8372d11.png)

设置 partSize 为 1024 * 1024，还是这样：

![image](https://user-images.githubusercontent.com/15927205/35602974-035be280-0676-11e8-859f-072d66795345.png)

这是为什么呢? 求指教！

@PeterRao 在线等，挺急的！

**Comment by 16slowly** [comment]
@PeterRao 在线等，挺急的！

**Comment by PeterRao** [comment]
底层换用了arrybuffer进行二进制传输，应该 chrome 工具 的bug，实际抓包是正确的，你也可以通过更改partSize后发送的请求数目，可以看到实际发生了变化。
