### ISSUE TITLE
multipartUpload 报错

### ISSUE THREAD

**Issue by 16slowly** [ali-sdk/ali-oss#369]
![image](https://user-images.githubusercontent.com/15927205/35656665-78011d0e-0733-11e8-93bf-fbdaf8637cfd.png)

- 不能上传的都是大于 100KB 的，大小限制在哪里设置？
- 不成功的反而返回了 response 和 url (但 url 访问失败 ), 成功的却是 undefined，与 API
 
![image](https://user-images.githubusercontent.com/15927205/35656753-fee4c8a2-0733-11e8-9d13-69703f460167.png)

不符呐，求解答 @PeterRao，万分感谢~

**Comment by PeterRao** [comment]
什么环境，调用代码怎么写的

**Comment by 16slowly** [comment]
Node 环境. 上传部分的代码如下：

```js
client.multipartUpload(key, filePath, {
    progresss: (progress, cpt, res) => {
        console.log(`upload ${filePath} progress: `, progess)
        console.log(`upload ${filePath} cpt: `, cpt)
        console.log(`upload ${filePath} res: `, res)
   }
})
.then(() => console.log(`upload ${filePath} success`))
.catch((error) => console.log('upload failed: ', error))
```
@PeterRao .

**Comment by PeterRao** [comment]
progress 需要传入一个thunk function 
```
var progress = function (p) {
  return function (done) {
    console.log(p);
    done();
  };
};
```
或者 generator function `(function *)` 官网文档有progress的说明https://help.aliyun.com/document_detail/64047.html

**Comment by 16slowly** [comment]
噢，知道了，感谢感谢！
