### ISSUE TITLE
oss 偶现 Unknown Error, status = 200

### ISSUE THREAD

**Issue by yibn2008** [ali-sdk/ali-oss#378]
如下图:

![image](https://user-images.githubusercontent.com/4136679/36824915-c6ba6014-1d3f-11e8-8d3c-c88568e8e45a.png)

由于是 ali-oss 底层报出来的, 错误信息实在有限, 并且响应码是 200, 却出现了 Error, 希望能在此处将 result 打印出来, 提供更多信息:

![image](https://user-images.githubusercontent.com/4136679/36824905-bdd4f518-1d3f-11e8-9613-b28643e284da.png)

**Comment by PeterRao** [comment]
是比较奇怪，这个err里面，有requestId，看是否能提供下requestId，我排查下。

**Comment by yibn2008** [comment]
没有, 当时没有打印出来

**Comment by PeterRao** [comment]
在复现的话 打印下requestId，发给我，我排查下，我看你也是阿里的直接 钉钉@琦飞，联系我，issue 我暂时关了。

**Comment by huanggaoqing** [comment]
这个问题是否有解决办法
