### ISSUE TITLE
multipartUpload上传小图成功，上传大图片报错

### ISSUE THREAD

**Issue by varandrew** [ali-sdk/ali-oss#380]
> OS:  MacOS High Sierra
   Browser:  Google Chrome  64.0.3282.186(正式版本)(64 位)

#### 我在使用oss上传图片时遇到了错误，如标题所说，尝试了好久仍然解决不了，希望得到你们的帮助，辛苦了!❤️

这是我的报错信息：
![err.png](https://raw.githubusercontent.com/varandrew/issue_image_folder/master/oss_err_squashed.png)

下面是我的oss上传代码：
![oss.png](https://raw.githubusercontent.com/varandrew/issue_image_folder/master/oss_squashed.png)

**Comment by PeterRao** [comment]
this.sts 信息打印出来。

**Comment by varandrew** [comment]
@PeterRao 给大佬递🍊
![](https://raw.githubusercontent.com/varandrew/issue_image_folder/master/sts.jpg)

**Comment by PeterRao** [comment]
浏览器的网络请求，在麻烦截图看下。http://lixcx.oss-cn-shanghai.aliyuncs.com/ 这个域名的第一个请求，看下返回内容是什么

**Comment by varandrew** [comment]
![Headers](https://raw.githubusercontent.com/varandrew/issue_image_folder/master/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-03-06%20%E4%B8%8A%E5%8D%88100650.jpg)
![Response](https://raw.githubusercontent.com/varandrew/issue_image_folder/master/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-03-06%20%E4%B8%8A%E5%8D%8810.07.56.png)
![Timing](https://github.com/varandrew/issue_image_folder/blob/master/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-03-06%20%E4%B8%8A%E5%8D%8810.10.09.png)
给大佬递笔~

**Comment by PeterRao** [comment]
我这边一直没法复现，我邮件你了，看下什么时候有空，能远程协助排查下。

**Comment by WiFiUncle** [comment]
https://github.com/WiFiUncle/ossUploader  
可以看下这个，使用oss上传文件的界面

**Comment by savokiss** [comment]
相似的问题，Vue + axios， 在dev环境下大文件不报错，build后 传大于100K的文件都会报错
感觉是和分片相关，错误信息 yield 了一个 undefined
![default](https://user-images.githubusercontent.com/5608189/37945199-a1dbe16a-31b1-11e8-9b24-5dc05353f0d2.png)

**Comment by savokiss** [comment]
放弃了multipart 了，是co内部的问题，改用 put 

将文件转成 base64 
```
// 将文件读取为 base64
export function readFileAsBase64 (file) {
  var reader = new FileReader()
  reader.readAsDataURL(file)
  return new Promise((resolve, reject) => {
    reader.onload = () => {
      resolve(reader.result.replace(/^data:image\/\w+;base64,/, ''))
    }
  })
}

```

然后再上传：
```
readFileAsBase64(this.file).then(base64 => {
  store.put(storeAs, new OSS.Buffer(base64, 'base64'))
})
```

**Comment by PeterRao** [comment]
@savokiss 你这个应该是另一个问题，可以重新开个issue，详细贴一下你使用的代码

**Comment by savokiss** [comment]
@PeterRao 嗯，因为我自己搭 demo 竟然一直重现不出来，所以没有信心说清楚哈~ 感觉是 co 和 promise 相关的问题。我们传的都是小文件，先用 put 了

**Comment by PeterRao** [comment]
谢谢 @varandrew 的反馈，最终定位是 https://github.com/PanJiaChen/vue-element-admin/issues/465 和 https://github.com/PanJiaChen/vue-element-admin/issues/445  其他框架中拦截本地请求导致

**Comment by JianxunRao** [comment]
@savokiss  我的项目也是Vue，集成ali-oss使用multipartupload()时也遇到来你说的问题。照你说的直接使用put可以正确上传文件。而不存在回调不一致或返回结果不包含url参数的问题。
