### ISSUE TITLE
取消分片上传方法

### ISSUE THREAD

**Issue by xiaoyuhen** [ali-sdk/ali-oss#384]
目前暴露出来的 abortMultipartUpload 方法会导致删除已上传的分片，且开启 DELETE 权限后，后端担心出问题。

请问有没有其他可以直接取消上传的办法？

**Comment by PegasusWang** [comment]
Browser-JS-SDK。后端不希望暴露给前端 bucket 的删除权限，这里就没法调用 abort 方法了。有没有其他直接取消上传的方法，看 python 语言的 sdk 实现 abort 就是直接调用的 delete 方法

**Comment by xiaoyuhen** [comment]
@binghaiwang 浏览器下不调用 abortMultipartUpload 如何取消呢？

**Comment by PegasusWang** [comment]
```
proto.abortMultipartUpload = function* abortMultipartUpload(name, uploadId, options) {
  this.cancel();
  options = options || {};
  options.subres = {uploadId: uploadId};
  var params = this._objectRequestParams('DELETE', name, options);
  params.successStatuses = [204];

  var result = yield this.request(params);
  return {
    res: result.res
  };
};
```
可以只用 cancel 不发 DELETE 请求呢？

**Comment by PeterRao** [comment]
现在接口有两种取消操作，一种是abortMultipartUpload，会删除已经上传的分片，同时也会发送DELETE请求。
另一种是在调用multipartUpload后，调用cancel方法，会中断上传，但分片还会保留，不会发送DELETE请求。
第一种方案下，可以通过STS服务及Access-Control-Allow-Origin设置来保证安全性。
第二种方案多用于断点续传，会产生上传碎片，占用存储空间https://help.aliyun.com/document_detail/31916.html?spm=5176.11065259.1996646101.searchclickresult.3aab2b2ekcc3dH

**Comment by xiaoyuhen** [comment]
@PeterRao 按照第二种方案解决了问题。
没有注意到 proto 上挂了一个 cancel 方法，感觉可以补到文档上呀。

**Comment by xiaoyuhen** [comment]
> //the other event to cancel, for example: click event
//to cancel upload must use the same client instance 
store.cancel();

现在写的地方不太显眼了

**Comment by PeterRao** [comment]
嗯，@binghaiwang 后面把 cancel 方法列到api列表里面吧。并标明和abortMultipartUpload的区别，挺多用户问的

**Comment by lvfeijian** [comment]
多个文件上传，cancel()如何取消某一个文件的上传

**Comment by ricky11** [comment]
Cancel or abort, will not stop any inflight put requests is that  correct.. so incase you cancel on the last final part what happens.  the final part will still complete and the file is stored?  but the user pressed cancel.  so whats the solution?

**Comment by eijil** [comment]
> 多个文件上传，cancel()如何取消某一个文件的上传

我也想问，目前想到的办法就是一个文件一个实例
