### ISSUE TITLE
上传文件多了很容易出现错误

### ISSUE THREAD

**Issue by gameatp** [ali-sdk/ali-oss#385]
---------uploadFile  ./bin/convertModels/1021550/8684b15583c31fb9I/img.png Failed: { ResponseError: socket hang up (req "error"), PUT http://dddcreatortest.oss-cn-hangzhou.aliyuncs.com/editorData/220/p
roject/4qQ39kLM-DaZecIK2-zY3mCEWu-Eu8NwHry/1021633/img.png -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":520,"closeSocketCount":453,"errorSocketCount":0,"timeoutSocket
Count":453,"requestCount":361,"freeSockets":{"dddcreatortest.oss-cn-hangzhou.aliyuncs.com:80::":7},"sockets":{"dddcreatortest.oss-cn-hangzhou.aliyuncs.com:80::":57},"requests":{}})
headers: {}
    at Client.requestError (/zz/servertrunk/node_modules/_ali-oss@4.11.4@ali-oss/lib/client.js:457:13)
    at requestError.next (<anonymous>)
    at onFulfilled (/zz/servertrunk/node_modules/_co@4.6.0@co/index.js:65:19)
    at /zz/servertrunk/node_modules/_co@4.6.0@co/index.js:54:5
    at new Promise (<anonymous>)
    at co (/zz/servertrunk/node_modules/_co@4.6.0@co/index.js:50:10)
    at toPromise (/zz/servertrunk/node_modules/_co@4.6.0@co/index.js:118:63)
    at next (/zz/servertrunk/node_modules/_co@4.6.0@co/index.js:99:29)
    at onRejected (/zz/servertrunk/node_modules/_co@4.6.0@co/index.js:85:7)
    at <anonymous> name: 'ResponseError', status: -1, code: 'ResponseError' }

**Comment by gameatp** [comment]
put
putStream
multipartUpload
都试了都没用

**Comment by PeterRao** [comment]
升级到4.13.x 版本

**Comment by gameatp** [comment]
刚升级了还是要报错，我找到出错代码打印了一下，就是发PUT请求的时候容易出错
请求错误: { ResponseError: socket hang up (req "error"), PUT http://dddcreatortest.oss-cn-hangzho
u.aliyuncs.com/editorData/220/project/4qQ39kLM-DaZecIK2-zY3mCEWu-Eu8NwHry/1023860/img.jpg -1 (con
nected: true, keepalive socket: false, agent status: {"createSocketCount":341,"closeSocketCount":
189,"errorSocketCount":0,"timeoutSocketCount":279,"requestCount":255,"freeSockets":{"dddcreatorte
st.oss-cn-hangzhou.aliyuncs.com:80::":8},"sockets":{"dddcreatortest.oss-cn-hangzhou.aliyuncs.com:
80::":54},"requests":{}})
![image](https://user-images.githubusercontent.com/4427058/37382885-466a2110-2780-11e8-96ea-45066282d3b8.png)

**Comment by PeterRao** [comment]
超时请求比较多。ping下dddcreatortest.oss-cn-hangzhou.aliyuncs.com 看看网络情况

**Comment by gameatp** [comment]
![image](https://user-images.githubusercontent.com/4427058/37386244-8e970018-2792-11e8-8686-49162539e78d.png)
网络环境很好的，只有1毫秒

**Comment by PeterRao** [comment]
贴下上传代码看下

**Comment by gameatp** [comment]
var co = require('co');
var OSS = require('ali-oss');
var fs = require('fs');
var readdir = require('fs-readdir-promise');
var config = require('./ali_oss.js');
var Version =   require('../editorcore/src/version.js')
var client = new OSS({
	accessKeyId:config.accessKey,
	accessKeySecret: config.secretKey,
	bucket: config.bucket,
	region: config.region
});
//upload assets

readdir('dist/assets/')
	.then(function(files) {
		files.map(function(file,i){
			co(function* () { 
			 
				var result = yield client.put( Version +"/assets/"+file, './dist/assets/'+file,{timeout:500000});
				console.log(file+"  was uploaded success!"); 
			}).catch(function (err) {
				console.log(err);
			});
		})
	})
	.catch(function(err) {
		console.log(err.message);
	});

**Comment by gameatp** [comment]
这个使我们前端自动发布到oss的代码，也是经常传失败

**Comment by PeterRao** [comment]
这么写会有问题，会同时把目录下面所有文件都同时并发进行上传。你试试改成一个一个文件的上传。参考
#136

**Comment by gameatp** [comment]
真的是这个问题，谢谢改了之后稳定多了
