### ISSUE TITLE
Cannot read property 'crypto' of undefined

### ISSUE THREAD

**Issue by xiaoyuhen** [ali-sdk/ali-oss#386]
直接引用  dist/aliyun-oss-sdk 会报 ```Cannot read property 'crypto' of undefined``` 。

引用源码不会出问题。尝试把 aliyun-oss-sdk 里的
https://github.com/ali-sdk/ali-oss/blob/master/dist/aliyun-oss-sdk.js#L8742
 改为 ```var _global = this || window || {}```可以解决问题。

看起来是引用的 ```crypto-browserify@ 1.0.9 ``` 造成的

**Comment by xiaoyuhen** [comment]
很奇怪，引用源码就没什么问题

**Comment by PeterRao** [comment]
嗯，确实是crypto-browserify出的问题，引用源码应该webapck应该处理掉这个this了。我们处理下看crypto-browserify这个能否升级或者替换。

**Comment by WiFiUncle** [comment]
同问。加载sdk源码没问题。但是babel编译后，就报
aliyun-oss-sdk.js:837 Uncaught TypeError: Cannot read property 'crypto' of undefined
  
oss.js:14 Uncaught TypeError: Cannot read property 'Wrapper' of undefined
    at oss.js:14
