### ISSUE TITLE
oss上传有界面啦！支持多文件上传

### ISSUE THREAD

**Issue by WiFiUncle** [ali-sdk/ali-oss#392]
仿百度webuploader上传界面，结合oss做了一个demo。支持多文件上传。
https://github.com/WiFiUncle/ossUploader
---------------------------------以下是issue线--------------------------------------------------
请问下，我这个demo想显示文件上传总进度要怎么做？ 我现在的想法是，每个文件上传的进度 X文件大小，算出该文件上传了多少，然后占总文件大小的多少。但是，上传好像是多线程的，就是同时上传多个文件，我这样做合适么？

**Comment by WiFiUncle** [comment]
上传的代码
`      /***
       *  上传文件
       * @param file 需要上传的文件
       * @param filePath 上传文件到哪个位置。按官方说法就是key
       * oss是对象存储, 没有path路径概念，不过个人认为这个可以当作路径比较好理解
       */
    uploadFile: function (file, filePath) {
      var client;
      var total = 0;
          filePath += file.name;
      client = applyTokenDo();
          client.multipartUpload(filePath, file, {
            progress: progress
          })
          .then(function (res) {
            $("#" + file.id).children(".success-span").addClass("success");
            uploader.fileStats.uploadFinishedFilesNum ++; //已成功上传数 + 1/
            uploader.fileStats.curFileSize += file.size; //当前已上传的文件大小
              /**
               * 这里有个一个问题:
               *  这是在成功回调中计算文件的大小，并不是实时的。
               *  举个栗子，你上传一个100M文件，得等到它全部上传完成后，你才知道它上传完，中间进度你并不知道。
               *  上面那个上传的process 中貌似是[0,1], 还得计算当前文件的大小乘以当前进度算出这个文件已经上传了多少。
               *
               */
            progressBar = (uploader.fileStats.curFileSize / uploader.fileStats.totalFilesSize).toFixed(2) * 100 + '%';

            if(total == uploader.fileStats.totalFilesNum) {
              console.log("upload success!");
              $("#startUpload").text('上传完成');
            }
            $totalProgressbar.css('width', progressBar)
                  .html(progressBar);
          });
    },`

**Comment by PeterRao** [comment]
我看了下你基于ali-oss的封装，是基于4.11.2版本的。可以抽空升级到最新版本，4.12.x 以下版本有个比较大的bug，会导致上传文件内容为空。#346 
PS: 上传进度的demo，项目example里面有使用例子。可参考实现。

**Comment by WiFiUncle** [comment]
好的，有空升级下。
你说的上传进度，我之前看过，只是单文件上传，
`
client.multipartUpload(filePath, file, {
progress: progress
}) 
`

**Comment by PeterRao** [comment]
嗯，多文件上传需要自己封装上传进度逻辑。

**Comment by WiFiUncle** [comment]
好的。请问下大家是怎么写这个逻辑的呢？方便告知么？

我现在的想法是，每个文件上传的进度 X文件大小，算出该文件上传了多少，然后占总文件大小的多少。但是，上传好像是多线程的，就是同时上传多个文件，我这样做合适么？

/*
* 这里有个一个问题:
* 这是在成功回调中计算文件的大小，并不是实时的。
* 举个栗子，你上传一个100M文件，得等到它全部上传完成后，你才知道它上传完，中间进度你并不知道。
* 上面那个上传的process 中貌似是[0,1], 还得计算当前文件的大小乘以当前进度算出这个文件已经上传了多少。
*
*/
详细看楼上我贴了代码。感谢

**Comment by PeterRao** [comment]
每次你上传单个文件就行。本身分片上对于单个文件已经多线程进行上传了。不需要多个文件同时上传。

**Comment by WiFiUncle** [comment]
那我自己弄个队列？上传成功完成之后再上传第二个？

**Comment by PeterRao** [comment]
是的，具体实现逻辑需要业务自己处理。

**Comment by WiFiUncle** [comment]
好好。谢谢了
