### ISSUE TITLE
client.put(...).then is not a function

### ISSUE THREAD

**Issue by wqlsir** [ali-sdk/ali-oss#393]
uploadFile(){
         const   client = new OSS({
            region: this.state.region,
            accessKeyId: this.state.accessKeyId,
            accessKeySecret: this.state.accessKeySecret,
            bucket: this.state.bucket,
        });
        const file = this.state.files[0];
         const val=file.file.name;
         const suffix = val.substr(val.indexOf("."));
         const obj=this.timeStamp();
         const storeAs = 'upload-file/'+obj+suffix; //文件名
        client.put(file, storeAs).then(function (r1) {
            console.log('put success: %j', r1);
            return client.get('object');
        }).then(function (r2) {
            console.log('get success: %j', r2);
        }).catch(function (err) {
            console.error('error: %j', err);
        });
    }

![image](https://user-images.githubusercontent.com/25899027/37583448-5cf62bee-2b8c-11e8-865f-498596a0f2a8.png)

**Comment by PeterRao** [comment]
promise用法需要使用 OSS.wrapper https://github.com/ali-sdk/ali-oss#wrapper-usage
