### ISSUE TITLE
Failed to minify the code from this file

### ISSUE THREAD

**Issue by kevinpursuing** [ali-sdk/ali-oss#395]
react 项目引入这个包后能够在本地运行，可是在npm run build 打包的时候提示打包失败，提示信息如下
Failed to minify the code from this file:

        ./node_modules/ali-oss/shims/mime.js:8

Read more here: http://bit.ly/2tRViJ9
请问是什么原因呢？

**Comment by binghaiwang** [comment]
如果使用的是webpack进行打包， 参考example中的配置，
 loader: 'babel-loader',
          options: {
            presets: ['babel-preset-es2015', { modules: false }], // fix uglifyjs not support es6
          },

**Comment by PeterRao** [comment]
参考 #362
