### ISSUE TITLE
.putStream 方法直接传入不带有后缀名的 Key 时会引发签名失败的错误。

### ISSUE THREAD

**Issue by XGHeaven** [ali-sdk/ali-oss#398]
```js
const stream = request.get('https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1521711023223&di=3d2c8f32d382a4139030e790ce06ecd1&imgtype=0&src=http%3A%2F%2Fwww.people.com.cn%2Fmediafile%2Fpic%2F20170103%2F49%2F9774185422066024517.jpg')

oss.putStream('foo', stream) // 会触发 403 签名错误
// or
oss.putStream('foo.jpg', stream) // 正常上传
oss.putStream('foo.jp', stream) // 还是正常 (>->)
```

但是使用 buffer 就通过 `.put` 方法没有问题。

**Comment by binghaiwang** [comment]
你使用的环境是什么， 浏览器putStream 不能使用

**Comment by PeterRao** [comment]
request 模块把 stream 从 paused 模式变成了 flowing 模式，转换下stream
、、、
      const transform = new require('stream').Transform();
      transform._transform = function(chunk, encoding, done) {
        this.push(chunk);
        done();
      };
     const stream = request.get('https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1521711023223&di=3d2c8f32d382a4139030e790ce06ecd1&imgtype=0&src=http%3A%2F%2Fwww.people.com.cn%2Fmediafile%2Fpic%2F20170103%2F49%2F9774185422066024517.jpg').pipe(transform)

    oss.putStream('foo', stream)
、、、

**Comment by PeterRao** [comment]
request 模块把 stream 从 paused 模式变成了 flowing 模式，转换下stream
```js
const transform = new require('stream').Transform();
transform._transform = function(chunk, encoding, done) {
  this.push(chunk);
  done();
};
const stream = request.get('https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1521711023223&di=3d2c8f32d382a4139030e790ce06ecd1&imgtype=0&src=http%3A%2F%2Fwww.people.com.cn%2Fmediafile%2Fpic%2F20170103%2F49%2F9774185422066024517.jpg')
  .pipe(transform)

oss.putStream('foo', stream)
```

**Comment by binghaiwang** [comment]
对于stream的上传，Request库本身是一个stream, 内部这里自动进行了content-type设置，建议调用sdk时候对options.mime进行设置

```
Request.prototype.pipeDest = function (dest) {
  ...省略...
  if (dest.setHeader && !dest.headersSent) {
    for (var i in response.headers) {
      // If the response content is being decoded, the Content-Encoding header
      // of the response doesn't represent the piped content, so don't pass it.
      if (!self.gzip || i !== 'content-encoding') {
        dest.setHeader(i, response.headers[i])
      }
    }
    dest.statusCode = response.statusCode
  }
 ...省略...
}
```

**Comment by XGHeaven** [comment]
那为什么只要带有扩展名就没问题呢？即使这个扩展名和实际的 content-type 不相同？

**Comment by XGHeaven** [comment]
好的，明白了。我发现通过 options 设置 mime 也是可以的。建议文档里描述一下这个问题。

**Comment by PeterRao** [comment]
![image](https://user-images.githubusercontent.com/1611647/37941957-61b63df0-31a3-11e8-8af1-c80424cb1608.png)
文档有这个参数说明

**Comment by XGHeaven** [comment]
我的意思是说和 request 库的配合问题。说明一下如果使用 request 或者其他库，请确保其不会自动设置 mime，或者手动设置 mime 来避免签名错误。
