### ISSUE TITLE
multipartUpload上传偶尔报InvalidPartOrderError错误，排查是doneParts列表中出现重复数据

### ISSUE THREAD

**Issue by pancaiqiang** [ali-sdk/ali-oss#404]

**Comment by pancaiqiang** [comment]
应该doneParts加个去重复处理就行

**Comment by binghaiwang** [comment]
@pancaiqiang 有没有对分片操作的时候做取消操作呢

**Comment by pancaiqiang** [comment]
没有做取消操作， 我这里逻辑是catch到异常后会做retry操作(断点续传)。按照规律一般分片上传出现ConnectionTimeoutError、 RequestError等错误的时候会有很大概率出现doneParts 中分片重复

**Comment by binghaiwang** [comment]
@pancaiqiang 你现在检测到的是 这边sdk返回给你的checkpoint里边的doneParts内部又重复数据对么？

**Comment by pancaiqiang** [comment]
是的

**Comment by pancaiqiang** [comment]
粘贴的这个片段就是204片重复了
` 
{
      "number": 202,
      "etag": "\"594E5B59D92AD7AD8D7C5CC5C41F959A\""
    }, {
      "number": 203,
      "etag": "\"9C770AD2025C9597CB61512E64335E57\""
    }, {
      "number": 204,
      "etag": "\"9F664D266A473AA7815C29CDF5FC924F\""
    }, {
      "number": 204,
      "etag": "\"9F664D266A473AA7815C29CDF5FC924F\""
    }, {
      "number": 205,
      "etag": "\"BBCE599A43F89FD8FA89ECF94BB1EFE9\""
    },  {
      "number": 206,
      "etag": "\"3905742199624CFC5DBF790DCBE16F5E\""
    }, 
`

**Comment by binghaiwang** [comment]
谢谢反馈，这块我们内部再看下具体问题，统一做下去重复
