### ISSUE TITLE
multipart initMultipartUpload "Cannot read property Bucket of null"

### ISSUE THREAD

**Issue by ZZZRTIAN** [ali-sdk/ali-oss#406]
请教一下
![image](https://user-images.githubusercontent.com/14285113/37897945-1c2c9f42-311a-11e8-910a-7cda87783604.png)
![image](https://user-images.githubusercontent.com/14285113/37898026-496cdeb8-311a-11e8-89b2-b3d312663b9a.png)

**Comment by ZZZRTIAN** [comment]
阿里云上oss上设置问题

**Comment by nanmu32** [comment]
是什么原因，我也遇见了
