### ISSUE TITLE
使用multipartUpload在浏览器直接上传阿里云，接口failed，报错如图

### ISSUE THREAD

**Issue by piluohen** [ali-sdk/ali-oss#411]
报错如图所示，怎么解决？以前都好的，现在新的老的ali-oss-sdk都不行
![53fe016d-00d6-4acf-9dd4-08294e7022bf](https://user-images.githubusercontent.com/22088874/38007643-fade4818-327c-11e8-8777-042e413351bc.png)

**Comment by binghaiwang** [comment]
确认下你的bucket设置跨域了么

**Comment by piluohen** [comment]
@binghaiwang 是在本地测试的，cors跨域origin设置的为*

**Comment by PeterRao** [comment]
https://help.aliyun.com/document_detail/31837.html region 名字错了 `oss-cn-hangzhou`

**Comment by JXLau** [comment]
> https://help.aliyun.com/document_detail/31837.html region 名字错了 `oss-cn-hangzhou`

我这边出现相同的问题， region 名是正确的，如图返回

<img width="313" alt="WX20191028-150339@2x" src="https://user-images.githubusercontent.com/30074374/67658507-b34aa380-f994-11e9-9f86-3f21447c8cb2.png">

**Comment by PeterRao** [comment]
> > https://help.aliyun.com/document_detail/31837.html region 名字错了 `oss-cn-hangzhou`
> 
> 我这边出现相同的问题， region 名是正确的，如图返回
> 
> <img alt="WX20191028-150339@2x" width="313" src="https://user-images.githubusercontent.com/30074374/67658507-b34aa380-f994-11e9-9f86-3f21447c8cb2.png">

1. ping 这个域名看网络是否可通
2. 网络通的话，重试下
