### ISSUE TITLE
使用阿里oss前端直传报这个错误，请问是什么原因呢？

### ISSUE THREAD

**Issue by jiexun216** [ali-sdk/ali-oss#415]
www.jiealioss.com/:1 Uncaught (in promise) TypeError: Failed to fetch (req "error"), POST http://aux.oss-cn-hangzhou.aliyuncs.com.aliyuncs.com/test/%E5%88%87%E6%8D%A21jpg.jpg?uploads= -1 (connected: false, keepalive socket: false)

**Comment by PeterRao** [comment]
你region写错了，应该是oss-cn-hangzhou。  不需要加后面的aliyuncs.com

**Comment by 769062159** [comment]
同问，我是cn-beijing,变成oss-cn-beijing也不行

**Comment by JXLau** [comment]
oss-cn-shanghai，也一直报这个错

**Comment by sunshaobin** [comment]
> oss-cn-shanghai，也一直报这个错
也是上海的也一直报这个错？大佬怎样解决的呢

**Comment by iam-frankqiu** [comment]
> oss-cn-shanghai，也一直报这个错
> <img alt="WX20191028-150339@2x" width="313" src="https://user-images.githubusercontent.com/30074374/67658397-6b2b8100-f994-11e9-8b1a-66fdfd03c3a3.png">
请问下找到原因了吗？我也一直报这个错

**Comment by iam-frankqiu** [comment]
> > oss-cn-shanghai，也一直报这个错
> > 也是上海的也一直报这个错？大佬怎样解决的呢

请问下找到原因了吗？我也一直报这个错

**Comment by web-Marker** [comment]
> > > oss-cn-shanghai，也一直报这个错
> > > 也是上海的也一直报这个错？大佬怎样解决的呢
> 
> 请问下找到原因了吗？我也一直报这个错

我也遇到了 价格微信不  一起交流下 z1307709

**Comment by SoMuchTo** [comment]
> oss-cn-shanghai，也一直报这个错
> <img alt="WX20191028-150339 @ 2x" width="313" src="https://user-images.githubusercontent.com/30074374/67658397-6b2b8100-f994-11e9-8b1a-66fdfd03c3a3.png">

请问找到解决方法了吗

**Comment by SoMuchTo** [comment]
> > > oss-cn-shanghai，也一直报这个错
> > > 也是上海的也一直报这个错？大佬怎样解决的呢
> 
> 请问下找到原因了吗？我也一直报这个错

请问你的那个问题找到解决方法了吗？

**Comment by AmyWang16** [comment]
同样的问题，请问解决了吗

**Comment by xie392** [comment]
我也是这个问题，请问有人解决了嘛？

**Comment by poipo-ly** [comment]
遇到这问题+1
