### ISSUE TITLE
阿里oss前端直传 报<Code > InvalidPart </Code>错误  如何解决呢？

### ISSUE THREAD

**Issue by jiexun216** [ali-sdk/ali-oss#416]
<Error>
<Code>InvalidPart</Code>
<Message>
One or more of the specified parts could not be found or the specified entity tag might not have matched the part's entity tag.
</Message>
<RequestId>5ABDFB3296C00639EF3E7080</RequestId>
<HostId>aux.oss-cn-hangzhou.aliyuncs.com</HostId>
<ETag>undefined</ETag>
<PartNumber>1</PartNumber>
<UploadId>87D4C8D9F285485B8B6F1A113EC1BDE5</UploadId>
</Error>

**Comment by PeterRao** [comment]
给出一下该请求的响应头

**Comment by jiexun216** [comment]
已经解决了 是这个expose headers未设置。谢谢了！！！
