### ISSUE TITLE
oss sts回调后端返回的json数据， 前端解析失败

### ISSUE THREAD

**Issue by zzzzzga** [ali-sdk/ali-oss#420]
stream-http/response.js
              case 'arraybuffer':
			if (xhr.readyState !== rStates.DONE || !xhr.response)
				break
			response = xhr.response
			self.push(new Buffer(new Uint8Array(response)))
			break
new Uint8Array(response) 该方法不能解析json字符串

**Comment by PeterRao** [comment]
提供下具体调用代码

**Comment by zzzzzga** [comment]
let options = {
    accessKeyId: stsTokenData.AccessKeyId,
    accessKeySecret: stsTokenData.AccessKeySecret,
    stsToken: stsTokenData.SecurityToken,
    bucket: stsTokenData.BucketName,
    endpoint: stsTokenData.EndPointName,      
    region: stsTokenData.RegionName,
    secure: stsTokenData.IsHttps,
    dataType: 'json',
    callback: {
      url: stsTokenData.CallBackInfo.Url,
      body: stsTokenData.CallBackInfo.Body,
      contentType: stsTokenData.CallBackInfo.ContentType,
      customValue: stsTokenData.CallBackInfo.CustomValue
    }
client.multipartUpload(filename, file, options).then((results) => {
    // 上传完成
    
    console.log(uploadInfo) 
  }).catch((err) => {    
    console.log(err)
    return Promise.reject(err)
  })

在options中配置回调地址，上传就不成功，发现的原因是 ：无法解析从回调地址返回的json

**Comment by zzzzzga** [comment]
stream-http  2.8以后才有问题，2.7没有问题

**Comment by binghaiwang** [comment]
callback 里边的传入数据能否具体一点 比如stsTokenData.CallBackInfo.ContentType 这个是什么， 并提供下你的x-oss-request-id
