### ISSUE TITLE
4.14.1有报错

### ISSUE THREAD

**Issue by jimshute** [ali-sdk/ali-oss#421]
![image](https://user-images.githubusercontent.com/6091246/38234267-f593ecbe-374f-11e8-957f-ff2d93bbd086.png)
![image](https://user-images.githubusercontent.com/6091246/38234275-fc101f9a-374f-11e8-81c1-5e8d38aa266b.png)

**Comment by PeterRao** [comment]
node 版本多少

**Comment by git9378** [comment]
我的也是同样的报错信息，node 版本是6.11.5 @PeterRao

**Comment by Justin-lu** [comment]
更新个文档就直接把版本更新到  `5.0.0`？

**Comment by PeterRao** [comment]
撤销4.14版本发布了，准备发5.0版本，后续需要支持async/awati 支持性需要到8以上
