### ISSUE TITLE
上传文件报错

### ISSUE THREAD

**Issue by Cyperwu** [ali-sdk/ali-oss#422]
* **Browser Version or Node Version**: Chrome Canary Version 67.0.3382.0 (Official Build) canary (64-bit)
* **ali-oss Version**: v4.13.2
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

具体报错信息：
```
aliyun-oss-sdk.min.js:14 Uncaught (in promise) TypeError: Cannot assign to read only property 'message' of object ''
    at e.exports.<anonymous> (aliyun-oss-sdk.min.js:14)
    at e.exports.n.emit (aliyun-oss-sdk.min.js:7)
    at aliyun-oss-sdk.min.js:10
```
调用了`stsclient.multipartUpload`方法

**Comment by binghaiwang** [comment]
麻烦用源码包复现下错误可以么， 再提供下请求的抓包信息

**Comment by PeterRao** [comment]
打印下初始化的参数，应该是bucket传入错误了

**Comment by cherry-geqi** [comment]
Chrome 66, ali-oss v5.1.1 出现同样问题，Chrome 低于 65 正常。

![cd3a1926-ff22-4900-935f-827ba9f3efa2](https://user-images.githubusercontent.com/13705685/39511841-6f419d80-4e21-11e8-8ec5-32cdbd5cc636.png)

![7e402c76-6d30-404a-bed7-c8857c264738](https://user-images.githubusercontent.com/13705685/39511849-77a715c2-4e21-11e8-9e16-c33146258702.png)

**Comment by wuzhihui1123** [comment]
您好， 怎么没看到问题解决就close掉了， 我这边遇到同样的问题  chrome版本 < 66 正常， >=66 就会出现这个问题
oss-sdk 版本：v4.11.5

**Comment by zcoding** [comment]
今天遇到同样的问题，之前因为新版本的浏览器用户量还比较少，所以没发现，今天一查才发现是sdk的bug

我来解释一下这个bug是怎么产生的：

以v4.13.2的代码为例，[完整代码点这里](https://github.com/ali-sdk/ali-oss/blob/v4.14.0/dist/aliyun-oss-sdk.js#L18056)：

```javascript
if (capability.abortController) {
  var controller = new AbortController();
  signal = controller.signal;
  self._fetchAbortController = controller;
  if ('requestTimeout' in opts && opts.requestTimeout !== 0) {
    global.setTimeout(function () {
      self.emit('requestTimeout');
      if (self._fetchAbortController) self._fetchAbortController.abort();
    }, opts.requestTimeout);
  }
}
```

重点关注2个地方：

1. `capability.abortController` 这里判断是否支持 `AbortController`，[查一下MDN](https://developer.mozilla.org/en-US/docs/Web/API/AbortController#Browser_compatibility)，要Chrome66及以上才支持；
2. `global.setTimeout(...)` 这里设置了定时器，但是！**没有取消定时器的操作！！**也就是说这个定时器是一定会执行的！！！这就是一个定时炸弹啊～那么，这个定时器做了什么操作呢？其实就是把请求cancel掉。也就是说，你的请求如果超过requestTimeout这个时间是一定会被cancel的，也就触发了`AbortError`

解决方案？升级到5.3.1吧，我看了5.3.1的代码，已经加上了取消定时器的操作了。
