### ISSUE TITLE
oss使用姿势问题

### ISSUE THREAD

**Issue by sven0726** [ali-sdk/ali-oss#424]
由于直接var oss = require("ali-oss") 会有编译问题，见 [issue-396](https://github.com/ali-sdk/ali-oss/issues/396#issuecomment-378975261)。所以使用下面方式引用了该包：
var oss = require('ali-oss/dist/aliyun-oss-sdk.js');

然而我尝试了三种创建client的方式都无法成功：
1. 
```
var client = new oss({
      accessKeyId: token.accessKeyId,
      accessKeySecret: token.accessKeySecret,
      bucket: token.bucket,
      region: token.region,
    });
```

Uncaught TypeError: oss is not a constructor

2.
```
 var client = new oss.Wrapper({
      accessKeyId: token.accessKeyId,
      accessKeySecret: token.accessKeySecret,
      bucket: token.bucket,
      region: token.region,
    });
```

Uncaught TypeError: oss.Wrapper is not a constructor

3.
```
var client = oss({
      accessKeyId: token.accessKeyId,
      accessKeySecret: token.accessKeySecret,
      bucket: token.bucket,
      region: token.region,
    });
```
Uncaught TypeError: oss is not a function

**Comment by binghaiwang** [comment]
可否提供一份demo代码， 不清楚这个pro.ant.design

**Comment by sven0726** [comment]
1. [clone 代码](https://pro.ant.design/docs/getting-started-cn#%E7%9B%B4%E6%8E%A5-clone-git-%E4%BB%93%E5%BA%93)
2. yarn add ali-oss
3.  把ali-oss 的引入到某个页面代码文件中
```
var oss = require("ali-oss") 
```
4. yarn run  build
```
Failed to minify the bundle. Error: index.83bdc50e.js from UglifyJs
Unexpected token: name (Mime) [index.83bdc50e.js:109724,8]
```

**Comment by binghaiwang** [comment]
确认下你是在什么环境中使用呢 @sven0726
node 还是 浏览器?

**Comment by sven0726** [comment]
我是在node环境下使用，是客服端代码，非服务器端。浏览器直传图片到oss。 用的是蚂蚁金服的dva脚手架，开发语言是react.

**Comment by binghaiwang** [comment]
var OSS = require('ali-oss/dist/aliyun-oss-sdk');

var client = new OSS.Wrapper({
  region: 'region',
  accessKeyId: 'accessKeyId',
  accessKeySecret: 'accessKeySecret',
  stsToken: 'stsToken',
  bucket: 'bucket'
});

console.log(client); 
我这边使用这样是可以的呢

```
Client {options: {…}, urllib: {…}, agent: noop, ctx: undefined, userAgent: "aliyun-sdk-js/4.13.2 Chrome 65.0.3325.181 on OS X 10.12.6 64-bit", …}
abortMultipartUpload
:
ƒ ()
agent
:
noop {}
append
:
ƒ ()
authorization
:
ƒ authorization(method, resource, subres, headers)
cancel
:
ƒ ()
checkBrowserAndVersion
:
ƒ checkBrowserAndVersion(name, version)
completeMultipartUpload
:
ƒ ()
copy
:
ƒ ()
createRequest
:
ƒ createRequest(params)
ctx
:
undefined
delete
:
ƒ ()
deleteMulti
:
ƒ ()
get
:
ƒ ()
getACL
:
ƒ ()
getObjectUrl
:
ƒ (name, baseUrl)
getStream
:
ƒ ()
head
:
ƒ ()
initMultipartUpload
:
ƒ ()
isCancel
:
ƒ ()
list
:
ƒ ()
listParts
:
ƒ ()
listUploads
:
ƒ ()
multipartUpload
:
ƒ ()
options
:
{region: "region", internal: false, secure: false, bucket: "bucket", endpoint: Url, …}
parseXML
:
ƒ parseXMLThunk(str)
put
:
ƒ ()
putACL
:
ƒ ()
putMeta
:
ƒ ()
putStream
:
ƒ ()
request
:
ƒ ()
requestError
:
ƒ ()
resetCancelFlag
:
ƒ ()
signature
:
ƒ signature(stringToSign)
signatureUrl
:
ƒ (name, options)
uploadPart
:
ƒ ()
urllib
:
{TIMEOUTS: Array(2), request: ƒ, requestWithCallback: ƒ}
userAgent
:
"aliyun-sdk-js/4.13.2 Chrome 65.0.3325.181 on OS X 10.12.6 64-bit"
_checkUserAgent
:
ƒ _checkUserAgent(ua)
```

或者你采用import OSS from 'ali-oss/dist/aliyun-oss-sdk';  这种引入方式试试

**Comment by binghaiwang** [comment]
你打印下这个client 信息  console.log(client);  还有使用的ali-oss的版本是多少

**Comment by sven0726** [comment]
```
var oss = require('ali-oss/dist/aliyun-oss-sdk.js');
console.log('====', oss)
```
![image](https://user-images.githubusercontent.com/4318521/38464177-93b9eb3e-3b3b-11e8-81e2-a173fbd32278.png)

上面打印的是oss 句柄。client panic 打不了。

"ali-oss": "^5.0.0"

@binghaiwang   ali-oss 的client 创建方式是这个吗：![demo](https://github.com/ali-sdk/ali-oss#ossoptions)

**Comment by binghaiwang** [comment]
不要用yarn 这个add 使用npm install ali-oss

**Comment by sven0726** [comment]
oss.default  是 undefined。

使用下面方式引用时打印如下
var oss = require('ali-oss');
![image](https://user-images.githubusercontent.com/4318521/38464837-b7b6a62a-3b46-11e8-8745-1670d12635bd.png)

我现在是因为没办法编译ali-oss。 所以使用 require('ali-oss/dist/aliyun-oss-sdk.js')  这个方式。请问这种方式如何创建oss 的client ，这是我想知道的问题

**Comment by binghaiwang** [comment]
创建方式都是一样的

**Comment by sven0726** [comment]
那是什么原因呢？

**Comment by sven0726** [comment]
你怎么使用的呢？ 我也试过直接拉了pro-antd的代码测试过。 你跑过 build 过程吗？ yarn run build

**Comment by binghaiwang** [comment]
我通过下边这个进行的项目创建
使用命令行工具#
你可以使用集成化的命令行工具 ant-design-pro-cli。
$ npm install ant-design-pro-cli -g
$ mkdir my-project && cd my-project
$ pro new  # 安装脚手架

然后在package里边引用ali-oss , 用yarn add ali-oss 然后  在index.js 里边
```
var oss = require('ali-oss');
var client = new oss.Wrapper({
  region: 'region',
  accessKeyId: 'accessKeyId',
  accessKeySecret: 'accessKeySecret',
  stsToken: 'stsToken',
  bucket: 'bucket',
});
console.log(client);
```

**Comment by binghaiwang** [comment]
build 的话  需要 require('ali-oss/dist/aliyun-oss-sdk') 这种是可以build成功的

**Comment by sven0726** [comment]
不是呀。你的两种操作我都做过。   require('ali-oss/dist/aliyun-oss-sdk')  编译成功了，
但是使用有问题呢,  问题就是我一开始提的问题 。 @binghaiwang

**Comment by binghaiwang** [comment]
@sven0726 我这边试过第二种方式，是可以正常使用的，我让人发你的代码你运行没呢？

**Comment by binghaiwang** [comment]
@sven0726 我这边把那个不能编译的问题解决后，发个版本你到时候用那个试一下吧，等发版本通知你这边，你再试下

**Comment by binghaiwang** [comment]
@sven0726 我这边复现出你的问题了，原因框架对已编译过的库重复编译了,你看下你那边的.webpackrc.js 这个配置文件， 去掉extraBabelIncludes:['/node_modules/ali-oss'] 这个， 然后通过require('ali-oss/dist/aliyun-oss-sdk') 这个引入就可以正常使用了。

**Comment by sven0726** [comment]
我回退到老的版本了。 
```
<script src="http://gosspublic.alicdn.com/aliyun-oss-sdk-4.3.0.min.js"></script>

<script type="text/javascript">
  var client = new OSS.Wrapper({
    region: '<oss region>',
    //云账号AccessKey有所有API访问权限，建议遵循阿里云安全最佳实践，创建并使用STS方式来进行API访问
    accessKeyId: '<Your accessKeyId(STS)>',
    accessKeySecret: '<Your accessKeySecret(STS)>',
    stsToken: '<Your securityToken(STS)>',
    bucket: '<Your bucket name>'
  });
</script>

```
