### ISSUE TITLE
put 上传如何设置socket并发数量？？

### ISSUE THREAD

**Issue by harlanc** [ali-sdk/ali-oss#429]
如题，是在OSS.Wrapper中配置么？？

var ossapi = new OSS.Wrapper({
    region: 'oss-cn-beijing',
    accessKeyId: test.id,
    accessKeySecret: test.secret,
    bucket: 'test',
    timeout: 120000,
   maxSockets : 3
});

**Comment by PeterRao** [comment]
var AgentKeepalive = require('agentkeepalive');
var agent = new AgentKeepalive({
     maxSockets: 3
});
var ossapi = new OSS.Wrapper({
     region: 'oss-cn-beijing',
     accessKeyId: test.id,
     accessKeySecret: test.secret,
     bucket: 'test',
     timeout: 120000,
     agent : agent
});
