### ISSUE TITLE
分片上传multipartUpload文件出错

### ISSUE THREAD

**Issue by liuminyong** [ali-sdk/ali-oss#432]
1：sdk4.14.0升级到5.0.0遇到错误：Error: Failed to upload some parts with error: Error: _createStream requires File/String. part_num: 1

2：proto._createStream = function _createStream(file, start, end) {
  if (is.blob(file) || is.file(file)) {
    return new WebFileReadStream(file.slice(start, end));
  }
  // else if (is.string(file)) {
  //   return fs.createReadStream(file, {
  //     start: start,
  //     end: end - 1
  //   });
  // }

  throw new Error('_createStream requires File/String.');
};
参数file传入的是文件的本地地址。

**Comment by binghaiwang** [comment]
请问你是在什么环境使用浏览器还是node

**Comment by liuminyong** [comment]
node

**Comment by binghaiwang** [comment]
但是看你发的代码 不是node的呀 是浏览器端的逻辑呢

**Comment by binghaiwang** [comment]
你能发下请求的抓包信息么  需要提供下x-oss-request-id

**Comment by binghaiwang** [comment]
你在下边这块打个断点看下
```
proto._createStream = function _createStream(file, start, end) {
  if (is.file(file)) {
    return new WebFileReadStream(file.slice(start, end));
  } else if (is.string(file)) {
    return fs.createReadStream(file, {
      start,
      end: end - 1,
    });
  }
  throw new Error('_createStream requires File/String.');
};
```

**Comment by binghaiwang** [comment]
你的node版本是多少 一定要>=8

**Comment by liuminyong** [comment]
现在用的这种方式var oss = require('ali-oss/dist/aliyun-oss-sdk.js');创建oss，你上面这段代码是在manage-upload.js里，调试source文件里找不到这个js。

**Comment by binghaiwang** [comment]
node中使用不要  require('ali-oss/dist/aliyun-oss-sdk.js') 着么用。。。

**Comment by liuminyong** [comment]
我们这是用electron做的一个客户端，是浏览器场景，v5.0.0用require('ali-oss')报错

**Comment by binghaiwang** [comment]
这个框架  的node版本是基于多少的呢 如果低于8.0 请继续使用v4.x 版本

**Comment by liuminyong** [comment]
可以关闭了，和electron版本有关，谢谢了！
