### ISSUE TITLE
是否有接口返回bucket的详细统计信息？

### ISSUE THREAD

**Issue by callmesoul** [ali-sdk/ali-oss#437]
是否有接口返回bucket的详细统计信息？
例如存储用量，本月外网流量等等~

**Comment by binghaiwang** [comment]
暂时没有这个功能接口的计划, 目前可以通过控制台进行查看。。

**Comment by callmesoul** [comment]
我需要通过接口展示到应用上，自己统计感觉不大实际。既然你们都有统计了，干嘛不把接口开放了呢？
看了五六家对象存储服务的，好像就七牛有统计数据的接口
