### ISSUE TITLE
方法调用传递参数异常

### ISSUE THREAD

**Issue by royiy2k** [ali-sdk/ali-oss#449]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

lib/browser/managed_upload.js 311行：
lib/managed_upload.js  260 行：

return Math.max(
    Math.ceil(fileSize / maxNumParts),
    partSize, //多了逗号
  );

**Comment by binghaiwang** [comment]
请检查你的node 版本是多少  sdk最低node版本8.0 以上
