### ISSUE TITLE
上传文件时提示timeout 5000ms

### ISSUE THREAD

**Issue by shipSun** [ali-sdk/ali-oss#451]
<img width="2048" alt="2018-04-20 9 29 27" src="https://user-images.githubusercontent.com/13898660/39026072-a9ae5e52-447d-11e8-8744-bfef9e2b4c44.png">

**Comment by shipSun** [comment]
safari版本号11.1

**Comment by binghaiwang** [comment]
1.先看下，有没有请求的信息， 有的话提供下request-id
2.如何复现，有没有一个可以复现的demo
3.确定下网络是否正确

**Comment by shipSun** [comment]
下面是请求数据：
摘要
URL: https://ics2.oss-cn-beijing.aliyuncs.com/upload/b32777ee10fabe1a6c6a67b870f71e44.png?uploads=
状态: 200 OK
来源: 网络

请求
Access-Control-Request-Headers: authorization,content-type,x-oss-date,x-oss-security-token,x-oss-user-agent
Origin: https://rrl360.com
Accept: */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
Referer: https://rrl360.com/product/create
Access-Control-Request-Method: POST

响应
Access-Control-Allow-Origin: *
Date: Fri, 20 Apr 2018 02:08:42 GMT
Connection: keep-alive
Access-Control-Allow-Methods: GET, POST, PUT, HEAD, DELETE
Server: AliyunOSS
Access-Control-Expose-Headers: Etag
Content-Length: 0
Access-Control-Allow-Headers: authorization, content-type, x-oss-date, x-oss-security-token, x-oss-user-agent
x-oss-request-id: 5AD94BAA25F151AD7CBA3A93
x-oss-server-time: 0

查询字符串参数
uploads

1、百分百复现
2、其他浏览器可以正常上传

**Comment by shipSun** [comment]
版本：4.11.5

**Comment by shipSun** [comment]
更换5.0.1版本修复了，谢谢

**Comment by binghaiwang** [comment]
@shipSun 建议使用最新的5.1.1
