### ISSUE TITLE
项目版本号的困惑

### ISSUE THREAD

**Issue by willwong123** [ali-sdk/ali-oss#454]
本来我们项目里面用的是  v4.4.1 版本的 sdk，但是最近有用户报了一个 bug。在  Issues 里面搜索了一下，就是这个 [#159](https://github.com/ali-sdk/ali-oss/issues/159)，所以我们准备把 sdk 升级一下。

结果就遇到了下面的一些情况，有些困惑。

1. 在 [Releases](https://github.com/ali-sdk/ali-oss/releases) 页面看到 4.15.0 和 v4.15.0，5.1.0 和 v5.1.0。这两者什么关系？

2. 4.x 的 [dist](https://github.com/ali-sdk/ali-oss/tree/4.x/dist) 目录下的两个文件都是空的？同理，通过 npm install ali-oss@^4 下载下来的也是空文件。

3. v4.15.0 的 [dist](https://github.com/ali-sdk/ali-oss/tree/v4.15.0/dist) 目录下的两个文件是正常的，但是 https://github.com/ali-sdk/ali-oss/blob/v4.15.0/dist/aliyun-oss-sdk.js#L1 这个地方的注释却是 v4.13.2；这里的版本号不是通过 build 的时候，获取的 package.json 中的 version？

4. v5.1.0 有哪些 break changes？可以直接从 v4.4.1 上吗？

5. `npm install ali-oss@latest` 下载下来的已经是 v5.1.1 了，并且可以看到 v5.1.1 版本的 publish_time 是 2018-04-16，为啥 Releases 里面看不到？

**Comment by binghaiwang** [comment]
4.x和5.x 
浏览器端： 对外部调用者可以无缝移植，只有内部的语法不一样， 4.x采用的还是老的es5语法 没有加入eslint 5.x做了改造采用es6/es7语法 , 并加入eslint 静态代码扫描

node平台：
4.x最低支持node 5
5.x最低支持node 8
