### ISSUE TITLE
oss请求返回的数据是xml格式的，demo里面是json，是不是我姿势不对

### ISSUE THREAD

**Issue by vincent-li** [ali-sdk/ali-oss#455]
一个小问题，我直接引用了dist/ 下的文件，ststoken是没有问题的。

oss = new OSS.Wrapper(result)

oss.list({
            prefix: path,
            delimiter: '/'
        }).then((res) => {
            let files = x2js.xml2json(res)
            console.log('--->', res)
            console.log('--->', files)
        })

上面的执行结果也是没有问题的，只是为何没有走到then，log出来信息。而是在connect里面查看请求的时候可以看到response是xml的返回。

需要什么特殊姿势吗？

**Comment by binghaiwang** [comment]
看下抓包信息

**Comment by binghaiwang** [comment]
或者你看下使用 example 里边  启动本地服务参考下
