### ISSUE TITLE
上传完成后我想更新这个视频，是不是只能删除掉这个视频了呢？

### ISSUE THREAD

**Issue by buzai** [ali-sdk/ali-oss#458]
其实 是想复用这个 vid。不用占用多余的存储空间。文档的api看了貌似只能我自己删除 然后重新传一个新的视频方式实现是么？

**Comment by buzai** [comment]
@binghaiwang 有没有个demo啥的文档没发现。。。可以覆盖的参数

**Comment by buzai** [comment]
@binghaiwang 

```
    //视频点播上传的OSS
    const vod = new OSS({
        accessKeyId: auth.AccessKeyId,
        accessKeySecret: auth.AccessKeySecret,
        bucket: address.Bucket,
        endpoint: address.Endpoint,
        stsToken: auth.SecurityToken,
        timeout: '3600s'
    })
    const source = await client.getStream(path)
    //执行并且等待上传完成
    await vod.putStream(address.FileName, source.stream)
```
path 是oss 的路径 我获取了一个 stream。
然后 用 vod 获取上传凭证的接口返回的数据 加上 oss sdk 构建的 vod 对象的 putStream 上传到点播平台。

但是 这个思路没法更新视频啊，这个获取凭证没法传递 vid 。有一个接口可以刷新凭证，但是这个刷新接口没发现可以更新文件名的参数，也就是说这个 刷新只是刷新了 token信息，对应这个vid的文件信息没法变

**Comment by binghaiwang** [comment]
putStream 第一个参数 跟oss上边的object 名 一样就会覆盖掉

**Comment by buzai** [comment]
@binghaiwang 十分感谢
