### ISSUE TITLE
ConnectionTimeoutError: Connect timeout for 60000ms

### ISSUE THREAD

**Issue by xiaoyuhen** [ali-sdk/ali-oss#461]
```
Failed to upload some parts with error: ConnectionTimeoutError: Connect timeout for 60000ms, PUT https://zhihu-video-input.oss-cn-hangzhou.aliyuncs.com/m3u8MultibitrateIn58/2018050316/95b9f5c8-4eaf-11e8-b5bc-0242ac112a0c.mp4?partNumber=1&uploadId=F4AC44DBC37144A4B6BA20D23E3C6CB9 -2 (connected: false, keepalive socket: false)headers: {} part_num: 1
```
近期后台监控到很多用户分片上传连接超时的问题，且某个视频如果上传失败，用户接下来的上传仍旧会失败，但把视频源文件要到之后并不能复现。
ali-oss 并不会在连接超时的 error 中添加 requestId ，所以也无法排查
ali-oss 已经升级到 5.1.1 版本，目前的分片为 1M/个

请问在用户连接超时时，如何获取到用户的 requestId？
某个分片连接超时 ali-oss 会重试吗？如果不能重试是否只能通过断点续传的方法才能让用户继续上传？

**Comment by binghaiwang** [comment]
这个连接超时 是因为客户端的连接超时， 所以还没有到达 oss服务器这边， 所以是不会有requestId的， 只能通关提示用户手动触发续传了

**Comment by xiaoyuhen** [comment]
那解决办法是提供断点续传功能？https://help.aliyun.com/document_detail/31850.html

但为什么会出现再次上传该视频文件仍旧失败的情况呢？

**Comment by PeterRao** [comment]
1. 超时不会返回 requestid。
2. 业务方需要自行处理超时逻辑，要么加大timeout时间或者提示用户保证网络通畅后进行续传操作。

**Comment by xiaoyuhen** [comment]
@PeterRao 目前的解决办法是这样

自己写了一个 retry 函数，在超时/网络错误时触发断点续传，并动态增加 timeout 时间。
之后又遇到了 token 过期的情况，增加了重新获取 token 的逻辑。

这些逻辑应该 SDK 去处理，而不应该交给业务方。
Android/iOS 的 oss-sdk 应该是有这些功能的，而这些功能对上传成功率的提升有很大效果。

**Comment by PeterRao** [comment]
1. 重试本身是业务上的逻辑，使用我们sdk各个业务重试的策略可能各不相同。
2. 不需要动态加大超时时间，初始去加大超时时间就行。超时时间不会影响上传逻辑和性能，固定60s之前是给node用的，对端应用这个时间太小了，@binghaiwang 看下是否去根据分片大小加大浏览器环境下的超时时间，给出一个合理的超时时间设置。
3. token过期的逻辑可以加到 sdk 里面，@binghaiwang @luozhang002  你们跟进下吧。

**Comment by xiaoyuhen** [comment]
@PeterRao 感谢回复。
重试这个事情倒不是很复杂，只是刚开始没有往这方面想，因为默认会觉得 SDK 应该会提供。目前暂时没有这方面的困扰了，超时问题已经解决。
