### ISSUE TITLE
在 Worker 里使用时报错“window is not defined”

### ISSUE THREAD

**Issue by fancyoung** [ali-sdk/ali-oss#462]
Web Worker 引入 ali-oss 时直接报错。

貌似是调“window.localStorage”时

**Comment by binghaiwang** [comment]
咱们sdk 暂时还不支持在worker中运行

**Comment by fancyoung** [comment]
@binghaiwang 貌似 aliyun-sdk-js 是可以，请问有什么特殊原因所以不支持么（是否有坑）。
因为只用到签名读文件部分，所以 ali-oss 不支持的话考虑自己实现。

**Comment by leejunhui** [comment]
2023 年了，ali-oss 现在支持 worker 了吗

**Comment by rowthan** [comment]
+1 怎么姐姐

**Comment by schunlee** [comment]
> +1 怎么姐姐

 我后面直接改用cloudflare worker + r2了，作为个python程序员，我简直很抓狂

**Comment by ricky11** [comment]
but even  const OSS = require('ali-oss'); still get window is not defined.

I am use cloudflare workers, which is the same as webworker.

**Comment by schunlee** [comment]
> but even const OSS = require('ali-oss'); still get window is not defined.
> 
> I am use cloudflare workers, which is the same as webworker.

why not try cloudflare R2?

**Comment by ricky11** [comment]
cloudflare r2, even though egress is free, they will force you to use their stream product.. and r2 lacks many other features of a typical storage service... you can expliceitly select regions (including Mainland regions)  -- Ali oss is reliable and good, unfortunately the sdk is not maintained!

**Comment by ricky11** [comment]
How are you importing ES6 style?

const OSS = await import('ali-oss/dist/aliyun-oss-sdk');
const { default: OSS } = await import('ali-oss')
import {OSS} from 'ali-oss';

Which way?
