### ISSUE TITLE
从5.1开始build之后出现 Uncaught TypeError: Cannot create property 'createCredentials' on string '0'

### ISSUE THREAD

**Issue by jiyarong** [ali-sdk/ali-oss#473]
* **Browser Version or Node Version**: chrome 最新， node 8.9.1
* **ali-oss Version**: 5.2

在create-react-app中使用
```js
var OSS = require('ali-oss/dist/aliyun-oss-sdk.min.js')
export const client = new OSS.Wrapper({
	region: 'oss-cn-beijing',
	accessKeyId: 'xxx',
	accessKeySecret: 'xxx',
	bucket: 'peter-blog'
});
```

build完之后，出现
`Uncaught TypeError: Cannot create property 'createCredentials' on string '0'`

**Comment by luozhang002** [comment]
请问你的build是指使用create-react-app脚手架工具构建后运行npm run build吗？
我本地使用create-react-app(1.5.2)脚手架创建了一个新的项目，用n把切换node 版本到8.9.1,chrome的版本如下
<img width="398" alt="2018-05-22 6 59 42" src="https://user-images.githubusercontent.com/5653578/40334226-2d8f2ccc-5d8f-11e8-88b8-9a26350f0c3a.png">
然后项目下安装了ali-oss@5.2.0版本，在工程App.js引入你写的这段代码，再npm run build运行项目，本地并未发现报错。建议你尝试下：使用create-react-app重新构建一个新的项目，然后再安装我们的ali-oss，再引入这段代码，再build看是否有报错，或者把node_module删除再重新build一次，再看看有什么结果

**Comment by jiyarong** [comment]
@luozhang002 build不报错，部署后报错

**Comment by mdluo** [comment]
最新的 ali-oss@5.3.0，通过 `ali-oss/dist/aliyun-oss-sdk.min` 导入，使用 webpack build 之后依然出现同样的报错，包括删除 node_module 重新安装之后。切换回 4.15.0 就没有这个问题了。

@luozhang002  问题还没有解决，请 reopen 这个 issue

**Comment by linmowang** [comment]
Browser Version or Node Version: chrome 最新， node 8.9.3
ali-oss Version:  6.0.1
build不报错，部署后报错

部署后也报了 Cannot create property 'createCredentials' on string '0'

**Comment by luozhang002** [comment]
本地并未重现错误，本地采用了create-react-app脚手架，在APP.js代码里加入简单的OSS上传逻辑。我代码如下：
<img width="987" alt="2018-09-10 11 11 20" src="https://user-images.githubusercontent.com/5653578/45274504-55d26980-b4ea-11e8-93ae-57fac7f91746.png">

server -s build 
<img width="720" alt="2018-09-10 11 10 50" src="https://user-images.githubusercontent.com/5653578/45274511-61be2b80-b4ea-11e8-8ac1-e589c9e77e97.png">

浏览器运行后的结果
![2018-09-10 11 11 04](https://user-images.githubusercontent.com/5653578/45274521-6f73b100-b4ea-11e8-946b-0e496a7fb0fb.png)

我本地并未浮现。所以希望能提供具体的步骤和截图，我这边也方便统一修下。而且 ·Cannot create property 'createCredentials' on string '0' 这个错误感觉跟构建工具有关系吧，跟SDK本身应该并没有多大关系。

**Comment by lzx493535562** [comment]
node v10.16
ali-oss v6.0.0
webpack v3.12.0
Browser路由模式
build后正常，部署到服务器访问时报错：
Uncaught TypeError: Cannot create property 'createCredentials' on string '0'
解决方案：删除node_modules; 使用yarn ；问题解决；
之前一直以为OSS版本问题，后面怀疑是使用cnpm&npm 吧(windows系统)！！！

**Comment by pan463859** [comment]
"ali-oss": "^6.1.1",
导入方式
import OSS from 'ali-oss'

var client =new OSS({
  region: '*****',
  accessKeyId: ****',
  accessKeySecret: '****',
  bucket: '*****'
});
  
function OSSDown (filename) {
  let url = client.signatureUrl(filename);
  return url
  }
export {
  OSSDown
} 
本地运行没问题，打包上线报错 用的是yarn安装的 然后webpack打包

**Comment by web-Marker** [comment]
@jiyarong 请打开问题，目前也出现了这个问题，本地开发没有问题，放到线上就出问题

**Comment by 0123cf** [comment]
同问题

**Comment by 0123cf** [comment]
@luozhang002 是build后才出现     人家很明确指出了  然后你直接把issue关闭，不好吧。。

**Comment by PeterRao** [comment]
是否能一共一个线上可访问的链接，我这边定位下

**Comment by song3593** [comment]
我们现在也遇到同样问题。本地正常，线上部署后出错

**Comment by song3593** [comment]
reopen吧

**Comment by PeterRao** [comment]
最好能给一个线上地址，我能调试下

**Comment by PeterRao** [comment]
各位使用6.10.0 版本试下。之前因为压缩工具导致的问题
