### ISSUE TITLE
ali-oss能否提供typescript支持？

### ISSUE THREAD

**Issue by cqu1980** [ali-sdk/ali-oss#474]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

我在typescript下开发Node.js项目，需要使用ali-oss，但是缺少ts下的提示，能否提供d.ts提示插件？

**Comment by Bosn** [comment]
同求，现在只能这样
```typescript
declare module 'ali-oss' {
  let mod: any
  export = mod
}
```

**Comment by luozhang002** [comment]
@cqu1980 @Bosn 这个已经进入排期，需要等到发布大版本后才考虑支持的

**Comment by allenlongbaobao** [comment]
@luozhang002 模板文件中是不是没有导出 STS，我在使用的时候是这样的：

`import {STS} from "ali-oss" `

但是提示 STS 没有导出，麻烦看一下。

**Comment by asins** [comment]
@types/ali-oss 里不包含STS的内容，只能自己去补全了。
