### ISSUE TITLE
从 5.0.1 升级到 5.2.0 之后，signatureUrl 返回的路径无法打开

### ISSUE THREAD

**Issue by tulayang** [ali-sdk/ali-oss#484]
5.0.1 的签名携带

OSSAccessKeyId=xxxxxxxx&Expires=xxxxxxxx&Signature=xxxxxxxxx3D&response-content-type=

5.2.0 的签名携带

OSSAccessKeyId=xxxxxxxx&Expires=xxxxxxxx&Signature=xxxxxxxxx3D&response-content-type=text20%plain

感觉 5.2.0 的 Signature 字段变长了，而且无法打开文件。回滚到 5.0.1 可以打开文件

**Comment by luozhang002** [comment]
@tulayang 我本地有个测试demo是下载文件的，采用5.2.0签名后是可以下载，浏览器也是可以访问的。

**Comment by tulayang** [comment]
@luozhang002

不好意思，我最近比较忙，还没来得及重新测试。现在恢复到了 5.0.1。我用你的方案重新测试一下。

**Comment by luozhang002** [comment]
好的
