### ISSUE TITLE
npm 没有发布 5.3.0 版本

### ISSUE THREAD

**Issue by xiaoyuhen** [ali-sdk/ali-oss#492]
![image](https://user-images.githubusercontent.com/11402392/41636429-04ed0b64-7481-11e8-976d-e65871b8bc33.png)

npm 仍旧是 5.2.0 版本。

**Comment by luozhang002** [comment]
@xiaoyuhen 只是把代码提交上去了，今天会发个版本的，下个版本5.3.0的

**Comment by luozhang002** [comment]
@xiaoyuhen 5.3.0和cdn都已经同步发布，欢迎试用
