### ISSUE TITLE
require('ali-oss')报错

### ISSUE THREAD

**Issue by lvyangxu** [ali-sdk/ali-oss#493]
384|Author | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
384|Author | /opt/app/front/Authorize/node_modules/ali-oss/lib/managed_upload.js:263
384|Author |   );
384|Author |   ^
384|Author | SyntaxError: Unexpected token )
384|Author |     at createScript (vm.js:53:10)
384|Author |     at Object.runInThisContext (vm.js:95:10)
384|Author |     at Module._compile (module.js:543:28)
384|Author |     at Object.Module._extensions..js (module.js:580:10)
384|Author |     at Module.load (module.js:488:32)
384|Author |     at tryModuleLoad (module.js:447:12)
384|Author |     at Function.Module._load (module.js:439:3)
384|Author |     at Module.require (module.js:498:17)
384|Author |     at require (internal/module.js:20:19)
384|Author |     at Object.<anonymous> (/opt/app/front/Authorize/node_modules/ali-oss/lib/client.js:135:14)

node 8.11.2 环境下,引用包报错
let oss = require('ali-oss')
奇怪的是windows下没有问题.centos就会报错

**Comment by luozhang002** [comment]
@lvyangxu 是node环境的吧，请确认ali-oss的版本，因为我本地没有centos的系统，所以我首先建议你尝试下用n升级下node新版，然后使用ali-oss 5.2.0版本再试用下，看看centos下是否还有问题。如果再有问题的话，我这边会搭建centos虚拟环境测试的。

**Comment by lvyangxu** [comment]
我的环境是Node8最新版+ali-oss 5.2.0，报的这个错误。是函数尾逗号的问题吗？

**Comment by luozhang002** [comment]
@lvyangxu，哪个函数，你本地代码排查先，通过注释删除看下，我这边要先搞个centos的环境

**Comment by lvyangxu** [comment]
我换成了node10的最新版，问题解决了。node旧版本中是不允许尾逗号（ trailing comma ）的

**Comment by luozhang002** [comment]
好的

**Comment by NoraGithub** [comment]
这个问题需要解决下吧。。。使用的7.9　怕是不兼容。。
