### ISSUE TITLE
对象复制错误

### ISSUE THREAD

**Issue by zengonly** [ali-sdk/ali-oss#494]
![image](https://user-images.githubusercontent.com/21103564/41758532-cff30566-761b-11e8-8434-7b99469bd644.png)
参数顺序返过来用可以
![image](https://user-images.githubusercontent.com/21103564/41758548-f0d73e50-761b-11e8-90d9-c822f848fcef.png)
![image](https://user-images.githubusercontent.com/21103564/41758565-0cca4ed6-761c-11e8-875a-c173700b89df.png)

**Comment by luozhang002** [comment]
@zengonly，你的指copy接口参数顺序反过来还能拷贝成功?，以copy('to','/from-bucket/from') 如果这样的话请确认你当前的bucket中是否存在‘to’
