### ISSUE TITLE
请问RN用这个有问题吗？一直报错

### ISSUE THREAD

**Issue by verzqli** [ali-sdk/ali-oss#496]
error: bundling failed: Error: Unable to resolve module ./browser/client from /Users/aiya/Documents/StudioProjects/****/node_modules/ali-oss/dist/aliyun-oss-sdk.js: The module ./browser/client could not be found from /Users/aiya/Documents/StudioProjects/****/node_modules/ali-oss/dist/aliyun-oss-sdk.js. Indeed, none of these files exist:
只要调用了var OSS = require('ali-oss'); 就会报上面那个错，不明白什么原因 node 版本V8.9.4

**Comment by luozhang002** [comment]
@verzqli 我们这个仓库是没有RN的，RN是单独起的一个项目  https://github.com/aliyun/aliyun-oss-react-native ，以后有问题可以直接里面提issue,已经发布1.0.0-alpha.1，花影使用，有啥不明白的，直接@我
