### ISSUE TITLE
how to list buckets, when the prefix contains "/"

### ISSUE THREAD

**Issue by stsean** [ali-sdk/ali-oss#497]
I want to use "listBuckets" to list all bucket which contains the prefix, such as "/foo/bar", but it will show the error about invalid prefix.
Is it a bug, or is the filename in the bucket cannot contain slash?

**Comment by luozhang002** [comment]
@stsean you use listBuckets in node ?

**Comment by stsean** [comment]
Yes. The  main purpose is that we want to Implement some functions like fs.readdir. Does this library have other functions to substitute fs.readdir, or we could use listBuckets only?

**Comment by luozhang002** [comment]
@stsean  listBuckets is designed to list all the buckets you create, the prefix options should obey the rule that it is should  be a part of bucket name ,and the bucket name can not cantain '/', it is a valid prefix.

**Comment by stsean** [comment]
Ok, I got it. thanks.
