### ISSUE TITLE
调用上传方法时报错 “ Uncaught (in promise): Error: _getFileSize requires Buffer/File/String.”

### ISSUE THREAD

**Issue by leihg** [ali-sdk/ali-oss#499]
作者，你好，在开发浏览器web项目客户端的时候调用方法 'multipartUpload'时报错，报错信息如下：

ERROR Error: Uncaught (in promise): Error: _getFileSize requires Buffer/File/String.
Error: _getFileSize requires Buffer/File/String.

请问，原因是？如何解决？thank you！

附，其他信息：
1、使用的是angular4框架，组件化开发；
2、语言：typescript；
3、使用的是sdk ‘aliyun-oss-sdk.min.js’，版本5.3.0
4、此组件所有代码如下：

`import { Component, OnInit, Input, Output, EventEmitter } from '';

declare const OSS: any;

@component({
selector: 'app-file-upload-oss',
templateUrl: './file-upload-oss.component.html',
styleUrls: ['./file-upload-oss.component.scss']
})

export class FileUploadOssComponent implements OnInit {

// configuration parameter
@input() type?: String = 'rectangle';
@input() region: string;
@input() accessKeyId: string;
@input() accesskey: string;

@input()
set bucket(val: string) {
if (val !== '' && val.indexOf('/') !== val.length - 1) {
val = val + '/';
}
this._bucket = val;
};
get bucket(): string {
return this._bucket;
};

@output() uploadStatus = new EventEmitter();

_bucket: string;
filesList: any[] = [];

// Handle files
handleFiles(files: any[]) {
return new Promise((resolve) => {
for (const file of files) {
file['loading'] = false;
file['remove'] = false;
file['percent'] = 0;
};
resolve(files);
});
};

// click select files
clickSelectFiles($event: any) {
this.filesList.length = 0;

this.handleFiles($event.target.files).then((files: any[]) => {
  this.filesList.push(...files);
});
};

// dragover preventDefault
dragover($event: any) {
$event.preventDefault();
};

// drop select files
dropSelectFiles($event: any) {
$event.preventDefault();

this.handleFiles($event.dataTransfer.files).then((files: any[]) => {
  this.filesList.push(...files);
});
};

// remove files
removeFile(index: number) {
this.filesList[index]['removeAnimation'] = 'fadeOutRight';
setTimeout(() => {
this.filesList.splice(index, 1);
}, 300);
};

// upload files
uploadFile() {
const file = document.getElementById('btn')['files'][0];
const files = this.filesList;
const key = 'object';

const client = new OSS.Wrapper({
  region: this.region,
  accessKeyId: this.accessKeyId,
  accessKeySecret: this.accesskey,
  bucket: this.bucket
});

client.multipartUpload(key, file, {
  progress: this.progress
}).then(((res: any) => {
  alert(`${res}`);
  console.log('upload success');
  this.uploadStatus.emit(res);
}));
};

// upload progress
progress(p: any) {
console.log(进度${p});
};

constructor() { }

ngOnInit() {
}

}
`

**Comment by luozhang002** [comment]
@leihg const file = document.getElementById('btn')['files'][0]; 你这个file是标准的H5 file吗，请确认下

**Comment by leihg** [comment]
@luozhang002 你好，是的，“const file = document.getElementById('btn')['files'][0]”，这是依照你们demo来使用的，其实，我需要上传的是下一行代码“const files = this.filesList;”，这是存放文件信息的数组；

**Comment by PeterRao** [comment]
console.log(file) 下，截图看下控制打印的信息。

**Comment by leihg** [comment]
以下是代码块：
  // upload files
  uploadFile() {
    const files = this.filesList;
    const key = 'object';

    console.log(files);

    const client = new OSS.Wrapper({
      region: this.region,
      accessKeyId: this.accessKeyId,
      accessKeySecret: this.accesskey,
      bucket: this.bucket
    });

    client.multipartUpload(key, files, {
      progress: this.progress
    }).then(((res: any) => {
      alert(`${res}`);
      console.log('upload success');
      this.uploadStatus.emit(res);
    }));

  };

以下是打印的file信息：
![tim 20180628180511](https://user-images.githubusercontent.com/19809782/42028092-e8ca9982-7afd-11e8-920f-af7ab9e9026a.png)

**Comment by PeterRao** [comment]
你传入的是个数组，接口要求传入的是 File 对象
```
console.log(files);

const client = new OSS.Wrapper({
  region: this.region,
  accessKeyId: this.accessKeyId,
  accessKeySecret: this.accesskey,
  bucket: this.bucket
});

client.multipartUpload(key, files[0], {
  progress: this.progress
}).then(((res: any) => {
  alert(`${res}`);
  console.log('upload success');
  this.uploadStatus.emit(res);
}));
```

**Comment by leihg** [comment]
你说的对，我修改为为File对象后那个错误就没有了，但是又报错另外一个错误，怎么回事儿啊，谢谢！


在2018年6月29日 10:09，饶培泽<notifications@github.com> 写道：

你传入的是个数组，接口要求传入的是 File 对象

console.log(files);

const client = new OSS.Wrapper({
  region: this.region,
  accessKeyId: this.accessKeyId,
  accessKeySecret: this.accesskey,
  bucket: this.bucket
});

client.multipartUpload(key, files[0], {
  progress: this.progress
}).then(((res: any) => {
  alert(`${res}`);
  console.log('upload success');
  this.uploadStatus.emit(res);
}));

**Comment by leihg** [comment]
我修改为为File对象后那个错误就没有了，但是又报错另外一个错误，错误信息如下:
![tim 20180629101258](https://user-images.githubusercontent.com/19809782/42069669-9973b7c8-7b85-11e8-8095-5df968622281.png)

**Comment by PeterRao** [comment]
设置 cors 跨域设置了吗。https://help.aliyun.com/document_detail/64056.html?spm=a2c4g.11186623.6.782.jJfZGw 步骤可以参考官网

**Comment by leihg** [comment]
已设置，如下 ：
![tim 20180629121749](https://user-images.githubusercontent.com/19809782/42072988-834ac5b6-7b96-11e8-8205-511da012877d.png)

报错信息中：
![tim 20180629122008](https://user-images.githubusercontent.com/19809782/42073052-da47b7b6-7b96-11e8-9110-e1de59bf1828.png)

地址没问题吗？

**Comment by PeterRao** [comment]
有问题
```
[region] {String} the bucket data region location, please see Data Regions, default is oss-cn-hangzhou.
```
这个应该传oss-cn-qingdao。你的地址多了一个`.`

**Comment by leihg** [comment]
依然不行，此处为何会有一点个 '.'
![tim 20180629124143](https://user-images.githubusercontent.com/19809782/42073518-e6ada5e4-7b99-11e8-8994-e73e863a5562.png)

**Comment by PeterRao** [comment]
把传递的参数在控制台打印下

**Comment by leihg** [comment]
初始化参数，都是些重要参数，accessKeySecret我打了马赛克，肯定没有错的，如下：
![tim 20180629162114](https://user-images.githubusercontent.com/19809782/42082208-f865a8f2-7bb9-11e8-80d1-7ad2d0c253d4.png)

**Comment by luozhang002** [comment]
@leihg https://help.aliyun.com/document_detail/31827.html#h2-url-0 bucket命名有问题呀，请仔细看文档, 不要加 '/'

**Comment by leihg** [comment]
从打印初始化参数中bucket命令确实带有"/"，但是我在命令的时候根本没有添加“/”，这应改sdk自动添加的吧，请看如下附件：

**Comment by leihg** [comment]
@luozhang002  ,从打印初始化参数中bucket命令确实带有"/"，但是我在命令的时候根本没有添加“/”，这应改sdk自动添加的吧，请看如下附件：
![tim 20180630080942](https://user-images.githubusercontent.com/19809782/42119424-275a2b04-7c3e-11e8-9b0c-14ab7c300f27.png)

**Comment by leihg** [comment]
@luozhang002 ,我的代码中确实有添加“/”处理，我去掉了，现在报403错误，是还有哪地方没有注意到吗？如下：
![tim 20180630085309](https://user-images.githubusercontent.com/19809782/42119834-1c133b00-7c43-11e8-9b48-93932ae1704f.png)

**Comment by luozhang002** [comment]
@leihg ,现在这个url地址是正确的了，你登陆控制台看下你的bucket ACL权限

**Comment by leihg** [comment]
现在能够上传成功，在OSS里面能看到上传成功的文件，但是会有以下问题：
1、上传时仿佛大于100kb的上传不了，我看你们sdk文档中写的是上传文件的大小限制在5G以下，为什么文件稍微大点（100kb以上）就上传不了；
2、每次上传都会报错（无论成功与否），报错信息如下：
![tim 20180630110550](https://user-images.githubusercontent.com/19809782/42120896-00305af4-7c56-11e8-8a1f-6ee4d091c590.png)
3、我在上传成功回调函数中做了一些事情，但是仿佛没有执行回调函数，是因为报错的原因吗？

以下是咨询：
1、回调函数能否返回文件上传成功后的url，即想通过此url查看已上传的文件；
2、OSS是否有对上传文件进行安全监测，如:病毒文件；

**Comment by luozhang002** [comment]
1.mulipartUpload上传回调后

**Comment by luozhang002** [comment]
1.上传回调后，可以自己打印res自己看下，
<img width="1165" alt="2018-06-30 12 30 59" src="https://user-images.githubusercontent.com/5653578/42121460-28db1db6-7c62-11e8-9492-f37183128fc8.png">，是可以看到url的，如果bucket设置的公共读写也是可以直接通过Url访问的。

**Comment by PeterRao** [comment]
[progress] {Function} thunk or generator, the progress callback called after each successful upload of one part, it will be given three parameters: (percentage {Number}, checkpoint {Object}, res {Object})

**Comment by shilianmalaxiangguo** [comment]
I'm stupid, see the console files it is a dear object
