### ISSUE TITLE
How to set the content-tpye of the upload object?

### ISSUE THREAD

**Issue by SSSANTON** [ali-sdk/ali-oss#507]
I upload a mp4 video with put object method like this：

`  ossclient.put('/videos/'+req.file.filename+pathLib.parse(req.file.originalname).ext, newName, {mime:'application/octet-stream'})`

After uploading , the content-type is still 'video/mp4', but I want to set it to 'application/octet-stream'.

**Comment by SSSANTON** [comment]
"ali-oss": "^6.0.1"
第二个参数是string
可以上传成功，但content-tpye不是上面设定的值。

**Comment by luozhang002** [comment]
@SSSANTON  开启调试模式  DEBUG=ali-oss node xxx.js， 设置一个 content-type然后截图 顺便吧x-oss-request-id发过来

**Comment by SSSANTON** [comment]
@luozhang002 


x-oss-request-id":"5B51B19741F2DE042C168747
![_20180720175819](https://user-images.githubusercontent.com/3401843/42996751-0da5e824-8c47-11e8-9125-ee3d5bee6052.png)
