### ISSUE TITLE
调用uploadPart方法返回数据中没有etag，导致文件片段无法completeMultipartUpload

### ISSUE THREAD

**Issue by XiangYangHan** [ali-sdk/ali-oss#509]
* **Browser Version or Node Version**: Chrome 版本 65.0.3325.146（正式版本）
* **ali-oss Version**: aliyun-oss-sdk-6.0.1.min.js
作者你好，在开发浏览器端获取stsToken后分片上传文件到OSS的功能中，我发现了一个现象与官方文档不一致的地方：我无法从uploadPart方法的返回中获取Etag，
响应头x-oss-request-id：5B56FB154C1E0B634A8818DE、5B56FB134C1E0B634A881072
![image](https://user-images.githubusercontent.com/24455362/43131998-0d647a28-8f6d-11e8-8e09-d592f42b536b.png)
这导致我们在后面调用completeMultipartUpload整合上传的文件片段时出现400 (Bad Request)，
响应头 x-oss-request-id：5B56FB76EB715091BB78D217
![image](https://user-images.githubusercontent.com/24455362/43132316-fd3ce490-8f6d-11e8-8ea4-20df27320446.png)
我们发现在响应头里面是有ETag的，现在的ETag是通过这样的方式返回的吗？
![image](https://user-images.githubusercontent.com/24455362/43132660-0c5931c6-8f6f-11e8-8be7-2fb5d2daf517.png)
请问该如何正确的获取ETag？谢谢

**Comment by luozhang002** [comment]
@XadillaX  
<img width="787" alt="2018-07-24 9 57 38" src="https://user-images.githubusercontent.com/5653578/43143130-a5b790b6-8f8c-11e8-9bb5-cb949172340d.png">

**Comment by XiangYangHan** [comment]
@luozhang002 你好，参照截图中的demo来做，还是没有取到etag
![image](https://user-images.githubusercontent.com/24455362/43175566-613d3f1a-8ff2-11e8-931a-a9269685267a.png)

**Comment by luozhang002** [comment]
我本地是OK的，6.0.1，你的那个 file传入的是啥东西。
<img width="970" alt="2018-07-25 10 53 24" src="https://user-images.githubusercontent.com/5653578/43177157-75af7682-8ff9-11e8-8009-e2cff3fbef44.png">

**Comment by XiangYangHan** [comment]
多谢你的耐心回答，这个file参数是页面中通过`<input type="file" multiple>`选择的文件对象。
下面是完整的函数调用栈截图，帮我看下是哪里出了问题
页面引入SDK：
![image](https://user-images.githubusercontent.com/24455362/43178269-1fdbe49c-8fff-11e8-996f-592dbb5f1fc2.png)
1. 获取选择的文件
![image](https://user-images.githubusercontent.com/24455362/43177807-a73adcc0-8ffc-11e8-8b3b-e3307105f4f7.png)
2. 计算文件md5传给本地服务器，用来让服务器判断是否上传过此文件，没有的话返回在OSS创建该文件的stsToken等信息。
3. 根据服务器返回的信息，初始化一个OSS对象，并调用其initMultipartUpload方法、uploadPart方法（出现问题）
![image](https://user-images.githubusercontent.com/24455362/43178199-b5439ef4-8ffe-11e8-9c58-6e97771b7f79.png)

**Comment by luozhang002** [comment]
@XiangYangHan  也看不出啥毛病 ，你为啥还要自己写整个分片上传的逻辑，我们已经提供了multipartUpload接口，不满足需求？。如果本地你自己写，你的demo先尝试上传单个文件 <input type =file>，成功后再写成上传多个文件的形式去遍历，然后再去加md5的逻辑，一步一步来，然后再看。

**Comment by XiangYangHan** [comment]
一开始就是使用multipartUpload接口来分片上传的，但是上传所有的分片后，在OSS浏览器查看文件的大小却是0，我就怀疑是不是没有自动调用CompleteMultipartUpload，所以才分开调用。
在测试时就是只选择了一个文件的，md5是在获取stsToken时需要的。
在debug调用multipartUpload接口时发现，指定progress回调函数得到的checkpoint参数中的doneParts属性中没有etag值，如图：
![image](https://user-images.githubusercontent.com/24455362/43181386-6961132a-900f-11e8-9e7e-17d523afe08d.png)
在分片上传完成后进入done回调函数后，得到的result参数中带有etag，查看这次响应头的x-oss-request-id为：5B580CCC7953A4E04A0BD69B
![image](https://user-images.githubusercontent.com/24455362/43181581-8ee09ef8-9010-11e8-8928-902b5fb4c5ed.png)

**Comment by ZManor** [comment]
补充一下，如果不分片或者文件大小不超过最小片大小，直接上传是成功的。
每次分片请求的响应头里是有ETag信息的，但是底层执行的回调onResponse里就拿不到
![image](https://user-images.githubusercontent.com/5259526/43183438-bb46aa1c-9017-11e8-8183-c8e15f6f6e41.png)
![20180725_142117](https://user-images.githubusercontent.com/5259526/43183457-cd1526c4-9017-11e8-9ada-86f87e16ae32.png)

**Comment by CRONWMMM** [comment]
这个 etag 需要登录阿里账户在后台开启的
看下这个，兄dei
[https://help.aliyun.com/document_detail/32069.html?spm=a2c4g.11186623.2.9.u9WqUs](url)

**Comment by ZManor** [comment]
这个我们当然设置过，不然checkpoint记录的doneParts里面就不会有etag项
![image](https://user-images.githubusercontent.com/5259526/43307070-cfd54094-91af-11e8-9240-e88fb35e966c.png)

**Comment by ZManor** [comment]
最后定位了问题：
`multipartUpload`的参数`options.parallel`，如果设置为`1`，最终调用`completeMultipartUpload`时传递的`parts`参数没有正确赋值；设为其他值启用并发就没问题了。
另外看到`managed-upload.js`中的条件判断为：
`if (this.checkBrowserAndVersion('Internet Explorer', '10') || parallel === 1)`
猜测IE10环境下也可能会有问题。

**Comment by disfeng** [comment]
所以这个bug不修复吗？
