### ISSUE TITLE
STS token过期自动刷新怎么玩？

### ISSUE THREAD

**Issue by gaoconggit** [ali-sdk/ali-oss#512]
STS token过期自动刷新怎么玩？

**Comment by PeterRao** [comment]
目前方案是上传时，判断sts token过期，重新获取下sts token进行调用重传接口。
后续计划把sts token重传做成sdk的内置逻辑。

**Comment by gaoconggit** [comment]
好的，多谢

**Comment by xuxu7** [comment]
any progress?

**Comment by linzhuozhang** [comment]
> 目前方案是上传时，判断sts token过期，重新获取下sts token进行调用重传接口。
> 后续计划把sts token重传做成sdk的内置逻辑。

sts token重传做成sdk的内置逻辑这个功能完成了吗？

**Comment by lzw1604748707** [comment]
> > 目前方案是上传时，判断sts token过期，重新获取下sts token进行调用重传接口。
> > 后续计划把sts token重传做成sdk的内置逻辑。
> 
> sts token重传做成sdk的内置逻辑这个功能完成了吗？

同问==

**Comment by PeterRao** [comment]
已 支持 refreshSTSToken 参数

**Comment by zjxpcyc** [comment]
@PeterRao 我看文档里面说  `refreshSTSToken` 这个函数必须返回 `Object` 。也就是要求必须是同步的函数。那么一般这个函数的逻辑是怎么写的？

按照我这边的理解，如果过期了, 那么就会调用这个函数刷新下。那么我们在实现这个函数的时候，应该是需要异步去请求服务接口才能拿到的。那么只能返回一个 `Promise` 了。
