### ISSUE TITLE
node 前增加了nginx后导致上传很慢，经常失败

### ISSUE THREAD

**Issue by phper-chen** [ali-sdk/ali-oss#513]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **请求头部**:
`Request Method:POST
Status Code:500 Internal Server Error
Remote Address:127.0.0.1:51331
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Origin:http://47
Content-Length:48
Content-Type:text/html; charset=utf-8
Date:Thu, 02 Aug 2018 14:08:25 GMT
Keep-Alive:timeout=38
Set-Cookie:c=eQtASLDh2F-8D9dTwERfloZ1yGbIYD_0; path=/; expires=Fri, 17 Aug 2018 14:08:25 GMT; httponly
Set-Cookie:c=VN1Ph4_WU4YZuCnlHTGu5C0YJjQAqeCGJVO7xlnEmew; path=/; expires=Fri, 17 Aug 2018 14:08:25 GMT; httponly
Vary:Origin`

* **以下是我捕获的错误，求解**:

`[File Upload Error]The file: firmware/SNC-CAM_LENS_SL1701_V1.0.0+SNC-VPU_LENS_SC1801_V1.0.0+ALPHA_LENS_SWC11X-S_V1.0.0=V1.0.0.tgz has a failure in upload with error :{"name":"ResponseTimeoutError","requestId":1,"path":"/firmware/SNC-CAM_LENS_SL1701_V1.0.0%2BSNC-VPU_LENS_SC1801_V1.0.0%2BALPHA_LENS_SWC11X-S_V1.0.0%3DV1.0.0.tgz","status":-1,"headers":{},"res":{"status":-1,"statusCode":-1,"headers":{},"size":0,"aborted":false,"rt":60020,"keepAliveSocket":false,"requestUrls":["http://xx.oss-cn-beijing.aliyuncs.com/firmware/SNC-CAM_LENS_SL1701_V1.0.0%2BSNC-VPU_LENS_SC1801_V1.0.0%2BALPHA_LENS_SWC11X-S_V1.0.0%3DV1.0.0.tgz"],"timing":null,"remoteAddress":"","remotePort":}}`

**Comment by phper-chen** [comment]
我直接传给node服务没问题，加了nginx后就老失败，是keep-alive问题吗？但是我设置了nginx.conf的keep-alive和timeout并没效果

**Comment by PeterRao** [comment]
你是客户端直接访问nginx，然后在proxy代理给node？

**Comment by phper-chen** [comment]
是啊 node线上不就这么搞吗  不然没法用域名啊

**Comment by phper-chen** [comment]
oss也太垃圾了吧 连个客服都没？

**Comment by 1019272778** [comment]
alioss sdk 是oss api功能的实现，是协议层的实现。并不能确保在特殊网络状况下传输一定是成功的。
