### ISSUE TITLE
multipartUpload 上传的 progress percent 为 1，上传失败。

### ISSUE THREAD

**Issue by 16slowly** [ali-sdk/ali-oss#515]
* **Browser Version or Node Version**:   chrome v67.0.3396.99
* **ali-oss Version**: v4.11.4
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**: 
5B6AAFF470B1635ED7334483, 5B6AAFF470B1635ED7334581,5B6AAFF470B1635ED73347D9

使用 multipartUpload 方法上传一个 1.5M 的图片，上传进度显示为 1，但最终依旧报错：

![image](https://user-images.githubusercontent.com/15927205/43829528-c138066c-9b31-11e8-9531-61f75dbf2d9a.png)

怀疑是 partSize 太小，试图将 partSize 设置为 2 * 1024 * 1024 (2M), 依旧报以上错误，查文档也无解。
求指导，@PeterRao, 感谢

**Comment by luozhang002** [comment]
@16slowly,推荐试用新版ali-oss 4.11.4，目前都已经到6.X系列了

**Comment by 16slowly** [comment]
@luozhang002, 我用了 ali-oss v6.0.1, 还是一样的报错： 

![image](https://user-images.githubusercontent.com/15927205/43883288-2d64edc4-9be5-11e8-9aea-7e4f8d4c8dca.png)

**Comment by ZManor** [comment]
参考下 #509

**Comment by 16slowly** [comment]
@ZManor 我看了一下 #509，但还是不太明白, 请问你们最后是怎么解决的呢？

**Comment by 16slowly** [comment]
服务器上进行以下设置后，上传成功了：

![image](https://user-images.githubusercontent.com/15927205/44000848-bd7f5cca-9e59-11e8-8faf-d8d278d1ef9d.png)
