### ISSUE TITLE
如何在上传完文件之后，从oss获取该文件的md5？

### ISSUE THREAD

**Issue by MunMunMiao** [ali-sdk/ali-oss#517]
* **Browser Version or Node Version**: v10.7.0
* **ali-oss Version**: 6.0.1
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

获取文件的大小、md5等数据

**Comment by leohxj** [comment]
我也想知道，目前是 response.header 里面获取 content-md5

**Comment by qingfengmy** [comment]
> 我也想知道，目前是 response.header 里面获取 content-md5

我的response.header里面怎么没有content-md5，请问还需要设置什么吗

**Comment by crapthings** [comment]
@qingfengmy 自己加的
