### ISSUE TITLE
使用put上传时，如何获取进度?

### ISSUE THREAD

**Issue by MunMunMiao** [ali-sdk/ali-oss#518]
* **Browser Version or Node Version**: v10.7.0
* **ali-oss Version**: 6.0.1
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

**Comment by luozhang002** [comment]
@MunMunMiao  这个目前暂不支持，multipartUpload支持的

**Comment by MunMunMiao** [comment]
@luozhang002 请问下个版本可以支持一下吗？
