### ISSUE TITLE
如何在浏览器中使用？

### ISSUE THREAD

**Issue by rockuw** [ali-sdk/ali-oss#52]
我通过browerify生成可用于浏览器的js文件，但是遇到下面的问题：

1. 浏览器报failed to parse URL '//x.y.z/foo/bar'，不知道为什么url中缺少了'http:'打头。通过手工修改js在url前面增加'http:'解决。
2. 浏览器发出的请求header中不包含'Date'，导致请求失败。

我觉得手工修改browserify生成的js文件肯定不是一个好办法，请问一下如果要在浏览器中使用`ali-oss`应该怎么做？

**Comment by fengmk2** [comment]
呃。。。这个是一个 node 服务端才能使用的模块，没法在浏览器环境使用。

**Comment by rockuw** [comment]
Fixed by #55 
A demo can be found at: https://github.com/rockuw/oss-in-browser
