### ISSUE TITLE
/lib/sts.js 101 行语法错误

### ISSUE THREAD

**Issue by 720t** [ali-sdk/ali-oss#520]
1.
debug(
    'response %s %s, got %s, headers: %j',
    reqParams.method, reqUrl, result.status, result.headers, // 这里多了个 ','号
  );
2. putObject 成功，但浏览器(360浏览器)报错：Refused to set unsafe header "User-Agent"

**Comment by luozhang002** [comment]
@720t  （1）针对','并不属于语法报错，其实是合理的 （2）你的这个ali-oss版本是多少，https://github.com/jhiesey/stream-http/issues/91 这个其实新浏览器新特性，原因是因为我们的ali-oss依赖了第三方库stream-http,该库对UA的设置做了安全限制，理论上如果用的是新版本不会出现这个错的，因为SDK内部已经规避了这个问题，请排查你的版本。

**Comment by 720t** [comment]
(1)',' 问题补充
如果不去掉',' 会报以下错误(vue-cli: npm run dev 和 npm run build ):
` Uncaught SyntaxError: Unexpected token ) sts.js:102
 [vue-router] Failed to resolve async component default: Error: Loading chunk 0 failed. vue-router.esm.js:16
warn @ vue-router.esm.js:16
(anonymous) @ vue-router.esm.js:1763
(anonymous) @ vue-router.esm.js:1833
vue-router.esm.js:16 [vue-router] uncaught error during route navigation:
warn @ vue-router.esm.js:16
abort @ vue-router.esm.js:1904
(anonymous) @ vue-router.esm.js:1947
(anonymous) @ vue-router.esm.js:1768
(anonymous) @ vue-router.esm.js:1833
vue-router.esm.js:1905 Error: Loading chunk 0 failed.
    at HTMLScriptElement.onScriptComplete (bootstrap a319396…:756)`

(2) ali-oss版本是：6.0.1 使用 npm install --save ali-oss 安装的

请问以上问题可以解决吗?

**Comment by luozhang002** [comment]
@720t  debug这个从js语法上来说的确是没问题的，这个 ‘,’下个版本去掉，保持统一规范。但其实vue之前测试的时候，npm run dev 也是OK的

**Comment by 720t** [comment]
@luozhang002 谢谢老大

**Comment by change24** [comment]
我刚下载的新版本  还是会Refused to set unsafe header "User-Agent"
运行在360浏览器

**Comment by change24** [comment]
@luozhang002 3q

**Comment by change24** [comment]
我刚下载的新版本 还是会Refused to set unsafe header "User-Agent"
运行在360浏览器
@luozhang002
