### ISSUE TITLE
如果不new OSS用单例模式的话会出现progress超过1的情况

### ISSUE THREAD

**Issue by ahungrynoob** [ali-sdk/ali-oss#522]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

但是new 一个OSS实例的话 又太慢了

**Comment by DXD23-SJTU** [comment]
我觉得这一个bug了。。。如果每次续传都要new一个实例，而不是复用原来的实例的话 太耗时也耗性能，求改进。
