### ISSUE TITLE
接入小程序会提示有fs对象引用？？不支持？

### ISSUE THREAD

**Issue by wyjieying** [ali-sdk/ali-oss#523]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

接入小程序会提示有fs对象引用？？

**Comment by luozhang002** [comment]
@wyjieying 暂时是不支持的

**Comment by wyjieying** [comment]
@luozhang002 有什么法子么？

**Comment by luozhang002** [comment]
@wyjieying 目前可以考虑官网提供的 OSSWeb直传 方法。
