### ISSUE TITLE
怎么样才能实现断点续传下载？

### ISSUE THREAD

**Issue by ovo4096** [ali-sdk/ali-oss#524]
怎么样才能实现断点续传下载，我看到 Java SDK 有这个功能但是 NodeJS SDK 还没有，求助下实现方式。

**Comment by luozhang002** [comment]
node js sdk还没有针对这块做封装，但是无论是Java SDk还是其他任何SDK，其原理或者底层都是都是基于OSS提供的开放api GetObject来做的，有个 range参数来支持断点续传下载。https://help.aliyun.com/document_detail/31980.html?spm=a2c4g.11186623.2.8.63657d30ThUhQE#reference_ccf_rgd_5db

**Comment by ovo4096** [comment]
@luozhang002 这样的话是不是只能自己实现了，有没有好的替代方案？

**Comment by helibin** [comment]
下载用的client.get(ossPath)，文档里倒是有说可以传Range过去，不过表示没有找到正确设置的方法

试过一下方法，均未生效
new OSS({ak, region,..., header: {Rage: 'bytes 0-199'}})
...client.get(ossPath, {Rage: 'bytes 0-199'})

返回值：
headers:
      { server: 'AliyunOSS',
        date: 'Sat, 27 Oct 2018 01:25:47 GMT',
        'content-type': 'video/mp4',
        'content-length': '23014356',
        connection: 'keep-alive',
        'x-oss-request-id': '5BD3BE9B80D9FF8FD2626EA0',
        'accept-ranges': 'bytes',
        etag: '"FFD09094FB5F0A107200AE3085055483-3"',
        'last-modified': 'Fri, 26 Oct 2018 07:38:21 GMT',
        'x-oss-object-type': 'Multipart',
        'x-oss-hash-crc64ecma': '4473677830635346951',
        'x-oss-storage-class': 'Standard',
        'x-oss-server-time': '2' },

表示无奈，求大神指导下

**Comment by helibin** [comment]
https://github.com/ali-sdk/ali-oss#getname-file-options
