### ISSUE TITLE
批量删除

### ISSUE THREAD

**Issue by LL-LAILAI** [ali-sdk/ali-oss#526]
调用方法如下：
let result2 = await client.deleteMulti(["123/456/A.png","123/456/B.png"])

![image](https://user-images.githubusercontent.com/30370215/45482678-49b40980-b781-11e8-90ea-4b83857028eb.png)
权限已经设置最高权限了，单个删除没有问题，批量删除就显示权限问腿

**Comment by luozhang002** [comment]
@LL-LAILAI  https://help.aliyun.com/knowledge_detail/56288.html#h2-u914Du7F6Eu7EC6u52192

**Comment by LL-LAILAI** [comment]
![16484455ae17d2ae5fecfa22aa3fac0f](https://user-images.githubusercontent.com/30370215/45583921-3d54bb80-b8fd-11e8-9755-e1993d488d2c.png)
这个是Policy配置，就是批量删除这个这个功能不可以，无论是node.js和browser.js版本都是批量删除这个功能不可以，其他的功能都没问题，如果是权限问题的话，理应当单个删除也不可以，但是现在只有批量删除不行，还有其他疑问的问题：
1.获取列表时，有时会把prefix当作第一个objects，有时却不会
![image](https://user-images.githubusercontent.com/30370215/45583841-dda9e080-b8fb-11e8-9231-20eef0fc4037.png)
![image](https://user-images.githubusercontent.com/30370215/45583876-5f9a0980-b8fc-11e8-94ce-c3366380cb59.png)
2.删除文件夹
只有在空文件夹是空的时候才可以删，非空文件夹却需要遍历删除完文件夹里面的文件才可以删除，若文件夹里面包含多层文件时，遍历就比较繁琐，能不能出一个删除文件夹的API。希望能完善SDK的参考文档

**Comment by phper-chen** [comment]
你的action权限只配置了ListBuckets

**Comment by 1027402982** [comment]
我跟你一样的问题 你解决了吗
