### ISSUE TITLE
使用node的SDK的getStream方法下载报status:400错误

### ISSUE THREAD

**Issue by dwzzwd** [ali-sdk/ali-oss#527]
* **Node Version**:v10.9.0
* **ali-oss Version**:v6.0.1

>报错的方法
```javascript
let result = await client.getStream('object-name');
```
#### 当参数'object-name'中，文件名含有'@'符号时报错

>如
```javascript
files/d19mjaut89upgwvbdwyg/web@pack.zip
```
>错误信息打印

![image](https://user-images.githubusercontent.com/22488181/45583979-0cc15180-b8fe-11e8-8022-56e1dc0a249f.png)

**Comment by luozhang002** [comment]
@dwzzwd  本地针对6.0.1版本写了测试用例并未发现问题，
const OSS = require('ali-oss');
const env = process.env;
const fs = require('fs')

var client = new OSS({
  accessKeyId: env.ALI_SDK_AK_ID,
  accessKeySecret: env.ALI_SDK_AK_SECRET,
  region:'oss-cn-zhangjiakou',
  bucket:'luozhang002'
});

var filepath = "./test.jpg";

client.putStream('ossdemo@readstream.txt', fs.createReadStream(filepath)).then((result) => {
    console.log(result);
}).catch(e=>{
    console.log(e)
});

//
client.getStream('ossdemo@readstream.txt').then(res=>{
    console.log(res)
}).catch(e=>{
    console.log(e)
})
