### ISSUE TITLE
遇到这个问题不知道如何解决，是什么原因造成的呢

### ISSUE THREAD

**Issue by zhanghaidonggf** [ali-sdk/ali-oss#529]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

![image](https://user-images.githubusercontent.com/5267244/46794217-f92ccd80-cd79-11e8-9969-b1d5cfb9b7e7.png)

**Comment by luozhang002** [comment]
@zhanghaidonggf -1 -2 的错误都没到oss ，一般属于网络错误
