### ISSUE TITLE
Support multipart upload

### ISSUE THREAD

**Issue by tiaozi0912** [ali-sdk/ali-oss#53]
Does this lib support multipart upload similar to https://github.com/aliyun-UED/aliyun-sdk-js/blob/master/samples/oss/multipartUpload.js?

**Comment by fengmk2** [comment]
`multipart upload` is on the TODO list.

Or you can help us to implement this feature?

**Comment by tiaozi0912** [comment]
Cool I'll look into it to see if anything I can help

**Comment by dead-horse** [comment]
https://github.com/ali-sdk/ali-oss/pull/55
