### ISSUE TITLE
Ionic集成错误，想用来上传手机上的图片。

### ISSUE THREAD

**Issue by zdd** [ali-sdk/ali-oss#531]
使用Ionic集成ali-oss时出现如下错误：

> polyfills.js:3 OPTIONS https://sfdq.oss-cn-beijing.aliyuncs.com/bt/z/test 403 (Forbidden)
> Failed to load https://sfdq.oss-cn-beijing.aliyuncs.com/bt/z/test: Response for preflight does not have HTTP ok status.
> oss.ts:45 error: %j Error: Failed to fetch (req "error"), PUT https://sfdq.oss-cn-beijing.aliyuncs.com/bt/z/test -1 (connected: false, keepalive socket: false)

调用代码：
```
async uploadFile () {
    try {
      await this.ossClient.put('bt/z/test', new Buffer("abcd"));
    } catch(err) {
      console.error('error: %j', err);
    }
  }
```

oss policy 文件：
```
{
  "Statement": [
    {
      "Action": [
        "oss:GetObject",
        "oss:ListObjects",
        "oss:PutObject",
        "oss:ListParts"
      ],
      "Effect": "Allow",
      "Resource": ["acs:oss:*:*:sfdq/*", "acs:oss:*:*:sfdq"]
    }
  ],
  "Version": "1"
}
```

**Comment by zdd** [comment]
ACL配置应该是没有问题，因为可以通过STS方式读取bucket中的文件，但是上传不行，很奇怪。。。

**Comment by edwardaa** [comment]
可能需要配置下 bucket 的 **跨域设置**：https://help.aliyun.com/document_detail/31870.html
