### ISSUE TITLE
可以考虑加入doesObjectExist方法吗？

### ISSUE THREAD

**Issue by liuhj1018** [ali-sdk/ali-oss#533]
* **Browser Version or Node Version**:
* **ali-oss Version**:6.0.1
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

**Comment by luozhang002** [comment]
@liuhj1018 这个接口暂时应该不会考虑，其实你完全可以get一下看有没有就可以了。

**Comment by liuhj1018** [comment]
那能不能在get的时候，如果key不存在，就返回一个空值，这样就不用每次都去捕捉NoSuchKeyError，毕竟这是一个错误，key不存在不应该属于一个错误

**Comment by liuhj1018** [comment]
并且很多时候，并不想get到object，只是想获取url，但是在用signatureUrl时，即使object不存在，也依然能生成url，这个url在交付出去的时候就有问题了

**Comment by luozhang002** [comment]
@liuhj1018 ，我们暴露signatureUrl这种基础的签名URL方法，无论传入的object存不存在都会按照指定规则生成指定URL，你这种情况，业务逻辑完全可以自己去写，通过get判断是否存在然后再决定是否生成对应的签名URL

**Comment by luanxuechao** [comment]
@liuhj1018  可以使用head方法
