### ISSUE TITLE
oss自定义域名的情况 怎么处理

### ISSUE THREAD

**Issue by jerrwy** [ali-sdk/ali-oss#535]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

**Comment by luozhang002** [comment]
@jerrwy ，https://help.aliyun.com/document_detail/64059.html

**Comment by jerrwy** [comment]
> @jerrwy ，https://help.aliyun.com/document_detail/64059.html

thx
