### ISSUE TITLE
Timeout and socket hang up error on STS token call

### ISSUE THREAD

**Issue by shabbir21** [ali-sdk/ali-oss#541]
* **Node Version**: 8
* **ali-oss Version**: 6.0.1

Hi,

We have our Node servers hosted on GCP but we are using Alibaba Cloud OSS for our storage needs.
Our android clients communicate with our Node server.

Our photo upload process to OSS is:
1. Client requests a token from our Node server
2. Our Node server requests Alibaba Cloud for a token to upload the image
3. The token returned by Aliyun is then returned to our client
4. Client then uses that token to upload the image to Aliyun

Point# **2** is failing with the following message: ```"Connect timeout for 60000ms, POST https://sts.aliyuncs.com -2 (connected: false, keepalive socket: false, socketHandledRequests: 1, socketHandledResponses: 0)
headers: {}" ```

* **Mini Showcase Repository**:
Our code is:
```
const OSS = require('ali-oss');
const STS = OSS.STS;
app.get('/cloud/ststoken', passport.ensureAuthenticated, async (req, res, next) => {
  try {
  const sts = new STS({
    accessKeyId: '*************',
    accessKeySecret: '******************************',
  });

    const roleArn = 'acs:ram::1234567899888:role/mobileappuploadimage';
    const expiryDuration = 15 * 60;

    let val = await sts.assumeRole(roleArn, null, expiryDuration, 'app');
    res.data = val.credentials;
    next();
  } catch (err) {
    next(errors.EXTERNAL_SERVER_RESPOND_WITH_ERROR({ info: { code: err.code, message: err.message } }));
  }
});
```

**Comment by luozhang002** [comment]
@shabbir21  -2 网络问题，先确保你本地网络环境。
