### ISSUE TITLE
node分片上传，使用官方的demo，上传途中会自动暂停，

### ISSUE THREAD

**Issue by ForeverSun** [ali-sdk/ali-oss#550]
node分片上传，使用官方的demo，上传途中会自动暂停，https://help.aliyun.com/document_detail/32072.html?spm=a2c4g.11186623.6.969.336c5999kSeCz6

**Comment by luozhang002** [comment]
@ForeverSun 本地并未复现，最好提供下些日志信息 ，你直接运行 DEBUG=ali-oss node index.js ，看下日志，progress的进度等

**Comment by ForeverSun** [comment]
我用的Electron做的，Electron2.0.4不会自动暂停，Electron3.0.9会出现这个问题
