### ISSUE TITLE
typescript 的支持有问题 

### ISSUE THREAD

**Issue by logictuLuoqi** [ali-sdk/ali-oss#551]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

bug  @types/ali-oss
我是import OSS from 'ali-oss'; 这样使用的
错误是 ali_oss_1.default is not a constructor
找到原因了 ts在生成的时候回自动添加 exprts.default在写@types/ali-oss没有加上这一条
而是直接moduel.exports 然后就报错了希望改进

**Comment by ptrdu** [comment]
> 什么时候解决呢

升级一下吧，好了
