### ISSUE TITLE
通过url上传文件

### ISSUE THREAD

**Issue by dida-1894** [ali-sdk/ali-oss#554]
请问，ali-oss是否可以通过url上传文件？我看到的文档里都是上传本地文件的api
* **Browser Version or Node Version**:v8.11.3
* **ali-oss Version**: ^6.0.1
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

**Comment by dida-1894** [comment]
我需要的是上传远端服务器的文件，比如 url地址为https://img3.doubanio.com/view/photo/l_ratio_poster/public/p2522880251.jpg的一张图片，不是把我本地的文件生成url再上传。

**Comment by xiaoice** [comment]
`rp(url).on('response', async (data) => {
    let fileName = md5(url) + path.extname(url);
    const ossFileName = [ossOption.cdnRootDir, 'upload', type, fileName.slice(0, 1), fileName.slice(1, 3), fileName].join('/');
    const rsp = await storeOss.put(ossFileName, data);
    if(rsp.res && rsp.res.status === 200){
      let name = (rsp.name || '').replace(ossOption.bucket, '');
      resove([cdnHost, name].join('/'));
    }
})`

**Comment by luozhang002** [comment]
@dida-1894 目前接口里面是不支持直接传文件URL直接上传的，逻辑可以自己处理，可以参考@xiaoice
