### ISSUE TITLE
使用multipartUpload 接口上传文件怎样获取uploadId?

### ISSUE THREAD

**Issue by ForeverSun** [ali-sdk/ali-oss#558]
multipartUpload 整合了initMultipartUpload, uploadPart, completeMultipartUpload几个方法很好用，但是在使用multipartUpload 时候我遇到2个问题：
1.使用multipartUpload 接口上传文件怎样获取uploadId（尤其在上传中时候）?在上传图中删除，同时清除碎片调用 abortMultipartUpload(name, uploadId[, options])其中需要用到uploadId
2.
```
var ossConfig = {
        region: 'oss-cn-beijing',
        accessKeyId: '**************',
        accessKeySecret: '********************',
        bucket: 'aliyunbuckettest'
    };
var client = new OSS(ossConfig);
```
client.cancel()是针对当前multipartUpload 上传的所有文件暂停的，如果针对队列中每个文件暂停，每个文件都 new OSS(ossConfig)是否可行（目前已实现）？

**Comment by luozhang002** [comment]
@ForeverSun 如果想调用abortMultipartUpload,建议自己写业务的时候自己以此调用initMultipartUpload, uploadPart, completeMultipartUpload这几个接口，业务可控性更强。
至于 你说的“client.cancel()是针对当前multipartUpload 上传的所有文件暂停的，如果针对队列中每个文件暂停，每个文件都 new OSS(ossConfig)是否可行（目前已实现）？”理论上是可行的。
