### ISSUE TITLE
Browserify compile error : Cannot find module './browser/client'

### ISSUE THREAD

**Issue by imquincychen** [ali-sdk/ali-oss#562]
* **Node Version**: 8.9.4
* **ali-oss Version**: 6.0.2

集成ali-oss到一个sdk中，browserify打包报以下错误
```
browserify src/index.js -t [ babelify ] -s terra -d | exorcist ./dist/terra.js.map | derequire > dist/terra.js

Error: Cannot find module './browser/client' from 'xxxxxxxx/node_modules/ali-oss/dist'
    at xxxxxxxx/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (xxxxxxxx/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (xxxxxxxx/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at xxxxxxxx/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by luozhang002** [comment]
@imquincychen  请问切到6.0.1会有这个问题吗。或者你能不能考虑直接引入cdn的方式试试会不会报错。http://gosspublic.alicdn.com/aliyun-oss-sdk-6.0.2.min.js

**Comment by imquincychen** [comment]
我刚刚看了一下你们源码，把`node_modules/ali-oss/package.json`中browser的`lib/client.js`指向改成`lib/browser.js`就好了
```
"browser": {
    "lib/client.js": "./dist/aliyun-oss-sdk.js"
}
```
但6.0.2的问题还是存在的。
另外问一个问题，有没有特殊值可以把timeout设置为无限大？刚刚尝试了一下timeout: 0不起作用。

**Comment by luozhang002** [comment]
@imquincychen 没有设置无限大的数值，设置无限大其实意义也不大

**Comment by imquincychen** [comment]
@luozhang002 好的，刚刚试了一下，6.0.1存在同样的问题，需要我提个PR吗

**Comment by luozhang002** [comment]
@imquincychen 可以的。

**Comment by philwu** [comment]
问题仍然存在
Node Version: 12.3.1
ali-oss Version: 6.1.1

**Comment by desertby** [comment]
> @luozhang002 我刚刚看了一下你们源码，把`node_modules/ali-oss/package.json`中browser的`lib/client.js`指向改成`lib/browser.js`就好了
> 
> ```
> "browser": {
>     "lib/client.js": "./lib/browser.js" // 原先是 ./dist/aliyun-oss-sdk.js
> }
> ```
> 
> 但6.0.2的问题还是存在的。
> 另外问一个问题，有没有特殊值可以把timeout设置为无限大？刚刚尝试了一下timeout: 0不起作用。

我修改了package.json的内容，但是修改完之后又出现了新的报错

`Error: Cannot find module '../../../../_is-buffer@1.1.6@is-buffer/index.js' from 'E:\working\XXX\test\node_modules\_core-util-is@1.0.2@core-util-is\lib'
    at E:\working\XXX\test\node_modules\_resolve@1.1.7@resolve\lib\async.js:55:21
    at load (E:\working\XXX\test\node_modules\_resolve@1.1.7@resolve\lib\async.js:69:43)
    at onex (E:\working\XXX\test\node_modules\_resolve@1.1.7@resolve\lib\async.js:92:31)
    at E:\working\XXX\test\node_modules\_resolve@1.1.7@resolve\lib\async.js:22:47
    at FSReqCallback.oncomplete (fs.js:158:21)`
