### ISSUE TITLE
SignatureDoesNotMatch

### ISSUE THREAD

**Issue by gera2ld** [ali-sdk/ali-oss#568]
修改`example/server/config.js`，设置了AccessKeyId、AccessKeySecret、RoleArn，然后
在`example`里`npm start`，获取token时报`SignatureDoesNotMatch`。

![image](https://user-images.githubusercontent.com/3139113/50145078-a75d7200-02eb-11e9-8048-d131df66f855.png)

**Comment by PeterRao** [comment]
AccessKeyId 和 AccessKeySecret 错误导致

**Comment by gera2ld** [comment]
错误的话会报 NoPermission 吧，我试了特意输个错的

**Comment by PeterRao** [comment]
https://github.com/ali-sdk/ali-oss#known-errors 所有的错误码可参考 https://github.com/ali-sdk/ali-oss#known-errors
