### ISSUE TITLE
put成功后返回的size总是为0

### ISSUE THREAD

**Issue by mani95lisa** [ali-sdk/ali-oss#569]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

如题，重新再去get，size才正常，为什么put成功后返回的就是0呢？

**Comment by luozhang002** [comment]
@mani95lisa  能否提供关键代码和log截图

**Comment by mani95lisa** [comment]
```javascript
const stream = await ctx.getFileStream();
    try {
      const res = await ctx.oss.put(name, stream);
      const file = {
        size: stream.fields.size,
        status: res.res.status,
        mime: stream.mime,
        cloud_name: name,
        origin_name: stream.filename,
        address: res.remoteAddress,
        server: 'ali_oss',
        creator: user.id,
        company: user.company,
      };
    } `
代码如上所示，获取size的时候只能通过在客户端设置stream的fields来获取，如果是直接读取res里面的size，永远都是0

**Comment by luozhang002** [comment]
@mani95lisa res.size并不是你说的stream的大小。https://help.aliyun.com/document_detail/31978.html 这个返回res.size其实就是返回示例中的content-lenght

**Comment by mytharcher** [comment]
建议提供一个上传成功后返回信息中就包含文件大小的接口，这个应该是非常普遍和常用的需求了。传完以后再次发请求一是实现麻烦，且不经济。

上传过程中其实也可以通过 stream 获取并计算出上传的字节数，这个功能真的建议内置在 sdk 或者服务端的返回值里。

**Comment by fengmk2** [comment]
可以贡献一下。
