### ISSUE TITLE
oss本地时间不是标准时间，导致上传失败

### ISSUE THREAD

**Issue by cailong1028** [ali-sdk/ali-oss#573]
* **node Version: v8.9.3**:
* **ali-oss Version: 6.0.1**:
* **Mini Showcase Repository: 无**:
* **Network Resoponse Header x-oss-request-id**:

#### 问题描述

用户客户端本地时间可能和现在标准时间有差别：比如当前网络正常时间是 `2018-12-25 14:20:23`，而用户电脑上时间为 `2018-12-24 14:20:23`，导致调用oss的上传方法（使用的是multipartUpload）的时候，

```

const client = new OSS(options);
client.multipartUpload(destUrl, localPath, options);

```

报如下错误

```

Error: The difference between the request time and the current time is too large.
    at Client.requestError (client.js:510)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109)

```

经查看源码可知, 在 `client.js` 中 `createRequest` 里面 会先初始化headers一些默认值

```

proto.createRequest = function createRequest(params) {
  const headers = {
    'x-oss-date': dateFormat(new Date(), 'UTC:ddd, dd mmm yyyy HH:MM:ss \'GMT\''),
    'x-oss-user-agent': this.userAgent,
    'User-Agent': this.userAgent
  };
  ....
  ....
}

```

然后再使用 `copy(origin).to(dest) ` 将传进来的参数 `params.headers` 的 属性传递给headers

```

copy(params.headers).to(headers);

```

所以在调用 `multipartUpload` 方法时，先获取服务端当前标准时间，以此时间发起oss上传请求，添加如下配置

```

client.multipartUpload(destUrl, localPath, {
    ...
    headers: {
                    'x-oss-date': dateFormat(new Date(parseInt(sessionStorage.getItem('serverTimeStamp'))), 'UTC:ddd, dd mmm yyyy HH:MM:ss \'GMT\'')
                }
});

```

还是报上面的错误，经检查发现，`copy(origin).to(dest)` 只是将 `origin ` 中有而 `dest` 中没有的属性赋给 `dest`，这里其实是想改为自身指定的配置，覆盖 `headers`中的默认值。

将`client.js` 中 `createRequest` 方法内的

```

copy(params.headers).to(headers);

```

改为

```

Object.assgin(headers, params.headers);

```

后上传成功。

希望在此处作出改动，谢谢，望回复。

**Comment by luozhang002** [comment]
服务端有个处理逻辑是前端时间和后端时间相差超过15分钟的话，后端会给出反馈，目前这种修复在browserjs里面发现时间差不一样的话，会有自动矫正逻辑，nodejs sdk里暂时未加这种处理逻辑

**Comment by kmac007** [comment]
> * **node Version: v8.9.3**:
> * **ali-oss Version: 6.0.1**:
> * **Mini Showcase Repository: 无**:
> * **Network Resoponse Header x-oss-request-id**:
> 
> #### 问题描述
> 用户客户端本地时间可能和现在标准时间有差别：比如当前网络正常时间是 `2018-12-25 14:20:23`，而用户电脑上时间为 `2018-12-24 14:20:23`，导致调用oss的上传方法（使用的是multipartUpload）的时候，
> 
> ```
> 
> const client = new OSS(options);
> client.multipartUpload(destUrl, localPath, options);
> ```
> 
> 报如下错误
> 
> ```
> 
> Error: The difference between the request time and the current time is too large.
>     at Client.requestError (client.js:510)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:109)
> ```
> 
> 经查看源码可知, 在 `client.js` 中 `createRequest` 里面 会先初始化headers一些默认值
> 
> ```
> 
> proto.createRequest = function createRequest(params) {
>   const headers = {
>     'x-oss-date': dateFormat(new Date(), 'UTC:ddd, dd mmm yyyy HH:MM:ss \'GMT\''),
>     'x-oss-user-agent': this.userAgent,
>     'User-Agent': this.userAgent
>   };
>   ....
>   ....
> }
> ```
> 
> 然后再使用 `copy(origin).to(dest) ` 将传进来的参数 `params.headers` 的 属性传递给headers
> 
> ```
> 
> copy(params.headers).to(headers);
> ```
> 
> 所以在调用 `multipartUpload` 方法时，先获取服务端当前标准时间，以此时间发起oss上传请求，添加如下配置
> 
> ```
> 
> client.multipartUpload(destUrl, localPath, {
>     ...
>     headers: {
>                     'x-oss-date': dateFormat(new Date(parseInt(sessionStorage.getItem('serverTimeStamp'))), 'UTC:ddd, dd mmm yyyy HH:MM:ss \'GMT\'')
>                 }
> });
> ```
> 
> 还是报上面的错误，经检查发现，`copy(origin).to(dest)` 只是将 `origin ` 中有而 `dest` 中没有的属性赋给 `dest`，这里其实是想改为自身指定的配置，覆盖 `headers`中的默认值。
> 
> 将`client.js` 中 `createRequest` 方法内的
> 
> ```
> 
> copy(params.headers).to(headers);
> ```
> 
> 改为
> 
> ```
> 
> Object.assgin(headers, params.headers);
> ```
> 
> 后上传成功。
> 
> 希望在此处作出改动，谢谢，望回复。

你好，请问最后采用的解决方案是什么呢，遇到同样的问题
