### ISSUE TITLE
前端直传跨域问题

### ISSUE THREAD

**Issue by Stevenqyy** [ali-sdk/ali-oss#575]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

前端使用webpack，使用npm安装ali-oss6.0.2，在vue项目中使用后端返回的sts临时账号上传时报如下错误：
Request header field x-oss-user-agent is not allowed by Access-Control-Allow-Headers in preflight response.

我的核心代码如下
 var client = new OSS({
        'region': "oss-cn-shenzhen",
        'endpoint': "oss-cn-shenzhen.aliyuncs.com",
        'accessKeyId': this.AccessKeyId,
        'accessKeySecret': this.AccessKeySecret,
        'bucket': "hexiaoxiang-xcx-2",
        'stsToken': this.SecurityToken
      });

client.put(name, file, {
              progress: function*(percentage, cpt) {
                this.percentage = percentage;
              }
            })
            .then(results => {
              this.uploadfile.push({
                url: results.res.requestUrls[0],
                fileUrl: results.res.requestUrls[0],
                name: results.name
              });
              alert("上传成功");
            })
            .catch(err => {
              console.log(err);
            });

**Comment by luozhang002** [comment]
@Stevenqyy  https://help.aliyun.com/document_detail/32069.html?spm=a2c4g.11186623.6.1009.24b95d26ahGh97 跨域配置参考下
