### ISSUE TITLE
前端上传50G的大文件时，浏览器占用内存和cpu过高

### ISSUE THREAD

**Issue by Jairs** [ali-sdk/ali-oss#578]
![image](https://user-images.githubusercontent.com/30263041/50536363-97b51780-0b8e-11e9-85ec-535a55c80ef6.png)
前端上传50G的大文件时，浏览器占用内存和cpu过高，很容易导致浏览器崩溃，这个要怎么解决？

**Comment by Jairs** [comment]
![image](https://user-images.githubusercontent.com/30263041/50578543-6ed6a000-0e76-11e9-82d3-c96e0a8596a9.png)
这样调用multipartUpload接口是最大可以上传多大的文件啊？

**Comment by luozhang002** [comment]
@Jairs oss后端规定，单个文件原则上最大上传48.8TB，上传这么大的文件对CPU和内存消耗是正常的，我本地没有这么大的文件，但是测了10G的指标正常的。如果你纯粹是为了把这么大的文件上传到OSS，采用官方ossutil命令行上传这么大的工具也是OK的。

**Comment by PeterRao** [comment]
把上传并发数改小一点，尝试下

**Comment by Jairs** [comment]
我发现在用火狐
![default](https://user-images.githubusercontent.com/30263041/50746335-81334e00-1269-11e9-9b8d-4f4b2bbe8f53.png)
这个版本时，内存占用率极高，40G的文件上传一定崩浏览器，并发数是2

**Comment by kid1412621** [comment]
我上传 200 M 的文件浏览器崩溃了

**Comment by jialinNEU** [comment]
> 我上传 200 M 的文件浏览器崩溃了
> Chrome 崩了 Firefox 没……

请问chrome上传崩溃这个问题解决了吗
