### ISSUE TITLE
Error: module "tty" is not defined

### ISSUE THREAD

**Issue by EthanCui** [ali-sdk/ali-oss#579]
VM1784:1 thirdScriptError
module "tty" is not defined; [Component] Event Handler Error @ pages/edituserinfo/edituserinfo#(anonymous)
Error: module "tty" is not defined
    at require (http://127.0.0.1:28750/appservice/__dev__/WAService.js:1:731599)
    at http://127.0.0.1:28750/appservice/__dev__/WAService.js:1:731349
    at http://127.0.0.1:28750/appservice/npm/ali-oss/npm/debug/src/node.js:5:11
    at require (http://127.0.0.1:28750/appservice/__dev__/WAService.js:1:731740)
    at http://127.0.0.1:28750/appservice/__dev__/WAService.js:1:731349
    at http://127.0.0.1:28750/appservice/npm/ali-oss/npm/debug/src/index.js:9:20
    at require (http://127.0.0.1:28750/appservice/__dev__/WAService.js:1:731740)
    at http://127.0.0.1:28750/appservice/__dev__/WAService.js:1:731349
    at http://127.0.0.1:28750/appservice/npm/ali-oss/lib/client.js:2:15
    at require (http://127.0.0.1:28750/appservice/__dev__/WAService.js:1:731740)
console.error @ VM1784:1
errorReport @ WAService.js:1
thirdErrorReport @ WAService.js:1
(anonymous) @ WAService.js:1
(anonymous) @ WAService.js:1
r.safeCallback @ WAService.js:1
r.call @ WAService.js:1
t.message @ WAService.js:1
r.safeCallback @ WAService.js:1
(anonymous) @ WAService.js:1
d @ WAService.js:1
(anonymous) @ WAService.js:1
n @ WAService.js:1
e @ appservice?t=1546251722172:3214
r.registerCallback.t @ appservice?t=1546251722172:3214
l.forEach.t @ appservice?t=1546251722172:3214
(anonymous) @ appservice?t=1546251722172:3214
s.onmessage @ appservice?t=1546251722172:3214

* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

**Comment by EthanCui** [comment]
拷贝  NPM文件   dist/npm/ali-oss/npm/debug/npm/ms/index.js
拷贝  NPM文件   dist/npm/ali-oss/npm/debug/src/debug.js
拷贝  NPM文件   dist/npm/ali-oss/npm/debug/src/browser.js
拷贝  NPM文件   dist/npm/ali-oss/npm/debug/src/node.js
拷贝  NPM文件   dist/npm/ali-oss/npm/debug/src/index.js
拷贝  NPM文件   dist/npm/ali-oss/npm/stream-wormhole/index.js
拷贝  NPM文件   dist/npm/ali-oss/npm/copy-to/index.js
{ SyntaxError: unknown: Unexpected token, expected ; (1:27)

**Comment by luozhang002** [comment]
@EthanCui  你这个是在微信小程序里用的这个库吗？小程序我们不支持引入SDK的。
