### ISSUE TITLE
有上传超大文件的例子吗，文件大于1T的

### ISSUE THREAD

**Issue by Jairs** [ali-sdk/ali-oss#580]
有上传超大文件的例子吗，文件大于1T的

**Comment by luozhang002** [comment]
@Jairs example目录下的上传demo试过吗？

**Comment by ForeverSun** [comment]
**### 上传限制**
大小限制：在这种上传方式下，Object的大小是由Part来决定的，最大支持10000块Part。每块Part最小100KB（最后一块可以比100KB小），最大5GB。Object的大小不能超过48.8TB。
命名限制
使用UTF-8编码。
长度必须在1–1023字节之间。
不能以正斜线（/）或者反斜线（\）字符开头。

**Comment by Jairs** [comment]
![image](https://user-images.githubusercontent.com/30263041/50622341-584c4980-0f47-11e9-9957-bc272caf5e4d.png)
利用multipartUpload就可以上传超大文件了，对吗？

**Comment by luozhang002** [comment]
@Jairs 是的，一般大文件上传直接用multipartUpload

**Comment by Jairs** [comment]
@luozhang002 请问什么情况下会出现（-1）requestError的错误码呢？
https://help.aliyun.com/document_detail/32005.html，在这里并没有看到这个错误码，但是这个错误的几率还是蛮高的

**Comment by luozhang002** [comment]
本地用example上传从未出现类似的问题，如果你一直跑的是用demo中的example进行本地文件选择上传的话，针对每个分片本来走的就是put请求，发送的有options和put也是正常的，还有进度百分百后 是不是在bucket可以看到上传文件，确定上传成功了。EntityTooSmall这个一般是针对post报的，你说报错最好能提供下截图，是在浏览器console面板报的错吗？

**Comment by Jairs** [comment]
之前忘了截图，是在console中报错的，progress已经显示上传了100%，但是会报这个错

**Comment by Jairs** [comment]
@luozhang002 之前忘了截图，是在console中报错的，progress已经显示上传了100%，但是会报这个错
