### ISSUE TITLE
浏览器分片上传parallel=1时，上传完成后的文件size=0

### ISSUE THREAD

**Issue by disfeng** [ali-sdk/ali-oss#585]
HI，我在使用ali-oss库的时候，使用分片上传时，将线程设置为1时，上传完成后文件大小为0；

**Comment by disfeng** [comment]
#02f9ba7ed8793573e3a16e4534b7b10d92e8b6b9

**Comment by disfeng** [comment]
[](url)

**Comment by disfeng** [comment]
02f9ba7ed8793573e3a16e4534b7b10d92e8b6b9

**Comment by luozhang002** [comment]
@disfeng 我本地运行demo，parallel设置为1，并未出现 size = 0的情况
<img width="556" alt="2019-01-14 10 56 28" src="https://user-images.githubusercontent.com/5653578/51094818-2fe80900-17eb-11e9-8628-626255a154b5.png">
<img width="1221" alt="2019-01-14 10 56 11" src="https://user-images.githubusercontent.com/5653578/51094822-38d8da80-17eb-11e9-8306-f2c63ed118e9.png">

还有你说的这个size是怎么获得的，是bucket上直接查看的，还是通过res拿到的。

**Comment by disfeng** [comment]
在buckt上查看的

**Comment by disfeng** [comment]
browser/managed-upload.js

if (this.checkBrowserAndVersion('Internet Explorer', '10') || parallel === 1) {
    for (let i = 0; i < todo.length; i++) {
      if (this.isCancel()) {
        throw this._makeCancelEvent();
      }
      /* eslint no-await-in-loop: [0] */
      await uploadPartJob(this, todo[i]);
    }
  } 
这个判断线程=1时走ie10的逻辑，线程为1但是使用了分片上传应该也是走else的逻辑吧。@luozhang002您查看的size是从res看的还是buckt哇

**Comment by disfeng** [comment]
不好意思手机上不方便，看到你的截图了，你的500k一片，文件大小还不够分片，或者你试试10m以上的文件，500k一片看看？

**Comment by luozhang002** [comment]
@disfeng 已经验证，这是个bug，感谢反馈，下个版本会修正。

**Comment by luozhang002** [comment]
@disfeng  目前6.1.1修复了这个bug,可以先试用一下。
