### ISSUE TITLE
xx/node_modules/ali-oss/lib/managed-upload.js:278

### ISSUE THREAD

**Issue by jonyshi** [ali-sdk/ali-oss#586]
aa.js
```js
var fs = require('fs');
console.log(" 00000000000 ")
var oss = require('ali-oss');
```

ali-oss@6.1.  

error 
![image](https://user-images.githubusercontent.com/21353460/51095791-2615d400-17f2-11e9-9d22-41cfd23159ce.png)

**Comment by luozhang002** [comment]
@jonyshi  能把具体定位到的managed-upload.js多少行截个图吗？
