### ISSUE TITLE
移动端使用put 上传一个绝对路径文件？

### ISSUE THREAD

**Issue by nirvana72** [ali-sdk/ali-oss#590]
put 参数只接收 file 或 blob ， PC端可以通过 input file控件来获取， 如果我是移动端调用相册， 返回的是手机中的绝对路径呢， 怎么上传

**Comment by luozhang002** [comment]
@nirvana72 移动端也是可以获取file对象的呀

**Comment by nirvana72** [comment]
也用 input type=file 控件？  
不同于PC端点击击选择本地文件
移动端的使用场景一般都是调用摄像头， 拍照或录像， 然后得到一个本地绝对路径
只有绝对路径， 没有为input type=file 控件手动赋值的过程
我想问的就是， html 中 不用input type=file控件， 如何使一个绝对路径文件转成file对象

**Comment by luozhang002** [comment]
@nirvana72 你看下这篇文章把 https://bbs.csdn.net/topics/390610561?page=1

**Comment by nirvana72** [comment]
谢谢， 关键点找到了， 使用ActiveXObject， 但暂不确定是否有兼容性和调用权限问题， 一会写个DEMO测试一下
