### ISSUE TITLE
对浏览器来说这个包太大了

### ISSUE THREAD

**Issue by seekcx** [ali-sdk/ali-oss#591]
测试了一下，这个包包含了很多依赖，总共占了 341 kb，和目前项目总大小差不多了，很明显不适合前端使用。

大多数情况下前端使用的都只有上传功能，有没有计划单独开发一个只包含上传功能的组件。

**Comment by luozhang002** [comment]
@seekcx 目前SDK里面涉及的接口确实很多，我觉得开发者完全可以拉代码把原型上挂载的非上传接口去掉，自己单独打包。

**Comment by PeterRao** [comment]
浏览器主要从node版本衍生出来，很多node兼容包被打包进来同时需要支持全部接口，如果只需要上传，可以参照oss官网公共api定义，自行构造请求实现。https://help.aliyun.com/document_detail/31978.html
。

**Comment by ShumRain** [comment]
确实太大了，可以使用webpack来动态import，在点击上传的时候再加载ali-oss
```
import(/* webpackChunkName: "ali-oss" */ 'ali-oss').then(OSS => OSS)
```

**Comment by wisetc** [comment]
ali-oss bundle 有 350多kb
![image](https://user-images.githubusercontent.com/9448115/55073680-4eab2b80-50c9-11e9-96b4-0fab7efed69e.png)

**Comment by Alex1990** [comment]
嗨，各位！我写了一个极简版 [tiny-oss](https://github.com/Alex1990/tiny-oss)，大小低于 10kb（min+gzipped)，目前只支持`put()`与`signatureUrl()`方法。

刚刚写完，包含简单的测试，目前还没有使用过，我准备之后在公司的项目内使用。也欢迎各位使用和测试，提出改进意见，不过基本上不会添加功能了，只专注于简单的上传。

**Comment by seekcx** [comment]
@Alex1990 非常感谢

**Comment by xuxu7** [comment]
同样的问题，需要精简版。
@Alex1990 不支持 STS ?

**Comment by Alex1990** [comment]
@xuxu7 支持的

**Comment by wisetc** [comment]
我是上传图片，在前端构造签名，然后用post表单的形式上传的，功能十分单一。




在2019年09月08日 15:15，Alex Chao 写道：

@xuxu7 支持的

**Comment by Alex1990** [comment]
你是指 https://www.alibabacloud.com/help/zh/doc-detail/31925.htm?spm=a2c63.p38356.b99.722.a6cf1f85PtPr92 这个嘛？目前我对这个不熟悉，之后有时间看下

**Comment by wisetc** [comment]
是的




在2019年09月08日 18:33，Alex Chao 写道：

你是指 https://www.alibabacloud.com/help/zh/doc-detail/31925.htm?spm=a2c63.p38356.b99.722.a6cf1f85PtPr92 这个嘛？目前我对这个不熟悉，之后有时间看下

**Comment by wisetc** [comment]
@Alex1990 主要是为了兼容极小部分机型的移动端钉钉浏览器

**Comment by sessionboy** [comment]
有什么进展吗，这个问题，通常只需要一个上传功能，却加载了很多无关的代码

**Comment by lance-ding** [comment]
可以使用官方cdn地址加载 `https://gosspublic.alicdn.com/aliyun-oss-sdk.min.js`，或者下载`aliyun-oss-sdk-x.x.x.min.js`文件到本地，然后在html中加载。

配置webpack: 
```
{
    externals: {
        "ali-oss": "OSS"
    }
}
```
打包后减少掉sdk的大小

**Comment by F5F5** [comment]
一年多过去了，包大小增加到447Kb，这个分包问题还没有得到解决😔

**Comment by seekcx** [comment]
@F5F5 我后来使用了 postObject 的方式，完全不用这个库，授权签名过程都在后台完成，前台只需要提交上传就行了。

![image](https://user-images.githubusercontent.com/8244814/78749515-fdeb3580-79a0-11ea-9d80-dfe84e4752fb.png)

**Comment by F5F5** [comment]
@seekcx 额，我是前端，需要拿到signatureUrl用来展示文件，其实只用到了这一个方法

**Comment by seekcx** [comment]
@F5F5  没了解过，只是展示签名更应该放到后端了。

**Comment by Alex1990** [comment]
@F5F5 signatureUrl 也可以后端来调用这个方法来获取授权的文件 url，然后返回给前端使用

**Comment by sessionboy** [comment]
这么久了还没解决？

**Comment by wubianlei** [comment]
大佬们能出个简版么。。。

**Comment by wisetc** [comment]
https://www.npmjs.com/package/@wisetc/utils-form

这个我应测试压力（移动端h5容器兼容性）封装一个简便功能的oss上传库，应该不到100kb，欢迎试用并发表使用意见。

**Comment by guobing1993** [comment]
![image](https://user-images.githubusercontent.com/22333388/83237508-99419f80-a1c7-11ea-9110-07bde27ba97d.png)
太大了

**Comment by zhangchao828** [comment]
两年了还没进展，一点都不负责任

**Comment by wisetc** [comment]
前端用其实不太安全的，其实这个就是给nodejs用的，浏览器用可以用HTTP接口直传。万一在浏览器上用出了安全问题，sdk也不愿背这个锅。




在2020年11月18日 10:05，止水 写道：

两年了还没进展，一点都不负责任

**Comment by eugle** [comment]
确实太大了，@Alex1990 可以增加 多文件上传吗？

现在竟然有500多KB，哎，现在都2021年了

**Comment by Alex1990** [comment]
@eugle 多文件上传可以直接调用多次 put 方法实现吧

**Comment by eugle** [comment]
@Alex1990 不一样的，现在包已经增加到568kb了，这就是传说中的屎山库，从2年前340kb增加到568kb

以后如果要演示什么是屎山，这个就是最好的例子，太棒了，开发界的榜样，

我当时接入选择也是脑壳有包，忽略了包大的问题，做为一个阿里粉，看来真是吃到了苍蝇，

开发这个也是费了很多时间，很气愤做为大厂竟然这样对待用户

**Comment by tiyunchen** [comment]
![image](https://user-images.githubusercontent.com/24793416/129311311-7d52ee0b-f759-48c1-89bb-437cebf303cb.png)
吐了

**Comment by xuxucode** [comment]
🪆

**Comment by night-king** [comment]
马上要上马，感觉size是个问题，看来这条路行不通了。

**Comment by scujccyzp** [comment]
![image](https://user-images.githubusercontent.com/53200294/158938946-682fc872-4add-4933-ae15-eb5e4a72562d.png)
现在已经1M了，阿里真有你的😄

**Comment by fengmk2** [comment]
这个包是给 node 环境使用的。

**Comment by xuxucode** [comment]
@fengmk2 阿里云 OSS 文档【Web端上传介绍】提到的 [Browser.js SDK](https://help.aliyun.com/document_detail/112718.html#:~:text=%E5%88%A9%E7%94%A8OSS%20Browser.js%20SDK%E5%B0%86%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E5%88%B0OSS) 指向这个 SDK，现在这种方式是否不再使用？

[OSS 文档中相关链接](https://help.aliyun.com/document_detail/64041.html#:~:text=%E5%8D%87%E7%BA%A7%E6%96%87%E6%A1%A3%E3%80%82-,Github%E5%9C%B0%E5%9D%80,-API%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E)

**Comment by fengmk2** [comment]
@PeterRao 得看看，如果是给浏览器使用，目前的方式不合理的。

**Comment by seekcx** [comment]
是否应该重新打开？

**Comment by elmelloi** [comment]
这个问题官方还打算解决吗？

**Comment by wforguo** [comment]
2023 最新体积

![image](https://github.com/ali-sdk/ali-oss/assets/23009078/494b7562-a2ac-490b-8a5e-b5585e81ceb7)

**Comment by fengmk2** [comment]
这个 npm 包是面向 nodejs 开发的，不是面向浏览器。

**Comment by wforguo** [comment]
aliyun OSS(Object Storage Service) js client for Node and **Browser env.**

**Comment by ricky11** [comment]
Still after 4 yeas, no movement on the browser version, what happened to v7 which is tree shakable, that document has not been updated..

**Comment by east-mod** [comment]
web pack:
```
                aliOss: {
                    test: /[\\/]node_modules[\\/]ali-oss[\\/]/, // 针对 ali-oss 单独分包
                    name: 'ali-oss',
                    chunks: 'all',
                    priority: 10, // 提升优先级，确保单独提取
                },
```
```
async function getOSSClient(config) {
    const OSS = (await import('ali-oss')).default;
    // 初始化 OSS 客户端
    return new OSS(config);
}
```
`const client = await getOSSClient(config); `

**Comment by Whering** [comment]
2025年了家人们，有轻量版本了吗🥹

**Comment by qrshi-Sss** [comment]
2026了兄弟们，1.51MB了

**Comment by seekcx** [comment]
> 2026了兄弟们，1.51MB了

感谢兄弟带来的最新报告，我都忘了当初是什么项目提了这个issue了，7年没解决也是牛的
