### ISSUE TITLE
断点续传不支持磁盘路径

### ISSUE THREAD

**Issue by dijiang** [ali-sdk/ali-oss#592]
比如我要上传整块磁盘。磁盘路径是\\\\.\\PhysicalDrive0。。
断点续传api目前不支持这个路径。。
然后就用sdk原始的api，initMultipartUpload, uploadPart, completeMultipartUpload 等进行实现这个功能。。
然后发现。。这些接口，简直做的稀巴烂。。比如listParts最大一次只支持1000。。但是uploadPart最大的是10000。。这仅是个细节。。
这一个小功能就要搞这么多细节。。
另外nodejs sdk的文档能否更新下？！！！。。其他sdk的文档介绍上传下载的时候都有一个概述。。简单上传和追加上传最大5g什么的提示。。就是nodejs的文档没有。。老子开始用appendDate实现的这个功能。。然后测试才发现这个问题。。推倒重来。。。f*ck！
最后。。是否考虑断点续传这个api支持磁盘路径？

**Comment by luozhang002** [comment]
@dijiang 

1. 至于你说的listParts和uploadPart限制，这是oss后端openAPI的限制，SDK的实现也只能按照OSS后端，接口这么设计肯定是有原因的，想知道设计原理的话可提售后工单联系技术中台进行解释。
https://help.aliyun.com/document_detail/31998.html（listParts）
https://help.aliyun.com/document_detail/31993.html(uploadParts)

2. 至于文档部分，确实没有在开头中描述上传文件大小，这边会联系文档尽快修改，感谢反馈

3.这个暂时不支持， 如果你只是想把整个磁盘的所有文件上传到OSS你可以使用上传工具类ossutil或者ossbrowser，因为SDK本身是对openapi的封装，这种场景暂不支持

**Comment by dijiang** [comment]
![image](https://user-images.githubusercontent.com/8736832/52766338-ded56a00-3061-11e9-9c0e-99f4328a5f30.png)

使用这个磁盘路径传一会会就报下面这个错误，用其他普通的文件路径没问题

![image](https://user-images.githubusercontent.com/8736832/52766442-1ba16100-3062-11e9-80b0-3fcdfb473d73.png)

这个是要将我所有的路都封死啦？。。本来以为使用原始的sdk api可以。。我这个需求就说要直接上传磁盘镜像文件（取证）啊，不是上传文件。。改咋搞哦？！！！。。就说一个简单的读文件api都搞不好？？？？？？？？？？？？？？？？？？？？？？？

**Comment by dijiang** [comment]
@luozhang002  读个路径和读其他文件本质上没有区别啊。。open，然后read就可以直接读啊，偏移什么的都一样的。。上面那个也是能传一会会的，过一会就报这个错。。这个是什么原因呢？

**Comment by dijiang** [comment]
![image](https://user-images.githubusercontent.com/8736832/52766892-a2a30900-3063-11e9-85d5-e57f85773304.png)

**Comment by dijiang** [comment]
@luozhang002 @pmq20 @lfeng @fengmk2 
![image](https://user-images.githubusercontent.com/8736832/52767641-11816180-3066-11e9-9a95-ed88e4f15fba.png)
![image](https://user-images.githubusercontent.com/8736832/52767713-4beafe80-3066-11e9-98c1-28d628dd9364.png)

skd 上的demo数值小点也是可以成功的啊。。我自己改改数值就不行了。。。

**Comment by dijiang** [comment]
@luozhang002 @luozhang002 @lfeng @fengmk2 
我的天。。貌似每块大小都要是1024的整数倍。。我换成这个大小测试好像就没问题了。。所有的文档里面貌似只说最后一块可以小于100k，其他的都是100k~5g，最多分10000块。。如果那里找到这个限制说明，我【直播剁屌】！！！
如何真是这样，我只能说无语了。。就你们文档的问题，就浪费我几天时间。。估计文档和sdk里面readme我都比写的人熟悉了。。
最后说一句，垃圾阿里。。这个是商业软件，花钱买的服务，不是开源玩的玩具。。

**Comment by fengmk2** [comment]
@dijiang oss 文档确实没有提到每块大小都必须是 1024 的整倍数 https://help.aliyun.com/document_detail/31993.html?spm=a2c4g.11186623.6.1061.22ab79deJsqG58

但是有特别说明除了最后一块都必须大于 100KB

> Multipart Upload要求除最后一个Part以外，其他的Part大小都要大于100KB。但是Upload Part接口并不会立即校验上传Part的大小（因为不知道是否为最后一块）；只有当Complete Multipart Upload的时候才会校验。

---

商业软件也是讲究文明用语的，感谢你的反馈。

**Comment by dijiang** [comment]
所有的文档里面都只说最后一块可以小于100k，其他的都是100k~5g，最多分10000块，这个是文档里面说的啊。。这个我是知道的。。
但没说是1024的整数倍啊。。不是这个大小就报错了啊。。
第一次是因为nodejs sdk的没说上传大小的限制，我传5g以上的大小用了错误的方法，这个其他skd有说明，认了，不仔细。。然后我换种实现方法。。然后就是这个1024整数倍的问题。。然后又卡住了。。这个我所有地方都没看到。。
这还能忍？。。你明白这种心情？？？？

**Comment by fengmk2** [comment]
@dijiang 你好，我跟你也一样，也是按照阿里云官方文档来写的 sdk，我们也不是 oss 服务端开发者。与其抱怨，还不如来贡献完善一下文档，写清楚这个限制。
