### ISSUE TITLE
BUG:ali-oss example without STS方式CORS error，同样配置oss-h5-upload-js-direct项目正常上传

### ISSUE THREAD

**Issue by panhezeng** [ali-sdk/ali-oss#593]
不管是使用ali-oss的example，还是我自己项目，使用SDK 6以上版本，都报CORS 错误。
测试使用的是本地key id/secret without STS 方式。

但是用你们其他文档里的oss-h5-upload-js-direct项目，使用本地key id/secret without STS 方式，是可以上传成功的。请问你们sdk的xhr是使用了什么默认选项吗？

可以确定我正确配置了CORS，允许所有来源*，而且使用你们的老示例项目oss-h5-upload-js-direct也是可以上传的。

oss-h5-upload-js-direct使用的是plupload，没有使用ali-oss。

has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

![avatar](https://i.ibb.co/17pSmMW/20190222144734.png)
![avatar](https://i.ibb.co/QpJnFsr/20190222144843.png)
![avatar](https://i.ibb.co/85qr9nP/20190222145055.png)

**Comment by luozhang002** [comment]
@panhezeng 跨域配置要把允许的方法：POST、GET、PUT、HEAD全部勾选上，单单看错的确是跨域配置有问题，如果还有问题请把你的跨域配置截个图，或者提供bucket我们可以查看配置到底对不对

**Comment by panhezeng** [comment]
![avatar](https://i.ibb.co/Gsmbm9H/20190225100204.png)

我肯定是反复尝试确认过问题原因的，不管是Google搜索，还是看官方文档，我确认跨域配置是没有问题的，不然我也不会找到oss-h5-upload-js-direct项目，并且使用它上传成功了，但是用你们sdk的example项目无论如何都不行。

我之前接ucloud和腾讯云都没遇到这样的问题，还有我看腾讯云的文档https://github.com/tencentyun/cos-js-sdk-v5 比你们多设置了一个credentials为false，你们的没有这个设置。
你们sdk的xhr.withCredentials和你们后端的credentials设置，是不是有什么不匹配的问题，在用localhost without STS 方式时，才会出现这种问题？

**Comment by panhezeng** [comment]
小小吐槽一下，为什么你们的js sdk github readme默认是英文，而且没有提供中文？而人家腾讯默认是中文，是觉得你们阿里云的用户主要是英语用户吗？是不是中文用户很少？

**Comment by luozhang002** [comment]
@panhezeng  阿里云目前其他的SDK 比如java python进去后默认都是英文的，而且开源SDK英文的居多，中文的我们会尽快翻译，官网文档上会有中英日文的。SDK的example我用STS和AK的方式重新测了一遍都是OK的，也不需要其他大改动，（1）main.js里 改下bucket和region ,region的格式：类似这种“oss-cn-zhangjiakou” （2）跨域配置正确。 就可以正常运行。

<img width="1264" alt="2019-02-25 10 28 54" src="https://user-images.githubusercontent.com/5653578/53310515-2ec8f200-38e8-11e9-9e7f-2eb7c6517de4.png">

**Comment by panhezeng** [comment]
好的，我再尝试一下，难道和我的网络环境也有关系吗？还有我的云账号是客户给的子账号，我得不到RoleArn，也不知道客户父级设置了什么，反正至少用客户给子账号权限和key，并且按图设置了跨域，请问从图片看，我的设置没有问题吧。而且我们在后端用python without STS 方式也是可以上传的，就是在本地用前端js无法上传，真是郁闷。

**Comment by panhezeng** [comment]
抱歉，是我OSS 的 option对象的region和bucket配置错误了。赶快关闭。

**Comment by itMuYou** [comment]
3242
