### ISSUE TITLE
new Buffer()已经被node标记为过时方法，建议更新一下，不然运行老是报警告

### ISSUE THREAD

**Issue by crackxia** [ali-sdk/ali-oss#594]
(node:28956) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by luozhang002** [comment]
@crackxia 感谢反馈，到时候废弃的会统一改调

**Comment by vae1970** [comment]
半年过去了，希望能早日修改，因为真的已经影响正常使用了QAQ
项目都无法启动了额

**Comment by PeterRao** [comment]
使用6.4.0 以上版本

**Comment by shanghen** [comment]
修复了？怎么6.17.1又出现该提醒了
(node:34403) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
