### ISSUE TITLE
multipartUpload 设置timeout上传的超时时间不起作用？

### ISSUE THREAD

**Issue by xyoscer** [ali-sdk/ali-oss#597]
client.multipartUpload(ossObj, uploadFile, {
      progress: (per, point, res) => {this.progressByOss(per, point, res)},
      parallel: 2, // 并发上传的个数
      mime: uploadFile.type, // 上传的文件类型
      partSize: this.partSize,  // 分片大小
      checkpoint: localDataByOss || this.tmpPoint,
      timeout: 60000 // 网络超时时间 ms
    }).then(()=> {}).catch(() => {})

如上js使用OSS上传，设置超时时间，在第一次调用multipartUpload时，timeout起作用，在中间分片上传过程中，这个时间并不起作用，默认超时使用的300000ms ,请问这个是怎么回事？

**Comment by gokuaiadmin** [comment]
刚看了源代码, PUT分块上传没有使用传入的timeout参数

**Comment by Ari1c** [comment]
@gokuaiadmin 目前对于multipartUpload 参数重的timeout不会对单个分片起作用。这个参数是对分片上传中initupload操作和completepart操作进行限制。没有对单独分片上传进行限制。如果需要的话我们可以加

**Comment by eugle** [comment]
@Ari1c 
加了吗？两年过去了？混了两年的高薪，厉害啊

**Comment by PeterRao** [comment]
使用最新版本 已修复
