### ISSUE TITLE
请问如何实现批量下载并且打包成一个zip

### ISSUE THREAD

**Issue by lmikoto** [ali-sdk/ali-oss#598]
预期的效果是类似于 主流网盘都拥有的批量下载功能。点了批量下载会把要下载的东西都放到一个zip里面，而且用户可以立刻得到反馈开始下载了，下载的过程中可以关闭tab页。
能给出一种技术方案吗，无论是前端还是后端的。

请不要提供类似于先下载到本地，然后打包成zip的这种方案。这种方案如果在后端实现，需要下载两遍，并且压缩一遍才能抵达用户，如果在前端实现，用户点了下载之后，如果文件很大，用户得不到及时的反馈。误认为这是bug，并且下载期间不能关闭tab页

**Comment by PeterRao** [comment]
@luozhang002 IMM 那边提供了这个功能没，没有的话，看给一个配合 函数计算 实现的例子？

**Comment by luozhang002** [comment]
@PeterRao IMM和函数计算应该不行，如果用函数计算的还数据流先引入函数计算那边，最好的方式比如 getObject传一串key，oss后端返回一个zip包，但是现在oss压缩下载暂不支持，之前问过产品，暂不支持的。
