### ISSUE TITLE
小程序wepy库现在能用没

### ISSUE THREAD

**Issue by xiaozzhou** [ali-sdk/ali-oss#599]
小程序wepy库现在能用没，目前require('ali-oss')，一直打包不出东西

**Comment by luozhang002** [comment]
@xiaozzhou  目前ali-oss这个库不支持小程序直接上传， 你可以采用签名直传的方式，https://help.aliyun.com/document_detail/92883.html  关于wepy框架直接上传的，阿里云官方并没有给出相关插件，github上有用户开发了相关插件 https://www.npmjs.com/package/wepy-plugin-aliyun-oss ，你可以试用下。
