### ISSUE TITLE
分片失效时间默认3600s太短了

### ISSUE THREAD

**Issue by imquincychen** [ali-sdk/ali-oss#600]
使用分片上传方法上传一个3GB的文件，时间超过1小时后上传出错

报错内容
![image](https://user-images.githubusercontent.com/39582014/53876426-b679d380-4041-11e9-9644-b2248cf9b7bf.png)

查了一下文档，是因为分片有效期为一个小时，但是这个失效时间是不是太短了？
![image](https://user-images.githubusercontent.com/39582014/53876305-7581bf00-4041-11e9-9c08-9f5416b33d74.png)

**Comment by luozhang002** [comment]
@你用的是STS方式上传吧，看提示应该是token过期了，需要自己去捕获这个异常，过期了再重新请求获取AK，然后再上传。

**Comment by imquincychen** [comment]
@luozhang002  方案可行，已解决
