### ISSUE TITLE
weex现在能用吗？

### ISSUE THREAD

**Issue by jjsaint** [ali-sdk/ali-oss#601]
weex现在能用吗？

**Comment by luozhang002** [comment]
weex上传目前js sdk是不支持的，但是可以采用weex接口扩展的方式自己封装，底层调用原生的安卓和ios，github上其实相关类似的插件https://www.npmjs.com/package/weex-aliyun-oss ，所有的原理都是一样的，React native也是通过插件扩张的方式。
