### ISSUE TITLE
IOS手机QQ浏览器上传超时

### ISSUE THREAD

**Issue by WinfredH** [ali-sdk/ali-oss#603]
* **Browser Version or Node Version**:
IOS 手机QQ浏览器 v9.0.3
* **ali-oss Version**:
v6.1.0
* **Mini Showcase Repository**:
无
* **Network Resoponse Header x-oss-request-id**:
5C8B5A943CC5B7D0985964A2

使用ali-oss的put方法上传文件，在其他浏览器中均表现正常，唯有在QQ浏览器中出现了文件已经上传完成，但是put报错超时

<img src="http://xyzq-static.oss-cn-shenzhen.aliyuncs.com/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20190315155937.jpg">

**Comment by 1019272778** [comment]
在某些友商浏览器上可能会有直接通过oss域名上传数据会出问题。建议可以通过cname的方式来上传。
参考链接：https://help.aliyun.com/document_detail/31836.html
alioss sdk 兼容了大部分的浏览器。但是也无法做到完全兼容。如果有一些特殊case，可以考虑通过web直传的方式
参考链接：https://help.aliyun.com/document_detail/31923.html
