### ISSUE TITLE
调用put接口, 返回RequestTimeTooSkewed错误的情况下, 仍然返回了statusCode=200

### ISSUE THREAD

**Issue by samilywang** [ali-sdk/ali-oss#604]
* **Browser Version or Node Version**: Chrome 72.0.3626.121
* **ali-oss Version**: 6.1.0
* **Mini Showcase Repository**: none
* **Network Resoponse Header x-oss-request-id**:
1. 返回403的requestId: 5C8B74392D5BE1E4437AEA67 
2. 返回200的requestId: 5C8B743A7F911B7F8BDE70C3

调用put接口, 在http request返回RequestTimeTooSkewed错误的情况下, 对应promise仍然返回了statusCode=200的一个PutObjectResult

复现步骤：
1. 将本地时间调整到和当前正常时间的差距大于15分钟(触发RequestTimeTooSkewed错误)
2. 调用put方法
3. 会先尝试上传对应文件, 该次请求返回403
4. js-sdk会自动重发一次上传文件的请求, 但是body为空, 该次请求成功, 返回200
5. oss中存在一个大小为0KB的文件

network信息：
![image](https://user-images.githubusercontent.com/13418696/54423870-9d150d80-474c-11e9-8e83-b0d1bdd5035f.png)

![image](https://user-images.githubusercontent.com/13418696/54423939-c5047100-474c-11e9-995e-67b76ef8d996.png)

![image](https://user-images.githubusercontent.com/13418696/54423957-d0579c80-474c-11e9-824f-70f1cf1005a3.png)

![image](https://user-images.githubusercontent.com/13418696/54423997-e9604d80-474c-11e9-9701-5b9085775e70.png)

oss仓库信息：
![image](https://user-images.githubusercontent.com/13418696/54424089-1c0a4600-474d-11e9-9f22-e095869a1db8.png)

**Comment by samilywang** [comment]
再附一张打印出来的put接口返回值

![image](https://user-images.githubusercontent.com/13418696/54424683-693ae780-474e-11e9-9c44-63e69e62a59b.png)

**Comment by luozhang002** [comment]
@samilywang  RequestTimeTooSkewed这个异常ali-oss里面确实会对这种情况进行时间校验重发一次请求，你check下request(params)时第一次和第二次的参数有什么不通，你这个测试demo是实例化OSS的时候传入的AK的吧，如果是AK的话建议走STS的方式，因为STS的方式无论你本地时间是过早还是果短，当请求STS server的时候，STS server会及时抛出错误 ，也就走不到SDK里面的判断逻辑了，也是比较安全的方式。
<img width="694" alt="屏幕快照 2019-03-17 上午7 51 01" src="https://user-images.githubusercontent.com/5653578/54484034-32251d00-4899-11e9-8f80-f00246663fb8.png">

**Comment by samilywang** [comment]
@luozhang002 这边实例化oss的时候传入的参数如下
![image](https://user-images.githubusercontent.com/13418696/54501638-695f0100-4961-11e9-82e5-9c6187822fe2.png)
已经使用了STS，不过stsToken并不是前端生成的，是由后端生成后传递到前端的，但后端的时间是正常的，所以sts server不会报错

两次请求的header和body如下:

*第一次*
![image](https://user-images.githubusercontent.com/13418696/54501824-80522300-4962-11e9-9e69-f69308b46fdc.png)

*第二次*
![image](https://user-images.githubusercontent.com/13418696/54501888-ceffbd00-4962-11e9-8d85-6e84f79deaa4.png)


相关区别就是第二次时间确实被修正了，但是body为空，所以导致上传的文件是一个空文件。

所以是不是ali-oss在处理重发请求的时候没有处理好上传文件body的问题？

**Comment by gokuaiadmin** [comment]
这里可能是个致命bug, 第一次put时会把stream消费完, stream.readable变成false, 因此第二次put无法读到数据, 导致上传了空文件, 如果外部调用代码只判断了200, 就会导致文件丢失

**Comment by kmac007** [comment]
同样的问题

**Comment by lilangkit** [comment]
该问题依旧存在
