### ISSUE TITLE
小需求

### ISSUE THREAD

**Issue by wxhccc** [ali-sdk/ali-oss#606]
请问能否提供一份njs(nginxScript)实现的请求签名代码，url方式或headers方式都行。我想用nginx反向代理时添加签名，这样不用将文件改成公共读也不需要保存文件地址时添加签名（签名有期限，保存到数据库不太好）。多谢了

**Comment by luozhang002** [comment]
目前js sdk已经封装签名代码，你说的nginxScript建议自己写，至于如何签名不懂的的是可以提供指导。

**Comment by wxhccc** [comment]
@luozhang002 ，需求已实现，还是看sdk源码解决的。sdk源码有加密过程的拆解函数，为什么不放出来呢？非url签名的场景还是比较多的。
