### ISSUE TITLE
deleteMulti does not work with stsKey

### ISSUE THREAD

**Issue by ricky11** [ali-sdk/ali-oss#613]
* **Browser Version or Node Version**:
NODE JS 8 LTS

* **ali-oss Version**:
LATEST

* **Network Resoponse Header x-oss-request-id**:
x-oss-request-id: 5CA49A824683C5A06F49FA0E

Using STS KEY as follows :

```
const ossClient = await new OSS({
  region: 'oss-cn-hongkong',
  accessKeyId: this.stsKey.AccessKeyId,
  accessKeySecret: this.stsKey.AccessKeySecret,
  stsToken: this.stsKey.SecurityToken,
  bucket: 'xxxx',
  cname: true,
  endpoint: 'oss.xxxx.com'
});

var sts = new STS({
  accessKeyId: process.env.ACCESSKEYID,
  accessKeySecret: process.env.SECRET,
  cname: true
});

const result = await ossClient.deleteMulti(Array)
```

We usually get a error as follows:

<Error>
<Code>
AccessDenied
</Code>
<Message>
Access denied by authorizer's policy.
</Message>
<RequestId>
5CA23775B663510F415433C2
</RequestId>
<HostId>
oss.xxxx.com
</HostId>
</Error>

We opened a ticket with support and the backend team confirmed the following -

**> We have confirmed with our backend team that currently DeleteMultipleObjects api does not support STS way for detail object folder path grant authority. We will raise request for product team to see if able to improve or add in the future, but not in short time.
> For now suggest you to firstly use listObject and deleteObject to delete your object as a temp workaround**

**How to solve this problem:**

DELETEMULTI API should work with STS KEY for Node SDK. Current workaround is to use DELETE API and loop over.

Thank you
Rishi

**Comment by ricky11** [comment]
Any help with this?

**Comment by PeterRao** [comment]
the deleteObject not match your sts policy, you can confirm the policy witch you backend team. The policy like this https://github.com/ali-sdk/ali-oss/blob/master/example/server/policy/all_policy.txt#L4

**Comment by ricky11** [comment]
Hi peter, Thanks, last month we confirmed with the backend support team, the following, so the problem does not have anything to do with stspolicy, it is because deleteMulti does not support STS authorization. Hence I posted this issue on github to convince the backend team to allow deleteMulti to support STS token.

See the response from backend team:

> We have confirmed with our backend team that currently DeleteMultipleObjects api does not support STS way for detail object folder path grant authority. We will raise request for product team to see if able to improve or add in the future, but not in short time.

**Comment by PeterRao** [comment]
Could you get the policy content from your backend team and post it here？

**Comment by PeterRao** [comment]
I had added the test case for deleteMultiple https://github.com/ali-sdk/ali-oss/blob/master/test/node/sts.test.js#L118, the test case is passed.
Could you post your policy and Array variable

**Comment by ricky11** [comment]
Hello, can you see anything wrong with the below policy?

it should only allow users to delete within their folder (data.id)
I still get authentication error for deleteMulti

  var policy = {
  "Version": "1",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "oss:ListObjects"
      ],
      "Resource": [
        "acs:oss:*:*:sinosend"
      ],
      "Condition": {
        "StringLike": {
          "oss:Prefix": data.id+"/*"
        }
      }
    },
    {
      "Effect": "Allow",
      "Action": [
        "oss:Get*",
        "oss:List*",
        "oss:Delete*",
        "oss:Put*",
        "oss:Head*",
        "oss:AbortMultipartUpload"
      ],
      "Resource": [
         "acs:oss:*:*:sinosend/"+data.id+"/*",
         "acs:oss:*:*:sinosend/thumbs/"+data.id+"/*"
            ]
    }
  ]
}

**Comment by ricky11** [comment]
HI Peter.

you said i should use tihs policy: https://github.com/ali-sdk/ali-oss/blob/master/example/server/policy/all_policy.txt#L4

But this is a open policy with no security??

**Comment by PeterRao** [comment]
Your policy Action not include `"oss:DeleteObject"`.

Policy has no security unless  leak your accessKeyId and accessKeySecret,  you can use http://gosspublic.alicdn.com/ram-policy-editor/english.html to create the policy.

**Comment by ricky11** [comment]
Hi Peter,

I have delete with wildcard.
But i have oss:Delete*",

Rishi

**Comment by PeterRao** [comment]
> Hi Peter,
> 
> I have delete with wildcard.
> But i have oss:Delete*",
> 
> Rishi

You use `Condition`, I think it will block the second  Statement.

![image](https://user-images.githubusercontent.com/1611647/67071595-87ba0300-f1b5-11e9-9824-91a810127d99.png)

**Comment by PeterRao** [comment]
Can you delete `Condition` and try it?

**Comment by ricky11** [comment]
Hello

If i delete the condition, then all resource can be accessed in the bucket.  As i only want the resource to be accessed in the user folder : "acs:oss:::sinosend/"+data.id+"/",

I dont understand why i need two statement, can i combine in to one and set the resource only as follows: 
"acs:oss:::sinosend/"+data.id+"/",
"acs:oss:::sinosend/thumbs/"+data.id+"/"

Thanks.

**Comment by PeterRao** [comment]
I am not very familiar with this `RAM Policy`. 

Use this Policy and try it?
`
{
"Effect": "Allow",
"Action": [
"oss:ListObjects"
],
"Resource": [
"acs:oss:::sinosend/"+data.id+"/",
],
xxx
}
`
