### ISSUE TITLE
object.get 请求包含  headers : "Accept-Encoding": "gzip" 时，对于文件大小超过10M的文本文件，gunzip解压缩报错

### ISSUE THREAD

**Issue by yi** [ali-sdk/ali-oss#616]
* **Browser Version or Node Version**:

Node.js 8.12.0

* **ali-oss Version**:
aliyun-sdk-nodejs/6.1.1 

* **Mini Showcase Repository**:
NA

* **Network Resoponse Header x-oss-request-id**:

object.get 请求包含  headers : "Accept-Encoding": "gzip" 时，对于文件大小超过10M的文本文件，gunzip解压缩报错

预期目的
===

使用这个 sdk 通过 get 操作拉回文本文件时，能支持 gzip 压缩，以节约 oss 流量成本

遇到的问题
===

在get小于10Mb的文件时，一切操作正常。当oss上的文本文件超过一定的大小（10Mb）时，将会遇到 ` incorrect header check` 错误。

复现步骤
===

 1. 在 OSS 上put两个 文本文件，一个文件大小 小于 10M（下称 文件A），另外一个文件大小大于 10M (下称 文件B)
 1. 两个文件都满足这个文档所规定的要求：https://help.aliyun.com/knowledge_detail/39645.html
 1. 在 get 请求的 options 中设置 `headers : {"Accept-Encoding": "gzip"}`
 1. 打开 debug 的 ali-oss*

请求文件A
====

request header:
```
 ali-oss request GET http://****.aliyuncs.com/detail/****.json, with headers {"x-oss-date":"Mon, 15 Apr 2019 05:40:38 GMT","x-oss-user-agent":"aliyun-sdk-nodejs/6.1.1 Node.js 8.12.0 on Darwin 64-bit","User-Agent":"aliyun-sdk-nodejs/6.1.1 Node.js 8.12.0 on Darwin 64-bit","Accept-Encoding":"gzip","Content-Type":"application/json","authorization":"****"}, !!stream: false
``` 

response header:
```
{ server: 'AliyunOSS',
  date: 'Mon, 15 Apr 2019 05:40:38 GMT',
  'content-type': 'text/plain',
  'transfer-encoding': 'chunked',
  connection: 'keep-alive',
  vary: 'Accept-Encoding',
  'x-oss-request-id': '5CB4195665D26240DBEB5335',
  'last-modified': 'Sun, 14 Apr 2019 04:50:08 GMT',
  'x-oss-object-type': 'Normal',
  'x-oss-hash-crc64ecma': '*****',
  'x-oss-storage-class': 'Standard',
  'access-control-allow-origin': '*',
  'cache-control': 'max-age = 315360000000',
  'x-oss-expiration': 'expiry-date="Tue, 14 Apr 2020 00:00:00 GMT", rule-id="84463454-094c-4062-85a5-45a18088b14b"',
  'content-md5': '****==',
  'x-oss-server-time': '0',
  'content-encoding': 'gzip' }
```

可以看到 文件A是通过 gzip压缩传输，并且在 sdk中被成功 gunzip，并且放回正确的 res 和 content

请求文件B
====

request header:
```
 ali-oss request GET http://***.aliyuncs.com/***.json, with headers {"x-oss-date":"Mon, 15 Apr 2019 05:40:39 GMT","x-oss-user-agent":"aliyun-sdk-nodejs/6.1.1 Node.js 8.12.0 on Darwin 64-bit","User-Agent":"aliyun-sdk-nodejs/6.1.1 Node.js 8.12.0 on Darwin 64-bit","Accept-Encoding":"gzip","Content-Type":"application/json","authorization":"OSS ****="}, !!stream: false
```

文件B 没有被成功返回，错误是 ` incorrect header check` 

由于[这里](https://github.com/ali-sdk/ali-oss/blob/master/lib/client.js#L313)会在 console 打印大量 未解码的 html body，暂时无法捕捉这个失败操作的 oss request id

经过测试，在OSS上，任意 10Mb 以上的满足 gzip 条件的文本文件，使用这个sdk 的 get 获取，都会发生这个报错。
===

**Comment by PeterRao** [comment]
我试了下没出现，能把object链接发一份看下？
