### ISSUE TITLE
当设置读写权限为公共读时，上传图片成功后，返回的图片地址，带有uploadid.

### ISSUE THREAD

**Issue by snowdream** [ali-sdk/ali-oss#618]
设置成私有时，上传图片成功后，返回的图片地址，不带有uploadid.
http://*****.oss-cn-hangzhou.aliyuncs.com/20190416/avatar_1555413433333.png

但是设置读写权限为公共读时，上传图片成功后，返回的图片地址，反而带有uploadid.
http://*****.oss-cn-hangzhou.aliyuncs.com/20190416/avatar_1555413433333.png?uploadId=1E9F2EE330DF46B9BEF60408078EBCAD

很不理解。
带有uploadid的图片地址不能匿名访问，我还需要手动处理url，过滤掉uploadid，再存进数据库，很麻烦。

**Comment by Ari1c** [comment]
@snowdream 我在本地6.1.1版本，根据私有和公共读权限的bucket测试上传的情况是没有携带uploadid的
![image](https://user-images.githubusercontent.com/33024188/62613929-033d3f80-b93d-11e9-9ad8-91fe742bf711.png)

**Comment by snowdream** [comment]
后续再观察。

**Comment by wpc669418** [comment]
文件比较大 分片的时候 就会必现
