### ISSUE TITLE
VUE 使用ali-oss TypeError: client.list(...).then is not a function

### ISSUE THREAD

**Issue by lieyunye** [ali-sdk/ali-oss#620]
* **ali-oss Version**:5.3.1

请问这是什么原因呀

**Comment by luozhang002** [comment]
@lieyunye  5.3.1版本在使用异步promise的时候 new OSS的时候要加上 new OSS.Wrapper 6.X系列的不用

**Comment by lieyunye** [comment]
好的
1、可以在sdk里加个上传速度的值吗
2、可以返回x-oss-request-id吗
