### ISSUE TITLE
什么情况下 etag 会变成「W/""」的形式？

### ISSUE THREAD

**Issue by Accelerise** [ali-sdk/ali-oss#624]
调用 multipartUpload API 分片上传，当每一片上传成功后，http 接口会返回相应 etag。
我的问题是，为什么它返回的 etag 会用「W/""」包起来，真正的 etag 在那两个引号中间？
而 SDK 并不会去掉那个「W/""」，导致 multipartUpload 在最后一步一定会发生 400 错误。
然而上线后那个「W/」又没了，我只是加了 secure: true 参数，因为必须使用 https 协议。

etag 在什么情况下会出现这种现象？

**Comment by Ari1c** [comment]
@Accelerise 能否把你分片上传的核心代码提供下，包括分片上传过程中设置的参数，我们check下，看会不会复现

**Comment by Accelerise** [comment]
看起来你们并不知情，可能是我这边的什么环节出了问题，感谢回复

**Comment by dead-horse** [comment]
https://en.wikipedia.org/wiki/HTTP_ETag#Strong_and_weak_validation

**Comment by dead-horse** [comment]
`W/` 是 etag 的一部分，标识其是一个 weak etag，即其中的 etag 值可能是时间戳等减少计算量的方式计算出的，而不是通过全文 hash 计算得出的。
