### ISSUE TITLE
wepy会支持吗

### ISSUE THREAD

**Issue by xinshengfan** [ali-sdk/ali-oss#625]
什么时候会支持wepy框架啊？有没有该计划呢？

**Comment by Ari1c** [comment]
目前小程序是支持直传https://help.aliyun.com/document_detail/92883.html?spm=a2c4g.11186623.6.1268.7dab74b85kKdcO但对于你这个框架，你可以参考这个链接看有没有帮助

**Comment by xinshengfan** [comment]
> 目前小程序是支持直传[https://help.aliyun.com/document_detail/92883.html?spm=a2c4g.11186623.6.1268.7dab74b85kKdcO，](https://help.aliyun.com/document_detail/92883.html?spm=a2c4g.11186623.6.1268.7dab74b85kKdcO%EF%BC%8C)
> 但对于你这个框架，你可以参考这个链接看有没有帮助

多谢，上传是可以解决的，现在是想做图片的按尺寸加载，希望服务器只返回图片的路径，由客户端的sdk计算添加尺寸后签名值，再生成访问链接url。但使用文档里的Node.js和Browser.js里的sdk都没有导入到这个框架里，想问下这种情况有什么好的解决方案吗？
