### ISSUE TITLE
使用browserify打包时报错：Cannot find module './browser/client'

### ISSUE THREAD

**Issue by chenquincy** [ali-sdk/ali-oss#629]
* **Browser Version or Node Version**: 11.12.0
* **ali-oss Version**: 6.1.1
* **Mini Showcase Repository**: http://static.quincychen.cn/browerify.zip
* **Network Resoponse Header x-oss-request-id**: none

### 错误详情

将ali-oss集成到sdk中，使用browserify打包会报错`Cannot find module './browser/client' from '/xxxxx/xxxx/node_modules/ali-oss/dist'`

### 重现步骤
下载demo包
``` shell
yarn
yarn build:browser
```

### 问题原因
查看了`dist/aliyun-oss-sdk.js`, 发现一下代码
``` javascript
var OSS = require('./browser/client');
OSS.Buffer = require('buffer').Buffer;
OSS.urllib = require('../shims/xhr');
OSS.version = require('./browser/version').version;
```
但是对应的`lib`文件夹中的文件并没有被打包到dist中，导致browserify命令失败

**Comment by chenquincy** [comment]
没有人吗

**Comment by chenquincy** [comment]
这个issue为什么到现在都没人回应？

**Comment by Ari1c** [comment]
@chenquincy 我们sdk本身都是已经打包混淆过的，不建议二次混淆打包，建议你可直接引入 cdn的版本 在<script>里引入
