### ISSUE TITLE
Does this SDK really support node.js???

### ISSUE THREAD

**Issue by hjlld** [ali-sdk/ali-oss#631]
* **Browser Version or Node Version**: Node.js 12.3.1
* **ali-oss Version**:  cloned from github repo `dist` folder
* **Mini Showcase Repository**: n/a
* **Network Resoponse Header x-oss-request-id**: n/a

The dist version of this SDK `aliyun-oss-sdk.js` has 11 references of the non-existed object `document` on node.js, as well as so many DOM operations.

It cannot be used on node.js at all!

here's one of the errors thrown:

```
D:\MyCode\OssDownloader\lib\aliyun-oss-sdk.js:91
  return document && document.location && document.location.protocol === 'https:';
  ^

ReferenceError: document is not defined
    at isHttpsWebProtocol (D:\MyCode\OssDownloader\lib\aliyun-oss-sdk.js:91:3)
    at Function.initOptions (D:\MyCode\OssDownloader\lib\aliyun-oss-sdk.js:131:25)
    at new Client (D:\MyCode\OssDownloader\lib\aliyun-oss-sdk.js:101:27)
    ...
```

**Comment by luozhang002** [comment]
@hjlld of course, we do ,it has worked well in nodejs for a long time ,can you provide your demo what you write ,we try in our local enviroment ,tks. aliyun-oss-sdk.js just was used in browser, with node you can use npm package.
