### ISSUE TITLE
Cannot read property 'x-oss-request-id' of undefined

### ISSUE THREAD

**Issue by ZoeShaw101** [ali-sdk/ali-oss#632]
使用sdk遇到这个问题，版本6.1.1，似乎是返回的response没有x-oss-request-id这个字段？求解答

```
client.put('image', new Buffer('test content')).then((result) => {
            console.log(result);
        });
```
```
Uncaught (in promise) TypeError: Cannot read property 'x-oss-request-id' of undefined
    at Client.requestError$ (http://127.0.0.1:53025/index.worker.js?t=1559197800782:2893:43)
    at tryCatch (http://127.0.0.1:53025/index.worker.js?t=1559197800782:17446:40)
    at Generator.invoke [as _invoke] (http://127.0.0.1:53025/index.worker.js?t=1559197800782:17680:22)
    at Generator.prototype.(anonymous function) [as next] (http://127.0.0.1:53025/index.worker.js?t=1559197800782:17498:21)
    at tryCatch (http://127.0.0.1:53025/index.worker.js?t=1559197800782:17446:40)
    at invoke (http://127.0.0.1:53025/index.worker.js?t=1559197800782:17536:20)
    at http://127.0.0.1:53025/index.worker.js?t=1559197800782:17579:11
    at new Promise (<anonymous>)
    at callInvokeWithMethodAndArg (http://127.0.0.1:53025/index.worker.js?t=1559197800782:17578:16)
    at AsyncIterator.enqueue [as _invoke] (http://127.0.0.1:53025/index.worker.js?t=1559197800782:17601:13)
```

**Comment by Ari1c** [comment]
你是指你打印的result中没有x-oss-request-id字段？（ps:我试的结果res.headers里有x-oss-request-id字段）

**Comment by ZoeShaw101** [comment]
@Ari1c  没有，是sdk里面报的错，是sdk解析response的时候没有x-oss-request-id字段

**Comment by Ari1c** [comment]
你有在里面的example跑一下吗

**Comment by ZoeShaw101** [comment]
@Ari1c 这个sdk只有在chrome端才能用吗，我的client是支付宝小程序

**Comment by Ari1c** [comment]
也不是啊，高版本浏览器都是可以的啊，小程序暂时只支持直传，https://help.aliyun.com/document_detail/92883.html?spm=a2c4g.11186623.6.1269.354460casu6Ll9

**Comment by Ari1c** [comment]
![image](https://user-images.githubusercontent.com/33024188/58677046-0dffb500-838d-11e9-9dcd-b2a4711a630c.png)
你在控制台check一下跨域配置里headers有配置x-oss-request-id字段

**Comment by ZoeShaw101** [comment]
@Ari1c 跨域设置加了的，还是不行。
另外小程序暂时只支持直传的例子：https://help.aliyun.com/document_detail/92883.html?spm=a2c4g.11186623.6.1269.354460casu6Ll9
适用于支付宝小程序么？

```
var key = 'image.jpg'
        my.uploadFile({
            url: 'https://ocr-image-bucket.oss-cn-shanghai.aliyuncs.com', //ocr image bucket host
            fileType: 'image',
            fileName: key,
            filePath: path,
            formData: {
                key: '${filename}',
                policy: '<>',
                OSSAccessKeyId: '<>',
                success_action_status: '200',
                signature: '<>'
            },
            success: (res) => {
              my.alert({ content: 'success info: ' + res.data });
              //todo 取识别结果
            },
        });
```
我这边也试了下支付宝小程序直传这个方式，oss返回400:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>IncorrectNumberOfFilesInPOSTRequest</Code>
  <Message>POST requires exactly one file upload per request.</Message>
  <RequestId>5CF091D883464DAC560BBF9B</RequestId>
  <HostId>ocr-image-bucket.oss-cn-shanghai.aliyuncs.com</HostId>
</Error>
```

**Comment by richard1122** [comment]
在云函数里面用 putStream 也遇到了一样的报错，执行环境是阿里云的香港 node8 云函数

**Comment by Ari1c** [comment]
@ZoeShaw101 小程序直传你要保证你的bucket是读写权限的（但不建议），不是读写权限的话是要设置policy,ak,signature的

**Comment by Ari1c** [comment]
@ZoeShaw101 https://help.aliyun.com/document_detail/127260.html?spm=a2c4g.11186623.6.1487.24483ccc3q7qLh 这是支付宝小程序的情况

**Comment by Ari1c** [comment]
@richard1122 你能描述具体点吗，也是在小程序中使用我们的sdk是吗（小程序目前支持直传）

**Comment by richard1122** [comment]
@Ari1c 是在云函数里直接 put stream 时候传一个 node 的 buffer

**Comment by Ari1c** [comment]
@richard1122 你的bucket有设置跨域规则（x-oss-request-id字段），或者把报错信息解一下图

**Comment by shadow88sky** [comment]
我也遇到同样的错误，node端 流式上传文件，报这个错误
![image](https://user-images.githubusercontent.com/8297339/64335310-224af200-d00d-11e9-96d9-7f7836794b91.png)
![image](https://user-images.githubusercontent.com/8297339/64335351-34c52b80-d00d-11e9-9b05-8a66145b7a17.png)

**Comment by shadow88sky** [comment]
如果是读取本地文件上传 则正常

**Comment by shadow88sky** [comment]
进去调试 ,里面报 
![image](https://user-images.githubusercontent.com/8297339/64336150-e6189100-d00e-11e9-8c28-ca2990867a4c.png)

**Comment by hainee** [comment]
到现在任然在报错
