### ISSUE TITLE
视频截帧

### ISSUE THREAD

**Issue by helibin** [ali-sdk/ali-oss#636]
这是我的视频地址:
http://resimg.iqeq01.com/webapires/baby/vedio/2018/07/19/c0d281446bf44ac2bf37daf1d2749af0.mp4

这是我截帧的地址:
http://resimg.iqeq01.com/webapires/baby/vedio/2018/07/19/c0d281446bf44ac2bf37daf1d2749af0.mp4?x-oss-process=video/snapshot,t_1000,f_png
结果是这样 倾倒的
![image](https://user-images.githubusercontent.com/14595752/59416484-05c96000-8df8-11e9-866d-b6f818b18424.png)

期望截的图是正向的，求解

**Comment by Ari1c** [comment]
@helibin https://help.aliyun.com/document_detail/64555.html?spm=a2c4g.11174283.6.1375.612e7da2azM00a
加上参数ar_auto,
http://resimg.iqeq01.com/webapires/baby/vedio/2018/07/19/c0d281446bf44ac2bf37daf1d2749af0.mp4?x-oss-process=video/snapshot,t_200,f_png,ar_auto
