### ISSUE TITLE
use node SDK UnknowError: Unknow error, status: 400

### ISSUE THREAD

**Issue by argusonly** [ali-sdk/ali-oss#638]
await client.multipartUpload(filename, file, {
            async progress (percentage, cpt, res) {
              _this.percent = Math.floor(percentage * 100) 
              if (cpt !== undefined) {
                this.content = JSON.stringify(cpt)
              }
            }
          })

![image](https://user-images.githubusercontent.com/28346196/59500538-3bd81400-8ecc-11e9-8684-7b0b1368681a.png)
上传过程中 频繁出现。。

**Comment by PeterRao** [comment]
截图看下浏览器的network请求返回状态码，及响应内容

**Comment by argusonly** [comment]
![image](https://user-images.githubusercontent.com/28346196/59573315-efb3ec00-90e4-11e9-908a-cb1f99c7a346.png)
还出现了 504 
![image](https://user-images.githubusercontent.com/28346196/59573329-06f2d980-90e5-11e9-8559-f03ae10f3a12.png)
![image](https://user-images.githubusercontent.com/28346196/59573335-107c4180-90e5-11e9-9777-5471169e7dfc.png)

**Comment by argusonly** [comment]
> ![image](https://user-images.githubusercontent.com/28346196/59573315-efb3ec00-90e4-11e9-908a-cb1f99c7a346.png)
> 还出现了 504
> ![image](https://user-images.githubusercontent.com/28346196/59573329-06f2d980-90e5-11e9-8559-f03ae10f3a12.png)
> ![image](https://user-images.githubusercontent.com/28346196/59573335-107c4180-90e5-11e9-9777-5471169e7dfc.png)

**Comment by argusonly** [comment]
> ![image](https://user-images.githubusercontent.com/28346196/59573315-efb3ec00-90e4-11e9-908a-cb1f99c7a346.png)
> 还出现了 504
> ![image](https://user-images.githubusercontent.com/28346196/59573329-06f2d980-90e5-11e9-8559-f03ae10f3a12.png)
> ![image](https://user-images.githubusercontent.com/28346196/59573335-107c4180-90e5-11e9-9777-5471169e7dfc.png)

@PeterRao

**Comment by argusonly** [comment]
@PeterRao 
![image](https://user-images.githubusercontent.com/28346196/59573577-3fdf7e00-90e6-11e9-8a77-7c4ccca266dd.png)

**Comment by PeterRao** [comment]
感觉这个你用中间的server，做了处理，返回的内容，都不是oss server应该返回的东西。
