### ISSUE TITLE
ts NormalSuccessResponse接口定义缺少字段啊

### ISSUE THREAD

**Issue by xylmoon** [ali-sdk/ali-oss#640]
6.1.1

` let { res: { requestUrls}  } = await this.client.copy(`image/${url}`.replace(`${this.ConfigService.ossConfig.dirPath}/`, ''), url);`

类型“NormalSuccessResponse”上不存在属性“requestUrls”。

看了一下接口定义
`    interface NormalSuccessResponse {
        // response status
        status: number;
        // response headers
        headers: object; // todo the object in detail
        // response size
        size: number;
        //  request total use time (ms)
        rt: number;
    }`

实际上返回值不止这些啊，接口定义不全，我需要用到res.requestUrls ，但声明文件没有定义。我先自己解决了哈，

**Comment by PeterRao** [comment]
不要使用type/@ali-oss
