### ISSUE TITLE
pipe express的req到putstream响应超时

### ISSUE THREAD

**Issue by artemis-my** [ali-sdk/ali-oss#641]
采用node sdk，我用node代理了文件上传的请求然后pipe到oss的putstream上，这种方式可以吗，目前得到的响应都是{"name":"ResponseTimeoutError","status":-1,"code":"ResponseTimeoutError"}。文件也确实上传失败。
```
app.post('/demo', (req, res) => {
    client.putStream('object', req).then(res => {
        console.log(res);
    }).catch(e => {
        console.log(e)
    })
})
```

**Comment by Ari1c** [comment]
@artemis-my 不可以这么使用，如下是我们提供的流式上传https://help.aliyun.com/document_detail/111267.html?spm=a2c4g.11186623.6.1107.146b65d3RZEVil

**Comment by artemis-my** [comment]
@Ari1c 后面我通过pipe方式上传成功了，之前失败那里，我在options中提供了contentLength属性，这个处理好像有问题，后面直接采用chunked encoding方式上传成功了。提供contentLength为何失败还有待debug。
