### ISSUE TITLE
client.put返回值没有带上headers

### ISSUE THREAD

**Issue by 21paradox** [ali-sdk/ali-oss#642]
* **Browser Version or Node Version**: chrome
* **ali-oss Version**: 6.1.1
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:5D148BCDBB04C51EABF54605

在浏览器调用client.put(key, file).then((result) => {})

返回的result.res.headers是空的object，控制台请求的返回结果是有content-md5的，希望能够加上返回的headers

![image](https://user-images.githubusercontent.com/6622122/60255234-f2db8300-9901-11e9-9e35-77fe79d3e566.png)

**Comment by Ari1c** [comment]
@21paradox 你具体怎么实例化client的

**Comment by 21paradox** [comment]
就是按照文档来的
```js
export const ossClient = new OSS({
  region: ALI_OSS_KEYS.region,
  accessKeyId: ALI_OSS_KEYS.AccessKeyId,
  accessKeySecret: ALI_OSS_KEYS.AccessKeySecret,
  bucket: ALI_OSS_KEYS.bucket,
});

```

**Comment by Ari1c** [comment]
@21paradox 你的这些都是配置在环境变量里面是吗

**Comment by Ari1c** [comment]
@21paradox 是按照文档一步步来进行操作的话，返回会包含headers

**Comment by Ari1c** [comment]
@21paradox let OSS = require('ali-oss');const client = new OSS({你的配置项})；client.put('obj',file).then()
这样就能得到你想要的headers里面的md5

**Comment by guoxiangwen** [comment]
@Ari1c 请问下 服务端签名 直传 也是用这个包吗？

**Comment by Ari1c** [comment]
@guoxiangwen 你说的包指的是ali-oss，需要的

**Comment by 21paradox** [comment]
跨域问题, fetch确实拿不到，不是sdk的问题。我关闭了吧。

**Comment by gaohuixx** [comment]
> 跨域问题, fetch确实拿不到，不是sdk的问题。我关闭了吧。
浏览器里直接向oss传文件，肯定是跨域啊，那就是说在浏览器里这个api永远都拿不到响应头呗。这么大的问题怎么不在文档里写出来呢
