### ISSUE TITLE
求助着急！ali-oss 线上访问报错 Uncaught TypeError: Cannot create property 'createCredentials' on string '0'

### ISSUE THREAD

**Issue by web-Marker** [ali-sdk/ali-oss#647]
"ali-oss": "^6.0.1",
const OSS = require('ali-oss')
 let client = new OSS(i)

本地运行dev build都不会报错，线上访问就出错，着急求助

**Comment by Ari1c** [comment]
@web-Marker  http://gosspublic.alicdn.com/aliyun-oss-sdk-6.1.1.min.js 在你的页面模板尝试下引入cdn的版本试试，版本改成6.0.1，你的业务逻辑是不是又把ali-oss这个包又压缩了？

**Comment by web-Marker** [comment]
> @web-Marker http://gosspublic.alicdn.com/aliyun-oss-sdk-6.1.1.min.js 在你的页面模板尝试下引入cdn的版本试试，版本改成6.0.1，你的业务逻辑是不是又把ali-oss这个包又压缩了？

确认了，webpack UglifyJSPlugin 二次压缩引起的错误，已解决
