### ISSUE TITLE
 真的有 ToC 的使用案例是在浏览器端直接写 secret 的吗?

### ISSUE THREAD

**Issue by zug89144** [ali-sdk/ali-oss#648]
在 README 内写到可以在浏览器端直接写 secret 来获取 OSS 的东西

想请问当初允许这样设计的原因是? (唯一可以想到的是在 ToB 的应用场景阿)

https://github.com/ali-sdk/ali-oss#basic-usage-1

**Comment by Ari1c** [comment]
@zug89144 首先这个是一个临时的ak，因为我们有node端，建议以STS的形式来存放token是有有效期的，当然我们也有浏览器端，所以也可以把ak这么来写入

**Comment by PeterRao** [comment]
@Ari1c browser时 给用户打个warning
