### ISSUE TITLE
我们整个项目编写时需要有回调，但sdk 是用 await处理异步。引起我下载文件时，还没有完就是读文件了。

### ISSUE THREAD

**Issue by mrlong** [ali-sdk/ali-oss#654]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

**Comment by mrlong** [comment]
![image](https://user-images.githubusercontent.com/225022/65829219-75932600-e2d5-11e9-977b-b1ecfcdb8465.png)

见图。

**Comment by PeterRao** [comment]
你可以使用 getStream 然后 pipe 到你本地文件，然后监听 stream 的 finish 事件。这个get只保证请求完成，不保证流写入完成。
