### ISSUE TITLE
Delete object that not exists returns a 204 no content success response

### ISSUE THREAD

**Issue by ricky11** [ali-sdk/ali-oss#657]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

I have posted this public comment here :
https://connect.alibabacloud.com/suggestion/2839?spm=5176.11425037.sug_all.2.1372218e4y0ueh

Using this above SDK we tested that if we delete object that exists we get a 204 no content success response. If we delete a object that DOES NOT exist we also get 204 no content success response.

it is hard for developer to know how to grammatically throw a error to the user if the object deleted does not exist.  It is different from deleteMulti, as deleteMulti will return a error or success.

[Solution]:

Provide correct response code ERROR 405 (method not allowed)  OR 403 error if object not exist for Delete Api.

**Comment by PeterRao** [comment]
DELETE operation should be idempotent. 204 mean delete operation success regardless of whether object exists.

https://stackoverflow.com/questions/6439416/deleting-a-resource-using-http-delete

**Comment by ricky11** [comment]
I see. thank you.
