### ISSUE TITLE
在使用listBucket的接口时候报错Error: humanize-ms("2019-10-16T03:36:32Z") result undefined

### ISSUE THREAD

**Issue by Adherentman** [ali-sdk/ali-oss#662]
<img width="856" alt="WX20191016-104626@2x" src="https://user-images.githubusercontent.com/26477346/66883954-42a19f80-f002-11e9-964c-f2b706b50ffa.png">

```typescript
export default class OSSController extends Controller {
  public async getAllBucket() {
    try {
     const sts = await generateSTS();
     const client = new OSS({
       accessKeyId: sts.Credentials.AccessKeyId,
       accessKeySecret: sts.Credentials.AccessKeySecret,
       stsToken: sts.Credentials.SecurityToken,
       region: 'oss-cn-hangzhou',
       timeout: sts.Credentials.Expiration,
     });
     const res = await client.listBuckets(null);
     console.log(res);
    } catch (error) {
      throw new Error(error);
    }
  }
}

```
* **Browser Version or Node Version**: 12
* **ali-oss Version**: 6.1.1
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**: 5DA6844D4B39ED3737FE5BEC

**Comment by PeterRao** [comment]
timeout 不符合格式
`
timeout:  {String|Number} instance level timeout for all operations, default is 60s.
`
