### ISSUE TITLE
put上传文件方法是否可以指定ACL？

### ISSUE THREAD

**Issue by myaisv** [ali-sdk/ali-oss#665]
在iOS\Android SDK的put上传文件方法中均可以通过“x-oss-object-acl”直接指定ACL，例如：
` putRequest.objectMeta = ["x-oss-object-acl":"public-read"]`

Nodejs 中的[put](https://github.com/ali-sdk/ali-oss#putname-file-options)方法是否有类似的特性？

**Comment by PeterRao** [comment]
iOS\Android 请移步[官网](https://help.aliyun.com/document_detail/32042.html?spm=a2c4g.11186623.6.1082.347d69cbM7d4K0)或者 对应的 github 咨询

**Comment by dumplinginsoda** [comment]
我也有相似疑问。

查询api文档及sdk代码后，发现是可行的。po在这个issue下面，希望可以帮到别的人 :) 

文档: https://help.aliyun.com/document_detail/31986.html?spm=5176.11065259.1996646101.searchclickresult.2b567ce2wnxwbM
代码: https://github.com/ali-sdk/ali-oss/blob/master/lib/object.js#L114
