### ISSUE TITLE
new OSS().copy() 现在用不了吗？？

### ISSUE THREAD

**Issue by Eusen** [ali-sdk/ali-oss#674]
调用 copy().then() 报这个错
`TypeError: Method Promise.prototype.then called on incompatible receiver [object Object]`

代码中定位到这个错误：
![image](https://user-images.githubusercontent.com/14822175/67474606-52b32200-f687-11e9-9b40-e2fadb1018a9.png)

**Comment by Eusen** [comment]
前段时间还能用，最近用直接报错

**Comment by PeterRao** [comment]
给出完整代码

**Comment by Eusen** [comment]
完整代码就是
``` ts
const instance = new OSS({...});
instance.copy('path1', 'path2');
```
还需要再怎么完整？就这个方法调用出错了。。

**Comment by Eusen** [comment]
？？？啥意思，关闭意思是没有错误吗？

**Comment by Eusen** [comment]
我图上贴的代码是 ali-oss 代码库里的内容，不是我自己的代码

**Comment by PeterRao** [comment]
https://github.com/ali-sdk/ali-oss/issues/653 按这个方法解决

**Comment by Eusen** [comment]
好的 谢谢！我试一下
