### ISSUE TITLE
node 端如何实现图片处理持久化?

### ISSUE THREAD

**Issue by yyman001** [ali-sdk/ali-oss#676]
* **Browser Version or Node Version**:
* **ali-oss Version**: 5.0.0
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

node 端如何实现图片处理持久化?
看了官方各种文档, 只有
Java SDK
Python SDK
Go SDK

还是说这个js 是有另外的方法可以支持?谢谢
使用js 签名方法也没有具体使用demo, 签名一直不对

**Comment by ZQ-jhon** [comment]
```typescript
fs.writeFile(path, ossResult.content as Buffer)
```
