### ISSUE TITLE
[建议]增加基础工具函数

### ISSUE THREAD

**Issue by alexchen1875** [ali-sdk/ali-oss#677]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

sdk中应该提供基本的工具函数:
1,指定prefix下的文件个数,某个object的总体大小(包含子object),用于业务中用户单独的使用空间,现在也可以通过marker解决,但其实没太大必要都自己是实现这样的基础功能.
2,支持按时间列出object.方便管理.现在要一页页根据meta数据去找.非常不友好.

**Comment by PeterRao** [comment]
sdk 只是对 公共api https://help.aliyun.com/document_detail/31947.html 的基本包装，及错误异常情况处理。如果公共 api，不实现上述功能，SDK 也不太会去实现。你所说的功能还是属于业务逻辑，需要开发者自己去实现，而且也很容易实现。
