### ISSUE TITLE
使用ali-oss+elment upload上传超大文件，chrome浏览器崩溃，而其他浏览器能正常上传的问题

### ISSUE THREAD

**Issue by susuW** [ali-sdk/ali-oss#680]
如题，
element的upload组件结合阿里云上传，只要上传的文件超过100M，谷歌浏览器就会直接崩溃。换了firefox上传，则能上传成功，请问该如何解决？

jdk版本为6.1.1,node版本为10.15.3

**Comment by susuW** [comment]
![image](https://user-images.githubusercontent.com/38358438/68015811-fd51c300-fccd-11e9-9cff-2901c003b7bf.png)

**Comment by PeterRao** [comment]
单独写个demo尝试下，排序框架影响。

**Comment by liuxiaogang** [comment]
这个确实是有问题的，目前还是没解决，在 Safari 里面上传是 OK，文件大于 100M 基本就会有问题

**Comment by jialinNEU** [comment]
> 如题，
> element的upload组件结合阿里云上传，只要上传的文件超过100M，谷歌浏览器就会直接崩溃。换了firefox上传，则能上传成功，请问该如何解决？
> 
> jdk版本为6.1.1,node版本为10.15.3

请问这个问题现在有解决吗？谢谢
