### ISSUE TITLE
Refused to set unsafe header "User-Agent"

### ISSUE THREAD

**Issue by satrong** [ali-sdk/ali-oss#692]
**Browser Version or Node Version**: 78.0.3904.108（正式版本）
**ali-oss Version**: 6.2.1
**Mini Showcase Repository**:
**Network Resoponse Header x-oss-request-id**:

使用 `import OSS from 'ali-oss/lib/browser';` 方法引入ali-oss库在上传图片的时候会抛错，错误信息：
> Refused to set unsafe header "User-Agent"

如果使用 `import OSS from 'ali-oss';` 方法引入ali-oss库则不会。但使用这种方式引入的话最后js会增加**近70kb**的代码（主要是ali-oss这个库太大了）。

目前看了这个报错本身与ali-oss没有直接关系，与webpack的`node-libs-browser`使用的`stream-http`版本有关。

但建议 ali-oss 在打包时候也分成两个模块，一个是给node用的，一个是给browser用的，这样就不会依赖webpack引用的stream-http。

**Comment by PeterRao** [comment]
暂时无法这么使用，需要整个架构进行调整。
