### ISSUE TITLE
名称末尾带 - 符号的文件无法更新成功

### ISSUE THREAD

**Issue by JE-lee** [ali-sdk/ali-oss#693]
```javascript
async () => {
const ossClient = new ALIOSS(ossConfig);
let content = '示例文字111111111'
await ossClient.put('http://xxxxxxx/test-.bpmn', new Buffer(content))

content = '示例文字222222'
await ossClient.put('http://xxxxxxx/test-.bpmn', new Buffer(content))
}
```

如上，第一次创建该文件后，oss上的内容是正确的，
第二次调用的时候无法更新，虽然返回200但是oss上的内容还是第一次上传的内容。

**将文件名末尾的 - 去掉，重新测试，就正常**

* **Browser Version or Node Version**: chrome latest
* **ali-oss Version**:  6.0.1
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

**Comment by PeterRao** [comment]
问题无法复现，能否get下文件内容打印下，进行截图反馈。
另外你上传的 object 名称不符合oss的要求。
![image](https://user-images.githubusercontent.com/1611647/70107887-cb43d000-1682-11ea-9a38-88765dbd06dd.png)
