### ISSUE TITLE
上传文件，路径发生了转义

### ISSUE THREAD

**Issue by xxyGoTop** [ali-sdk/ali-oss#705]
问题:

使用ali-oss的put上传文件，发现路径发生转义

代码：
```js
  const promiseQueue = files.map((file) => {
    const from = path.join(fromPath, file);
    const to = path.join(toPath, file);

    console.log('ossput', `${from} => ${to}`);
    return ossClient.put(to, from);
  });
```
上传成功图：

![image](https://cdn.nlark.com/yuque/0/2019/png/103362/1575871010172-c849a684-714b-4560-a575-45babb4d5725.png)

阿里云展示图:

![image](https://cdn.nlark.com/yuque/0/2019/png/103362/1575871086365-64b7a97b-b392-426e-b6e0-51f91d58df24.png)

路径:
![image](https://cdn.nlark.com/yuque/0/2019/png/103362/1575871109537-348f7f5a-874e-43cd-8693-d0f6ba65ed0a.png)

**Comment by PeterRao** [comment]
object 名称是对的。
只是用http访问时，特殊字符 `\` 会被转义成 %5，否则不符合http协议规范

**Comment by xxyGoTop** [comment]
window系统路径 **/**

**Comment by PeterRao** [comment]
自行替换成 /。sdk不会做这种处理的。
