### ISSUE TITLE
Pagination (NextMarker) doesn't work on Object Operations .list(query[, options])

### ISSUE THREAD

**Issue by neilspink** [ali-sdk/ali-oss#706]
- node version v10.17.0
- ali-oss v6.3.1

Next marker which is needed for object pagination in OSS is being ignored and not working as documented in API here:
https://github.com/ali-sdk/ali-oss#listquery-options

My NodeJS test program:
https://github.com/neilspink/ali-fc/blob/oss-pagination/oss-pagination/list-files.js

```
const OSS = require('ali-oss');

const oss_region = 'oss-cn-shanghai';
const bucket_name = '<yourBucketName>';
const object_prefix = '';
const accessKeyId = '<yourAccessKeyId>';
const accessKeySecret = '<yourAccessKeySecret>';

const store = new OSS({
    region: oss_region,
    internal: false,
    secure: true,
    accessKeyId: accessKeyId,
    accessKeySecret: accessKeySecret,
    bucket: bucket_name
});

async function listFiles2() {

    let truncated = false;
    let nextMarker = '';

    do {
        const objectsRequest = {
            Marker: nextMarker,
            Prefix: object_prefix,
            MaxKeys: 100
        };

        console.log(objectsRequest);

        const result = await store.list(objectsRequest);

        console.log(result.nextMarker);
        console.log('************************************');

        truncated = result.isTruncated;
        nextMarker = result.nextMarker;
    } while (truncated === true)
}

listFiles2();
```

**Comment by PeterRao** [comment]
![image](https://user-images.githubusercontent.com/1611647/70792029-57689c80-1dd3-11ea-82bc-1a506b0c8ab4.png)
query params should be lower case

**Comment by neilspink** [comment]
It works thanks. I copied the code from a CSharp example https://partners-intl.aliyun.com/help/doc-detail/91923.htm

One last question please, max-keys produces a SyntaxError: Unexpected token -
how do we work around that?

**Comment by neilspink** [comment]
Thanks, got it, now it works, i.e.

```
                const objectsRequest = {
                        marker: nextMarker,
                        ['max-keys']: 10
                }
```

I had copied code from a [CSharp example]( https://partners-intl.aliyun.com/help/doc-detail/91923.htm) and not checked against the NodeJS SDK documentation
