### ISSUE TITLE
不支持 x-oss-server-side-encryption  header设置

### ISSUE THREAD

**Issue by chenquincy** [ali-sdk/ali-oss#715]
* **Browser Version or Node Version**: v11.12.0
* **ali-oss Version**: 6.0.2
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

使用 put 方法和 multipartUpload 方法上传文件至私密桶，添加 `x-oss-server-side-encryption` header 时报错：
``` 
InvalidArgumentError: x-oss-server-side-encryption header is not supported for this operation.
```
但是 [文档](https://www.alibabacloud.com/help/zh/doc-detail/31871.htm#title-26o-9ll-9zn) 中显示是支持的
headers取值：
``` json
"headers": {
  "x-oss-server-side-encryption": "KMS"
}
```

**Comment by Pedestrian93** [comment]
能贴下详细代码吗

**Comment by chenquincy** [comment]
@Pedestrian93  
大概代码如下
``` javascript
const uploader = new AliOss({
    bucket,
    accessKeyId,
    accessKeySecret,
    stsToken,
    region,
    timeout: 100000000
})
uploader.put(objectKey, file, {
  headers: {
    "x-oss-server-side-encryption": "KMS"
  }
})
```

**Comment by chenquincy** [comment]
@Pedestrian93 
[initMultipartUpload](https://github.com/ali-sdk/ali-oss#initmultipartuploadname-options) 中有说明到 `x-oss-server-side-encryption` 配置，但是 [multipartUpload](https://github.com/ali-sdk/ali-oss#multipartuploadname-file-options) 中却没有，在使用的时候通过 headers 传递同样会报错。

**Comment by Pedestrian93** [comment]
简单 put 和 initMultipartUpload 应该是支持的

**Comment by chenquincy** [comment]
@Pedestrian93  那么为什么 `multipartUpload` 不支持，这应该是个实现上的bug？我看了下源码，`multipartUpload` 实际上就是几个方法的组合使用，先 `initMultipartUpload` 再执行上传，特殊 `headers` 在 `initMultipartUpload` 后应该被过滤，后面的步骤不使用，但实际上没有

**Comment by chenquincy** [comment]
另外，我在 Node 端使用 `put` 方法也会报同样的错误，浏览器端没有尝试，但应该也会报错。

**Comment by chenquincy** [comment]
@Pedestrian93 能否告知这个问题大概什么时候能发版修复？

**Comment by Pedestrian93** [comment]
明天可以发布

**Comment by chenquincy** [comment]
@Pedestrian93  我来催更了

**Comment by PeterRao** [comment]
> @Pedestrian93 我来催更了

代码 还在review

**Comment by chenquincy** [comment]
@PeterRao   明天能发版吗

**Comment by PeterRao** [comment]
已经发布6.4.0
