### ISSUE TITLE
electron 5.0.2 + node 12: getStream is not a function

### ISSUE THREAD

**Issue by Tianzhao0126** [ali-sdk/ali-oss#723]
getLatestVer: async (callback) => {
    const configJson = JSON.parse(config);
    const fileList = await store.list({
      'max-keys': 5,
    });
    if (fileList.objects.length > 0) {
      const latestVer = fileList.objects[0].name.substring(0, 5);
      if (latestVer < configJson.version) {
        callback({ updateAvail: true, latestVer });
        const buffer = await store.getStream(fileList.objects[0].name);  // getStream is not a function
        buffer.stream.pipe(fs.createWriteStream(path.resolve(__dirname, '..\\..\\test.zip')));
      } else {
        callback({ updateAvail: false });
      }
    } else {
      callback({ updateAvail: false });
    }
  },

想以Stream方式下载zip文件,但运行以上代码会报store.getStream is not a function

**Comment by zlyyyy** [comment]
老哥你是怎么解决的

**Comment by Tianzhao0126** [comment]
> 老哥你是怎么解决的

当时没学好electron...刚po完就发现我在渲染进程里面去做流下载...然后就赶紧close掉了
