### ISSUE TITLE
拖拽上传的图片文件无法

### ISSUE THREAD

**Issue by beginToday** [ali-sdk/ali-oss#724]
![image](https://user-images.githubusercontent.com/15193509/71761426-5f64b980-2f05-11ea-9527-06fc7634b1c6.png)

下面是上传的文件

![image](https://user-images.githubusercontent.com/15193509/71761437-760b1080-2f05-11ea-8070-f3f7b1b53ae4.png)

**Comment by PeterRao** [comment]
给一下具体实现代码demo或者最小复现的仓库地址。
