### ISSUE TITLE
浏览器分片上传multpartUpload()文件过程中删除文件未报错

### ISSUE THREAD

**Issue by zhyjor** [ali-sdk/ali-oss#727]
现象：浏览器上传文件过程中删除文件未报错，上传看起来是继续进行，但是最后完整性校验的时候，会提醒EntityTooSmallError错误

复现条件：使用multpartUpload上传一个任意大小文件，在上传未结束的时候删除或移动、修改文件，上传会继续进行，最终达到100%，然后报
```
code: EntityTooSmall, 
message: Your proposed upload smaller than the minimum allowed size., 
name: EntityTooSmallError, 
```
分析：看日志会发现这个时候其实是空的数据包，content-length是0，因此触发了这个报错

建议：能否在上传过程中判断空包，判断文件被修改

**Comment by PeterRao** [comment]
这个判断不出来的。而且不同的浏览器实现方式不一样。
建议在页面上给用户提醒下，上传过程中，不要修改或者移动文件。
