### ISSUE TITLE
多次调用multipartUpload方法导致上传网络请求失败

### ISSUE THREAD

**Issue by Pasoul** [ali-sdk/ali-oss#728]
* **Browser Version or Node Version**: Chrome 版本 76.0.3809.100  Node：12.9.1
* **ali-oss Version**:  "ali-oss": "^6.4.0"
* **Mini Showcase Repository**: 
* **Network Resoponse Header x-oss-request-id**:

页面上有四个地方可以上传图片，快速连续上传四张，就会导致有的请求失败了，如下图所示
![image](https://user-images.githubusercontent.com/22902187/71897982-7a505b80-319b-11ea-8861-90fc16680aba.png)
![image](https://user-images.githubusercontent.com/22902187/71898242-242fe800-319c-11ea-83ab-4fb82860746d.png)

**Comment by Pasoul** [comment]
更新：上传进度一直卡在0.5，上传一张图片（2.3M）也会卡住

**Comment by PeterRao** [comment]
你是往哪个region传输，ping 下 域名看下网络情况
