### ISSUE TITLE
A question of setting routing rule by PutBucketWebsite

### ISSUE THREAD

**Issue by shuo-ouyang** [ali-sdk/ali-oss#730]
* **Browser Version or Node Version**: 13.5.0
* **ali-oss Version**: 6.4.0
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

I deploy static webpages on aliyun OSS and use **PutBucketWebsite** to upload files. However, I could not find a way to set **routing rule(SupportSubDir)** by means of passing parameters to **PutBucketWebsite** function. In other words, whenever I upload files to OSS, the **SupportSubDir** option will be changed to false because I do not set associated options. To keep **SupportSubDir** always true, I have to set the routing rule manually in function(construct xml string), as shown below, but it seems graceless. So is there a beautiful way to set routing rule by **PutBucketWebsite**?

#### origin code
```javascript
...
  config.index = config.index || 'index.html';
  let xml = `${'<?xml version="1.0" encoding="UTF-8"?>\n<WebsiteConfiguration>\n' +
    ' <IndexDocument><Suffix>'}${config.index}</Suffix></IndexDocument>\n`;
  if (config.error) {
    xml += `<ErrorDocument><Key>${config.error}</Key></ErrorDocument>\n`;
  }
  xml += '</WebsiteConfiguration>';
...
```

#### modified code
```javascript

  config.index = config.index || 'index.html';
  let xml = `${'<?xml version="1.0" encoding="UTF-8"?>\n<WebsiteConfiguration>\n' +
    ' <IndexDocument><Suffix>'}${config.index}</Suffix><SupportSubDir>true</SupportSubDir><Type>0</Type></IndexDocument>\n`;
  if (config.error) {
    xml += `<ErrorDocument><Key>${config.error}</Key></ErrorDocument>\n`;
  }
  xml += '</WebsiteConfiguration>';
  ...
```

**Comment by PeterRao** [comment]
'SupportSubDir' is newly released features. 'ali-oss' is not support yet.

**Comment by Litt1e0range** [comment]
@PeterRao Thanks for your response. I will re-write my code when `ali-oss` supports this new feature.

**Comment by PeterRao** [comment]
https://github.com/ali-sdk/ali-oss#putbucketwebsitename-config-options
