### ISSUE TITLE
Question 0 

### ISSUE THREAD

**Issue by ricky11** [ali-sdk/ali-oss#735]
Is this the official NODE SDK for ali-oss?

aliyun told me this is a third party sdk, but its mentioned in their documentation, so we are confused

**Comment by PeterRao** [comment]
Yes, it's  the official NODE SDK, you can see the [document](https://www.alibabacloud.com/help/doc-detail/32068.htm#concept-32068-zh) on aliyun sdk website

**Comment by ricky11** [comment]
Hi Peter, Thanks for your reply.

What about this : https://github.com/aliyun/openapi-core-nodejs-sdk

this is also mentioned in the alibaba documentation ? 

Also ali-oss is 300kb gziped, is their a plan to modernize the codebase as the package is very large.

tks
