### ISSUE TITLE
TypeError: "s.data is null" in version 6.5.1 and 6.5.0,but 6.0.0 is ok

### ISSUE THREAD

**Issue by caozhzh** [ali-sdk/ali-oss#740]
when client.multipartUpload called in 6.5.1 or 6.5.0,sometime will catch error:
TypeError: "s.data is null" in initMultipartUpload
but http response code is 200, the error happened when file name within uploads parameter
![6 5 1](https://user-images.githubusercontent.com/304496/74203967-573e2d80-4cac-11ea-9bf4-fab52f4bc80f.png)

bug when using 6.0.0,even file name with uploads parameter will be ok, and two more http request be sent
![Screenshot from 2020-02-11 08-27-32](https://user-images.githubusercontent.com/304496/74204180-14c92080-4cad-11ea-91a6-a01812a36825.png)

**Comment by PeterRao** [comment]
![image](https://user-images.githubusercontent.com/1611647/74399702-9f00b880-4e56-11ea-9266-a0b6aa128aea.png)
can you show the response content for the post method

**Comment by PeterRao** [comment]
https://github.com/ali-sdk/ali-oss/issues/753
