### ISSUE TITLE
在Windows端会小几率出现不存在的文件却返回存在

### ISSUE THREAD

**Issue by nailao** [ali-sdk/ali-oss#743]
查询文件是否存在的函数
```
const queryFile = async (client, file) => {
    return await client.get(file.name).then(()=> true).catch(() => false);
};
```

![image](https://user-images.githubusercontent.com/19665552/75253554-b73ee300-5819-11ea-9172-21521d6ee8a6.png)

按照上图，我查询L1-7-CW/DZBH/index.2f3871d9.js（文件名是随机的）这个文件应该是百分百找不到的，但是我在Windows执行时有几率会返回找到文件，可是这个文件根本不存在OSS里面。

ali-oss是安装的最新版。

**Comment by PeterRao** [comment]
把requestid 打印下发下

**Comment by nailao** [comment]
> 把requestid 打印下发下

client.get不返回requestid，倒是有个requestUrls，这个返回的结果是
requestUrls: [ '域名/L1-7-CW/DZBH/index.2f3871d9.js' ]
然后打开这个地址是找不到文件，到OSS去找也确实不存在。

我现在不用get方法判断文件不存在了，通过client.getObjectMeta这个方法，现在一切正常。
