### ISSUE TITLE
windows平台下，electron环境上传文件到OSS异常

### ISSUE THREAD

**Issue by ainuo5213** [ali-sdk/ali-oss#745]
你好，我现在遇到个bug，放心这应该不是我代码的问题。我自己在纯node环境测试上传文件到object时，文件确实被上传上去且有数据；但是我在electron里面使用时，上传文件的key和localFile的路径都是对的且打印得出来，并且正确，但是上传到object时没有数据（0kb），文件是空的，但文件确实被上传去了而且我本地文件也有数据。所以你们看看这是否是平台的原因，我电脑是win10 64位的

**Comment by PeterRao** [comment]
可以给一下最小能复现的库，有个我们这边维护的oss browser项目(https://github.com/aliyun/oss-browser)也是用node进行的上传，是能上传成功的。
