### ISSUE TITLE
IE11下引入oss会报错： “strict 模式下不允许分配到只读属性”

### ISSUE THREAD

**Issue by uchihayu** [ali-sdk/ali-oss#747]
![image](https://user-images.githubusercontent.com/12794409/75623188-9512df80-5be2-11ea-8f2d-a2bd13a738b6.png)
![image](https://user-images.githubusercontent.com/12794409/75623219-dc00d500-5be2-11ea-9036-fb96a8e824ac.png)

* **Browser Version or Node Version**:
IE11 + windows 10;   node@10.16.3 + webpack@3.12.0 +vue@2.5.16
* **ali-oss Version**:
6.1.0   npm安装与cdn引入均出现错误
* **Mini Showcase Repository**: 暂无
* **Network Resoponse Header x-oss-request-id**: 暂无

**Comment by PeterRao** [comment]
我们这边没复现出来，是否能给一个线上地址或者最小能复现的仓库地址

**Comment by sevensun1213** [comment]
我这边npm安装6.10.0在IE11下报严格模式的错误，cdn引入可以兼容IE11。

**Comment by ruchenshanghai** [comment]
+1 我使用vue cli 3.0引入也是报错
