### ISSUE TITLE
putStream 不能在业务层主动终止请求

### ISSUE THREAD

**Issue by YuhangGe** [ali-sdk/ali-oss#752]
* **Browser Version or Node Version**: nodejs
* **ali-oss Version**: latest
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

在 #402  这次 pr 中，在第 125 到 130 行，引入了一个中间 `transform`，但并没有使用 `pump` 一类的思路来完备地处理好当 `putStream` 传递进来的 `stream` 出现 close/error 等情况时，将 `transform` 也一并回收，同时通知 urllib 终止。

出于好奇，我看了下 `urllib` 这个库里的源码，在 #402 这次 pr 前，业务层传递给 `putStream` 的 `stream` 对象会被直接传递给 `urllib`，而 urllib 里面使用了 `pump(args.stream, req, handleRequestError)` 来完备地处理好回收事项。但 #402 这次 pr 后，就存上文提到问题了。

这个 issue 之所以被发现，是我传递给 `putStream` 函数的 `stream` 对象会自己检测文件大小，超过 1G 就会主动终止。但却没有办法通知 `urlib` 进行终止，urllib 会在 1分钟后报 timeout 错误。

**Comment by YuhangGe** [comment]
目前使用的临时方案是业务层主动拿到这个 transform，再主动销毁。这样一来 urllib 那边就能主动终止并清理资源了。

````js
const transform = stream._readableState.pipes[0];
transform.destroy(); 
````

由于取用了私有成员变量，在 typescript 里写出来的代码很丑。

**Comment by PeterRao** [comment]
https://github.com/ali-sdk/ali-oss/pull/782 修复，使用最新版本
