### ISSUE TITLE
TypeError: Cannot read property 'Bucket' of null in 6.2.1 6.5.1

### ISSUE THREAD

**Issue by Zhanghailin1995** [ali-sdk/ali-oss#753]
使用multipartUpload 接口报错,经过debug发现是因为multipartUpload 接口调用了initMultipartUpload接口，接口返回了xml信息，但是在parseXML的时候返回了null

**Comment by Zhanghailin1995** [comment]
![报错](https://user-images.githubusercontent.com/49049478/76841141-554f2780-6873-11ea-9ce9-f466ebb440f3.png)
![报错1](https://user-images.githubusercontent.com/49049478/76841276-862f5c80-6873-11ea-85a0-c21f8679aa61.png)

![保存](https://user-images.githubusercontent.com/49049478/76841234-73b52300-6873-11ea-99f9-7cce40fabdaa.png)
str.toString return “”,其实接口返回了xml信息
![返回值](https://user-images.githubusercontent.com/49049478/76841537-e1f9e580-6873-11ea-80d6-048bd80146f0.png)

**Comment by Zhanghailin1995** [comment]
6.0.0版本无此问题

**Comment by PeterRao** [comment]
什么浏览器

**Comment by Zhanghailin1995** [comment]
> 什么浏览器

chrome

**Comment by PeterRao** [comment]
是否有能复现的测试页面，我这边复现不了

**Comment by 23john** [comment]
Chrome浏览器下有这个问题，6.6.0 也有这个问题，可能是跟什么东西冲突，iview 之类的，我单独vue-cli使用没报错

**Comment by Zhanghailin1995** [comment]
> Chrome浏览器下有这个问题，6.6.0 也有这个问题，可能是跟什么东西冲突，iview 之类的，我单独vue-cli使用没报错

似乎是这样的，我现在用的6.5.1没有问题了，似乎是有个Buffer包冲突了之后出现的问题

**Comment by 23john** [comment]
> > Chrome浏览器下有这个问题，6.6.0 也有这个问题，可能是跟什么东西冲突，iview 之类的，我单独vue-cli使用没报错
> 
> 似乎是这样的，我现在用的6.5.1没有问题了，似乎是有个Buffer包冲突了之后出现的问题

6.0.0就没这问题了 估计是SDK的问题

**Comment by PeterRao** [comment]
> > > Chrome浏览器下有这个问题，6.6.0 也有这个问题，可能是跟什么东西冲突，iview 之类的，我单独vue-cli使用没报错
> > 
> > 
> > 似乎是这样的，我现在用的6.5.1没有问题了，似乎是有个Buffer包冲突了之后出现的问题
> 
> 6.0.0就没这问题了 估计是SDK的问题

是否能有个测试页面或者最小复现仓库能给下

**Comment by PeterRao** [comment]
最后我定位到了，是mockjs这个库，在发送responseType: arraybuffer 时，自己封装了一次，把原生的xmlHttpRequest中的responseType变成了 ''，导致了后续无法解析。
解决方案， 两个办法
1. 去除这个mockjs
2. 使用mode: 'fetch' 方式

**Comment by shenyang8888** [comment]
我这边 用的6.10.0  也有这个问题
