### ISSUE TITLE
为什么stsToken的场景下oss accessSecretKey需要服务端传递给客户端然后再通过sdk发出去

### ISSUE THREAD

**Issue by Matrixbirds** [ali-sdk/ali-oss#758]
感觉和aliyun[官方文档](https://help.aliyun.com/document_detail/31927.html?spm=a2c4g.11186623.6.1520.4a4f52afKFJsks)

有点歧义

官方文档里doGet这里并没有下发accessSecretKey给客户端而是通过signature的和callback的方式直接在客户端上传

**Comment by PeterRao** [comment]
一种是服务端签名，一种是客户端签名。
假如你服务端已经签名了，你无需使用sdk了，直接向签名的url直接put数据就行。
客户端签名主要方面实现很多复杂的功能，比如分片上传等。
