### ISSUE TITLE
4.16版本的sdk支持以instance方式，而不是accessKeyId和accessKeySecret的方式访问OSS吗？

### ISSUE THREAD

**Issue by SangoYu** [ali-sdk/ali-oss#761]
* **Node Version 7.10.0:
* **ali-oss Version 4.16.0:

4版本的sdk支持不需要配置accessKeyId, accessKeySecret，而是以ECS的instance去访问oss资源吗？现在如果不配置accessKeyId和accessKeySecret,去初始化OSS client会直接抛错 “require accessKeyId, accessKeySecret”。请问这个后面会支持吗？

**Comment by PeterRao** [comment]
ECS的instance去访问oss资源 这是个什么意思，有代码示例吗

**Comment by SangoYu** [comment]
基于实例的角色授权 @PeterRao

**Comment by PeterRao** [comment]
> 基于实例的角色授权 @PeterRao

这种用法，我这边不太了解，有文档可以参考或者能复现的最小代码库吗

**Comment by wuliupo** [comment]
就是说，可以不暴露 accessKeySecret 到浏览器吗？有没有这种方式？

**Comment by PeterRao** [comment]
两种方案
1. 使用 sdk 的 STS 模式，这种会 生成一个临时ak，保证安全性。
1. 后端签名，前端直接往签名的url进行post
可参考 https://github.com/ali-sdk/ali-oss/blob/master/example/src/template/postObject.html 实现
