### ISSUE TITLE
is mime.default_type meaningful ?

### ISSUE THREAD

**Issue by microJ** [ali-sdk/ali-oss#778]
https://github.com/ali-sdk/ali-oss/blob/fed2ba76a31179a932030a7a4b54fa27947b29de/lib/browser/client.js#L190

`shims/mime.js` 中代码是 `mime@2.x` 的代码，2.x 版本已经去掉了 `mime.default_type`，1.x 中 `default_type` 的值是 `application/octet-stream`，这里为什么要判断是 `application/octet-stream` 的时候将 `mime` 置空呢？

**Comment by PeterRao** [comment]
这个应该之前遗留下来的mime最早是从1.0 弄出来的。后面mime升级后，这个代码没删掉。
本质是想去掉 application/octet-stream 这个，不想额外增加content-type(虽然  application/octet-stream 本身就是默认值)和其他sdk保持一致
