### ISSUE TITLE
求不用generator版 

### ISSUE THREAD

**Issue by jtHwong** [ali-sdk/ali-oss#78]
能不能提供一个无generator，yield版本。

**原因：**
- 比如meteor，这种nodejs只能保持在`0.10.40`的库，不能够很好的支持。
- 比较老的项目，不能升级nodejs，但希望用到aliyun sdk。

**Comment by rockuw** [comment]
callback的版本可以用这个：https://github.com/aliyun-UED/aliyun-sdk-js

**Comment by jtHwong** [comment]
好的 我试试
