### ISSUE TITLE
NodeJS 调用SDK报错 The upload ID may be invalid

### ISSUE THREAD

**Issue by HelloHxz** [ali-sdk/ali-oss#787]
The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed；

我实例化了三个OSSClient.multipartUpload去上传代码，大部分电脑不报错，暂时遇到一个用户报错，请问可能哪里出了问题

**Comment by PeterRao** [comment]
有reqiestid 吗 ，发一下
