### ISSUE TITLE
使用multipartUpload上传报错: fs.stat is not a function;

### ISSUE THREAD

**Issue by callmeguaishu** [ali-sdk/ali-oss#808]
![image](https://user-images.githubusercontent.com/22768593/83870058-26ed3400-a760-11ea-9ecd-ceb4feec9b4b.png)

angular项目中使用multipartUpload上传会报这个错误，正常的put上传可以。自己用fs.stat()函数试过这个路径是ok的

![image](https://user-images.githubusercontent.com/22768593/83870484-ef32bc00-a760-11ea-85dc-db664db71fee.png)

**Comment by PeterRao** [comment]
浏览器需要传入是是File对象或者Blob，前端无法根据路径获取本地文件。
