### ISSUE TITLE
Remove OSSAccessKeyId, Expires and Signature if x-oss-object-acl set to "public-read when call put() in Object operations

### ISSUE THREAD

**Issue by smoothdvd** [ali-sdk/ali-oss#812]
* **ali-oss Version**: 6.9.0

```
const headers = {
  "x-oss-object-acl": options.metadata.ACL
}

const result = ossClient.put(filename, data, {
  mime: contentType,
  headers
}
```
object's url returned with format like "https://oss-cn-hangzhou.aliyuncs.com/f0bab27815a74c51da15211eb75d98c.png?OSSAccessKeyId=keyid&Expires=1591710141&Signature=0123456789"

But this object's ACL is set with "public-read", better return url without any query strings, like "https://oss-cn-hangzhou.aliyuncs.com/f0bab27815a74c51da15211eb75d98c.png"

**Comment by PeterRao** [comment]
When your Bucket's acl is not public, putObject must signature. You can use  get unsigned url with  generateObjectUrl api
