### ISSUE TITLE
uploadPartCopy大约2G的同bucket下文件经常出现ServiceUnavailableError

### ISSUE THREAD

**Issue by dijiang** [ali-sdk/ali-oss#820]
{"name":"ServiceUnavailableError","status":504,"code":"ServiceUnavailable","requestId":"5EF06CE70BFD85363587A49A","hostId":"****-update-test.oss-cn-shanghai.aliyuncs.com","params":{"object":"test233.raw","bucket":"xxxx","method":"PUT","subres":{"partNumber":4,"uploadId":"E7A0651682FA417083726DCA1172FBDA"},"timeout":7200000,"headers":{"x-oss-date":"Mon, 22 Jun 2020 08:33:43 GMT","x-oss-copy-source":"/xxxx/test233.raw.1592813969019.part4","x-oss-copy-source-range":"bytes=0-2145295016"},"successStatuses":[200]}}

nodejs sdk uploadPartCopy 经常出现这个错误是咋回事？

**Comment by PeterRao** [comment]
分片2G太大了 调小一下试试。
