### ISSUE TITLE
Document and actual API responses are inconsistent

### ISSUE THREAD

**Issue by fangbinwei** [ali-sdk/ali-oss#821]
* **Browser Version or Node Version**: 12.14.0
* **ali-oss Version**: 6.8.0
* **Mini Showcase Repository**: none
* **Network Resoponse Header x-oss-request-id**: none

文档中的一些API参数/响应的类型描述和实际代码返回的并不一致. 比如[`.list(query[, options])`](https://github.com/ali-sdk/ali-oss#listquery-options), 文档中显示`objects`是Array类型,`nextMaker`是string,`prefiex`是Array, 但是实际上, 应该是这样, `objects`可能是undefined, `prefixes`, `nextMarker`可能是null, 所以是文档的遗漏么? 接口的实现还是会保持不变么?

```js
    interface ListObjectResult {
        objects?: ObjectMeta[];
        prefixes: string[] | null;
        isTruncated: boolean;
        nextMarker: string | null;
        res: NormalSuccessResponse;
    }
```
因为最近在使用`@types/ali-oss`的过程有遇到一些小毛病, 也有意完善, 所以如果能明确上面的问题, 就更好了, 因为像`prefixes`如果可能是null, 在`@types/ali-oss`类型定义里补充上, 还是会有帮助的.

**Comment by PeterRao** [comment]
@types/ali-oss 没更新了很久了。后面准备项目往ts迁移。项目自己生成描述文件。
