### ISSUE TITLE
这个上传工具库是否可以用到webworker中？

### ISSUE THREAD

**Issue by w529456185** [ali-sdk/ali-oss#822]
在webworker中使用本上传工具库报错：
Cannot read property 'x-oss-request-id' of undefined

**Comment by PeterRao** [comment]
报错具体信息截图下

**Comment by w529456185** [comment]
![image](https://user-images.githubusercontent.com/4921608/86314394-23af7000-bc5a-11ea-8d63-54ad897799e4.png)
