### ISSUE TITLE
通过Bucket授权的直传模式下，如何限制上传的文件类型？

### ISSUE THREAD

**Issue by renlindong** [ali-sdk/ali-oss#829]
* **Browser Version or Node Version**: v10.16.2
* **ali-oss Version**: 6.7.0
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

通过Bucket授权的直传模式下，如何限制上传的文件类型？

**Comment by PeterRao** [comment]
客户端自行限制，oss没有该功能
