### ISSUE TITLE
head 方法设计不合理

### ISSUE THREAD

**Issue by qinshou** [ali-sdk/ali-oss#83]
- 描述：[head](https://github.com/ali-sdk/ali-oss?spm=5176.docoss/sdk/javascript-sdk/install.2.2.5wpvr6#headname-options) 方法应该永远 resolve ，如果找不到可以 resolve(null) ，但是不能 reject。

- 原因：因为没有 exist 类方法，通常使用 head 来判断该文件是否存在。但 head 方法当 result 0 时直接走了 reject，实际上 result 0 也是“执行成功”。但比如插入失败（已存在或非法名字等）属于执行失败，此时应走 reject 。
- 影响：判断结果只能通过 catch，从而导致脱离主逻辑次序，影响程序设计。
- 解决：当找不到这个文件时，通过 resolve( null ) 返回。或增加 exist 方法。

**Comment by rockuw** [comment]
增加exist方法的话其实会多一次请求：

```js
if (client.object_exist(obj)) { // 1st req
  var r = client.head(obj);  // 2nd req
}
```

似乎是`.head`返回`null`更好一些。@dead_horse 怎么看？

**Comment by qinshou** [comment]
@rockuw 
需求场景是判断object是否存在，如果新增 exist 就不用 head 来判断了。也不会影响现有系统，增量解决。

还有个问题，看head的方法是发一个请求，通过判断statusCode。但是这样后台会增加失败访问的计数器，不利于统计。你怎么看？

**Comment by rockuw** [comment]
@qinshou 

OSS的API里没有相关的exist的API，怎么处理完全取决于用户。
实际上，因为下面的操作不是原子的，提供这样一个API的意义也不大，而且还会增加一次网络请求：

```js
if (client.object_exist(obj)) { // 1st req
  var r = client.head(obj);  // 2nd req
}
```

**Comment by qinshou** [comment]
@rockuw 
实际上的用途是
```
if(!client.head(obj)) { // 不存在
  client.put(obj);
}
```
我这里场景是上传队列，要做个去重

**Comment by dead-horse** [comment]
可以加一个 `exist` 接口，404 不报错返回 null，还是保留 `head` 现在这样吧，不然这种不兼容变更不好发

**Comment by rockuw** [comment]
@qinshou 

你自己封装一个函数好了：

```js
function objectExist(client, obj) {
  // xxx  
}
```
