### ISSUE TITLE
is.readbleStream is not a function

### ISSUE THREAD

**Issue by guoxiuwu** [ali-sdk/ali-oss#840]
您好，我用parcel 打包之后, 调用oss 时出现了下面的这个错误.  具体信息如截图， 请帮忙看一下是什么原因, 谢谢！

![2020-07-26_115718](https://user-images.githubusercontent.com/32088212/88471101-5f76e600-cf37-11ea-9bd8-a1102e770f2b.png)
![2020-07-26_115403](https://user-images.githubusercontent.com/32088212/88471102-6140a980-cf37-11ea-9c02-d15ac7191d01.png)
![2020-07-26_115350](https://user-images.githubusercontent.com/32088212/88471103-61d94000-cf37-11ea-9d55-459bddf623c1.png)

**Comment by guoxiuwu** [comment]
@microJ  麻烦帮忙看一下这个问题,谢谢
https://github.com/ali-sdk/ali-oss/commit/6f4ae5113df3c0ca26b4957a9aec6c811b85b257

**Comment by weiyie** [comment]
@guoxiuwu   parcel没有将browser下的入口替换成dist下文件。你可以直接引入`const OSS = require('ali-oss/dist/aliyun-oss-sdk.js')`

**Comment by guoxiuwu** [comment]
好的 谢谢！
