### ISSUE TITLE
使用putStream循环上传大量文件，修改过maxSockets，还是报错

### ISSUE THREAD

**Issue by Anndy-Han** [ali-sdk/ali-oss#841]
* **Browser Version or Node Version**:  83.0.4103.116
* **ali-oss Version**: 6.8.0
* **Mini Showcase Repository**: 无
* **Network Resoponse Header x-oss-request-id**: 无

使用putStream循环上传大量文件，修改过maxSockets，还是报错。
![image](https://user-images.githubusercontent.com/29654838/88516117-5e20e880-d01f-11ea-8e14-15012104a59c.png)

**Comment by PeterRao** [comment]
createSocketCounet 很多，能贴下代码，看如何修改的maxSockets
