### ISSUE TITLE
微信小程序报 [不允许require变量] ，新建一个小程序项目用npm安装依然出现该错误

### ISSUE THREAD

**Issue by lithromantic-Fish** [ali-sdk/ali-oss#851]
紧接着报VM190:1 MiniProgramError
module "miniprogram_npm/debug/tty.js" is not defined
Error: module "miniprogram_npm/debug/tty.js" is not defined
一系列问题，往解决一下

**Comment by PeterRao** [comment]
sdk 支持程序，可以参考 https://help.aliyun.com/document_detail/92883.html?spm=a2c4g.11186623.6.1571.961b3799RX0wNz 这个文档
