### ISSUE TITLE
ali-oss的node库咋不支持服务端签名前端直传呢？

### ISSUE THREAD

**Issue by luzhaoren** [ali-sdk/ali-oss#855]
ali-oss的node库咋不支持服务端签名前端直传呢？除了STS授权方式外，有没有计划支持一下服务端签名前端直传的实现哇？

**Comment by PeterRao** [comment]
服务端签名的话，你直接用服务端签名的url进行上传就行。不需要sdk做什么

**Comment by weiyie** [comment]
服务端签名前端直传不是有？[直传服务端demo](https://github.com/ali-sdk/ali-oss/blob/master/example/server/postObject.js)
