### ISSUE TITLE
error response ResponseError: socket hang up

### ISSUE THREAD

**Issue by Solid-Metal** [ali-sdk/ali-oss#859]
hey everyone, i got a problem, i use ali oss to put a file, the file indeed took time to process, about 2.5 min, but still it weird i got hang up when just start to upload it, is there any fix for this?

heres the error snippet

error response ResponseError: socket hang up <<REDACTED HOST + FILE NAME>> -1 (connected: true, keepalive socket: true, agent status: {"createSocketCount":1,"createSocketErrorCount":0,"closeSocketCount":0,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":1,"freeSockets":{},"sockets":{"REDACTED SOCKET:80:":1},"requests":{}}, socketHandledRequests: 2, socketHandledResponses: 1)
headers: {}

**Comment by Ryuurock** [comment]
+1

**Comment by PeterRao** [comment]
when long time has not data send, oss server will close connection.
you can follow this article, use OSS_HEARTBEAT_PACKET  like this https://zhuanlan.zhihu.com/p/35527207
