### ISSUE TITLE
在阿里小程序中无法使用

### ISSUE THREAD

**Issue by ht616** [ali-sdk/ali-oss#862]
let OSS = require('ali-oss');

let client = new OSS({
  region: '<Your region>',
  accessKeyId: '<Your AccessKeyId>',
  accessKeySecret: '<Your AccessKeySecret>',
  bucket: '<Your bucket name>'，
});

async function getBuffer () {
  try {
    let result = await client.get('object-name');
    console.log(result.content);
  } catch (e) {
    console.log(e);
  }
}

getBuffer();

提示找不到 x-oss-request-id

* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

**Comment by weiyie** [comment]
不建议在小程序中使用ali-oss

**Comment by PeterRao** [comment]
参考 https://help.aliyun.com/document_detail/173882.html?spm=a2c4g.11186623.6.1670.48863d9fNpNnsb

**Comment by littleprincewdk** [comment]
@PeterRao 小程序内分片上传可以吗
