### ISSUE TITLE
使用signatureUrl生成图片链接报错，这个错误会不定时出现 过会儿重新请求又可以了

### ISSUE THREAD

**Issue by YuDaChao** [ali-sdk/ali-oss#864]
* **Browser Version or Node Version**:
* **ali-oss Version**:
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

![image](https://user-images.githubusercontent.com/23699765/93964124-739d5f00-fd91-11ea-8d37-3313aced6539.png)

**Comment by PeterRao** [comment]
生成的url发下，看报错可能是网络问题

**Comment by YuDaChao** [comment]
@PeterRao 感谢回复；现在暂时没有出现这个问题了 等出现了我发一下
