### ISSUE TITLE
建议给 public api 包一层 co.wrap

### ISSUE THREAD

**Issue by magicdawn** [ali-sdk/ali-oss#87]
现在 对外暴露的 API 都是直接的 generator function, 只能配合着 co yield 使用。
包上一层 co.wrap 之后，api方法返回的是 Promise, 可以配合 yield / await / or直接then 使用。

**Comment by rockuw** [comment]
Good point!

@fengmk2 @dead-horse 怎么看？

**Comment by fengmk2** [comment]
这个不由此模块来做，你可以发布一个新模块来做这件事情

**Comment by fengmk2** [comment]
等async 变成node内置，我们会直接提供async接口

**Comment by dead-horse** [comment]
增加一个 `oss.createPromise` 方法？

**Comment by magicdawn** [comment]
但是 fn = co.wrap genfn 的结果就是一个async function啊。除了 fn.length 不一样外。

**Comment by rockuw** [comment]
@magicdawn 4.3.0

https://github.com/ali-sdk/ali-oss#wrapper-usage
