### ISSUE TITLE
开启版本控制的情况下，再次上传相同文件未返回 version-id

### ISSUE THREAD

**Issue by Auxxxxlx** [ali-sdk/ali-oss#870]
<img width="1001" alt="截屏2020-10-08 18 53 13" src="https://user-images.githubusercontent.com/13865581/95449661-a81b3880-0997-11eb-8e35-8478ee4436d6.png">

请求应该是返回了 version id，sdk在处理返回值的时候删掉了？？
<img width="631" alt="截屏2020-10-08 18 53 48" src="https://user-images.githubusercontent.com/13865581/95449682-abaebf80-0997-11eb-819f-b13ab0250b26.png">

**Comment by PeterRao** [comment]
我们这边支持下

**Comment by weiyie** [comment]
### 
![image](https://user-images.githubusercontent.com/19388725/95561766-cd6a7e00-0a4d-11eb-9d67-721fffbc60f4.png)
