### ISSUE TITLE
Refused to set unsafe header "User-Agent"

### ISSUE THREAD

**Issue by Syes-K** [ali-sdk/ali-oss#872]
* **Browser Version or Node Version**: chrome 86.0.4240.75
* **ali-oss Version**: ali-oss@6.11.1
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

When I upload the video to OSS( I use the temporary token in the latest Chrome browser)。
The  console of chrome   always throw a error “Refused to set unsafe header "User-Agent"”。

**Comment by Syes-K** [comment]
The previous version of ali-oss does not have this error

**Comment by PeterRao** [comment]
6.11.2 已解决
