### ISSUE TITLE
关于切片上传进度的问题

### ISSUE THREAD

**Issue by useryechen** [ali-sdk/ali-oss#880]
* **Browser Version or Node Version**: `chrome86`
* **ali-oss Version**: `6.11.2`
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**: `5F9BCAA0A851A73431B12055`

**Comment by useryechen** [comment]
在调用`api`上传过程中，在`multipartUpload`回调中，通过`options`中`progress`可以拿到当前文件整体上传进度，而不能拿到当前切片的具体上传进度。自己之前做切片上传的时候，可以通过监听`onUploadProgress`拿到当前切片已经发送的进度。如果这样，那当我上传一个`40M`的文件的时候，假设我的每个切片大小为`4M`，那么进度条显示的就很突兀，直接从百分之十到百分之二十。

**Comment by PeterRao** [comment]
可以通一些css动画解决突兀问题，progress一方面是记录进度一方面也是记录分片信息，不太适合针对单个分片来记录进度。

**Comment by useryechen** [comment]
> 可以通一些css动画解决突兀问题，progress一方面是记录进度一方面也是记录分片信息，不太适合针对单个分片来记录进度。

感谢回复，动画之前已经加过了，如果没有提供具体的分片信息那就先这样吧
