### ISSUE TITLE
Property 'calculatePostSignature' does not exist on type 'OSS'

### ISSUE THREAD

**Issue by godtail** [ali-sdk/ali-oss#883]
* **Browser Version or Node Version**:
13.11.0
* **ali-oss Version**:
6.11.2
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

When I use ali-oss by typescript, I get an error `Property 'calculatePostSignature' does not exist on type 'OSS'`

It looks like `@types/ali-oss` not update yet.

![image](https://user-images.githubusercontent.com/18417644/97870387-e1a05300-1d4d-11eb-9b55-699619a5b03a.png)

**Comment by godtail** [comment]
Can we support typescript ?

**Comment by PeterRao** [comment]
@types/ali-oss is deprecated, we plan to rewrite ali-oss witch typescript on 7.x version
