### ISSUE TITLE
premature close

### ISSUE THREAD

**Issue by fanmengqi** [ali-sdk/ali-oss#884]
请问这种错误是什么情况导致的，经常出现

version: 6.11.2

ResponseError: premature close, PUT http://**.png -1 (connected: true, keepalive socket: false, agent status: {"createSocketCount":2,"createSocketErrorCount":0,"closeSocketCount":1,"errorSocketCount":0,"timeoutSocketCount":0,"requestCount":0,"freeSockets":{},"sockets":{"dagong-pro.oss-cn-beijing.aliyuncs.com:80:":1},"requests":{}}, socketHandledRequests: 1, socketHandledResponses: 0)

**Comment by xxyGoTop** [comment]
同问

**Comment by bigdong89** [comment]
同问，现在脚本上传图片不上去了

**Comment by JackGou1029** [comment]
同问，csv无法上传

**Comment by PeterRao** [comment]
使用https试下，可能是网络问题。服务端关闭连接了

**Comment by JackGou1029** [comment]
在分片上传时遇到这个报错

**Comment by JackGou1029** [comment]
已经使用https上传，但还是在上传到一半的时候报错

**Comment by liumenghua** [comment]
遇到同样问题
