### ISSUE TITLE
 signatureUrl上传文件损坏

### ISSUE THREAD

**Issue by q1104133609** [ali-sdk/ali-oss#891]
let OSS = require('ali-oss');
let store = new OSS({
    bucket,
    region,
    accessKeyId,
    accessKeySecret
})
const url = store.signatureUrl('download.jpg', {
    expires: 3600,
    method: 'PUT',
    'content-type': 'image/jpeg',
  });
console.log(url);

**Comment by PeterRao** [comment]
具体什么错误？

**Comment by q1104133609** [comment]
就是上传完成了 文件下载下来查看就损坏了

**Comment by PeterRao** [comment]
对比下上传的文件和下载的文件md5或者crc64是否一样

**Comment by q1104133609** [comment]
好像是是说md5不一致  我这边是直接用的nodesdk生成的

**Comment by PeterRao** [comment]
上传的原始文件 和下载后的原始文件 md5 不是一致的？你看下oss返回的响应头里面 content-md5 和你上传前的文件一样吗

**Comment by suinia** [comment]
同样遇到这个问题

**Comment by suinia** [comment]
应该是前端fetch上传需要把 file 转成 Blob
```
      const body = new Blob([file], { type: contentType });
      fetch(url, {
        method: 'PUT',
        headers: new Headers({ 'Content-Type': contentType }),
        body,
      })
```

**Comment by q1104133609** [comment]
好的我们这边试下 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ali-sdk/ali-oss"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月25日(星期三) 下午2:59
收件人:&nbsp;"ali-sdk/ali-oss"<ali-oss@noreply.github.com&gt;;
抄送:&nbsp;"小白"<1104133609@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ali-sdk/ali-oss]  signatureUrl上传文件损坏 (#891)





 
应该是前端fetch上传需要把 file 转成 Blob
       const body = new Blob([file], { type: contentType });       fetch(url, {         method: 'PUT',         headers: new Headers({ 'Content-Type': contentType }),         body,       })

**Comment by emclab** [comment]
在React Native0.70前端中碰到同样的问题。下面的code不work：

```
import ReactNativeBlobUtil from 'react-native-blob-util';  //v0.19
fileData = await ReactNativeBlobUtil.fs.readFile(filePath);  //或‘base64‘。 file Path是image picker读进来的路径 如，file:///data/user/0/com.xyz_app6/cache/rn_image_picker_lib。。。
response = await ReactNativeBlobUtil.fetch('PUT', preSignedUrl, {"Content-Type":`${contentType}`}, fileData); //content Type是image/jpeg。 preSignedUrl是node服务器生成的。
```

上传的文件很小。只有几个BYTE。如果用‘base64’，文件size好像正常。但仍然是打不开corrupted。用fetch PUT或axios PUT 都有corrupted。上面的code需要如何改进？谢谢
