### ISSUE TITLE
在某些android5手机上，解析url的正则出现问题

### ISSUE THREAD

**Issue by yindeqiang** [ali-sdk/ali-oss#899]
Url.prototype.parse 方法中的

```
if (!ipv6Hostname) {
            var hostparts = this.hostname.split(/\./);


使用 'www.baidu.com'.split(/\./) 结果为

["w", "w", "w", ".", "b", "a", "i", "d", "u", ".", "c", "o", "m"]

```

经过测试6.10.0 和 6.11.0的版本没有执行这句split都正常，但6.11.1 和 6.12.2版本出错。

测试手机 coloros v3.0.0 android5.1

**Comment by beajer** [comment]
https://github.com/zloirock/core-js/issues/751

**Comment by PeterRao** [comment]
这个不是android问题，应该是cores-js问题。我们收到及其这个问题了。

**Comment by PeterRao** [comment]
通过shime的方式临时解决了下，使用6.12.0版本尝试下
