### ISSUE TITLE
abortMultipartUpload 中断问题

### ISSUE THREAD

**Issue by yang498** [ali-sdk/ali-oss#904]
`multipartUpload` 上传多个文件之后，使用 `abortMultipartUpload` 中断其中的一个文件，会将当前实例的所有任务中断，且捕获到的 err 是 `{ name: 'cancel', status: 0 }`，不是例子中的 `err.name === 'abort'`

**Comment by lihaixing** [comment]
请问这个问题如何处理呢

**Comment by yang498** [comment]
> 请问这个问题如何处理呢

在调用 `abortMultipartUpload` 时重新初始化一个实例调用，可以只中断传入的 `checkpoint`
