### ISSUE TITLE
 Error: XHR error (req "error")

### ISSUE THREAD

**Issue by ItsNikkiZeng** [ali-sdk/ali-oss#923]
* **Browser Version or Node Version**: Chrome 87.0.4280.88   
* **ali-oss Version**: Aliyun OSS SDK for JavaScript v6.6.0
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:N/A case request send failed

When user upload file it will show below err:

aliyun-oss-sdk.min.js:13 OPTIONS https://zhon-static-hz.oss-cn-hangzhou.aliyuncs.com/u/N2QLY2iLgM/1611304486791_2fe6e387.rar?uploads= 0 ()
err: Error: XHR error (req "error"), POST https://zhon-static-hz.oss-cn-hangzhou.aliyuncs.com/u/N2QLY2iLgM/1611304486791_2fe6e387.rar?uploads= -1 (connected: false, keepalive socket: false)
headers: {}

here is my config
new OSS({
          accessKeyId: data.AccessKeyId,
          accessKeySecret: data.AccessKeySecret,
          stsToken: data.SecurityToken,
          bucket: "zhon-static-hz",
          endpoing: "oss-cn-hangzhou.aliyuncs.com"
})

**Comment by PeterRao** [comment]
set cors rule first  https://github.com/ali-sdk/ali-oss#bucket-setup
