### ISSUE TITLE
这个包太大了，比阿里巴巴还要大

### ISSUE THREAD

**Issue by eugle** [ali-sdk/ali-oss#925]
这个包已经死了吗？没有人维护了吗？

**Comment by PeterRao** [comment]
sdk库因为要兼容node和浏览器等一切历史原因，导致打包了不少useless package，我们也在逐步优化7.x版本会提供tree shaking 的打包方式后续计划提供mini的版本，请耐心等待。
请不要发额外的issue，这里是技术社区只讨论技术问题。如果需求比较强烈，建议工单进行咨询要求，OSS产品会根据工单反馈情况优先进行安排。

**Comment by Tyrone2333** [comment]
> sdk库因为要兼容node和浏览器等一切历史原因，导致打包了不少useless package，我们也在逐步优化7.x版本会提供tree shaking 的打包方式后续计划提供mini的版本，请耐心等待。 请不要发额外的issue，这里是技术社区只讨论技术问题。如果需求比较强烈，建议工单进行咨询要求，OSS产品会根据工单反馈情况优先进行安排。

2年了,  7.x版本文件夹都还没新建吧
