### ISSUE TITLE
上传一个10G的文件，传到8G左右就出错了

### ISSUE THREAD

**Issue by gouchaoer** [ali-sdk/ali-oss#936]
浏览器：chrome88.0
oss库版本：aliyun-oss-sdk-6.8.0.min.js
endpoint: "oss-accelerate.aliyuncs.com"
const region = 'oss-cn-shanghai'; // oss服务区域名称
const partSize = 4 * 1024 * 1024; // 每个分片大小
const parallel = 4; // 同时上传的分片数
const checkpoints = {}; // 所有分片上传文件的检查点

因为上传是在海外所以我用了全球加速的OSS的endpoint，上传了一个3G的是OK的，这个10G的传到8G多就不行了

![image](https://user-images.githubusercontent.com/5207582/109760210-4a7ad780-7c29-11eb-8d72-fe7b4177a964.png)

**Comment by gouchaoer** [comment]
我的multipartUpload的catch异常代码如下：
```
    }).catch(err => {
        var msg = "err_name:" + err.name + "; err_message:" + err.message;
        var status_msg = `上传错误，请刷新页面后再次尝试上传，如果仍然上传错误就把后面的错误原因截图发给管理员。${msg}`;
        console.log(status_msg);
        console.log(status_msg, err);
        var status = document.getElementById('status'); // 状态显示元素
        status.innerText = status_msg;
    });
```

这是啥原因呢？可以在代码里重传么？

**Comment by beajer** [comment]
可以在代码里检测err.status，如果为-1或-2,用保存的checkpoint再次调用multipartUpload可以重传

**Comment by gouchaoer** [comment]
> 可以在代码里检测err.status，如果为-1或-2,用保存的checkpoint再次调用multipartUpload可以重传

hi，请问一下：

1，sdk抛出的异常能判断这是啥原因造成的上传失败呢？
2，能提供一个带retry的example代码么？我现在的代码抄的这里的`https://github.com/ali-sdk/ali-oss#multipartuploadname-file-options`，没有retry我不知道咋写

**Comment by gouchaoer** [comment]
> 可以在代码里检测err.status，如果为-1或-2,用保存的checkpoint再次调用multipartUpload可以重传

你们这个commit是不是已经处理了status=-1或-2的情况，自动retry了啊？
https://github.com/ali-sdk/ali-oss/pull/876/commits/e7a19ebe36c68e0b18f5ce882fdaf20955dd4d19

**Comment by beajer** [comment]
retry分片的上传会出现分片为0的bug，在修复

**Comment by gouchaoer** [comment]
开了个工单，那边给我个retry的demo：

参考下  https://help.aliyun.com/document_detail/111269.html  
有断点续传的demo 示例

我试了之后发现这个demo过时了，需要魔改一下才能适配现在的oss js客户端，你们demo没有及时update啊
