### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by conversun** [ali-sdk/ali-oss#942]
<img width="925" alt="46" src="https://user-images.githubusercontent.com/22893221/111895626-ef314d80-8a4e-11eb-80c8-ab0c1a99a154.png">

[2021-03-21T06_07_22_026Z-debug.log](https://github.com/ali-sdk/ali-oss/files/6176921/2021-03-21T06_07_22_026Z-debug.log)

**Comment by beajer** [comment]
try
```
npm cache clean --force
```
or try to use a registry

**Comment by conversun** [comment]
> npm cache clean --force

Thx, it work
