### ISSUE TITLE
console.log(2);

### ISSUE THREAD

**Issue by rufeng2015** [ali-sdk/ali-oss#947]
* ** node 14.4.0 **:
* ** ali-oss  6.15.0 **:
![image](https://user-images.githubusercontent.com/14096175/112794969-6cd20a80-909a-11eb-93bc-31f0e46647a0.png)
6.10.x ,6.15.0 这两个版本里 不知道从哪里来了一个 console.log(2),在跑起来项目时控制台会打印这个，
你们可以去掉吗，项目里全局搜索代码里没有找到这个log

**Comment by PeterRao** [comment]
使用最新版本 试下
