### ISSUE TITLE
文件保存成功后返回的地址错误。

### ISSUE THREAD

**Issue by frank10000** [ali-sdk/ali-oss#950]
* **Browser Version or Node Version** :
* **ali-oss Version**: 6.15.2
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

断点续传的时候第一次调用 multipartUpload 和第二次调用 multipartUpload 的时候传递的object-key不一样，上传完成后是第一次上传的object-key所对应的路径。

**Comment by ricky11** [comment]
are you using multipartipload api?  pls show some code.

**Comment by frank10000** [comment]
> are you using multipartipload api? pls show some code.

I just write by official document
[official demo ](https://help.aliyun.com/document_detail/31850.html)

**Comment by PeterRao** [comment]
每次使用分片上传，新创建一个实例，你可能是用了同一个实例

**Comment by frank10000** [comment]
> 每次使用分片上传，新创建一个实例，你可能是用了同一个实例

每次都是用new OSS创建出来的实例。由于是断点续传，存储的文件路径不一样的，但是采用的是第一次的。是不是应该存为第二次的
