### ISSUE TITLE
使用put 方法，当上传失败时，会自动重试，但是 request Payload 却为空，会上传一个空文件 (0kb) 

### ISSUE THREAD

**Issue by lunajing** [ali-sdk/ali-oss#951]
x-oss-user-agent: aliyun-sdk-js/6.9.0 Chrome 90.0.4430.85 on OS X 10.15.7 64-bit

复现步骤（必现）：

1. 将浏览器设置为弱网
2. 调用put方法
3. 会先尝试上传对应文件, 超时
4. js-sdk会自动重发一次上传文件的请求, 但是body为空, 该次请求成功, 返回200
5. oss中存在一个大小为0KB的文件

上传超时的requestId: 6093C22E3218A13631BF68BB
返回200的requestId: 6093C26B224F963734FB7906

**Comment by PeterRao** [comment]
使用最新版本试下
