### ISSUE TITLE
调 uploader.stopUpload() 会用几率出现   Cannot read property 'cancel' of null

### ISSUE THREAD

**Issue by xuergo** [ali-sdk/ali-oss#953]
这是一个很难试出来的问题 差不多当前文件快传完的时候 调 uploader.stopUpload() 有记录出现 Cannot read property 'cancel' of null，不知道有人遇到吗？

**Comment by ZhangJianChengZzz** [comment]
看了一下源码是nextUpload这个将_ossUpload变成了null，可以在stopUpload中加一个判断条件判断是否存在_ossUpload再调用cancel()
