### ISSUE TITLE
OSS服务端开启GZip压缩而导致发HEAD请求无法获取文件大小

### ISSUE THREAD

**Issue by fuweichin** [ali-sdk/ali-oss#954]
* **Browser Version or Node Version**: Chrome 90
* **ali-oss Version**: 6.15.2
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**: 60A4D87D224F96373522494A

使用`client.head()`方法来查询文件的元数据时，因阿里云OSS默认对HTML/JSON/XML等类型文件启用了GZip，见[OSS的gzip压缩如何使用](https://help.aliyun.com/knowledge_detail/39645.html)，导致这些文件的HEAD请求服务端未返回`Content-Length`响应标头，从而没能获取文件大小。

我尝试用Firefox的网络请求"编辑并重发"功能修改请求标头`Accept-Encoding: identity`，这样可以让OSS服务器不压缩响应体而返回`Content-Length`。但是Accept-Encoding属于[禁止修改的请求标头](https://developer.mozilla.org/zh-CN/docs/Glossary/Forbidden_header_name)，通过正常JS途径无法设置。

这样也可以绕过阿里云OSS的GZip压缩：在上传文件时，如果文件的mime type是会阿里云OSS会GZip压缩的类型，如['text/cache-manifest', 'text/xml', 'text/plain', 'text/css', 'application/javascript', 'application/x-javascript', 'application/rss+xml', 'application/json', 'text/json']，那么把请求头Content-Type设为'application/octet-stream'而不是文件原mime type。

虽然有一些变通解决方法，但这是一个坑，目前仍需开发者自己想办法绕过。希望sdk开发者能协调阿里云OSS客服解决。

**Comment by ricky11** [comment]
That is interesting. Sorry I cannot write Chinese, so i use translation.

You mean you cannot get the Content-Length using the head api, due to GZIP compression enabled on oss side?

Can you get back other user metadata x-oss-xxx that you defined?

![image](https://user-images.githubusercontent.com/5736415/118948776-2e1a4b80-b98b-11eb-9bbb-6de6f490cb59.png)

What is the reason you need the content-length of the file so i can better understand the problem?

Sorry, i am not ali-oss developer, but i also use this package.

Thakns

**Comment by fuweichin** [comment]
I use this SDK to upload a directory of files, similar to local directory copy, I need `head()` to retirve file metadata, like 'stat' in Unix shell or 'fs.lstatSync()' in Node.js.

Before sending actual PUT request to upload a file, send a pre-check HEAD request to check if the corresponding object key already denotes a remote file. If it does, then compare local file and remote file, check if the two files differ in content (by comparing size and md5). If two files differ in size, there is no need to calculate md5 of local file, just say they are conflic in content. If not confilic, skip this file, else let user choose to skip / overwrite (and even skip all / overwrite all).

Content-MD5 header cannot be set/get in some S3-compatible storage so I use x-*-meta-md5. what I didn't expected was Content-Length may not present when GZip enabled and interfered.

**Comment by PeterRao** [comment]
我试了下 如果开启了gzip，应该不会返回content-length参数。返回的content-length 应该sdk的网络框架自己加上的。
curl -i -X HEAD https://ali-oss-test-case.oss-us-west-1.aliyuncs.com/bucket.test.js -H "Accept: */*" -H "Accept-Encoding: gzip"
curl -i -X HEAD https://ali-oss-test-case.oss-us-west-1.aliyuncs.com/bucket.test.js

要解决这个问题，可以试下GetObjectMeta接口。

**Comment by PeterRao** [comment]
> 我试了下 如果开启了gzip，应该不会返回content-length参数。返回的content-length 应该sdk的网络框架自己加上的。 curl -i -X HEAD https://ali-oss-test-case.oss-us-west-1.aliyuncs.com/bucket.test.js -H "Accept: _/_" -H "Accept-Encoding: gzip" curl -i -X HEAD https://ali-oss-test-case.oss-us-west-1.aliyuncs.com/bucket.test.js
> 
> 要解决这个问题，可以试下GetObjectMeta接口。

和服务端同学沟通了下，这个在浏览器中只能使用 GetObjectMeta 来获取文件大小。HeadObject 可能因为开启gzip了，无法获取正确的大小
