### ISSUE TITLE
proxy 字段不起作用

### ISSUE THREAD

**Issue by yejiajiehz** [ali-sdk/ali-oss#957]
* **Browser Version or Node Version**:  mac chrome 91
* **ali-oss Version**: 6.15.0
* **Mini Showcase Repository**:
* **Network Resoponse Header x-oss-request-id**:

配置 proxy，enableProxy 之后，发现没有任何作用   
阅读代码发现，createRequest ->  requestWithCallback 代码中没有对应的实现   
这个功能是否需要配合自定义的 urllib 实现？

**Comment by PeterRao** [comment]
node 环境吗

**Comment by yejiajiehz** [comment]
浏览器环境。没有在文档中找到 proxy 相关的说明  
如果我需要做代理，是否应该直接使用 endpoint 到我的代理服务器，再转发到 阿里云 oss？

**Comment by PeterRao** [comment]
浏览器的话，你直接用endpoint，浏览器不支持proxy这个选项。
