### ISSUE TITLE
client.multipartUpload(...).then is not a function

### ISSUE THREAD

**Issue by VanStranger** [ali-sdk/ali-oss#961]
i used this <script type="text/javascript" src="http://gosspublic.alicdn.com/aliyun-oss-sdk.min.js"></script>
and I can't get multipartUpload().then.

**Comment by KillingMeNow** [comment]
try add version 
https://gosspublic.alicdn.com/aliyun-oss-sdk-6.15.0.min.js

**Comment by VanStranger** [comment]
> try add version
> https://gosspublic.alicdn.com/aliyun-oss-sdk-6.15.0.min.js

3ku,solved.
I really can't find the version.3ks again.
