### ISSUE TITLE
In @types/ali-oss do not define listV2

### ISSUE THREAD

**Issue by FocusCare** [ali-sdk/ali-oss#971]
* **Chrome  91.0.4472.114**:
* **ali-oss 6.16.0**:
* **@types/ali-oss do not define listV2**:
* **none**:

![image](https://user-images.githubusercontent.com/3634726/126285823-243a824e-d3ed-47c9-b074-c8df3195e0f3.png)

**Comment by sialvsic** [comment]
same on @types/ali-oss": "^6.16.3",

**Comment by aaroncastle** [comment]
Since the declaration file is not an official product, it has not been maintained for a long time. It is recommended to modify the declaration file to add the listV2 method and remove the space after ‘max-keys ’ in the ListChannelsQuery interface. This is a mistake of the author.
