### ISSUE TITLE
abortMultipartUpload 接口提示403

### ISSUE THREAD

**Issue by Corgis** [ali-sdk/ali-oss#972]
通过const client = new OSS({}) 创建了一个连接，然后client.multipartUpload 方法开始分片上传大文件，传输的过程中 想通过该client 调用  client.abortMultipartUpload(name, uploadId) 方法 来取消上传  结果该接口总是返回403错误，是怎么回事呢？

**Comment by ricky11** [comment]
Can you show the code?
You need the object path, upload id.

![image](https://user-images.githubusercontent.com/5736415/126488241-dd78af0a-d41d-45eb-9993-d6914a6c982c.png)

Maybe try call the .cancel() should be enough to cancel the upload.

**Comment by Corgis** [comment]
async uploadFile(e){
  const vm = this
  const curFile = e.file
  let fileName = curFile.name
  let fileSpliceName = 'sample/' + curFile.name + curFile.uid
  if(vm.formData.selectType==='bed'){
    fileName = curFile.name.substr(0, curFile.name.length - 4)
    fileSpliceName = 'bed/'+ curFile.name.substr(0, curFile.name.length - 4) + curFile.uid+'.bed'
  }
  // 记录多文件上传的信息
  vm.uploadList.push({
    name:fileName,
    size:curFile.size,
    fileUrl:fileSpliceName,
    state:'ready',
    uid:curFile.uid,
    raw:curFile,
    percentage:0
  })
  // console.log(e,'e================')

  await vm.ossConnect()
  await vm.ossClient.multipartUpload(fileSpliceName,curFile,{
    partSize:5 * 1024 * 1024, // 默认就为1MB,此处设置为5MB
    progress: async (p,cpt,res ) =>{
      console.log(cpt)
      // 获取uploadId
      const uploadId = cpt.uploadId
      // 多文件每个文件的uid标识
      const curUid = cpt.file.uid
      // 获取uid相同的文件所在数组的下标
      const sub = vm.fileList.findIndex(item => item.uid === curUid)
      // 更新fileList的进度值
      const extendData = extend(true, {}, vm.fileList[sub], { percentage: (p*100).toFixed(0)})
      vm.$set(vm.fileList, sub, extendData)
      // 更新uploadList，增加uploadId值,每个文件对应的该值唯一且不会变
      if (!vm.uploadList[sub].uploadId){
        const extenduploadData = extend(true, {}, vm.uploadList[sub], {uploadId})
        vm.$set(vm.uploadList, sub, extenduploadData)
      }
      // 通知后台存文件记录
      if(p===1){
        await vm.insertsample(sub)
      }
    }
  }).then((res)=>{

  }).catch(err =>{
    this.$message.warning('文件上传失败，请尝试断点续传或刷新页面重新上传')
  })
}
// 建立oss
async ossConnect(){
  const vm = this
  await vm.$store.dispatch('oss/assumerole').then((data) => {
    vm.ossClient = new OSS({
      region: 'oss-cn-hangzhou', // oss-cn-shenzhen.aliyuncs.com
      accessKeyId: data.credentials.accessKeyId,
      accessKeySecret: data.credentials.accessKeySecret,
      stsToken: data.credentials.securityToken,
      bucket: 'oss-genefileg'
    })
    console.log(vm.ossClient,'vm.ossClient')
  }).catch((err) =>{
    this.$message.error('oss连接失败，请重新点击开始上传');
  })
}
// 取消分片上传
async abortUpload(sub){
  const vm = this
  if(vm.uploadList[sub]){
    const name = vm.uploadList[sub].fileUrl
    const uploadId = vm.uploadList[sub].uploadId
    console.log(name)
    const result = await vm.ossClient.abortMultipartUpload(name, uploadId);
    console.log(name,result,'result======')
    if(result){
      this.$message.success(`文件 ${vm.fileList[sub].name} 取消上传成功`);
    }
  }
}

**Comment by Corgis** [comment]
```javascript
async uploadFile(e){
  const vm = this
  const curFile = e.file
  let fileName = curFile.name
  let fileSpliceName = 'sample/' + curFile.name + curFile.uid
  if(vm.formData.selectType==='bed'){
    fileName = curFile.name.substr(0, curFile.name.length - 4)
    fileSpliceName = 'bed/'+ curFile.name.substr(0, curFile.name.length - 4) + curFile.uid+'.bed'
  }
  // 记录多文件上传的信息
  vm.uploadList.push({
    name:fileName,
    size:curFile.size,
    fileUrl:fileSpliceName,
    state:'ready',
    uid:curFile.uid,
    raw:curFile,
    percentage:0
  })
  // console.log(e,'e================')

  await vm.ossConnect()
  await vm.ossClient.multipartUpload(fileSpliceName,curFile,{
    partSize:5 * 1024 * 1024, // 默认就为1MB,此处设置为5MB
    progress: async (p,cpt,res ) =>{
      console.log(cpt)
      // 获取uploadId
      const uploadId = cpt.uploadId
      // 多文件每个文件的uid标识
      const curUid = cpt.file.uid
      // 获取uid相同的文件所在数组的下标
      const sub = vm.fileList.findIndex(item => item.uid === curUid)
      // 更新fileList的进度值
      const extendData = extend(true, {}, vm.fileList[sub], { percentage: (p*100).toFixed(0)})
      vm.$set(vm.fileList, sub, extendData)
      // 更新uploadList，增加uploadId值,每个文件对应的该值唯一且不会变
      if (!vm.uploadList[sub].uploadId){
        const extenduploadData = extend(true, {}, vm.uploadList[sub], {uploadId})
        vm.$set(vm.uploadList, sub, extenduploadData)
      }
      // 通知后台存文件记录
      if(p===1){
        await vm.insertsample(sub)
      }
    }
  }).then((res)=>{

  }).catch(err =>{
    this.$message.warning('文件上传失败，请尝试断点续传或刷新页面重新上传')
  })
}
// 建立oss
async ossConnect(){
  const vm = this
  await vm.$store.dispatch('oss/assumerole').then((data) => {
    vm.ossClient = new OSS({
      region: 'oss-cn-hangzhou', // oss-cn-shenzhen.aliyuncs.com
      accessKeyId: data.credentials.accessKeyId,
      accessKeySecret: data.credentials.accessKeySecret,
      stsToken: data.credentials.securityToken,
      bucket: 'oss-genefileg'
    })
    console.log(vm.ossClient,'vm.ossClient')
  }).catch((err) =>{
    this.$message.error('oss连接失败，请重新点击开始上传');
  })
}
// 取消分片上传
async abortUpload(sub){
  const vm = this
  if(vm.uploadList[sub]){
    const name = vm.uploadList[sub].fileUrl
    const uploadId = vm.uploadList[sub].uploadId
    console.log(name)
    const result = await vm.ossClient.abortMultipartUpload(name, uploadId);
    console.log(name,result,'result======')
    if(result){
      this.$message.success(`文件 ${vm.fileList[sub].name} 取消上传成功`);
    }
  }
}
```

**Comment by Corgis** [comment]
表现在接口下的形式如下
![image](https://user-images.githubusercontent.com/13865529/126578917-f61003f6-23d5-4bc7-bd81-3b28b171f1de.png)

**Comment by PeterRao** [comment]
没有给delete权限

**Comment by Corgis** [comment]
已经解决，谢谢
