### ISSUE TITLE
如何查取配置项纪录 , 我想了解 bucket 配置项做过哪些改动应该如何做?

### ISSUE THREAD

**Issue by qq240814476** [ali-sdk/ali-oss#975]
如何查取配置项纪录 , 我想了解 
- bucket 配置项做过哪些改动?
- 何时做的这些改动
应该如何做?
应该可以查到配置项日志吧?

**Comment by PeterRao** [comment]
目前无法获取修改历史，如果开通了实时日志，能查看到修改的日志，但日志里面可能只有修改时间、ip等等，看不到修改的内容。
